### ISSUE TITLE
SSHProcess do not follow asyncio api

### ISSUE THREAD

**Issue by gawel** [ronf/asyncssh#107]
You can access the exit_status but asyncio subprocesses use a returncode attribute.

I've added a property wrapper to my subclass and it seems to work fine: https://github.com/bearstech/nuka/commit/ae5bc37ad3e74dafc4b1d1cf75676737bb8fc2b3#diff-8d8bfade2d1df32f9f13af3d6a077b44R141

Maybe you should do the same

**Comment by ronf** [comment]
I thought about doing this, but there's actually a small difference between what asyncssh returns and "returncode" which is returned by asyncio.subprocess.Process. In the case of a process being terminated by a signal, the asyncio returncode documentation says:

>   A negative value -N indicates that the child was terminated by signal N (Unix only).

With the SSH protocol, numeric signal values are not available. Signal names are provided, but they can vary from one system to another, so mapping a signal name from a remote system to a signal number that makes sense on the local system isn't always possible. So, I got as close as I could to the asyncio behavior by having my "exit_status" value return -1 for all processes terminated by a signal, but require that you pull the specific signal information out of a different field called "exit_signal" if you want to know which signal was returned. If I provided a returncode value and a caller depended on getting back different negative values for different signals, their code would break.

**Comment by gawel** [comment]
Ok, thanks for the explanation! The wrapper do the trick for me.

FYI we tested your lib with nuka (WIP) and it works pretty well with more than 200 "simultaneous" connections. It's a bit slower than the ssh binary but it's cool to have tracebacks instead of return codes / error messages :)

Thanks for the great work!

**Comment by ronf** [comment]
My pleasure - thanks for the feedback! Regarding performance, I've also seen that it can be somewhat slower than running the C version of OpenSSH on things like large bulk transfers, but if you are opening a large number of short-lived connections there are cases where it can actually be faster because of the reduced overhead of not having to start a new process each time.

The wrapper you showed here should work fine, as long as your calling code doesn't depend on specific negative values coming back for different signals.
