### ISSUE TITLE
create_process doesn't fully support file-like objects

### ISSUE THREAD

**Issue by gsauthof** [ronf/asyncssh#110]
The [asyncssh documentation](http://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnection.create_process) specifies that one can use file-like objects for stdout/stderr.

[It turns out that asyncssh](https://github.com/ronf/asyncssh/blob/6265bf2e17f948e6e9c302ab9abd4ad5512fe614/asyncssh/process.py#L532) calls `fileno()` on that file-like object in order to `fstat()`.

Thus, common file-like objects doesn't work with that API. For example, `io.StringIO` doesn't work.

For my use case, storing the most recent lines only, I had to create some [ghetto-style work-around](https://gist.github.com/gsauthof/086a13af08045b2ebae7624a304ebc69).

It would be great if `create_process()` (and friends) would support common file-like objects.

I would put the

    mode = os.fstat(file.fileno()).st_mode

part into a try/except block like so:

    # helper function
    def is_regular(file):
      try:
        mode = os.fstat(file.fileno()).st_mode
        return stat.S_ISREG(mode)
      except OSError:
        return True

    # example usage
    if is_regular(file):
      reader = _FileReader(self, file, bufsize,
                                     datatype, self._encoding)
     else:
        _, reader = yield from self._loop.connect_read_pipe(pipe_factory, file)

This works because file-like objects are supposed to raise OSError if they don't implement `fileno()`. See also the `io.StringIO` documentation.

**Comment by ronf** [comment]
Thanks very much for the report.

I tried making a change similar to what you suggested here, but there are some complications I'm running into. I was able to work around one of them, but I'm still debating what to do about a couple of others.

One problem here is that the code is designed to always operate on bytes. Even when you pass in a file object that is open in text mode, the code extracts the underlying byte I/O object from within the file object and operates on that, as the block boundaries on some sources don't always guarantee you get full Unicode characters delivered to you. You need to be able to cope with a partial Unicode character, buffering up the bytes until more data arrives before you try again to decode it.

The process module handles this by checking for an 'encoding' member and if found using the "buffer" member of the object passed in instead of the object itself. However, StringIO objects don't have either an encoding or a buffer member, even though they operate on strings and not bytes. There's really no clean way I can see to get an underlying "bytes" object to operate on when a StringIO is passed in. I could look explicitly for a StringIO and do something custom there, but it wouldn't handle a generic file-like object that wanted to operate on strings instead of bytes.

There's another issue as well: AsyncSSH will call close() on the file object as soon as the channel is closed. However, getvalue() cannot be called on a StringIO object after it is closed. So, in most cases, you won't be able to retrieve the output stored into a StringIO as it'll already be discarded before you get notified that the output is complete.

It should still be possible here to use other file-like objects, and I could potentially try and make this more robust in terms of accessing members like fileno, encoding, and buffer. However, other than adding it as its own special case, it would be difficult to get it to work with StringIO, and I'm not sure how useful it is to do that. On the input side, you can just use the "input" argument if you want to feed in a text string as stdin, and on the output side you can simply call something like run() or communicate() and get the collected output of stdout and stderr as strings (or bytes, depending on if you have set an encoding). So, there's really no reason to use BytesIO or StringIO here.

**Comment by ronf** [comment]
I spent a bit more time on this today, and have checked in changes based on the proposed code above to handle OSError being raised in a call to fileno(). Also, I've adjusted the way I detect and handle text vs. binary file objects, so that it can automatically detect this as long as the text-based file objects have an 'encoding' member (even if 'encoding' is not set to anything).

Even with this changes, it's still problematic to use BytesIO or StringIO objects as targets, as the data is discarded as soon as close() is called. However, if you create your own subclass of either of these classes which saves a copy of the final output in the close() call, it should work fine. I have added unit tests which test specifically against BytesIO and StringIO which work this way.

That said, using BytesIO/StringIO really only makes sense if you are going to modify the output captured by those in some way, such as what you are doing here. If you just want to pass in a string as-is as input, you can use the "input" argument instead of "stdin", and if you want to capture all of the output from running a process, you can get that from calling communicate() or from the SSHCompletedProcess or ProcessError classes returned/raised in a call to SSHClientConnection.run().

If you'd like to try this new functionality out, it's now checked into the "develop" branch.

**Comment by gsauthof** [comment]
Great work, this will simplify my code. I'll try to test the change next week.

**Comment by ronf** [comment]
This change is now released in AsyncSSH 1.11.1.

**Comment by gsauthof** [comment]
FWIW, I've tested my use cases with the develop branch a few days ago and everything works as expected.

**Comment by ronf** [comment]
Terrific - thanks for letting me know!
