### ISSUE TITLE
Tests are failing when OpenSSH doesn't support some ciphers

### ISSUE THREAD

**Issue by vincentbernat** [ronf/asyncssh#113]
Hey!

OpenSSH 7.6p1 dropped support for arcfour, blowfish and CAST ciphers. This makes unittests fail. Except the obvious fix of removing the corresponding tests, I don't know if there is a better way to fix this.

**Comment by ronf** [comment]
Yeah - this should be fixed already on the "develop" branch. It determines the OpenSSH version dynamically, and avoids using OpenSSH for those unit tests if you have 7.6 or later installed.

**Comment by vincentbernat** [comment]
Great! I have also this error:

```
======================================================================
ERROR: tearDownClass (tests.test_agent._TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-asyncssh-1.11.0/tests/util.py", line 319, in tearDownClass
    cls.loop.run_until_complete(cls.asyncTearDownClass())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/build/python-asyncssh-1.11.0/tests/test_agent.py", line 124, in asyncTearDownClass
    os.kill(cls._agent_pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process

----------------------------------------------------------------------
```

I thought at first that it was because agent doesn't clean its socket on shutdown, so I added a "rm -f agent" before spawning the agent, but no change. I'll investigate if you don't know.

**Comment by ronf** [comment]
Yeah - I've gotten that error here locally once or twice lately, but it doesn't seem to be related to any change I've made, and it doesn't happen consistently. I'm wondering if there might be some kind of crash happening in the ssh-agent process, since that's what it doesn't seem to be able to find on tear down.

Which platform are you seeing this on? It hasn't come up so far on Travis CI on either Mac or Linux builds, but I have seen it locally a couple of times on a Mac. I could easily ignore this error, but that process really shouldn't be going away on its own.

**Comment by vincentbernat** [comment]
I am getting it with Debian Sid. It seems to be reproducible (3 out of 3 times). It has been uncovered here: https://udd.debian.org/dmd.cgi?email1=bernat%40debian.org. I'll add more debug output to understand why it happens (redirecting stderr to a file instead of /dev/null).

**Comment by vincentbernat** [comment]
Let's close this one. I'll open another one for the ssh-agent problem.
