### ISSUE TITLE
SCP Wildcard issue on bash, but it works on zsh

### ISSUE THREAD

**Issue by alshain** [ronf/asyncssh#116]
Connected to two different Linux systems, I get different behavior for the following call:

    asyncssh.scp((con, "logs/*"), "/local/path", recurse=True)

On one system, Ubuntu 16.10, with shell set to zsh, this works flawlessly.

On the other system, Ubuntu 14.04 LTS, with shell set to bash, I get "file not found".

Of course, said directory exists on both systems and files are present. If I remove the wildcard, it works fine on both systems, except for the fact that I get an additional subfolder "logs" which I don't want.

Is this issue caused by different shells or something else?

```
awaiting memcached shutdown [<asyncssh.connection.SSHClientConnection object at 0x7fde5e805908>]
Traceback (most recent call last):

  File "automate.py", line 654, in gather_logs
    await download_file(client)
  File "automate.py", line 651, in download_file
    await asyncssh.scp((con, f"logs/*"), expanded, recurse=True)
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 787, in scp
    yield from sink.run(dstpath)
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 529, in run
    self.handle_error(exc)
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 249, in handle_error
    raise exc from None
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 527, in run
    yield from self._recv_files(b'', dstpath)
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 513, in _recv_files
    self.handle_error(exc)
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 249, in handle_error
    raise exc from None
  File "/home/alshain/.pyenv/versions/general/lib/python3.6/site-packages/asyncssh/scp.py", line 481, in _recv_files
    suppress_send=True)
asyncssh.scp.SCPError: SFTP Error: scp: logs/*: No such file or directory

```

**Comment by ronf** [comment]
I haven't been able to reproduce this here so far, on either MacOS or Linux. I don't have an Ubuntu 14.04 system handy, though, so I've only been able to try changing my shell between "bash" and "zsh" on MacOS 10.13.1 and Ubuntu 16.04.3 LTS.

Can you try changing to zsh on 14.04 LTS or changing to bash on 16.10 to see if the relevant difference is the Ubuntu version or the shell you are running?

Also, can you add a progress handler callback, and print out the "src" and "dst" strings that you get back when SCP is run?

You might also want to check if "noglob" is set on the system where scp is failing, and that the directory bash sets as the current working directory on that system is the one that the "logs" directory is located in. If that looks ok, I'd suggest trying to have asyncssh run a shell command of "echo logs/*" on the system you are trying to copy from and see what you get back.

**Comment by ronf** [comment]
After thinking about this a bit more, I'm pretty sure you'll find "noglob" is the problem here, since you said it worked (other than the extra level of "logs" directory) when you removed the wildcard. It may be getting set in the .bashrc on the remote system, preventing "scp" when it runs there from getting an expanded list of files to copy.

**Comment by alshain** [comment]
Thanks a lot for the reply. I checked for noglob, but didn't find it in the bash configuration.

The issue is probably the following: When no files are present in the directory, it raises this error. I run all commands across many machines, and probably one did not have any log files.

Below, I made a script to test globbing: It works on the "problematic" machine, and fails when I delete the files before trying to download them, so that's probably it.



```python
import asyncio
import asyncssh
import argparse
import os


LOCAL = False
NO_FILES = False

def connect_string():
    if LOCAL:
        return "local_user", "local_vm"
    else:
        return "remote_user", "remote_host"

TEST_DIR = "ssh_test2"

async def setup_remote_host(con: asyncssh.SSHClientConnection):
    await con.run(f"mkdir -p ~/{TEST_DIR}")
    await con.run(f"rm -rf ~/{TEST_DIR}/*")
    await con.run(f"rm -rf ~/{TEST_DIR}/*")
    if not NO_FILES:
        await con.run(f"touch ~/{TEST_DIR}/a")
        await con.run(f"touch ~/{TEST_DIR}/b")
        await con.run(f"touch ~/{TEST_DIR}/c")


async def test_ssh():
    user, host = connect_string()
    con: asyncssh.SSHClientConnection = await asyncssh.connect(host=host, username=user, known_hosts=None)
    print("Connected")
    await setup_remote_host(con)
    print(await con.run("echo {TEST_DIR}/*"))
    print(await con.run("echo *"))
    os.makedirs(os.path.expanduser(f"~/{TEST_DIR}"), exist_ok=True)
    await asyncssh.scp((con, f"{TEST_DIR}/*"), f"/home/osboxes/{TEST_DIR}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--local", action="store_true")
    parser.add_argument("--no-files", action="store_true")
    arguments = parser.parse_args()
    LOCAL = arguments.local
    NO_FILES = arguments.no_files
    asyncio.get_event_loop().run_until_complete(test_ssh())
```

**Comment by ronf** [comment]
Indeed - that seems to be it, and it's an issue specific to bash (or at least not applicable to zsh).

I did a little more digging, and this is a settable option in bash. If you add "shopt -s nullglob" to your .bashrc, it will cause glob patterns that don't match anything to expand to the empty string rather than leaving them unchanged, which is what is leading to the error here.

**Comment by alshain** [comment]
Maybe it would be good to mention, that wildcard behavior depends on the shell being used?

> Wild card patterns are also supported on source paths.

http://asyncssh.readthedocs.io/en/latest/#scp-client

Initially, I read this as `asyncssh` itself supporting wildcards. From what I understand now, it's just a string that's interpolated on the target system's shell, so it's not actually an asyncssh-feature?

**Comment by ronf** [comment]
In the specific example I was giving there, the wildcard expansion was in fact being done by AsyncSSH, since it was copying local files to a remote system. When doing a copy from a remote system of wildcard patterns, though, it is up to the remote system to do any wildcard expansion. Unlike sftp, there are no operations in SCP to query the remote filesystem. All you can do is execute an "scp" command with some flags and filename arguments, and it's up to the remote system to decide what to do from there. In the case of UNIX systems, the wildcard expansion is generally done by the user's login shell before invoking scp, but other scp implementations (including AsyncSSH's own scp server) may have no shell involved where it's up to the server to do the expansion of the arguments itself.

I can be more explicit in the documentation about this, but I probably wouldn't want to get into the specifics of config switches of remote shells which affect expansion. What do you think of:

>  Wild card patterns are also supported on local source paths. For instance,  the following copies all files with extension "txt":
>
>      await asyncssh.scp('*.txt', 'localhost:')
>
> When copying files from a remote system, any wild card expansion is the responsibility of the remote SCP program or the shell which starts it.

**Comment by alshain** [comment]
Ah I see, I don't really understand how SCP actually works, hence my need for assumptions. Thank you for the explanation.

> What do you think of:

I think this explains things nicely, thanks again!
