### ISSUE TITLE
How to Interact with network device like a shell

### ISSUE THREAD

**Issue by lyonsdpy** [ronf/asyncssh#121]
I want to interact with a swith(or a router) use AsyncSSH just like SecurCRT does,but I don't get it.
the CRT works flow >> SSH Session --> command1 --> see output1 --> command2 --> see output2 --> command exit --> server close the session

but when I in AsyncSSH
1、I must send EOF after every commands,Otherwise there will not have any output in read() or readline().(awaiting forever), and if the EOF send, the second command will not exec and raise "Channel not open for sending"
2、So I tried run each of my command in each create_session(),open_session(),create_process(),run(),all of these def will create a new channel to server.It means if I have 2 commands，it will work in two different chan . anyway It works, but much slow.

So, is there any ways to execute command like these：
In one channel, I can send command1 and then read output1，after that I still can send command2 and than read output2. 
(the writelines() can send all command ,So  I just can read all of them together, thus I can't insert any judgment logic)

exp1:
```
    for command in command_list:
        print("**************************%s******************************" % command)
        process.stdin.write(command)
        process.stdin.write_eof()
        line = await process.stdout.read()
        print(str(line))
```
>If no "process.stdin.write_eof()" ,  "await process.stdout.read()" or readline() never return, even set read(n=1024)

exp2:
```
        remote_result1 = await conn.run('ls')
        remote_result2 = await conn.run('pwd')
        print('##' * 40)
        print(remote_result1.stdout, end='')
        print('##' * 40)
        print(remote_result2.stdout, end='')
```
> it works , but it show two Welcome string lines before each command, so I think its run in two different vty lines for the swith

**Comment by ronf** [comment]
If you can identify the end of the output of each command in some way, it should be possible to do what you want here of sending multiple commands in a single session. You would need to use either readline(), reading multiple lines until you see the end marker, or use read() with a maximum length to return. When using read with no argument (or -1 explicitly as the length), it is documented to block until it gets an EOF from the other side, and that's what you are seeing here:

> read(n=-1)
>
>  Read data from the stream
>
> This method is a coroutine which reads up to n bytes or characters from the stream. If n is not provided or set to -1, it reads until EOF or a signal is received.

You say that you saw the same problem with readline() and read() with n set to 1024, but that shouldn't be the case. Unless you use readexactly(), read() should return as soon as any data is available, and readline() should return as soon as a full line of output (with a newline at the end) is available.

You're right that using run() opens and closes a new channel every time, and in that case it'd be OK to write EOF and read until EOF each time. This still happens over a single SSH connection with a single authentication operation, so it should be quite fast unless there's a lot of processing on the remote system each time you start up a new shell process. Since you do get a new shell every time, though, some things like trying to run a command to change directory or set environment variables won't work if you go with that approach. You'd have to combine such things into a single command since each command runs in its own fresh shell.

**Comment by lyonsdpy** [comment]
thanks for your help, now I already can read the info from the readline(),but another problem came when I try it to read info from a Huawei Switch.(witch works correctly on Linux)
It returned messy codes.

**Comment by ronf** [comment]
Could you provide more detail about the output you are getting vs. what you are expecting, and how you are reading it?

**Comment by lyonsdpy** [comment]
I used wrong word "messy codes" before , actually the output has a lot of blank and I get the right output after use strip().

but I'm now puzzled by following code：

exp1: (its work)
```
command = 'display cur'
async with conn.create_process(command) as process:
      while True:
           line = await process.stdout.readline()
           if line:
                print(line.strip())
```

exp2:(nothing output)
```
command = 'display cur'
async with conn.create_process() as process:
      process.stdin.write(command)
      process.stdin.write_eof()
      while True:
           line = await process.stdout.readline()
           if line:
                print(line.strip())
```

what's the diffrent between exp1 and exp2 ?

exp3:(its work again)
```
command = 'display cur'
async with conn.create_process(term_type="vt100") as process:
      process.stdin.write(command + "\r\n")
      process.stdin.write_eof()
      while True:
           line = await process.stdout.readline()
           if line:
                print(line.strip())
```

but exp3 give's the "term_type" a value(default is None),so it will request a pseudo-terminal. however , the switch paused the output after read "--MORE--",I need to press a space key to output more.

So I'm now confused about the 3 examples, why exp1 can works but exp2 not ,  why exp3 works after setting a "term_type" ? Is there a common way to control all ssh devices ?

**Comment by ronf** [comment]
The difference between exp1 and exp2 is that in exp1 you are requesting to run 'display cur' as a standalone command, whereas in exp2 you are asking to start up an interactive shell on the remote system and then writing 'display cur' to it. However, you are not writing a carriage return at the end of the command, so the remote system is still waiting for more input before executing anything. You'll need to write command+'r' rather than just command by itself.

With exp3, you send '\r\n' after command, which is probably more than you need, but this gets the command to execute. My guess is that you'll see an extra command prompt at the end of the output, though, from the extra '\n' you are sending as input.

As you said, exp3 also asks for a PTY, so there will be other differences. In addition to the thing you mention about '--MORE--' prompts, the version where you ask for a PTY will combine together all the output to stdout and stderr, whereas running exp1 or exp2 would keep those separate. That probably doesn't matter in this case if you are talking to a switch, as it might not use stderr for anything. However, it's something to keep in mind when running SSH commands on other targets.

My suggestion is to try exp2 with the write() call changed to write command+'\r'. I think that'll fix the problem you see there. However, exp1 is probably the right way to do this for single commands. Opening an interactive shell like exp2 should only be needed if you want to run a series of commands on a single session or run commands that require extra interactive input, where you need to alternate between output and input while driving it. In that case, though, you wouldn't want to do the write_eof() until you're all done providing input.

By the way, the reason for the blank lines when you weren't using 'strip()' is that readline() returns the '\n' at the end of each line it returns. If you want to call print() on it, you should do it with an extra argument of end='' to suppress adding another newline. In that case, you won't need to do the strip().

**Comment by lyonsdpy** [comment]
I've tried  <font color="red">process.stdin.write(command +'\r\n')</font> in example2 before, but nothing changed. That's why I tried example3.

because the test env is in comany intranet, I just can describe the output like below pseudo code
```
command = "display current-configuration"
Expected output = 1000lines
```
exp1_output:
```
Connection made to 10.130.5.15
Authentication successful
line 1 content
line 2 content
line 3 content
....
....
line 1000 content

Process finished with exit code 0
```
exp2_output:(add "\r\n"or"\r" in stdin.write())
```
Connection made to 10.130.5.15
Authentication successful
```
exp3_output:
```
Connection made to 10.130.5.15
Authentication successful
line 1 content
line 2 content
line 3 content
...
...
line 30 content
--More--
```

You can see that exp2 and exp3 never exit.

**Comment by ronf** [comment]
Did you remove the write_eof() calls from exp2 and exp3? If so, that might explain why those cases didn't exit. The first case would exit even without a write_eof(), as the SSH server should close the session as soon as the command exits, but in the other cases you are opening an interactive shell so it would wait for a new command to be sent each time the current command finished running.

I can't explain why exp2 would still produce no output if you sent in a command with a proper line ending. It must be waiting for some other input from you. Could it be prompting for something? If you do a read(1024) instead of readline(), do you see ANY output returned?

As for exp3, it would make sense that it would be stuck waiting for input once it printed "--More--". If you didn't provide input and didn't do a write_eof(), it would block forever there. If you did write_eof(), I'd expect it to continue on and clean up, but it might do so without producing the rest of the output. You'd need to find a way to disable that paging functionality (by writing some earlier command to turn it off, for instance) if you want to set the terminal type.

**Comment by lyonsdpy** [comment]
When I debugging the exp2 , I find the coroutine 'process.stdout.read(n=1024)' or 'process.stdout.realine()' returns ''(None) everytime . 

if "conn.create_process()" with term-type ,it works well
if "conn.create_process()" with command, it works well

I find All the functions which create client channel ( include create_process(),open_process(),run(),open_session() ) all call create_session().
and then create_session() call chan.create() .

the chan.create() will judge whether the command is Null, the source code p below:
```
        if command:
            result = yield from self._make_request(b'exec', String(command))
        elif subsystem:
            result = yield from self._make_request(b'subsystem',
                                                   String(subsystem))
        else:
            result = yield from self._make_request(b'shell')
``` 
And I think my problem is relating to the 'exec' and 'shell'.  the 'shell' maybe have some different with 'exec'  in SSH protocol , maybe the 'shell' need server to support some function .

**Comment by ronf** [comment]
Your exp1 would be sent as an 'exec' request as long as command wasn't an empty string, while exp2 and exp3 would be sent as 'shell'. As you already mentioned, setting the term_type would trigger a PTY request. The differences in handling of these cases would really depend on the target system, though. There's really no difference on the client side after that except that when a PTY is requested all the output will generally come back on stdout, rather than it being split between stdout and stderr. Even that is really up to the target system, though.

Getting the value None back from the read calls doesn't really make sense, though. As far as I know, AsyncSSH never returns None from these calls. At EOF, it should return an empty string. Otherwise, it returns a non-empty string or raises an exception.

Are you sure that None is actually being returned by the process.stdout.read calls? Can you confirm that the process.stdout object is actually an SSHReader object when you see this?

**Comment by slieberth** [comment]
I am working on a module, which is based on asyncssh for router/switch automation. asyncssh works great in this scenario. Key is that the output is parsed and a specific router prompt is identified. Then the next CLi command is send and so on.  I have currently tested with Juniper and Cisco-XR. Please give me a couple of days to upload the repo (@github) and the documentation (@readthedocs)
If someone is interested I can share the asyncssh code snippets on this channel.

**Comment by ronf** [comment]
@slieberth - If you'd like to post a link here to your project once it is uploaded, that sounds great. It might serve as an example for others who find this thread later. Thanks very much!

**Comment by slieberth** [comment]
my aioRunbook project is still in the early phase from documentation perspective ... but nevertheless I give it a try:
https://github.com/slieberth/aioRunbook
please check following module for the asyncssh part:
https://github.com/slieberth/aioRunbook/blob/master/adapters/aioSshConnect.py

interaction with routes are controlled by a yaml config file, e.g.
---
- check:
    name: "myXR - set hostname"
    commands:
      - conf
      - hostname myXR
      - commit
      - exit
    textFSMOneLine: '(.*error.*) 0'
- check:
    name: "myXR - verify hostname setting"
    commands:
      - show running | incl hostname
    textFSMOneLine: '(.*myXR.*) 1'
---

the host parameters are defined separately:

---
myXR:  {'device': '192.168.56.31','method':'ssh','vendor':'cisco','password': 'cisco', 'user': 'cisco'}
---

I will post another note, once the documentation and installtion-procedure is more mature

**Comment by lyonsdpy** [comment]
@ronf 
Thanks,I'll review exp2 code and test again on Monday. (The enviroment is in my company) .

Yesterday I send a mail to the device manufactor , they tell me that I must request a pty in SSH session  due to the product implementation. but I don't want meet the scrolling pause . so I tried to set term_size(0,1000000) , it works on cisco , juniper , but not on huawei , h3c . 

then I find there is a command to control it , so I insert it before my first command , whereas I must send the "vendor" value . 

maybe there is another way to solve it . 

@slieberth 
In my experience there was almost no change in a vendor's platform bottom protocol implementation. but cisco and juniper having the same gene.  I suguest you to test more like fortinet,huawei etc.

In addition , have you cansider about integrate netconf in aioRunbook project ?  the "ncclient" project uses "paramiko" as ssh service , as I know there isn't an "aioNetconf" based on "asyncssh" yet .

**Comment by slieberth** [comment]
@lyonsdpy :  thanks for feedback ... 
having worked for both companies, my experience is that juniper and cisco are actually quite different from CLI perspective  ;-) . However complexity comes in with both (actually with any) network-system-vendor: how do change to coonfig mode ... how do you deal with command confirms like "do you really want to clear the counters" (cisco), how do you detect the new prompt in cisco if you change to admin level ...  or if you connect to line cards on a juniper device ... 
Yes - there are methods (concurrent.futures.ThreadPoolExecutor) to integrate blocking adapters like pysnmp and ncclient. I have already integrated pysnnmp (from Ilya Etingof) as first blocking adapter into aioRunbook ... and ncclient will follow by end of February.

**Comment by slieberth** [comment]
yes, there is the need to send vendor specific commands to disable paging ( "set cli screen-length 0\n" for juniper and "terminal length 0\n" for cisco )
in addition the output must be cleaned up:  corrections of the line break format and non printable characters. (e.g. cisco tend to send occasionally backspace characters in the CLI output, this triggered actually an error in my pdflatex post-processing)
This is already implemented in my aioSshConnect adapter (We have actually experience in using the logic with a  blocking ( pexpect ) variant over the last two years in a tier one telco. 
There is another asyncssh collection on github: netdev 
Also there is the netmiko (blocking - paramiko based) collection of Kirk Byers.

**Comment by ronf** [comment]
Closing this for now since it has been inactive for a couple of months, but feel free to open a new issue if you have additional questions or concerns.

**Comment by cardador** [comment]
Since I ended up in a similar situation as stated by @lyonsdpy in the early text and found the discussion useful to solve my problem, mainly based on @slieberth's code, I have written a code snippet and would like to share it here, hopefully it can help someone:
https://github.com/cardador/snippet_asyncssh
In a short summary, I wasn't able to get the stdout/stderror buffers using the process object returned by create_process, instead I used create_session in a similar way except for the buffer redirection.

**Comment by ronf** [comment]
It should be possible to make this work with the regular create_process call. Here's a modification to the script you posted that shows an example of this. It also fixes a minor issue with the way you provided the username:

```python
import asyncio, asyncssh, sys
import logging

PROMPT = r':~$'


class Target:

    async def _run_client(self, cmdsequence, ip, **kwargs):
        async with asyncssh.connect(ip, **kwargs) as conn:
            process = await conn.create_process(
                # next line should point to an interactive (slow in my case)
                # process on a remote host'
                command='<remote process, eg: bc>')
            await asyncio.wait_for(process.stdout.readuntil(PROMPT), timeout=10)
            for cmd in cmdsequence:
                process.stdin.write(cmd + '\n')
                result = ''
                try:
                    result+=await\
                            asyncio.wait_for(
                                process.stdout.readuntil(PROMPT),timeout=10)
                except Exception as e:
                    logging.warning("prompt timeout step {}".format(e))
                print(result, end='')

    def remote_cmd(self, cmdsequence, ip, **kwargs):
        try:
            asyncio.get_event_loop().run_until_complete(
                self._run_client(cmdsequence, ip, **kwargs))
        except (OSError, asyncssh.Error) as exc:
            sys.exit('SSH connection failed: ' + str(exc))


tg = Target()
tg.remote_cmd(['2+2', '1*2*3*4', '2^32'], '192.168.0.100', username='<user>')
```

Basically, when you use create_process(), you just need to use the returned "process" instead of "session", and change the "chan.write" to "process.stdin.write".

**Comment by cardador** [comment]
Hi @ronf, thanks for the quick answer and suggestion for this solution. Yeah indeed it worked the way you suggested, I will update the other scripts to use create_process instead!
Thanks!
