### ISSUE TITLE
Allow begin_auth to be a coroutine

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#122]
I am wondering if the `asyncssh.SSHServer.begin_auth` could be a coroutine. My basic testing doesn't appear to allow this. I drilled down into the code a bit, but it seems like several level of functionality would need to be modified to support coroutines. Would this be a crazy change to make?

As for why - in my case I want to store usernames in a database. But even a more simple setup might have all the usernames on disk somewhere. Seems like IO would be a common operation in this function.

**Comment by b-ryan** [comment]
Great - I will be excited to try out that enhancement.

In my case I didn't paint the entire picture of what I am doing. I am using a database, but accessing it through an HTTP service. I have been looking at aiohttp for the async portion of things there.

**Comment by ronf** [comment]
I see - that makes sense, and I think it should work well here.

I've just checked in commit e692f42 to the develop branch. With this change, you should be able to define begin_auth() in your SSHServer class as a coroutine if you need to, and perform async operations within it.

The only thing to keep in mind is that this coroutine may be canceled if the connection closes while you are in the middle of retrieving data. In that case, make sure you re-raise CanceledError if you try to catch that to clean anything up, so that AsyncSSH can finish doing its own cleanup.

**Comment by ronf** [comment]
This change is now released in AsyncSSH 1.12.0. If you have any problems with it, feel free to open a new issue (or reopen this one).

**Comment by b-ryan** [comment]
Excellent thank you! I am hoping to have some time this week to try it out

**Comment by b-ryan** [comment]
@ronf was this released to pypi? I am seeing the latest version as 1.11.1

**Comment by ronf** [comment]
My fault - I missed that step! It was available on Github and updated on ReadTheDocs, but not on PyPI. That should be fixed now.

Thanks for catching this!

**Comment by b-ryan** [comment]
You got it! Confirmed it's on there now, thanks for the quick response.
