### ISSUE TITLE
Server: detect if no SSH keys available for auth OR support "none" auth

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#124]
I see the code always disables the "none" authentication method. I have a use case for it. Although you might be able to tell me a way to accomplish what I want without it.

If a user does not have any SSH keys, they will be denied and all they will see is "Permission denied (publickey)." This is not behavior I want. I would prefer that if I can detect in some way the user has no keys, send them a custom message, like "you need to create an ssh key first" and then fail the auth.

If this is not possible, then I would like to just allow the "none" authentication method and deal with it in some custom way - I know what I am getting into in this scenario.

Thoughts?

**Comment by ronf** [comment]
According to RFC 4252:

>Authentication methods are identified by their name, as defined in
>[SSH-ARCH].  The "none" method is reserved, and MUST NOT be listed as
>supported.  However, it MAY be sent by the client.  The server MUST
>always reject this request, unless the client is to be granted access
>without any authentication, in which case, the server MUST accept
>this request.  The main purpose of sending this request is to get the
>list of supported methods from the server.

So, while you can return success when the client sends the initial request for auth of "none", that would disable auth entirely for the client, which is not what you want here. Since "none" is not allowed to be in the list of auth methods returned by the server, though, you can't stack it behind other forms of auth.

However, I have an application that needed something like this, and I did it by enabling kbdint authentication and then having that return True immediately in get_kbdint_challenge() to allow the authentication to proceed without the user actually seeing a challenge. In my case, I kept a local variable in my application which allowed me to tell whether this fallback was used or not, so I could behave differently later after the auth completed when the user opened a channel.

In your case, you might be able to get the kbdint auth itself to print the message and then fail through the challenge mechanism without specifying any prompts. Alternately, if you are ok returning this message in the disconnect error, you could send your own disconnect right from the auth callback. For instance, try adding the following to your SSHServer subclass:

```python
    def kbdint_auth_supported(self):
        return True

    def get_kbdint_challenge(self, username, lang, submethods):
        self._conn.disconnect(asyncssh.DISC_NO_MORE_AUTH_METHODS_AVAILABLE,
                              'You need to create an SSH key first')
```

This results in output such as:

>Received disconnect from ::1 port 8022:14: You need to create an SSH key first
>Disconnected from ::1 port 8022

If you also support public key auth in this server, that should be preferred, but it'll fall back to kbdint if that fails and end up returning this disconnect message.

**Comment by b-ryan** [comment]
I had read that section of the RFC but did not grasp the fact that "none" was sent initially as a way to get a list of other auth methods.

Thanks a lot for the information. This is very informative and using interactive auth should do the trick.

**Comment by telnet23** [comment]
For what it's worth, a similar library, [Paramiko](https://www.paramiko.org), allows "none" to be specified as an authentication method in [`get_allowed_auths`](https://docs.paramiko.org/en/stable/api/server.html#paramiko.server.ServerInterface.get_allowed_auths) and calls [`check_auth_none`](https://docs.paramiko.org/en/stable/api/server.html#paramiko.server.ServerInterface.check_auth_none) to check whether the "none" authentication method is successful.

**Comment by ronf** [comment]
This is a very old issue. Since then (specifically, in AsyncsSH 2.10. 0), there's a new top-level AsyncSSH method named get_server_auth_methods() which can return the list of available auth methods for a given user on an SSH server. See #453 for more details.

If no auth is required, this new method will return `['none']`. Otherwise, it will return a list of supported auth methods, as returned by the server, without the need for the application to specify 'none' or handle the resulting `PermissionDenied` error.

In cases where authentication is required, preferred_auth can be used on the client to specify the preferred order of auth methods to attempt, but `'none'` should never appear in that list.
