### ISSUE TITLE
Docs incorrect for SSHServerSession

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#125]
https://github.com/ronf/asyncssh/blob/0267f2e98c60dd77f3fff8b6572ed50389b14751/asyncssh/session.py#L27

The docs say the `connection_made` function will receive an instance of `SSHClientChannel`, but for server sessions, this will actually be an instance of `SSHServerChannel`. I would make a PR to fix but I don't know the best way to do this.

**Comment by ronf** [comment]
Thanks for catching this, Buck.

It looks like the problem is that I defined connection_made() on the parent class SSHSession, so the same documentation is inherited by both SSHClientSession and SSHServerSession. Even though the function signature is otherwise identical between the two, I guess I'll need to remove it from the parent and duplicate it on the two child classes if I want to be able to document a different type for the chan argument there.

This is a pretty simple change - I'll get it into the "develop" branch shortly, and it'll go into the next release when it goes out.

**Comment by ronf** [comment]
Ok - this fix is in commit 9f2b6fb. Thanks again!

**Comment by b-ryan** [comment]
You got it.
