### ISSUE TITLE
Official public API of SSHAuthorizedKeys validate function?

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#126]
Hey @ronf,

The application I am writing needs to do its own public key validation within the `validate_public_key` function. To do this, I am creating an instance of SSHAuthorizedKeys and checking that the `validate` function returns a dict, essentially:

```python
authed_keys = asyncssh.import_authorized_keys("\n".join(pubkeys))
authorized = isinstance(authed_keys.validate(key, client_addr), dict)
```

Is this correct? And whether or not it is, could this be documented either by an example (for the validate_public_key function) or in the API documentation for SSHAuthorizedKeys (or both)? I am happy to make a PR to do this so long as I know the code I am using is correct.

**Comment by ronf** [comment]
Doing proper validation against authorized_keys requires a bit more than what you've got here, if you want to be able to support both client keys and client certificates. That's one of the reasons that SSHAuthorizedKeys is basically a black box right now which exposes methods to load authorized keys entries, but not any functions to do validation.

In the specific case where you need to support only regular public keys and not certificates, what you're doing would probably work, but I think it would be better to actually change that from an isinstance() call to something like:

```python
authorized =authed_keys.validate(key, client_addr) is not None
```

Can you say a bit more about what you are doing here, though? If you set the authorized keys in AsyncSSH, it will automatically do this check for you and only call validate_public_key() on your SSHServer object when there are no authorized_keys matches. I'm guess in this case you aren't setting the authorized_keys on AsyncSSH at all and that's why you need to do this call, but I'm wondering if there might be another way.

For instance, the begin_auth() method provides you with the user name, and you call choose which set of authorized_keys to load form within that callback if you don't want to share a single authorized_keys list for all users. That would allow you to leverage this existing authorized_keys matching and avoid you needing to make this call yourself in validate_public_key(). It would also properly handle both client keys and certificates when done that way. There's an example of this in the "Simple Server":

```python
    def begin_auth(self, username):
        try:
            self._conn.set_authorized_keys('authorized_keys/%s' % username)
        except IOError:
            pass

        return True
```

**Comment by b-ryan** [comment]
Perhaps I could get away with using the built in authorization. The key thing for me is that I would like to keep track of which key was authorized. Essentially I am setting things up such that for certain users, any public key will be accepted and I will keep track of that public key. Future authentication attempts will require the same key.

**Comment by b-ryan** [comment]
Actually, having just written that and knowing that `validate_public_key` will be called when there are no authorized keys matches, I think I realized how I can make this happen. I will re-open this if I run into a snag.

Thanks again!
