### ISSUE TITLE
Exception when using coroutine for connection_requested

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#127]
I am seeing an exception in the logs when an SSHServer's `connection_requested` function is implemented as a co-routine and returns `False`. Server code:

```
import logging
import asyncio, asyncssh, sys

logging.basicConfig(level=logging.DEBUG)


class MySSHServer(asyncssh.SSHServer):
    async def connection_requested(self, dest_host, dest_port, orig_host, orig_port):
        return False

async def start_server():
    await asyncssh.create_server(MySSHServer, '', 8022,
                                 server_host_keys=['/home/buck/.ssh/connect-master.key'],
                                 authorized_client_keys='/home/buck/.ssh/authorized_keys')

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH server failed: ' + str(exc))

loop.run_forever()
```

Now try to make a direct TCP/IP channel:

```
ssh -p 8022 buck@localhost -N -L 1234:localhost:3306
mysql --host 127.0.0.1 --port 1234
```

LOGS:

```
Traceback (most recent call last):
  File "/home/buck/.virtualenvs/polecat-ssh/lib/python3.5/site-packages/asyncssh/connection.py", line 409, in _reap_task
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/buck/.virtualenvs/polecat-ssh/lib/python3.5/site-packages/asyncssh/channel.py", line 1791, in _finish_open_request
    yield from super()._finish_open_request(session)
  File "/home/buck/.virtualenvs/polecat-ssh/lib/python3.5/site-packages/asyncssh/channel.py", line 440, in _finish_open_request
    self._session.connection_made(chan)
AttributeError: 'bool' object has no attribute 'connection_made'
```

I am able to eliminate the exception by raising a `ChannelOpenError` though, as the code suggests. I thought it would be nice to make a PR to fix this so this is what I have found.

It looks like when this is not a coroutine this line handles the `False` return values: https://github.com/ronf/asyncssh/blob/0267f2e98c60dd77f3fff8b6572ed50389b14751/asyncssh/connection.py#L3911

But since it is a coroutine it is not handled until here: https://github.com/ronf/asyncssh/blob/0267f2e98c60dd77f3fff8b6572ed50389b14751/asyncssh/channel.py#L424

So the most straightforward solution is to raise a ChannelOpenError there. I can make a PR to do that but obviously if you'd like to approach it differently let me know.

**Comment by ronf** [comment]
Thanks for the report. What you're trying to do here is technically not supported at the moment, though. The connection_requested() method is not allowed to be a coroutine. I could change that, but if you take a look at the current documentation, it says the following:

> If blocking operations need to be performed before the session
> can be created, a coroutine which returns an
> :class:`SSHTCPSession` object can be returned instead of
> the session iself. This can be either returned directly or as
> a part of a tuple with an :class:`SSHTCPChannel` object.

So, you are allowed to _return_ a coroutine from connection_requested(), but connection_requested() itself is not (yet) allowed to be a coroutine. This coroutine can either be returned by itself or it can be the second value in a tuple along with an SSHTCPChannel object, but the decision about whether to allow the connection or whether to use standard port forwarding must be made immediately the way it is currently coded. You can only defer the work using a coroutine if you decide you want to allow the connection but want to return a custom SSHTCPSession object. Also, if you want to create a custom SSHTCPChannel object, right now that must be done immediately in connection_requested() and not deferred. The coroutine you return is only allowed in place of the SSHTCPSession part of the return value.

I could probably allow connection_requested() to be a coroutine, following a pattern that looks more like _process_tcpip_forward_global_request() and _finish_port_forward() in SSHServerConnection. That way, I could handle not only the "False" return value here but also the "True" return value to trigger standard port forwarding, and the ability to defer creating an SSHTCPChannel. For backward compatibility, I'd still need to allow just the SSHTCPSession part of the return value to be a coroutine as well, though. That was always kind of ugly and I never liked it much, but when I first came up with that I hadn't really figured out the pattern I settled on later for allowing my packet processing callbacks to create tasks when they needed to support calling coroutines.

In your fix, I think you might also run into a problem in cases where the line editor is enabled. The call to _wrap_session() there assumes the value is already a real session object. You'd want to do the check before the call to _wrap_session(). The bigger issue there, though, is not handling the other return values like True and a tuple of (chan, session). It would not make sense to allow a return value of (chan, False), but that's something your change would end up attempting to support.

Are you actually doing some kind of async operation in order to decide whether to return False or not?

**Comment by b-ryan** [comment]
Ah! That makes sense - thank you for the clarification and sorry for not reading the docs closely enough.

I am not doing anything async to decide whether or not to return False, just doing blocking work to initialize the connection. I just switched my code to do this the supported way.
