### ISSUE TITLE
Question - How to create a dynamic SSH Tunnel

### ISSUE THREAD

**Issue by lux-lth** [ronf/asyncssh#141]
Hello Ron,

I'm would like to setup dynamics SSH tunnels using asyncSSH, but I have no idea how to do that.

I basically want the equivalent to : 

`ssh -D4445 user@domain.tld`

I've seen this : https://asyncssh.readthedocs.io/en/latest/#port-forwarding

But it doesn't seem to allow dynamic port forwarding, or am I missing something ?

Could you point me to the right direction please ?

Best regards,
Loïc.

**Comment by ronf** [comment]
Unfortunately, this is one of the few features of OpenSSH that isn't available in AsyncSSH yet. It probably wouldn't be too difficult to add, but I wasn't really sure it would be of much use given that you could just open tunnels to arbitrary ports on the server side directly using calls in AsyncSSH, rather than relying on something like SOCKS to communicate what port you wanted to access.

Could you tell me a bit more about your use case? Are you trying to use AsyncSSH to set up an SSH connection but then have other external applications which support acting as a SOCKS client that want to forward traffic over that connection?

**Comment by ronf** [comment]
I've checked in a first cut of SOCKS dynamic port forwarding in the develop branch (8383894). Look for the new method forward_socks() on SSHClientConnection which you can use instead of forward_local_port(), if you want to set up a SOCKS listener which can accept dynamic host/port information. SOCKS versions 4, 4a, and 5 are supported.

I'm not sure if this was what you were looking for, but if so I'd love any feedback on whether it works for you or not!

**Comment by ronf** [comment]
TCP/IP dynamic port forwarding via SOCKS is now available in AsyncSSH 1.13.0.

**Comment by lux-lth** [comment]
Hey Ron, I'm sorry I didn't took the time to test this, I tried though, but some issues with pip, ssl, ...
Judging by your great skills I'm pretty sure you did that nicely, thank you again for all the great work on this. AsyncSSH is great !

**Comment by ronf** [comment]
No worries - it should be easier to test now that it's available on PyPI. I'm glad that AsyncSSH is working well for you.

If you have any problems with forward_socks() or you have any other suggestions, let me know!
