### ISSUE TITLE
recursive option on SFTPClient.glob

### ISSUE THREAD

**Issue by silverwind** [ronf/asyncssh#143]
Would it be possible to add  [glob's recursive option](https://docs.python.org/3/library/glob.html#glob.glob) option to [SFTPClient.glob](http://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClient.glob) to enable use of `**` patterns?

**Comment by ronf** [comment]
Yes - that seems like a nice enhancement. Thanks for the suggestion!

I don't think a separate keyword argument should be requited to enable it, though. Just specifying '**' in your pattern should be good enough to indicate that you want this new feature, since '**' was previously no different than '*' in what it returned.

I worked on this a bit tonight, and I've made some other enhancements while I was there:
  - As requested, '**' can be used for a recursive directory match.
  - Character ranges enclosed in square brackets (like [A-Za-z]) are now supported.
  - Ending a pattern with a trailing slash now returns only directories that match.

I still need to add some unit tests for these new cases, but I should have something I can check into the 'develop' branch by the weekend.

**Comment by silverwind** [comment]
Hmm, I'm slightly leaning to having it to be off by default consistency with `glob`. Comparably, shells also have such options to enable recursive globbing and I think the notion behind them being off by default is to save users from accidents. But if you like to keep it that way, fine with me personally. I always enable recursive globbing everywhere :)

Your other additions are also very welcome, thanks!

**Comment by ronf** [comment]
Normally, I'd also prefer to model things after the corresponding local file APIs. However, there's an added complication here. In addition to glob(), these new features will be available in the pattern matching of the mget(), mput(), and mcopy() functions. All of those already have a "recurse=True|False" argument which means something different, though -- it controls whether to recursively copy any directories which match the specified patterns (whether or not the pattern itself does a recursive match). Having both a "recurse=" and "recursive=" keyword parameter would be very confusing, though, and renaming it something like "recursive_glob=" to try and make it clearer doesn't help much.

I can't really imagine anyone today is using `**` in a pattern and _expecting_ it to behave the same as a single `*`, so I don't think adding this support is likely to break anything, even if it is always enabled. I think that's probably the cleanest option.

If you'd like to try out these few features, it should now be available as commit dfc9820 in the develop branch.

**Comment by ronf** [comment]
The enhanced glob support discussed here is now available in AsyncSSH 1.13.0. If you have any problems with this feature, please let me know!
