### ISSUE TITLE
why the reader block when no data receive？

### ISSUE THREAD

**Issue by diemus** [ronf/asyncssh#148]
it seems that there is no native way to remove login infomation like "Welcome to Ubuntu 18.04 LTS". so i try these code:
`    
async with asyncssh.connect('127.0.0.1') as conn:

        async with conn.create_process() as process:
            await process.stdout.read(8096)

            for cmd in script.split('\n'):
                process.stdin.write(cmd + '\n')
            process.stdin.write_eof()
            result = await process.stdout.read()

            return result`

it works well,but when there is no login infomation, it will blocked. is there a way to avoid this ?

**Comment by diemus** [comment]
@ronf Thank you very much for your help .  I'm still learning how to use your fantastic asyncssh .  I was going to solve this in a very ugly way.  it didn't come to me there is such an elegant solution.  I thought the run method can only run one command at a time like the example in document.  looks like I still have a lot to learn from you

**Comment by ronf** [comment]
Whether run() can support multiple commands or not is really up to the SSH server you are connecting to. In the case of UNIX-based SSH servers, I would generally expect this to work, as it will feed the command you provide in the run() call to a UNIX shell in order to execute it. However, you may find other systems out there which act as SSH servers where this won't work. In such cases, you may end up having to call create_process() without a command, and even possibly break up your input a line at a time as you were doing. However, I'd only suggest doing that if you can't get the simpler solution to work with a particular server.

**Comment by diemus** [comment]
Thanks for your reminding
