### ISSUE TITLE
Question: unit testing SSHReader.

### ISSUE THREAD

**Issue by jonathanslenders** [ronf/asyncssh#149]
Hi @ronf,

Are you aware of any good way to write tests against code that is expecting an ``SSHReader``/``SSHWriter`` pair. Right now, these classes require a session/channel, which makes it difficult to test without having an actual SSH connection.

I was looking into the ``asyncio.StreamReader``/``asyncio.StreamWriter`` which looked ideal, but then I realized they operate on bytes rather then text.

If not, no problem. Thanks in any case.

**Comment by ronf** [comment]
I think you're on the right track here -- SSHReader and SSHWriter are designed to mimic those asyncio classes, with the main difference being that an optional encoding can be passed in when the session/channel objects are created so that the SSHStreamReader/SSHStreamWriter can do I/O on either Unicode data or on raw bytes. You should be able to create your own subclass of StreamReader/StreamWriter that overrides all of the methods that do I/O, though, and just call encode() or decode() to convert back and forth between bytes and Unicode characters before passing the data through.

The only other thing you might need is to stub out a channel and/or logger property on the streams if you use those, or stub out get_extra_info() which can return metadata about the session/channel.

**Comment by jonathanslenders** [comment]
Thanks @ronf,

I ended up doing the following. (in case somebody needs it):

Text reader/writer that work together:
```python
class TextStreamReader:
    """
    SSHReader mock.
    """
    def __init__(self):
        self.stream_reader = StreamReader()
        self.encoding = 'utf-8'

    async def readuntil(self, text: str) -> str:
        result = await self.stream_reader.readuntil(
            text.encode(self.encoding))
        return result.decode(self.encoding)

    async def read(self, amount: int) -> str:
        result = await self.stream_reader.read(amount)
        return result.decode(self.encoding)

    async def readline(self) -> str:
        result = await self.stream_reader.readline()
        return result.decode(self.encoding)

    def feed_text(self, text: str):
        self.stream_reader.feed_data(text.encode('utf-8'))

    def feed_eof(self):
        self.stream_reader.feed_eof()


class TextStreamWriter:
    """
    SSHWriter mock.
    """
    def __init__(self, reader: TextStreamReader):
        self.reader = reader

    def write(self, text: str):
        self.reader.feed_text(text)

    def close(self):
        self.reader.feed_eof()

    async def drain(self):
        pass
```

Then a mock for the SSH server:
```python
class _Server:
    """
    Mock for the stream reader/writer, emulating an SSH server.

    The `reader` and `writer` attributes are
    `TextStreamReader`/`TextStreamWriter` objects that can be used by code
    which expects an `SSHReader`/`SSHWriter.`
    """
    def __init__(self):
        self.reader = TextStreamReader()
        self._server_writer = TextStreamWriter(self.reader)

        self._server_reader = TextStreamReader()
        self.writer = TextStreamWriter(self._server_reader)

        self._f = asyncio.ensure_future(self.run())

    def close(self):
        self._f.cancel()

    async def run(self):
        writer = self._server_writer
        reader = self._server_reader

        # Emulate interaction.
        while True:
            line = await reader.readline()
            line = line.strip()

            if line == "question":
                writer.write("answer\n")
                await writer.drain()
           # ...
```

**Comment by ronf** [comment]
One minor thing on this: The argument to read() would be specifying how many Unicode characters to return, not how many original bytes. So, it could end up returning fewer characters than requested. That's technically ok, since read() with a length is allowed to return less, but in some cases you could end up in the middle of a Unicode byte sequence in what the underlying read() gives you, and in that case the call to decode() could fail.

I ran into a similar issue with my SSHProcess file redirection, where I could receive a buffer which include only a partial Unicode character at the end. So, I built a decode() method that would buffer the partial character and try the decode again when additional data arrived later. For completeness, it would also report an error if it received an EOF and there was still partial data left that couldn't be decoded. Take a look at _UnicodeReader in process.py for the details.

**Comment by jonathanslenders** [comment]
Good point. It doesn't matter that much for our tests right now, but that's right indeed.

Do you know about ``codecs.getincrementaldecoder``? I used this in prompt_toolkit to solve the issue you are describing: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/input/posix_utils.py

**Comment by ronf** [comment]
Oh, nice! I didn't know about that. Thanks for the pointer -- I'll definitely have to look into whether I can simplify my _UnicodeReader class by using this!

Also, while I was there, I noticed the getreader() and getwriter() functions on codecs. Those seem designed to let you pass in a StreamReader/StreamWriter that expects bytes and get back a wrapper around it that will take Unicode data. I wonder if you could use that as the basis for your mock SSHReader/SSHWriter classes to avoid much of the boiler-plate you have above.
