### ISSUE TITLE
using a ssh server to do a ssh connection to another server and run a command like ls

### ISSUE THREAD

**Issue by kw-andy** [ronf/asyncssh#151]
Hi,

I'm trying to run my python ssh server and once I'm connected on it, to run a ssh connection to another remote server.

This my ssh server 

- https://gist.github.com/kw-andy/778715240fa20c58dbd6503d972d4f7d

This is my function I'm using 

```python
    async def run_client(self):
        async with asyncssh.connect('174.xx.12.xx', username='andyxx', client_keys=['resources/priv_keys']) as conn:
            result = await conn.run('ls .', check=True)
            print(result.stdout, end='')
```

I've put inside of my class `MySSHServer` but when I run the ssh python server,  it does not do the ssh connection to the remote server.

Any ideas on what I should do?

Cheers

**Comment by ronf** [comment]
What does the call to run_client() look like, and where in MySSHServer are you invoking it? The methods in the SSHServer class are generally callbacks, and only some of them support being implemented as coroutines. Also, make sure that you are doing an "await" on run_client() from wherever you are calling it.

**Comment by ronf** [comment]
Sorry - I missed the link you put in above. Looking at that, you are defining run_client() but you aren't actually calling it.

**Comment by kw-andy** [comment]
hi @ronf how should I call it? when running the ssh server?

**Comment by kw-andy** [comment]
@ronf I'm a bit confused.

I set `run_client()` inside of my class `MySSHServer`. When I create the MySSHServer and call `handle_client()`, it should call `run_client()`too or did I misunderstand it?

**Comment by ronf** [comment]
No - there's nothing special about the run_client() method name. If you want the code in it to run on every new server connection coming in, you should make handle_client() an async function and move the code in run_client() into handle_client(). Since handle_client() is declared as a process factory in the call to create_server(), it'll be run every time a new connection comes in to that server.

**Comment by ronf** [comment]
If you want the output to go to the original SSH connection, you'll need to use something like process.stdout.write() instead of print() here. Also, you'll need to move the process.exit() call down to the bottom, so you don't close the original connection until you are done sending the output from the new connection.

**Comment by kw-andy** [comment]
dear @ronf 

After many tweaking , I managed to do a ls on a remote server.

Please find my async method below

```python
async def handle_client(process):
    process.stdout.write('Welcome to my SSH server, %s!\n' %
                         process.channel.get_extra_info('username'))


    async with asyncssh.connect('192.168.1.23', username='pi', client_keys=['resources/priv_keys']) as conn:
        result = await conn.run('ls .', check=True)
        #print(result.stdout, end='') #using a print will only do the print on the server side
        process.stdout.write(result.stdout) #the end='' has to be removed and result must have a stdout

    process.exit(0)
```

Thank you again for your help

**Comment by ronf** [comment]
This looks reasonable. Just a couple of things to note:

  * Only output to stdout is being passed through here. If you want to pass stderr output as well, you'll need another line looking like "process.stderr.write(result.stderr)".
  * This works well if the program you run doesn't generate a lot of output. If it does, you may not want to collect up all the output before you write it. One way to do that is to use redirection:
```python
    async with asyncssh.connect('192.168.1.23', username='pi', client_keys=['resources/priv_keys']) as conn:
        await conn.run('ls .', stdin=process.stdin, stdout=process.stdout, stderr=process.stderr)

    process.exit(0)
```

This will pass input from the client to stdin of the server session and output on stdout and stderr of the server session back to the client as it is generated, rather than waiting until the command completes.

Note that I also took out the "check=True" here. if you want to check for errors, you should add a "try" block around conn.run() that tests for the ProcessError exception.

You may also want to pass the exit status through by doing something like:

```python
    async with asyncssh.connect('192.168.1.23', username='pi', client_keys=['resources/priv_keys']) as conn:
        result = await conn.run('ls .', stdin=process.stdin, stdout=process.stdout, stderr=process.stderr)

    process.exit(result.exit_status)
```
