### ISSUE TITLE
Feature: Support openssh keepalive requests

### ISSUE THREAD

**Issue by matthijskooijman** [ronf/asyncssh#157]
When I connect to AsyncSSH using a regular Linux OpenSSH client, the debug log on the server shows:

    DEBUG:asyncssh:[conn=0] Received unknown global request: keepalive@openssh.com

This seems like a fairly standard request, perhaps AsyncSSH should support it out of the box? I can even imagine that handling these requests is enabled by default, but can be disabled or customized by overriding a method?

**Comment by ronf** [comment]
The funny thing here is that even without explicitly supporting this request, AsyncSSH _is_ actually supporting it. The OpenSSH code doesn't care if the response to the request is success or failure. All it cares about is the the request gets a response of some kind.

I've thought about registering this as a valid request just to avoid the "unknown global request" debug message, but if I create a handler for it I'd still probably want _some_ kind of debug message which reports that the message was received. I suppose I could make it something that only showed up at debug level 2 rather than level 1, but there'd really be no change in behavior on the OpenSSH side if I implemented it.

Looking at the OpenSSH code, I see that it sometimes seems to send this keepalive as a channel message, so I'd probably need to implement that too, though I'm not sure I've ever actually seen the unknown channel message error for it. That could be because it looks like this is only done when OpenSSH is the server, though, and I rarely keep AsyncSSH client connections to OpenSSH open and idle long enough to trigger it.

**Comment by ronf** [comment]
After thinking about this a bit, I decided to go ahead and add explicit handlers here and update the new log messages to be at debug level 2 instead of 1, to reduce noise in the logs. This is now committed in b495fff.

**Comment by ronf** [comment]
This is now available in AsyncSSH 1.14.0.
