### ISSUE TITLE
SSH Agent server implementation

### ISSUE THREAD

**Issue by paravoid** [ronf/asyncssh#178]
AsyncSSH looks great, kudos! I'm wondering if you've thought about implementing an SSH agent server class, i.e. something that one can subclass and implement their own agent? It seems like it would fit well in this project's scope.

(I've actually [built my own agent from scratch](https://gerrit.wikimedia.org/g/operations/software/keyholder/) for various reasons, but was looking into alternative SSH implementations and came across AsyncSSH shortly after I finished doing so…).

**Comment by ronf** [comment]
This is an interesting thought. Pretty much all of what would be needed in terms of request & response definitions already exists in the current agent.py code, and it wouldn't take much to add code to parse requests and serialize responses. Actually implementing a fully functional agent which did signing would be a bit more effort, but even there all the functions needed to encode & decode keys and perform signing operations all already exists.

If this capability existed, what sort of customizations would you want to use it for?

**Comment by paravoid** [comment]
I don't have an immediate need for this right now, as I've already made my own implementation of the agent protocol (using the [Construct library](https://github.com/construct/construct)) and an agent implementation, but encountered your project soon after that and potentially wouldn't had gone through the trouble if that functionality existed already.

The use case there was to build an agent that can hold multiple keys but selectively present and allow these to be used by user (or groups) as identified with SO_PEERCRED on the Unix socket connecting to them. This is useful in machines with lots of keys, dozens of users and multiple levels of access. The [current implementation](https://github.com/wikimedia/keyholder) reads a configuration file and applies these controls on REQUEST_IDENTITIES, SIGN_REQUEST etc. but the longer-term vision is that it would also implement a custom key constraint extension and decouple the configuration from the agent, so some way to implement custom extensions may be useful to have as well.

Hope this helps!

**Comment by ronf** [comment]
Thanks. I appreciate the additional context around what you had in mind.

I've done a bit of additional exploration on this and one issue I've run across is that it may be hard to support an SSH agent on Windows without re-introducing the pypiwin32 dependency. It turns out you can open and read/write named pipes in Python on Windows with the standard library, but you can't create new named pipes. Also, I'm not really sure what the equivalent would be of SO_PEERCRED on Windows.

That's not a show-stopper, as I could say that SSH agent server support is UNIX-only, but even on UNIX it looks like there are different implementations of that required for different flavors of BSD, Linux, and MacOS (see https://stackoverflow.com/questions/358967/how-can-i-pass-user-credentials-through-a-unix-domain-socket-on-mac-os-x for starters, and that may not cover everything).

I also really don't like the idea of hard-coding the value of SO_PEERCRED, as that could vary from one OS to another. The exact layout of the structure passed in and out of setsockopt() could also vary. Without something like SO_PEERCRED to grab user/group information of the client, though, I'm not sure how useful this support would be.

**Comment by paravoid** [comment]
Well the SO_PEERCRED thing is just one use case (and just happens to be my use case!). I wouldn't make this task conditional on that -- I can imagine all kinds of other ideas on why one may want to write their own agent that has more smarts than e.g. OpenSSH's.

That said, I do understand not wanting to go through the effort if there isn't anyone actually looking into using that immediately.

**Comment by ronf** [comment]
Yeah, I may still look into providing a basic framework to parse the messages and call methods a developer can implement to actually decide what keys to allow. I'll leave this open for now, as a reminder about that.

**Comment by ronf** [comment]
Sorry, I never got around to this, and I'm still not sure how useful it would be. If it's something you're still interested in, let me know.
