### ISSUE TITLE
Add option to disable strict host key checking

### ISSUE THREAD

**Issue by DerekTBrown** [ronf/asyncssh#179]
Is there an option to disable strict host key checking?   Seems like this should be supported.

**Comment by DerekTBrown** [comment]
As far as I can tell- this just disables known host checking, not host key validation.  For instance host key principal validation is still performed.

**Comment by ronf** [comment]
There are no principals involved when validating host keys, but you're right that some validation is still done in the case where a server presents an OpenSSH certificate instead of a key.

Specifically, checks are done that the certificate is a host certificate (not a user certificate), that the current time is within the certificate validity period, and that if there are principals configured on the certificate, one of them much match the name of the host that AsyncSSH is connecting to.

Since known_hosts=None prevents the server CA key from being validated, I guess there's not much value in doing any of the other certificate checks in that case. It wouldn't prevent a man-in-the-middle attack, so it doesn't add much value in that regard, and I can see how doing the check could prevent you from connecting to a host that had an invalid certificate. I agree that there should probably be some way to allow that.

It's probably not worth adding a separate control for this, so tying it to known_hosts=None is probably the best option. What do you think?

**Comment by ronf** [comment]
I thought about this some more and looked at the code, and I've decided to use known_hosts=None to disable both host/CA key _and_ certificate checks. There's really no value in doing the certificate checks without verifying that the CA key is trusted, so tying these together makes sense.

This is commit 6c6bef1 in the "develop" branch, and will become a part of the next release. Thanks for pointing this issue out!

**Comment by DerekTBrown** [comment]
@ronf Thanks for such a quick response!

**Comment by ronf** [comment]
The fix described here is now released in AsyncSSH 1.15.1.
