### ISSUE TITLE
SSHReader.Read doesnot return data,even after SSHWriter.Write called

### ISSUE THREAD

**Issue by sudheer594** [ronf/asyncssh#207]
Hi,
I have been playing around with the asyncssh library. i was able to run command or ftp quickly with the documentation provided.
but, when i created a ssh shell, i am unable to send any data to terminal though , can receive the data fine from session
I am using python 3.7 and aiohttp
here is the sample to reproduce the issue and github link https://github.com/sudheer594/asyncsshsample
this task never completes except for the first time.so, even i type in the frontend terminal, i donot get the response calling sshReader.Read
`  ssh_task = app.loop.create_task(sshReader.read(1024))`

What am i missing here?

`
async def websocket_handler(request):
    print('Websocket connection starting')
    ws = aiohttp.web.WebSocketResponse()
    await ws.prepare(request)
    print('Websocket connection ready')
    async with connect("localhost") as conn:
        (sshWriter, sshReader, sshExReader)= await conn.open_session()
        app = request.app()
        ws_task = app.loop.create_task(ws.receive())
        ssh_task = app.loop.create_task(sshReader.read(1024))
        sshex_task = app.loop.create_task(sshExReader.read(1024))
            
        while True:
            
            done, pending = await asyncio.wait([ws_task,ssh_task,sshex_task],return_when=asyncio.FIRST_COMPLETED)

            if ws_task in done:
                msg = ws_task.result()
                print(msg)
                if msg.type == aiohttp.WSMsgType.TEXT:
                    if msg.data == 'close':
                        conn.close()
                        await conn.wait_closed()
                        break
                    else:
                        sshWriter.write(msg.data)
                        await sshWriter.drain()
                    ws_task = app.loop.create_task(ws.receive())
        
                elif msg.type == aiohttp.WSMsgType.CLOSE:
                    conn.close()
                    await conn.wait_closed()
                    break
                elif msg.type == aiohttp.WSMsgType.ERROR:
                    print('ws connection closed with exception %s' %
                            ws.exception())
                    conn.close()
                    await conn.wait_closed()
                    break
                    
            if ssh_task in done:
                data = ssh_task.result()
                print(data)
                await ws.send_str(data)
                ssh_task = app.loop.create_task(sshReader.read(1024))
            if sshex_task in done:
                data = sshex_task.result()
                print(data)
                await ws.send_str(data)
                ssh_task = app.loop.create_task(sshExReader.read(1024))
        
            
    print('Websocket connection closed')
    return ws   
`

**Comment by ronf** [comment]
I haven't analyzed the program above in detail yet, but here are a couple of initial thoughts:

- You appear to be starting an interactive shell, rather than opening a new session for each command you want to run. However, I'm not sure you are sending a carriage return at the end of the command you feed in with sshWriter.write(). If you don't have that, the shell won't run the command.

- Another problem I see is that you won't really be able to know when you are at the end of the command output. The data may be spread across multiple read calls, and when it is finally finished, the session will return to the shell to read another command, but you won't necessarily know when that happens, so you can send some kind of EOF back to the web socket indicating that command is done.

A better option here might be to wait until you get a command to run and then do an open_session() which passes that command in as an argument, instead of using sshWriter.write() to a shell. That way, when the command completes, the SSH session will return EOF to you (an empty string in the read) and you can know to close the connection. This would also avoid you needing to add a carriage return to the end of the command. If you wanted to support running multiple commands, they could all share the same SSH connection, but each would run as its own SSH session.

**Comment by sudheer594** [comment]
Hi Ron, 
Yes, i want to run a interactive shell in web browser to emulate the terminal in linux.
This is similar to https://github.com/bastillion-io/Bastillion which provides web based ssh sessions. 
i want the web session to emulate exactly like linux terminal. so, command and response doesnot suit the usecase.
please let me know, how this can be achieved using async ssh

Thanks

**Comment by ronf** [comment]
Yes - AsyncSSH can support this. To get the remote SSH server to allocate a PTY and provide full terminal capabilities, you'll need your call to open_session() to pass in what terminal type you are emulating in your web session. You can also optionally specify a terminal size, and even what terminal modes you want the remote system to use (see https://asyncssh.readthedocs.io/en/latest/api.html#ptymodes).

Setting a terminal type will also cause the remote system to begin doing things like echoing the user's input back to them. Without a terminal type, it won't do this.

**Comment by sudheer594** [comment]
That was quick response. I will give it a try

**Comment by sudheer594** [comment]
Hi Ron,
It worked `conn.open_session(term_type='xterm-256color')`, exactly what i was expecting. 
Thanks for the quick help and keep doing the awesome work.

**Comment by ronf** [comment]
Terrific - happy to help!
