### ISSUE TITLE
`connect()` needs a timeout parameter

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#21]
I'm writing a tool that spins up and manages instances on Amazon EC2.

When you launch a new instance on EC2, SSH takes some time to come up. So I periodically try connecting to the instance to find out when SSH becomes available. My tool does this for potentially hundreds of instances that get launched at once.

To minimize the amount of time between when SSH becomes available and I find out about it, I want to check for connectivity on a frequent basis. To do that I need a way to timeout connection attempts and try again. This doesn't appear to be possible at the moment.

Specifically, it looks like `connect()` and `create_connection()` are lacking a `timeout` parameter, or something similar.

So the below snippet, for example, takes well over a minute to error out because SSH is not available, when I want it to timeout after, say, only 3 seconds.

```python
@asyncio.coroutine
def conn_error():
    with (yield from asyncssh.connect(host='google.com')) as conn:
        stdin, stdout, stderr = yield from conn.open_session('echo "Test"')
        output = yield from stdout.read()
        print(output, end='')


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(conn_error())
```

Does it make sense to add a `timeout` parameter to the various `connect()` methods? [Paramiko's `connect()`](http://paramiko-docs.readthedocs.org/en/latest/api/client.html#paramiko.client.SSHClient.connect) supports this, which is how I am able to do this currently.

**Comment by yosemitesammy217** [comment]
+1 for adding timeout feature to connections!

-- 
Sam Crooks
972-762-5911
sam.a.crooks@gmail.com

**Comment by ronf** [comment]
You should be able to do this using asyncio.wait_for(). It would look something like:

```python
try:
    conn = yield from asyncio.wait_for(asyncssh.connect('localhost'), timeout=3)
    # do stuff with conn
    conn.close()
except TimeoutError:
    # handle connection timeout
```

You could use the "with" version of this as well:

```python
try:
    with (yield from asyncio.wait_for(asyncssh.connect('localhost'), timeout=3)) as conn:
        # do stuff with conn
except TimeoutError:
    # handle connection timeout
```

**Comment by nchammas** [comment]
Thanks for the suggestion. I'll try it out.

To be clear, is this the intended way for users to timeout a connection attempt in AsyncSSH, or is a timeout parameter still appropriate here?

I guess both would work fine, the main differences being that a) semantically, one is a coroutine timeout while the other is a TCP timeout, and b) a timeout parameter is less verbose.

**Comment by ronf** [comment]
While I could provide a timeout parameter, it's actually not possible with asyncio to pass that timeout down into the Python socket.connect() call. When a timeout is set like that, it turns connect() into a blocking call, which asyncio doesn't allow. There's actually an explicit check for this in the asyncio code, and a ValueError is raised if you try to pass in a socket with a non-zero timeout:

```python
    def sock_connect(self, sock, address):
        """Connect to a remote socket at address.

        The address must be already resolved to avoid the trap of hanging the
        entire event loop when the address requires doing a DNS lookup. For
        example, it must be an IP address, not an hostname, for AF_INET and
        AF_INET6 address families. Use getaddrinfo() to resolve the hostname
        asynchronously.

        This method is a coroutine.
        """
        if self._debug and sock.gettimeout() != 0:
            raise ValueError("the socket must be non-blocking")
        fut = futures.Future(loop=self)
        try:
            if self._debug:
                base_events._check_resolved_address(sock, address)
        except ValueError as err:
            fut.set_exception(err)
        else:
            self._sock_connect(fut, sock, address)
        return fut
```

This makes sense, since asyncio never wants its operations to block.

Given this, adding a timeout parameter to my code wouldn't really save much. You'd still need to do the "try .. except TimeoutError" exactly like in the example above, so all it would really accomplish is to shrink "asyncio.wait_for(asyncssh.connect('localhost'), timeout=3))" down to "asyncssh.connect('localhost', timeout=3)". While I'll admit that's a bit nicer looking, there are potentially many calls where you might want to introduce such a timeout (basically any coroutine which might block). I'm not sure it makes sense to add this extra argument in all of those places.

Asyncio doesn't provide timeout parameters for any of its "blocking" coroutines today. It expects you to use wait_for() to do this yourself if you need to. One advantage to that is that you can use the same approach regardless of what call you need to wrap a timeout around.

One other benefit to the asyncio approach is that you can pass in multiple coroutines or futures to asyncio.wait() and wait on all of them in parallel with a common timeout. This can either return results as each call completes or fails, or wait for all of them to complete. In this case, it doesn't raise TimeoutError, but if you specify a timeout you get a list of all of the calls which are still pending. From there, you can decide to cancel them if you don't want to wait any longer.

**Comment by nchammas** [comment]
OK, this makes sense. Thanks for explaining how timeouts are handled with asyncio.

**Comment by nchammas** [comment]
@ronf - Is there any place this could be documented? I imagine this being a fairly common use case that users who are new to asyncio might wonder about.

**Comment by ronf** [comment]
@nchammas Sure - I've added the following note to the asyncssh.create_connection() documentation:

    Note: Unlike socket.create_connection(), asyncio calls to create a connection do not support
    a timeout parameter. However, asyncio calls can be wrapped in a call to asyncio.wait_for()
    or asyncio.wait() which takes a timeout and provides equivalent functionality.

**Comment by nchammas** [comment]
Great! Thank you.
