### ISSUE TITLE
stdout is not reading last line in interactive shell

### ISSUE THREAD

**Issue by Ali-aqrabawi** [ronf/asyncssh#210]
`python version = 3.6.5 [GCC 7.3.0] on linux`
`os = ubuntu 18.04 bionic`
`asyncssh = 1.16.1`

i'm testing interactive shell with Cisco device (tested with IOS, NXOS and ASA),

when i write a command and do readline() inside infinite loop the stdout read all the outputs except the last line.

    async def run_client():
        async with asyncssh.connect('192.168.1.1', username='user', password='pass', 
                                    known_hosts=None) as conn:
        async with conn.create_process('') as process:
            process.stdin.write('terminal len 0\n')
            process.stdin.write('show version\n')
            result = ''
            while True:
                line = await process.stdout.readline()
                print(line)
                result += line
                if re.search('#$',line):
                    break

 the output will be everything except last line which is basically the device prompt which is `router#`

however if i add a `print` like below i can see the last line:

    def data_received(self, data, datatype):
        """Handle incoming data on the channel"""
        print(data) <---
        self._recv_buf[datatype].append(data)
        self._recv_buf_len += len(data)
        self._unblock_read(datatype)
        self._maybe_pause_reading()

**Comment by ronf** [comment]
Yes - this is expected behavior. The partial line is arriving and is being buffered. Since you called readline(), though, it won't return this data until either it sees a newline in the output or end-of-file is sent on the channel.

Your best bet is to not start an interactive shell here, and instead send each command on a separate channel. You can reuse the connection, so you'll only have to authenticate once. However, by calling create_process() separately for each command and passing the command name in the call, you'll get a separate process for each and the remote system should close the channel automatically at the end of the command output. If the amount of output isn't too large and you don't need to process the data as it arrives, you could even call something like run() and collect up all of the output of the command without having to explicitly call read() or readline().

Your other option is to call read() here with an explicit maximum number of bytes to read. That will always return as soon as ANY data has arrived, whether it ends in a newline or not. You can then reassemble the data into lines yourself if you want, or process each chunk of output as it arrives without it being a line at a time, depending on what you want to do with it. You'd have to come up with a different way to test for when you are at the end, though. If at all possible, I would strongly recommend going with the other option here of running each command as its own session.

**Comment by Ali-aqrabawi** [comment]
that's make so much sense,

the problem is that i can't use `b'exec'` sessions because the cisco devices sometimes require extra password(secret) to be provided, as a workaround i'm sending extra \n:

    async def run_client():
        async with asyncssh.connect('192.168.1.1', username='user', password='pass', 
                                known_hosts=None) as conn:
            async with conn.create_process('') as process:
                process.stdin.write('terminal len 0\n')
                process.stdin.write('show version\n')
                result = ''
                while True:
                     line = await process.stdout.readline()
                     print(line)
                     result += line
                    if re.search('#$',line):
                         break

**Comment by ronf** [comment]
I see. It's true that you wouldn't be able to use run() if you need to do any conditional input based on the response you get back. You could still use exec in that case and still read the output yourself, but you'd only be able to send a single command, so you couldn't do something like what you show here with 'terminal len 0' and 'show version' on the same channel. For that, you're right that you'd need to use a 'shell'.

The extra newline on the input side is a clever way to handle this. However, I wouldn't expect the re.search() that you show here to ever match in that case, as the returned line would be the prompt string including the newline, so it would end in something like '#\n' or '#\r\n'. rather than just '#'.

Also, if you search for that, it may match other lines that end in '#' in your output. So, you'd probably want to match on a longer string, such as the entire prompt string. If the Cisco device has some kind of 'comment' line you can enter at the prompt which doesn't perform any action, you might even want to send that instead of the blank line, and match on that string being echoed back. That way, you could generate something like a random string or other end marker that would be much more likely to be unique.

**Comment by Ali-aqrabawi** [comment]
thanks, the random string is a better way!
