### ISSUE TITLE
What does this warning mean? Agent not Found

### ISSUE THREAD

**Issue by xNinjaKittyx** [ronf/asyncssh#217]
Recently on one of my setups at work, I've been getting the following warning
```
Unable to read keys from agent: [Errno 2] Agent not found
```

What does this mean? I'm using known_hosts=None in the connection call.

**Comment by ronf** [comment]
This message indicates that AsyncSSH was unable to find an SSH agent to get keys from. It's only a warning and can be ignored, or you can pass in "agent_path=None" to explicitly disable the default behavior of trying to contact an SSH agent.

I've debated about whether or not to skip showing a warning when there is no agent path specified and SSH_AUTH_SOCK is unset, or perhaps changing the level of that message to something like INFO or DEBUG in that case. For now, though, it will warn you if you leave SSH agent support enabled and there's no agent available to get keys from.

**Comment by xNinjaKittyx** [comment]
Was this recently added? I don't remember seeing this in the past, and I don't think I've changed anything on the server.

**Comment by ronf** [comment]
Hmm, yes - there was a problem discovered on Windows that prevented AsyncSSH from properly using an SSH agent by default when SSH_AUTH_SOCK wasn't set. This was fixed in 1.17.0. It looks like the previous version of that check suppressed the "Agent not found" message from coming up on UNIX when SSH_AUTH_SOCK wasn't set, but as a consequence it broke the Windows case where an agent could exist even without SSH_AUTH_SOCK being set. The new code always calls into the AsyncSSH agent client code, letting that decide if it can find an agent or not. However, that code raises an exception on any failure, including "Agent not found" -- it needs to do this because it might be invoked by the application directly via connect_agent(), and that needs to notify the caller on any form of connection failure.

Unfortunately, getting the old behavior back on UNIX without breaking Windows would probably require an explicit platform check in the connection code, which I'm really hesitant to do. I think it's probably cleaner to leave in the warning if you don't explicitly disable the use of an agent (by setting agent_path=None).

**Comment by ronf** [comment]
I spent a little more time on this and found a way to eliminate the agent warning on Windows without having to do any explicit platform checks. This change is now available in AsyncSSH 1.17.1.
