### ISSUE TITLE
right to handle connection break under ayncssh rules

### ISSUE THREAD

**Issue by openalmeida** [ronf/asyncssh#23]
Hi,

I've checked https://github.com/ronf/asyncssh/issues/21 about timeout issue and known that programming under asyncio is different from common rules.

So, whats the new ways or ideas to handle exceptions after connection created, such as
 - re-connect or handle it when connection break (hardware problem)
 - multiple connection (connection pool ?)
 - any farther.

e.g.
```Python
# ... some logic need a long time as below
#
stdin, stdout, stderr = yield from conn.open_session('sleep 50000;echo -n "Hello!"')

"""
but before its done, my laptop got WIFI signal lost for a moment,
i've got my Python application blocked
expect automate re-connect or exit gently that i can do myself a notice next step
"""
```

**Comment by ronf** [comment]
When using the stream interface provided via open_session(), you'd need to have an outstanding read() or write() operation on one of stdin, stdout, or stderr to be able to see that the connection has been broken. So, for instance, if you had a read() on stdout waiting to get back the "Hello" in the example above, that read() would unblock early and raise an exception if the connection broke. The exact exception would depend on what the socket code returned, but an example of what you might see is ConnectionResetError on a read(). On write(), a common error is BrokenPipeError if you were blocked waiting for a write to complete and the connection is no longer able to accept any more data.

Note that it can take a long time for the TCP socket code to detect connection failures in some cases, particularly if there's no data being transferred over it at the time of the network failure. In extreme cases, it may take minutes or hours before the failure is seen if neither side is writing any data.

**Comment by openalmeida** [comment]
yes, what i expect is some kind of return too.

```python
stdin, stdout, stderr = yield from asyncio.wait_for(
    conn.open_session('sleep 50000;echo -n "Hello!"'),
    5
)
try:
    output = yield from stdout.read() # for this example, it blocked here, and no exception raise
except Exception as e:
    print(e)
print(output)

"""
i dont know if there's some kind of kernel signal or anything i should watch,
maybe create another coroutine or thread with a connection check loop ?
"""
```

thank you

**Comment by ronf** [comment]
If you control both ends, you can periodically send data back and forth on the connection. That will allow you to detect much more quickly when the connection is no longer healthy. Most of the problems seen with not detecting a broken connection occur on idle connections. This issue is not specific to asyncssh or asyncio -- it's the general nature of the way TCP sockets work.

If you know data is supposed to arrive periodically, you can also add a timeout (as discussed in #21) to the read calls you're making and you'll get woken up any time data doesn't arrive in the expected amount of time, even if the connection is still healthy. You could then decide if you want to try and close and reopen the connection.

Note that the wait_for() in your example above will only apply to making the initial connection. If you want to get a timeout on the read() call, you'd need to have a wait_for() wrapped around that as well. In this case, though, that timeout would go off even when the connection was still healthy, since the command you're running will take longer than 5 seconds to complete.

**Comment by openalmeida** [comment]
awesome, got it.
