### ISSUE TITLE
Redirecting to sys.stdout

### ISSUE THREAD

**Issue by haggaie** [ronf/asyncssh#245]
I thought I would be able to redirect the output of an ssh command directly to `sys.stdout`. I tried using the following program:
```python3
#!/usr/bin/python3
import asyncio, asyncssh, sys

async def main():
    host = sys.argv[1]

    ssh = await asyncssh.connect(host)
    await ssh.run('uname -r', stdout=sys.stdout)
    print('Done')

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

but I got an error in the `print('Done')` line:

```python traceback
Traceback (most recent call last):
  File "./mwe-closed-stdout.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./mwe-closed-stdout.py", line 9, in main
    print('Done')
ValueError: I/O operation on closed file.
```

Does asyncssh close the stdout file at the end of the command? Is there a better or more correct way of doing this?

**Comment by ronf** [comment]
Yes - anything assigned to stdout/stderr in the run() call will be closed when EOF (or close) is received on the SSH session.

The simplest way to do what you want here is to pass a cloned fd of stdout to run() instead of stdout itself. This would look something like:

```python
import asyncio, asyncssh, os, sys
  
async def main():
    host = sys.argv[1]

    ssh = await asyncssh.connect(host)
    cloned_stdout = os.dup(sys.stdout.fileno())
    await ssh.run('uname -r', stdout=cloned_stdout)
    print('Done')

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

That way, the cloned fd is what gets closed, but the original stdout fd is still open and usable. You could even do this for multiple run() commands, as long as they are not run in parallel (to avoid interleaving the output). In this case, you'd clone the stdout fd before each call to run(), and the original sys.stdout would remain available to you before, after, and in between commands if you needed to do any other output.

One other caveat: Since sys.stdout is buffered by default, you'll probably need to call sys.stdout.flush() before you call os.dup(), to make sure any pending output is sent out before the underlying file descriptor is cloned.

**Comment by haggaie** [comment]
Thanks. I guess I should have thought of `dup` :)
