### ISSUE TITLE
[Help] Socks Tunnel implements

### ISSUE THREAD

**Issue by castrorry** [ronf/asyncssh#250]
To implement a server to listen for dynamic Socks connections, what should I return in `connection_requested` in `asyncssh.SSHServer`?

**Comment by ronf** [comment]
SOCKS forwarding support isn't done using connection_requested. It's a special listener you need to create, more like what you'd do with port forwarding. Here's an example:

```python
    async with asyncssh.connect('localhost') as conn:
        listener = await conn.forward_socks('', 11080)
        await listener.wait_closed()
```

This will accept SOCKS client connections on port 11080 and tunnel the traffic via SSH as an outbound direct-tcpip tunnel.

Currently, there's no support for a callback which runs on every inbound socks connection to decide whether to allow the connection or not. Since this is all happening from an SSHClientConnection, it doesn't really fit with things like the connection_requested() callback. In fact, you don't even need to create an SSHServer at all to use this SOCKS support.
