### ISSUE TITLE
SSHServerProcess.redirect kills stdin

### ISSUE THREAD

**Issue by haliphax** [ronf/asyncssh#252]
I'm trying to shell out to a subprocess and then afterward return control to the AsyncSSH SSHServerProcess for further interaction. However, if my server process's stdin is passed to the subprocess with `redirect()`, the pipe is broken/closed when I get it back. If I don't pass stdin through, everything is fine. Am I missing something?

Also, it seems as though `stdin.readexactly(1)` won't register the next 5 keypresses, and _then_ complains about `os.write` failure.

Here's basically what I'm doing:

````python
p = subprocess.Popen(('telnet', '-E', 'localhost'), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
await process.redirect(stdin=p.stdin, stdout=p.stdout, stderr=p.stderr)
await process.stderr.drain()
await process.stdout.drain()
    
while True:
    await process.sdtdin.readexactly(1)  # this is broken
````

<s>Maybe it's the behavior of `telnet` that's doing this? I'll try it with a different interactive process.</s> Nope, other stuff breaks, too.

**Comment by haliphax** [comment]
Also, it seems as though `stdin.readexactly(1)` won't register the next 5 keypresses, and _then_ complains about `os.write` failure.

**Comment by haliphax** [comment]
Here's basically what I'm doing:

    p = subprocess.Popen(('telnet', '-E', 'localhost', stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=False)
    await process.redirect(stdin=p.stdin, stdout=p.stdout, stderr=p.stderr, send_eof=False)
    await process.stderr.drain()
    await process.stdout.drain()
    
    while True:
        await process.sdtdin.readexactly(1)  # this is broken

Maybe it's the behavior of `telnet` that's doing this? I'll try it with a different interactive process.

**Comment by haliphax** [comment]
Nope, other stuff breaks, too.

**Comment by ronf** [comment]
To start with, you'll probably need to set send_eof=False when you set up the redirect. Otherwise, as soon as you get EOF on the local subprocess's stdout or stderr, that EOF will be passed through to your process's SSHWriter objects, closing the SSH process's channel. From looking at your previous edits on this, it looks like you might have already tried that, though. Did that not work for you?

Setting that should prevent EOF from being sent on stdout/stderr on the SSH process, allowing you to take back over when the "telnet" command exits and continue to read from stdin on the SSH process or write to stdout/stderr.

Experimenting a bit here, I think send_eof is working properly, but the SSH process doesn't remove the redirection on stdin even after the local subprocess exits. If you want to read from it again, you need to explicitly redirect it back to a pipe:

```python
    await process.redirect(stdin=subprocess.PIPE)
```

You'd do this right after the calls to drain().

Once I did that in my testing, I was able to read from the SSHProcess's stdin and write to its stdout even after the local subprocess completed. I could even create a second local subprocess and redirect the SSH process stdin/stdout/stderr to that new subprocess, running as many commands as I wanted on a single inbound SSH connection.

As an aside, newer versions of AsyncSSH should work with asyncio.create_subprocess_shell() if you wanted to use that instead of the non-async subprocess.Popen(). It doesn't really matter much, as AsyncSSH will do all the I/O asynchronously either way, but this can be useful if you have other StreamReader/StreamWriter objects you want to pass in to redirect().

**Comment by haliphax** [comment]
Awesome. Yeah, I had tried send_eof=False and close_fds=False, but neither did quite what I was needing. I'll give it a shot with re-redirecting stdin after it's done for. Thank you so much!

**Comment by haliphax** [comment]
Yep, that did the trick. Much appreciated.
