### ISSUE TITLE
Asyncssh.scp folder names with spaces where asyncssh is acting a client and server.

### ISSUE THREAD

**Issue by knkp** [ronf/asyncssh#256]
Ran into another snag. Trying to run asyncssh.scp with a path where a folder has spaces in it is failing with:
`SCP Operation failed: Connection lost`

I am using the commit https://github.com/ronf/asyncssh/commit/c992ec4dd0e05997692763fbce2b690452a93608 that fixed the previous issue #253 

This is also using asyncssh as both client and server.

I can't say I've found a solution to this one yet but I can tell you where in the code it is diverging:
_location:_
`asyncssh.scp.py._SCPSource.run()`

_code:_
```

    async def run(self, srcpath):
        """Start SCP transfer"""

        try:
            if isinstance(srcpath, str):
                srcpath = srcpath.encode('utf-8')

--here--> exc = await self.await_response()

            if exc:
                raise exc

            for path in await match_glob(self._fs, srcpath):
                await self._send_files(path, b'')
        except (OSError, SFTPError) as exc:
            self.handle_error(exc)
        finally:
            await self.close()
```
If the there are no folders with spaces in their names I can easily see that it makes it to 
the _send_files method. Otherwise, the Connection Lost exception is called immediately.

I'll keep toying with this one to see if I can figure out more.

**Comment by ronf** [comment]
It sounds like you're probably hitting an exception on the server side which is causing it to drop the connection. You might want to enable debug logging there, which will let you see the unhandled exception in the debug output.

**Comment by ronf** [comment]
How are you encoding the arguments in the case where you have a directory with spaces in it? The following worked for me:

```python
    await asyncssh.scp('localhost:/tmp/dir\\ with\\ spaces/test', '/tmp/test2/')
```

However, when trying without the backslashes, I got back:

```
SFTP operation failed: scp: /tmp/dir: No such file or directory
```

Going the other way where it was a local path with spaces in it, no backslashes were required. The following worked fine:

```python
    await asyncssh.scp('/tmp/dir with spaces/test', 'localhost:/tmp/test2/')
```
Which direction are you transferring the files, and what sort of arguments are you passing?

So far, I haven't seen the "Connection lost" error you mentioned in any of my testing.

**Comment by knkp** [comment]
_client:_
```
 async with asyncssh.connect(self.SERVER_HOST, self.PORT, 
                                    client_keys=self.CLIENT_KEY, 
                                    known_hosts=None) as conn:
           
                await asyncssh.scp(self.FILE_PATH, (conn, self.SEND_TO))
```
_server:_
```

class SCPServer(asyncssh.SFTPServer):
    def __init__(self, conn):
        self.base_path = bytes(WORKING_DIRECTORY, 'utf-8')
        super().__init__(conn)

    def map_path(self, path):
        NewPath = self.base_path + path
        return NewPath

async def start_server():
    asyncssh.set_log_level('DEBUG')
    asyncssh.set_debug_level(3)
    await asyncssh.listen('', PORT, server_host_keys=SERVER_HOST_KEYS,
                                    authorized_client_keys=AUTHORIZED_CLIENT_KEYS,
                                    sftp_factory=SCPServer, allow_scp=True, 
                                    reuse_address=True)
```
In this test, 
self.FILE_PATH='c:/.../client_dir/a\\ client\\ folder/somefile.txt'
self.PATH='/a\\ client\\ folder/somefile.txt'

This is all running from a unittest.
I've tried enabling debugging on the server as you can see but I don't see anything yet in the logs. But I think that's because I haven't figured out how to do it correctly yet.

After playing with it a bit more. On windows, adding the `\\ ` for each space, seem's to cause the file not found exception to occur. But just using spaces works fine.

For example, for the above code:
``` await asyncssh.scp('/c:/../a folder/test', (conn, b'.'))```
works fine, but
```await asyncssh.scp('c:/../a folder/test', (conn, b'./a folder/test'))```
fails with the connection lost error.

I'm wondering if what I'm experiencing has something to do with how I'm overwriting `map_path`
But I haven't gotten any further confirmation on that so far.

**Comment by ronf** [comment]
Ok - the problem definitely has to do with unescaped spaces. On UNIX, the following works:

```python
    async with asyncssh.connect('localhost', 8022) as conn:
        await asyncssh.scp('/tmp/dir with spaces/test',
                           (conn, '/tmp/other\\ dir\\ with\\ spaces'))
```

Without the backslashes, the regular "scp" server returns the error:

```
DEBUG:asyncssh.sftp:[conn=0, chan=0] Handling SCP error: scp: ambiguous target
```

When using AsyncSSH as the SCP server, it gets an related to argparse argument parsing:

```
INFO:asyncssh:[conn=0, chan=0] Error starting SCP server: unrecognized arguments: dir with spaces
```

On the client side, this shows up as the "Connection lost" you are seeing:

```
INFO:asyncssh:[conn=0, chan=0]   Command: scp -t /tmp/other dir with spaces
DEBUG:asyncssh:[conn=0, chan=0] Reading from channel started
DEBUG:asyncssh:[conn=0, chan=0] Received 45 data bytes from STDERR
INFO:asyncssh:[conn=0, chan=0] Received exit status 1
INFO:asyncssh:[conn=0, chan=0] Received channel close
INFO:asyncssh:[conn=0, chan=0] Channel closed
DEBUG:asyncssh.sftp:[conn=0, chan=0] Handling SCP error: Connection lost
INFO:asyncssh.sftp:[conn=0, chan=0] Stopping remote SCP
INFO:asyncssh:[conn=0, chan=0] Closing channel
INFO:asyncssh:[conn=0] Closing connection
INFO:asyncssh:[conn=0] Sending disconnect: Disconnected by application (11)
INFO:asyncssh:[conn=0] Connection closed
SFTP operation failed: Connection lost
```

Basically, both the standard SCP server and the AsyncSSH one expect one positional argument for the target filename after shell expansion when receiving an "scp -t" command. I can make the AsyncSSH argument parser more forgiving, but you'd still have the problem when copying to the standard SCP server if you don't do properly escaping.

The backslash escaping seems to work for me on Windows as well. You only need it when specifying remote pathnames, just as you should always use forward slashes as a path separator there. You also need to make sure to use a pair of backslashes due to Python string literal escaping (unless you want to use "raw" strings). I haven't played with map_path() here, but since this all happens before getting into the SFTP server code, I don't expect that to be a factor.

Instead of backslashes, you could also use shell quoting (single or double quotes) around arguments with spaces, as long as you made sure that the quotes used are different than the quotes used for the Python string literal.

Looking at the AsyncSSH scp code, it currently uses shlex.split() to split up the arguments before passing them into argparse. So, trying to get that to allow unescaped spaces to be considered part of a single "filename" argument would not be easy.

I don't know if using SFTP instead of SCP is an option for you here, but that's a much cleaner option if you want to operate on filenames with unusual characters in them. It's much more structured on the wire, and doesn't rely on things like shell command line parsing.

**Comment by knkp** [comment]
Changing my code so that I pass escaped character's on the target directory representing the remote path and only using spaces on directories the local file path has fixed the issue for me. Now the test's are passing.

Thank you for your help ronf!

**Comment by knkp** [comment]
By the way I don't believe this should require you to change anything. Issue was in my code. That being said unless you say otherwise I will close the issue tomorrow.

**Comment by ronf** [comment]
Yeah - I think in this case it's probably best to leave AsyncSSH as-is, requiring the escaping of spaces on remote file paths just as the standard 'scp' does. I'll go ahead and close this. Thanks for confirming that you were able to make it work!
