### ISSUE TITLE
asyncssh.sftp.SFTPError: Failure on open() with pflags_or_mode=FXF_CREAT

### ISSUE THREAD

**Issue by shsimeonova** [ronf/asyncssh#271]
Hello Ron! 

I'm trying to figure out how to upload a file without having it first locally on my machine. My case is i'm receiving file bytes and i want to send those bytes to my sftp server and upload as file in a specific path. From what i read in the source the put() method uploads files only by local path, so i figured out maybe the open() method would do me a favour. I'm currently trying this:

```
@classmethod
    async def put_file(cls, file_bytes, remote_path, credentials):
        conn = await cls.connect(credentials)

        async with conn.start_sftp_client() as sftp_client:
            try:
                file = await sftp_client.open(remote_path, pflags_or_mode=FXF_CREAT)
                await file.write(file_bytes)
            except asyncssh.SFTPError as err:
                return None
```
and im getting
```
asyncssh.sftp.SFTPError: Failure
```
Thank you in advance! :)

**Comment by shsimeonova** [comment]
Update: I'm trying to isolate the problem with connecting to my local machine now, removed pflags_or_mode=FXF_CREAT arg and getting
`AttributeError: 'bytes' object has no attribute 'encode'`

from what i read bytes should be a proper type for write() fncion https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClientFile.write

**Comment by ronf** [comment]
Yes - open() is what you want here.

You can read & write using bytes objects, but only if you specify `encoding=None` as an argument in the call to open(). Otherwise, it defaults to UTF-8 and expects you to be passing in string data, similar to write() calls elsewhere in AsyncSSH.

If you use a mode string instead of the SFTP flags, you can add 'b' to the mode to get the same result, just as you would for a local file open() call. For instance, opening with a mode of 'wb' will open the file for writing in binary mode, creating it if necessary. Take a look at https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClient.open for more details of the available open modes and their corresponding flags.

As for the first error you got, I think it is because you can't specify FXF_CREAT by itself. It should be added to FXF_WRITE. Again, see the above link for the combinations you'll probably want to use if you decide to directly specify pflags.
