### ISSUE TITLE
Hitting maximum concurrent transfer limit

### ISSUE THREAD

**Issue by sonicxml** [ronf/asyncssh#281]
Hello! I have been trying to use this library to write a module that essentially downloads files from SFTP servers. The module was very thoroughly documented, thanks for that!

The general structure of my code looks something like this:
```
async for file in sftp.readdir():
    if condition:
        f = await sftp.open(path, "rb")
        await f.read()
```

However, with one of the SFTP servers, I'm running into the following error from the `sftp.open` call:
```
  File "/Users/user/dev/repo/sftpfetcher.py", line 199, in _read_file
    f = await sftp.open(path, "rb")
  File "/Users/user/.virtualenvs/venv/lib/python3.8/site-packages/asyncssh/sftp.py", line 2692, in open
    handle = await self._handler.open(path, pflags, attrs)
  File "/Users/user/.virtualenvs/venv/lib/python3.8/site-packages/asyncssh/sftp.py", line 1356, in open
    return await self._make_request(FXP_OPEN, String(filename),
  File "/Users/user/.virtualenvs/venv/lib/python3.8/site-packages/asyncssh/sftp.py", line 1186, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "/Users/user/.virtualenvs/venv/lib/python3.8/site-packages/asyncssh/sftp.py", line 1218, in _process_status
    raise _construct_sftp_error(code, reason, lang)
asyncssh.sftp.SFTPPermissionDenied: Maximum concurrent transfers exceeded for the current context
```

I realize that this message is coming from the SFTP server and not `asyncssh`, but unfortunately I do not have access to that server to change any configuration settings. Is there anything in `asyncssh` that would allow me to control the maximum number of concurrent transfers (or any other recommended way to handle this)? Also, is there any way to know what the maximum number of concurrent transfers for a server is? 

Thanks for the library and the help!

**Comment by ronf** [comment]
Thanks - glad you're finding it useful, and I'd be happy to try and help.

The error message could mean a couple of different things, depending on whether they consider a "concurrent transfer" to be multiple outstanding read or write operations or multiple open files.

In general, since you appear to be downloading the files sequentially in your example, you can protect against having too many open files by changing to something like:

```python
async for file in sftp.readdir():
    if condition:
        async with sftp.open(path, "rb") as f:
            await f.read()
```

This will make sure to do the equivalent of an f.close() when you leave the block where you are doing the sftp.open(). You could also add an f.close() explicitly in the "if condition" block, but using "async with" makes sure the close happens even if the read() exits with an error.

If the problem is too many concurrent read or write operations, you can control that by setting the optional max_requests argument in sftp.open(). It defaults to a max of 128 parallel requests, but you can raise or lower it to whatever you like.

Since you are getting the error on an open() call and not a read() call, I'm going to guess that the issue is too many files being opened at once, in which case the "async with" should help.

**Comment by sonicxml** [comment]
Brilliant, thanks! I'm very used to opening normal files with the `with open` context syntax (which is probably why I forgot the `f.close`) but it just never clicked that I could do the same thing with async opens. Thanks so much for the help!
