### ISSUE TITLE
Fix API docs on websites

### ISSUE THREAD

**Issue by cgi1** [ronf/asyncssh#282]
https://asyncssh.readthedocs.io/en/latest/_modules/asyncssh/connection.html
link to API docs leads to
https://asyncssh.readthedocs.io/en/latest/_modules/asyncssh/api.html
Which is 404

Same goes for the ChangeLog link:
https://asyncssh.readthedocs.io/en/latest/_modules/asyncssh/changes.html
Which is 404

**Comment by ronf** [comment]
Thanks very much for the report! I never noticed this, as I usually click on those links when sitting on one of the top-level doc pages, where they work.

This should be fixed in the "develop" branch in commit 5cd7c16. If you try going to https://asyncssh.readthedocs.io/en/develop/_modules/asyncssh/connection.html (note the "develop" there) and then try clicking on the sidebar links, they should work now.

This change will get rolled into the master branch (fixing the "latest" and "stable" readthedocs pages) when I do the next release.

**Comment by cgi1** [comment]
Thanks for the response - It works for me!
