### ISSUE TITLE
Equivalent control of "onlcr"

### ISSUE THREAD

**Issue by jeremyschulman** [ronf/asyncssh#283]
Thank you very much for creating this package.  I am just starting to use it.  I currently have a bit of code that looks like this:

````python
        async with asyncssh.connect(**conn_args) as conn:
            print(f"CONNECTED TO: {self.host}")
            self._stdin, self._stdout, self._stderr = await conn.open_session(
                term_type='cli', term_size=(120, 80))
           # read & write ...
````

And then with the stdin and stdout I am reading and writing to target device.  I've noticed that the stdout contain "\r\n" rather than just "\n".

I am curious if there is a way within the asyncssh package that I could make a control adjustment so that the resulting stdout is "\n".   From researching this topic, I found this post:

https://unix.stackexchange.com/questions/420424/why-does-ssh-t-option-adds-cr-lf-in-redirected-output

Which discusses the use of the flag "onlcr" and "-onlcr".  Not sure if this is relevant or helpful; but I appreciate your time to review and answer my question.

Thank you!

**Comment by jeremyschulman** [comment]
I have located the use of the `term_modes` option; but I am not certain what value to provide.  For example:

````python
        async with asyncssh.connect(**conn_args) as conn:
            self._stdin, self._stdout, self._stderr = await conn.open_session(
                term_type='cli', term_size=(120, 80),
                term_modes={PTY_ONLCR: False}
            )
````

I still observe the "\r\n" in the resulting stdout.

**Comment by ronf** [comment]
Yes - this should be possible using the term_modes argument, but only if the server has pseudo-TTY support for this setting. The call would look something like:

```python
            self._stdin, self._stdout, self._stderr = await conn.open_session(
                term_type='cli', term_size=(120, 80), 
                term_modes={asyncssh.PTY_ONLCR: False})
```

In a quick test, this worked for me when connecting to a UNIX system.

**Comment by ronf** [comment]
Sorry, looks like our messages crossed. If this didn't work for you, the remote system may not have full PTY mode support. Do you know what kind of system it is? Just to confirm you have the call right, you might want to try pointing at a UNIX machine and see if it works there.

**Comment by jeremyschulman** [comment]
@ronf - thank you for the prompt reply!  I am working with a networking device, Arista EOS, which is a Linux distribution "under the hood".  The value I am using for term_type is just a made up value.  When I tried using 'xterm' I failed to get any result back.  Perhaps there is another value I should use; but I do not know how to determine it. 
Any guidance or suggestions would be greatly appreciated.

**Comment by jeremyschulman** [comment]
````
[jeremy.schulman@lx5e01 ~]$ cat /etc/os-release
# os-release generated by Eos-release-4.23.3 for platform i386_el7

NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
````

**Comment by jeremyschulman** [comment]
I've tried a number of different combinations, but without success; for example:
````python
        async with asyncssh.connect(**conn_args) as conn:
            self._stdin, self._stdout, self._stderr = await conn.open_session(
                term_type='pty', term_size=(120, 80),
                term_modes={
                    PTY_OCRNL: True,
                    PTY_ONLCR: False,
                    PTY_ONLRET: False
                }
            )
````

Is there a way on the device (I can access the bash shell) to determine which options are supported?

The other "twist" in this is that when I am opening an SSH session to the device I am accessing the "CLI shell" and not bash; which is to say when I SSH connect to the device I am being redirected to a program (i.e. CLI).

**Comment by ronf** [comment]
No, unfortunately there's no way to query which terminal modes are supported by an SSH server.

Given that this didn't work on this device, the simplest answer may be to just do a string replace() from '\r\n' to '\n' on the output you get back, particularly if you are collecting all the output before you look at any of it.

This becomes a bit trickier if you are reading the output incrementally, as the '\r' and '\n' could be split across two different reads. However, if you break up the output on '\n' during your parsing, you could then see if the character before the '\n' is a '\r' and if so remove it.

Alternately, what happens if you don't set a term_type or term_size at all? That'll prevent AsyncSSH from asking for a PTY, and perhaps in that case the remote system won't add the '\r's. There may be other differences as well, such as not echoing your input back to you. That may or may not be a good thing in your case.

**Comment by jeremyschulman** [comment]
@ronf - I will try a few experiments where I do not specify a term_type or try adjusting the term_size settings.  

As a result of using `open_session` I see that that the underlying `create_session` uses `SSHClientStreamSession` as a session_factory.  Perhaps there is a different session_factory I should be using rather than the stream session?

**Comment by jeremyschulman** [comment]
I've discovered that if I use `res = await conn.run(command)` that I do not see the extraneous "\r" in the result.  Looking under the hood I see that `create_session` uses the `SSHClientProcess` factory instead of the `SSHClientStreamSession`.

My question to you is can I use the `SSHClientProcess` approach, but still maintain the use reading and writing multiple commands to the channel?  If so could you please share a sample of code to do this?

My use case is that after I login to a network device I need to issue one or more commands to disable the "paging" so that I can run large output command such as "show running-config" without the "more" option.  Hope that makes sense.

**Comment by ronf** [comment]
Did you mean create_process() here, rather than create_session()? The run() function uses create_process(), which in turn uses SSHClientProcess, which is a child class of SSHClientStreamSession. There should be no difference between the those when it comes to output of '\r' vs. '\r\n',  but there could be a difference based on whether you are passing in a terminal type or not. You may want to try create_process() rather than run() so that you can get back stdin/stdout/stderr similar to create_session() if you want to do interactive I/O, but you should also be able to make create_session() work in that case by using a similar set of arguments as create_process(). My guess is the important thing here is to not create a PTY, which means not passing in the term_type argument.

The main advantage to create_process() over create_session() is the redirect capability where you can automatically have AsyncSSH feed input or output from other files, pipes, sockets, etc. This allows you to get larger amounts of output without buffering it all in memory the way you would with run(), but also without having to do the I/O yourself.

Do you still see the paging behavior when you don't specify a terminal type?

If you are still seeing paging and need to run commands to disable that at the beginning of a session, doing interactive I/O makes sense. You can find an example of interactive I/O based on create_process() at https://asyncssh.readthedocs.io/en/latest/#interactive-input.

**Comment by jeremyschulman** [comment]
@ronf - You are correct, and thank you for the explanation!  I will give your suggestions a try and keep you updated.

**Comment by jeremyschulman** [comment]
I tried this approach:
````python
        async with asyncssh.connect(**self.conn_args) as conn:
            async with conn.create_process() as process:

                output = ''
                process.stdin.write("\n")
                while True:
                    output += await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                    breakpoint()

                    if self.PROMPT_PATTERN.match(output):
                        break
````

But the `breakpoint` was never reached; i.e. stuck in the `read()`.  Not sure why, or if I should be using something other than read.

**Comment by jeremyschulman** [comment]
I also tried the approach of omitting the `term_type` and again found myself stuck blocking in `read()`.   So similar behaviors in both approaches.

**Comment by ronf** [comment]
That's strange, unless the command generated no output. As long as you pass in a number greater than zero for the read(), it should return as soon as _any_ data arrives. You might want to enable debug logging and see whether the server is sending any data or not.

Also, if you have no terminal type, you may not see any prompt, which could explain what's happening here. Try actually writing a command rather than just a blank line.

**Comment by jeremyschulman** [comment]
Ok, I initiated the `create_process` with the initial command:

````python
        async with asyncssh.connect(**self.conn_args) as conn:
            command = disable_paging_commands[0]
            async with conn.create_process(command) as process:
                output = await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                breakpoint()

                process.stdin.write("show version\n")
                output = await process.stdout.read()
                breakpoint()
                x = 1
````

The first `output` contains what I expect.  (yea!)

But then when I attempt to write the "show version" command the resulting output is empty-string:

````python
(Pdb) output
''
````

**Comment by jeremyschulman** [comment]
I further noticed this:

````python
(Pdb) process.stdout.at_eof()
True
````

**Comment by jeremyschulman** [comment]
With logging enabled:

````
2020-05-31 11:18:16,791: INFO - INIT: lx010301.nyc1
2020-05-31 11:18:16,795: INFO - Opening SSH connection to 172.30.50.28, port 22
2020-05-31 11:18:16,841: INFO - [conn=0] Connection to 172.30.50.28, port 22 succeeded
2020-05-31 11:18:16,841: INFO - [conn=0]   Local address: 172.30.41.35, port 61891
2020-05-31 11:18:17,610: INFO - [conn=0] Beginning auth for user jeremy.schulman
2020-05-31 11:18:18,148: INFO - [conn=0] Auth for user jeremy.schulman succeeded
2020-05-31 11:18:18,149: INFO - [conn=0, chan=0] Requesting new SSH session
2020-05-31 11:18:18,339: INFO - [conn=0, chan=0]   Command: terminal length 0
> /Users/jeremy.schulman/Projects/NetworkBackup/netcfgbu/netcfgbu/netcfgbu_ssh.py(109)_get_config_disable_paging()
-> process.stdin.write("show version\r\n")
(Pdb) c
2020-05-31 11:18:24,034: INFO - [conn=0, chan=0] Received exit status 0
2020-05-31 11:18:24,035: INFO - [conn=0, chan=0] Received channel close
> /Users/jeremy.schulman/Projects/NetworkBackup/netcfgbu/netcfgbu/netcfgbu_ssh.py(113)_get_config_disable_paging()
-> x = 1
(Pdb) c
2020-05-31 11:18:27,737: INFO - [conn=0, chan=0] Closing channel
2020-05-31 11:18:27,737: INFO - [conn=0, chan=0] Channel closed
2020-05-31 11:18:27,737: INFO - [conn=0] Closing connection
2020-05-31 11:18:27,737: INFO - [conn=0] Sending disconnect: Disconnected by application (11)
2020-05-31 11:18:27,738: INFO - [conn=0] Connection closed
2020-05-31 11:18:27,741: INFO - DONE: lx010301.nyc1
````

**Comment by ronf** [comment]
Yeah - you can't pass a command on the create_process() call if you want to run multiple commands on a single channel. You need to request an interactive shell by leaving that command out and writing it in something like a stdin.write() call instead. Otherwise, the remote end will close the channel (signaling EOF as you saw) after it finishes running the command you provided when you created the session.

**Comment by jeremyschulman** [comment]
Ok, I tried something like this:

````python
        async with asyncssh.connect(**self.conn_args) as conn:
            command = disable_paging_commands[0]
            async with conn.create_process() as process:
                breakpoint()
                process.stdin.write("show version\n")
                await process.stdin.drain()
                output = await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                breakpoint()

                process.stdin.write("show version\r\n")
                await process.stdin.drain()
                output = await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                breakpoint()
                x = 1
````

Found myself stuck in the `read` again.  

My guess at this point is that when I need to read/write multiple commands to the same channel that I am going to need to resort to using `open_session` and then strip out the unwanted "\r" at the end of my processing.

If you have any other suggestions I will try them; but if not we should close this issue out.

**Comment by ronf** [comment]
There really should be no difference in behavior when switching between open_session() and create_process(). Both actually use SSHClientStreamSession internally. SSHClientProcess is just a thin wrapper around the streams API which provides things like I/O redirection.

You might want to take out the call to stdin.drain() there, as it really shouldn't be needed in this case. If you are sending a large amount of input and want to wait for that to all be sent, it could make sense, but not for a short command like that.

Also, you might try changing the first "show version" command there to end in "\r" rather than "\n". Some systems accept both, but normally input would end in a "\r", at least when a terminal is involved.

I agree that the simplest thing at this point might be to just live with the "\r\n" line endings in the output and strip them off yourself. It's easy to do, especially if you are processing the output a line at a time for other reasons. However, if you do see differences between open_session() and create_process() not caused by changing arguments to them, I'd be very curious about the details.

**Comment by jeremyschulman** [comment]
I tried the "\r" at the end and still stuck in `read`.  From all these observations it appears that a VTY is required for me to make multiple reads/writes.  When I remove the term_type from the open_session I get the same stuck results.

**Comment by jeremyschulman** [comment]
Interestingly enough when I add the term_type to create_process this works:

```python
        async with asyncssh.connect(**self.conn_args) as conn:
            command = disable_paging_commands[0]
            async with conn.create_process(term_type='vt100') as process:
                breakpoint()
                process.stdin.write("show version\n\r")
                output = await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                breakpoint()

                process.stdin.write("show version\r\n")
                await process.stdin.drain()
                output = await process.stdout.read(io.DEFAULT_BUFFER_SIZE)
                breakpoint()
                x = 1
````
I am no longer stuck in the `read`; but my results again have "\r\n".

**Comment by jeremyschulman** [comment]
At present this is the latest working snippet:

```python
    async def _get_config_disable_paging(self):

        disable_paging_commands = self.os_spec['disable_paging']
        if not isinstance(disable_paging_commands, list):
            disable_paging_commands = [disable_paging_commands]

        try:
            conn = await asyncio.wait_for(asyncssh.connect(**self.conn_args), timeout=60)
        except asyncssh.Error as exc:
            self.failed = exc
            return

        async with conn.create_process(term_type='vt100') as process:
            self._process = process
            await self.read_until_prompt()

            for cmd in disable_paging_commands:
                # TODO: need to check result for errors
                await self.run_command(cmd)

            command = self.show_running
            result = await self.run_command(command)
            self.config = result.replace("\r", "")
````

*Aside*: I intend to add code that will try different connection arguments for the use-case where the username/password could be different across devices; which is why I am not using a context manager for the connection instance.

**Comment by ronf** [comment]
> Interestingly enough when I add the term_type to create_process this works

Ok - so it was the PTY request that made the difference here, not the difference between open_session() and create_process(). That makes sense - thanks for confirming.

> Aside: I intend to add code that will try different connection arguments for the use-case where the username/password could be different across devices; which is why I am not using a context manager for the connection instance.

Keep in mind that these are not mutually exclusive. You don't have to use "async with <func> as conn:" to invoke it as a context manager. You can also do "conn = <func>" followed by "async with conn:", allowing you to vary the way you construct the connection but still get the benefits of automatically closing the connection and cleaning up when you leave the block.

If you do decide not to use a context manager, I'd recommend you have some kind of "try..finally" block that does a "conn.close()" followed by an "await conn.wait_closed()" to make sure things are fully cleaned up before you exit.

**Comment by jeremyschulman** [comment]
@ronf - thank you for the pointers/suggestions re:context manager and cleanup.  I'll definitely try this out and keep your notes in mind.

I am closing this issue as you've really helped me out and I believe I am aok to continue with my project.  It's WIP; but if your interested, you can find it here:

https://github.com/jeremyschulman/netcfgbu

**Comment by ronf** [comment]
Happy to help! By the way, you might want to check out issue #280 here. It's slightly different in terms of why a PTY was needed, but there's some sample code there that you might find useful around trying to read output up to the next prompt. Note that this code is somewhat fragile, though, if the output of the commands you are running might in some cases contain text matching the prompt you use. So, as part of your setup, you might want to set the prompt to something more unique, if the remote system allows you to customize that.

**Comment by jeremyschulman** [comment]
Hi @ronf - thank you; I actually found that issue and after looking through the comments and then looking at the their project it helped out a great deal.
