### ISSUE TITLE
ProtocolError: 'utf-8' codec

### ISSUE THREAD

**Issue by jeremyschulman** [ronf/asyncssh#286]
I am using the `develop` branch to connect to a device with KeyExchange set in the ssh_confg file to:
"KexAlgorithms ecdh-sha2-nistp256,diffie-hellman-group14-sha1"

I observe the packets arriving in small chunks ~374 bytes; slowly.  At some point in the process I observe this error and the asyncssh then sends a disconnect.

This is the same "problem device" as used in the issue #285 for reference.  I am **hoping** that there is another obscure ssh-config setting that I need to use to deal with this old version of OpenSSH (should that actually be the problem).

Really appreciate your time to review this packet trace and let me know how next to proceed.

```python
2020-06-08 09:56:07,718 INFO: [conn=0] Sending disconnect: 'utf-8' codec can't decode byte 0x92 in position 193: invalid start byte (2)
2020-06-08 09:56:07,718 DEBUG: [conn=0, pktid=25] Sent MSG_IGNORE (2), 5 bytes
  00000000: 02 00 00 00 00                                   .....
2020-06-08 09:56:07,719 DEBUG: [conn=0, pktid=26] Sent MSG_DISCONNECT (1), 90 bytes
  00000000: 01 00 00 00 02 00 00 00 48 27 75 74 66 2d 38 27  ........H'utf-8'
  00000010: 20 63 6f 64 65 63 20 63 61 6e 27 74 20 64 65 63   codec can't dec
  00000020: 6f 64 65 20 62 79 74 65 20 30 78 39 32 20 69 6e  ode byte 0x92 in
  00000030: 20 70 6f 73 69 74 69 6f 6e 20 31 39 33 3a 20 69   position 193: i
  00000040: 6e 76 61 6c 69 64 20 73 74 61 72 74 20 62 79 74  nvalid start byt
  00000050: 65 00 00 00 05 65 6e 2d 55 53                    e....en-US
2020-06-08 09:56:07,719 INFO: [conn=0] Connection failure: 'utf-8' codec can't decode byte 0x92 in position 193: invalid start byte
2020-06-08 09:56:07,719 INFO: [conn=0, chan=0] Closing channel due to connection close
2020-06-08 09:56:07,719 INFO: [conn=0, chan=0] Channel closed: 'utf-8' codec can't decode byte 0x92 in position 193: invalid start byte
2020-06-08 09:56:07,719 INFO: [conn=0] Closing connection
2020-06-08 09:56:07,719 INFO: [conn=0] Sending disconnect: Disconnected by application (11)
2020-06-08 09:56:07,719 DEBUG: [conn=0, pktid=27] Sent MSG_IGNORE (2), 5 bytes
  00000000: 02 00 00 00 00                                   .....
2020-06-08 09:56:07,720 DEBUG: [conn=0, pktid=28] Sent MSG_DISCONNECT (1), 45 bytes
  00000000: 01 00 00 00 0b 00 00 00 1b 44 69 73 63 6f 6e 6e  .........Disconn
  00000010: 65 63 74 65 64 20 62 79 20 61 70 70 6c 69 63 61  ected by applica
  00000020: 74 69 6f 6e 00 00 00 05 65 6e 2d 55 53           tion....en-US
2020-06-08 09:56:07,720 INFO: CLOSED: <***redacted***>
2020-06-08 09:56:07,720 INFO: [conn=0] Closing connection
2020-06-08 09:56:07,720 INFO: [conn=0] Sending disconnect: Disconnected by application (11)
2020-06-08 09:56:07,720 DEBUG: [conn=0, pktid=29] Sent MSG_IGNORE (2), 5 bytes
  00000000: 02 00 00 00 00                                   .....
2020-06-08 09:56:07,720 DEBUG: [conn=0, pktid=30] Sent MSG_DISCONNECT (1), 45 bytes
  00000000: 01 00 00 00 0b 00 00 00 1b 44 69 73 63 6f 6e 6e  .........Disconn
  00000010: 65 63 74 65 64 20 62 79 20 61 70 70 6c 69 63 61  ected by applica
  00000020: 74 69 6f 6e 00 00 00 05 65 6e 2d 55 53           tion....en-US
2020-06-08 09:56:07,720 INFO: FALSE
```

**Comment by ronf** [comment]
If you're getting non-ASCII data on the connection which isn't valid UTF-8, you should either specify the encoding used for it as the "encoding" parameter, or you can have AsyncSSH treat it as raw binary data by specifying encoding=None, in which case the data AsyncSSH returns will be of type bytes rather than str and it won't be converted to Unicode.

**Comment by jeremyschulman** [comment]
@ronf - I've converted the code to open the session with `encoding=None`.  So the good news is that I am not seeing the same issue.  I am, however, still seeing that the data transfer is ridiculously slow.  The transfer appears to be sending packets 372 bytes length.  And between each packet it is pausing for about 10 seconds.  

My guess is that this is due to the sending device.  I am curious if there is an ssh_config option that I could try to adjust to resolve this. Any thoughts/suggestions would be greatly appreciated!

**Comment by jeremyschulman** [comment]
@ronf - upon further debugging on the device, we are observing the same behavior directly on the CLI.  So it appears to be an issue that we need to discuss with the vendor directly.

Further regarding the encoding=None issue; we also identified that someone in the configuration file there was a bad character; likely due to a copy-paste.  🤦 

I am curious, now that I have the my code using encoding=None; is this more efficient to proceed this way, or should I revert back to using strings?

**Comment by ronf** [comment]
Yeah - it sounds like there's not much you can do in AsyncSSH about the device slowness.

Regarding the "bad character", that's quite common -- in particular, 0x92 is one of the double-quote characters in the Windows 1252 code page. You'll often end up with that when pasting a string containing "smart quotes".

As for whether to stick with encoding=None or not, it depends on what you're eventually doing with the output. If you don't need to interpret it as Unicode data and don't mind the data being delivered to you as a "bytes" value rather than a Python string, you're probably better off sticking with encoding=None. That should be slightly more efficient, avoiding the conversions from bytes on the wire to & from Unicode. You just need to make sure if you're doing something like writing data to a file that you open the file in binary mode.

**Comment by jeremyschulman** [comment]
@ronf - Thank you for the advice.  I'll keep with encoding=None.
Closing issue.
