### ISSUE TITLE
No matching encryption algorithm found (develop branch)

### ISSUE THREAD

**Issue by jeremyschulman** [ronf/asyncssh#287]
I am running a test using the develop branch and I observe this output.  It appears to me that the Client to server and Server to client have matching encryption options.  Note that my ssh_config file does not define any encryption options.  

Could you please explain why I am observing this error?  Thank you.

```python
2020-06-08 16:36:45,191 DEBUG: [conn=0] Received key exchange request
2020-06-08 16:36:45,191 DEBUG: [conn=0]   Key exchange algs: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2020-06-08 16:36:45,191 DEBUG: [conn=0]   Host key algs: ssh-rsa
2020-06-08 16:36:45,191 DEBUG: [conn=0]   Client to server:
2020-06-08 16:36:45,191 DEBUG: [conn=0]     Encryption algs: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
2020-06-08 16:36:45,191 DEBUG: [conn=0]     MAC algs: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
2020-06-08 16:36:45,191 DEBUG: [conn=0]     Compression algs: none
2020-06-08 16:36:45,191 DEBUG: [conn=0]   Server to client:
2020-06-08 16:36:45,191 DEBUG: [conn=0]     Encryption algs: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
2020-06-08 16:36:45,191 DEBUG: [conn=0]     MAC algs: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96
2020-06-08 16:36:45,191 DEBUG: [conn=0]     Compression algs: none
2020-06-08 16:36:45,192 INFO: [conn=0] Sending disconnect: No matching encryption algorithm found (3)
```

When I revert to using the master branch without ssh_config support I am able to connect to the device AOK.

**Comment by ronf** [comment]
One of the changes between the "develop" branch of AsyncSSH and the currently shipping version is that it now disables weaker algorithms by default similar to other modern SSH implementations. It lets you re-enable them, but you have to be explicit about it. It looks like the system you are talking to only supports CBC-based ciphers, which are considered vulnerable these days.

If you want to re-enable the CBC ciphers, you can. You can even add them to the default list without having to list all of them, by passing in a value such as '+aes128-cbc,aes256-cbc' in the "encryption_algs" argument, or in a "Ciphers" line in the config file with the same syntax.

**Comment by jeremyschulman** [comment]
@ronf - I guess where I am confused is that from reading the output of the log it would see that "both sides agree to support" the same settings; and then I would presume asyncssh would "honor" the agreement and uses a shared/agreed value.  I don't quite understand the motivation for purposefully disabling the weaker algorithms if both sides support them in the exchange.
  Perhaps could you share URLs to the other modern SSH implementations for my reference and I could educate myself?

**Comment by ronf** [comment]
First, take a closer look at the debug output. The piece you shows is only half of the story. You showed what was in the "Received key exchange request". Both sides send a list of possible algorithms to use for client->server communication and another set for server->client communication. Usually, those lists are the same, but that's not what you need to compare. You need to look at the algorithms sent by AsyncSSH and compare those to the algorithms received by it from the other SSH implementation. In what you showed here, the other SSH implementation said it wanted to use CBC-based encryption algorithms for both directions. However, take a look for the rest of the key exchange debugging. You should see something like:

```
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0]   Key exchange algs: diffie-hellman-group14-sha256
DEBUG:asyncssh:[conn=0]   Host key algs: sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-ed448-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-1.3.132.0.10-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com
DEBUG:asyncssh:[conn=0]   Encryption algs: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
DEBUG:asyncssh:[conn=0]   MAC algs: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG:asyncssh:[conn=0]   Compression algs: zlib@openssh.com,none
```

Since AsyncSSH always sends the same list for both client->server and server->client, the debugging doesn't bother showing the lists twice. As you can see in my example here, the default list of encryption algorithms doesn't include anything CBC-based any more. The default ciphers are:

    chacha20-poly1305@openssh.com
    aes256-gcm@openssh.com
    aes128-gcm@openssh.com
    aes256-ctr
    aes192-ctr
    aes128-ctr

None of these match what the other SSH implementation sent in your case, and that's why you got the error that you did.

Here's a page from OpenSSH about legacy algorithms and the commands you can use to list which algorithms are enabled by default: https://www.openssh.com/legacy.html

For AsyncSSH, this is discussed at https://asyncssh.readthedocs.io/en/develop/api.html#supported-algorithms.

Here's another page on this: https://forums.centos.org/viewtopic.php?t=69503

If you search, you'll see a number of different vendors have published pages about how to disable weak algorithms. For the longest time, I resisted disabling anything by default, preferring to leave the old algorithms enabled but always later in the list than the stronger algorithms. However, this could still end up with an older device appearing to connect securely when it's really only capable of using weak algorithms. By disabling them by default, you have to opt-in before the connection will work, and you can decide if you're ok using weaker algorithms or not.

**Comment by jeremyschulman** [comment]
@ronf - Thank you very much for taking the time to write this explanation.  I've added the following to my ssh_config file and now I am able to connect AOK:

````
KexAlgorithms ^ecdh-sha2-nistp256,diffie-hellman-group14-sha1
Ciphers ^aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
````

**I have an enhancement request that would aid in the debub/troubleshooting process**.  When AsyncSSH raises

````
KeyExchangeFailed: No matching encryption algorithm found
````

Could the exception object include server supported values so that this information can be represented back to the User and they can make the necessary configuration changes?  If this information is not available in the exception instance then they would be required to enable debug logging to identify this information.

**Comment by ronf** [comment]
Having this exception return both the local and remote algorithms it was trying match up seems reasonable, and this should be straightforward as both lists are available in a common "_choose_alg" function that is currently responsible for raising that exception for all of the different algorithm matches. Once I get some other changes checked in, I'll look at adding this.

**Comment by jeremyschulman** [comment]
@ronf - thank you very much.  I will close this issue and create a new enhancement request.
