### ISSUE TITLE
How to use in webterminal 

### ISSUE THREAD

**Issue by kexirong** [ronf/asyncssh#288]
The documentation failed to make me understand how to use in webterminal .
I need help .
thanks .

**Comment by kexirong** [comment]
These codes do not run correctly
'''
async def run_client():
    async with asyncssh.connect('localhost', known_hosts=None, username='kexirong', password='kexirong') as conn:
        w, r, er = await conn.open_session(term_type='xterm-256color')
        for i in ['ls ./\n', 'echo hello\n', 'echo word\n']:
            w.write(i)
            print(await r.read())
            print(await er.read())
try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
'''

**Comment by ronf** [comment]
I'm sorry, I don't really know what you mean by "webterminal".

Regarding the example code you posted, you can't do a read() call without a length,  as it will block until the other end closes the channel. You need to do something more like what's in #227, or you need to open separate sessions for each command you want to run (which is a lot cleaner and more reliable), if the server you are connecting to supports opening multiple sessions on a single connection, which you can find an example of in #241.

**Comment by kexirong** [comment]
@ronf Thanks for your reply.
Webterminal means to Implement terminal in webpage.
like the putty, send a word then back a word and display.

**Comment by kexirong** [comment]
I modified the code
```
async def run_client():
    async with asyncssh.connect('localhost', known_hosts=None, username='kexirong', password='kexirong') as conn:
        w, r, er = await conn.open_session(term_type='xterm-256color')
        for i in ['ls ./\necho hello\necho word\n']:
            w.write(i)
        await asyncio.sleep(1)
        print(await r.read(2048))
```
output:
```
ls ./
echo hello
echo word
]0;kexirong@localhost:~[kexirong@localhost ~]$ ls ./
abc  common.py  data.py  __pycache__  qkacmdb-sanic  test
]0;kexirong@localhost:~[kexirong@localhost ~]$ echo hello
hello
]0;kexirong@localhost:~[kexirong@localhost ~]$ echo word
word
]0;kexirong@localhost:~[kexirong@localhost ~]$ 
```
how to don't display the line 1,2,3

**Comment by ronf** [comment]
Since you are opening a connection with a PTY associated with it, the remote shell you start up is going to echo input by default, and that's why you are seeing the first three lines of output with the commands in them, and then seeing the shell repeat them later again in conjunction with the shell prompt.

When you use an interactive shell like this rather than executing specific commands each on their own channels, there's really no way to distinguish what part of the output you get back is related to the input you provided, what part is the shell prompting you, and what part is actually the output of the commands you are running. That's one of the reasons I suggested doing something more like what it in #241, at least for SSH servers that can support that.

**Comment by ronf** [comment]
Since you are opening a connection with a PTY associated with it, the remote shell you start up is going to echo input by default, and that's why you are seeing the first three lines of output with the commands in them, and then seeing the shell repeat them later again in conjunction with the shell prompt.

When you use an interactive shell like this rather than executing specific commands each on their own channels, there's really no way to distinguish what part of the output you get back is related to the input you provided, what part is the shell prompting you, and what part is actually the output of the commands you are running. That's one of the reasons I suggested doing something more like what it in #241, at least for SSH servers that can support that.
