### ISSUE TITLE
AsyncSSH uses version of Cryptography which in turn uses deprecated methods

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#29]
Just a heads up about the deprecation warnings that show up with the current (1.3.0) version of AsyncSSH:

```
lib/python3.5/site-packages/cryptography/utils.py:71: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

Deprecation warnings show up when you invoke Python with `-Wdefault::DeprecationWarning`.

It looks like the Cryptography folks have [already fixed this issue](https://github.com/pyca/cryptography/issues/2382), so consider this report a reminder to update AsyncSSH's dependencies when the Crypto folks make a new release.

**Comment by nchammas** [comment]
For the record, if I understand correctly, AssyncSSH [allows cryptography >= 1.0.0](https://github.com/ronf/asyncssh/blob/3ecb45182761afd06dae71f47502392544d30e12/setup.py#L46). I just noticed that Cryptography has made a couple of bugfix releases since that version, one of which patches a [security issue](https://github.com/pyca/cryptography/blob/0eafd9cd32a69909bd7bab955459925f54bd7278/CHANGELOG.rst#102---2015-09-27).

It might be good to bump up the cryptography dependency right away in master to require those fixes, and again when they make a release to fix the aforementioned deprecation warnings.

**Comment by nchammas** [comment]
On the topic of staying on top of dependency changes, I recently discovered [Requires.io](https://requires.io/). It looks handy for helping the project maintainer track this kind of stuff.

**Comment by ronf** [comment]
Thanks for letting me know, Nicholas. I'll be sure to update my dependency to the newer cryptography version once it is out and my tests against it work.

I actually have another good reason to do this -- I've been testing against a version of cryptography with OpenSSL ECDH support added and have AsyncSSH all ready to use that instead of my pure Python implementation as soon as that change is integrated.

Regarding updating to version 1.0.2 in the meantime, I had some problems with the static version of OpenSSL linked with the MacOS cryptography 1.0.1 release. So, even though I allow the later versions to be used (and they do work for me if I don't do the wheel install), I didn't want to force the later versions to be used until someone has had a chance to look more closely at that problem.

**Comment by nchammas** [comment]
> Regarding updating to version 1.0.2 in the meantime, I had some problems with the static version of OpenSSL linked with the MacOS cryptography 1.0.1 release. 

I believe I ran into a related issue which I [discussed briefly with the Cryptography devs](https://botbot.me/freenode/cryptography-dev/2015-10-13/?msg=51751053&page=1) earlier today. It's keeping me from using AsyncSSH at all.

I'm going to watch https://github.com/pyca/cryptography/issues/2330 and try again as soon as it's resolved and new releases of Cryptography and AsyncSSH have been made which incorporate the fix.

**Comment by ronf** [comment]
Yeah - until this is fixed, my suggestion is that you either go back to 1.0.0 or you use the "--no-use-wheel" option when you do the cryptography install. That seems to prevent the crash from occurring for me.

**Comment by ronf** [comment]
I've moved AsyncSSH to depend on cryptography 1.1 now that it is out and I'm no longer seeing this crash, so I'm going to close this issue.
