### ISSUE TITLE
[Question] Package Structure of asyncssh.scp

### ISSUE THREAD

**Issue by iwoloschin** [ronf/asyncssh#297]
I've recently started using [Pylance](https://github.com/microsoft/pylance-release) and it's throwing some errors about asyncssh. Here's one I've reported to Pylance:

https://github.com/microsoft/pylance-release/issues/188

For that specific error a reasonable fix might be moving `asyncssh/scp.py` to `asyncssh/_scp.py` and changing the relevant imports to `from ._scp import scp` or similar. I took a brief look and I think this is a reasonable change, especially since almost everything in `scp.py` is a not part of the public API. I'm not sure how a change like this would impact other projects relying on asyncssh, but in my own use I only use top level (`from asyncssh import ...`) imports, meaning a change like this shouldn't break anything.

To be clear, I do not think this change is necessary, obviously things are working as is, but I do think that a (hopefully small?) change like this could help reduce some confusion, either for humans or type checkers!

For a real life example of a library that does a lot of this sort of stuff check out [httpx](https://github.com/encode/httpx/tree/master/httpx).

**Comment by ronf** [comment]
In terms of a "public API", you're right that AsyncSSH doesn't make any promises to preserve anything outside of what's imported by the top-level module (via asyncssh/__init__.py). Changes in other modules are fair game, but I'm still a bit hesitant to make this change given that Python doesn't have a problem with importing a function which has the same name as a module, particularly when the module that would be "shadowed" is actually not part of the project's public API and should not (and in fact cannot) be imported directly by applications.

I would also worry about a leading underscore like that causing some people to think this was some kind of accelerator module written in C, since most of the places in Python I've seen leading underscores used in module names is for that purpose. I know that technically it could be used for any "private" module, and there are a small number of examples of that already in the Python standard library, but even those typically implement the same APIs as a module of the same name without an underscore, and that would not be the case here.

It looks like PyLance is fixing this on their side, and I can see how that would be useful in other cases where a package has an internal module which happens to be the same name as a symbol they want to export at the package level. I appreciate the report of this, though, both here and in PyLance!

**Comment by jakebailey** [comment]
For what it's worth, a number of libraries I know of do this when they're just using regular Python code; many have modules like `_compat` or `_typing` to wrap up shared version compatibility primatives or common things to do with `typing`. urllib3 has [\_collections](https://github.com/urllib3/urllib3/blob/master/src/urllib3/_collections.py) which holds a few datatype implementations. In general, I think `_` prefixes are good to say "please don't import this", especially if you don't want to promise compatibility. C code often ends up in this camp because people often wrap the compiled code in a more friendly format (but a few libraries don't and expose the C-compiled code directly).

Things like `from .scp import scp` are a bit nebulous in the way they operate; this in particular only works because that line imports `asyncssh.scp`, meaning the import system remembers that it's already done it, and then the assignment creates a variable so it's always going to give back the variable. It's tricky, but consistent, so we can handle it in Pylance.

There are unfortunately other import side effect problems in the same vein that aren't so nice... 😄

**Comment by ronf** [comment]
Fair enough -- I'll definitely think twice before doing an import like this in the future. :)

I can definitely see an argument for _all_ of the asyncssh modules starting with a leading underscore to signify that all of them are "private" and that applications shouldn't import them (along the lines of what "httpx" does). However, I think it'd be a bit late to make that kind of change now. Perhaps that's something I'll consider if I ever get to a version 3.0, where there would be less concern about preserving backward compatibility (even though technically I don't promise that compatibility now for anything in internal modules).

**Comment by iwoloschin** [comment]
One thing to consider is making this sort of explicit private/public API change along with any type annotation work, basically do not make any wholesale changes, but if you touch an internal module to add type annotations, take that as an opportunity to mark it explicitly as private or public. I don't know if that's something that would require a 3.0 release for a clean break or if that's something that could be slowly expanded upon with the current release.

**Comment by ronf** [comment]
I'd still probably want to wait for a 3.0 before making any significant visibility changes on anything. From various bug reports I've gotten, I've seen at least a few examples where code referenced a public symbol but happened to import it using a non-top-level import. So, if I were to mark the modules under AsyncSSH private, it would break that code even though the items being accessed were public. That might be a good thing in the long run to make sure no one imports anything not explicitly exported by the top-level module, but I'd still prefer to only do it as part of a major version where such breakage is announced in advance.

I have separately looked at adding type annotations and even made a pretty significant effort on this in a private branch a while back, but at the time a lot of the things I referenced in cryptography hadn't made it into typeshed yet, and so I had to create a lot of my own interface files for code outside of  AsyncSSH that I didn't really want to export as part of AsyncSSH. At some point I'll look at this again and perhaps take a more incremental approach, doing the "easy" stuff first even if I can't add types for ALL of any given module, but I wanted to give that stuff a little more time to mature first.

The other complication with type checking is that I intentionally allow a large number of different types for some parameters to provide different ways of passing things for convenience. While there are "Union" types that can handle this, some of those unions were getting REALLY complicated to express. In the end, it actually made the code less readable in many places.
