### ISSUE TITLE
Limit Size of Stdout and Stderr?

### ISSUE THREAD

**Issue by xuhang57** [ronf/asyncssh#306]
Hi there,

Is there a way to limit the size of stdout/stderr in collect_output() or create_process()? I've checked the documentation it seems like we can use the `bufsize` to limit the size from a file to stdin. However, I am looking for something similar with the `limit` in https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.create_subprocess_exec

Thanks!

**Comment by ronf** [comment]
The asyncio documentation is not particularly clear on what "limit" actually is. However, from reading the source, it has to do with how much data can be read into a receive buffer before asyncio stops accepting data. When the receive buffer on a session reaches the limit, it triggers a pause_reading() action on the associated transport object, and later once you've read enough data to get below the limit this triggers a resume_reading() on the transport, allowing more data to be added to the receive buffer.

This is very different than bufsize in SSHProcess, which is about how much data asyncio will attempt to read from a stream in a single read() call when doing redirection of stdin/stdout/stderr, where you aren't reading the data yourself. This bufsize has nothing to do with how much data can be buffered when no read() is outstanding. In the redirection case there would pretty much always be a read outstanding, so a concept of "limit" doesn't really apply in that case.

AsyncSSH does actually have its own implementation of "limit" which triggers pause_reading()/resume_reading(), but right now it's not exposed directly. When a channel is opened, the corresponding SSHStreamSession sets the limit to the channel's receive window, which you can actually control when you open the channel. Basically, the idea is to allow whatever the receive window is to be in flight at any given time, and an equal amount to be buffered in receive buffers. So, if you have a 2 MiB receive window (the default), you can have up to 4 MiB of data sent by the other end of the channel before it your receive needs to begin reading to prevent the other end from being told to stop sending. It'll "pause" after the first 2 MiB of unread data is buffered and stop adjusting the receive window at that point, forcing the other end to stop sending when another 2 MiB is used up.

You mention collect_output(), but that's intended to return everything that's sitting in the receive buffers without blocking, so I'm not quite sure how that relates to "limit", except in the sense that it won't allow the receive buffer to grow beyond what the limit is set to. An exception is made here if you use communicate(), wait(), or run(), as those all set the limit to None, to make sure ALL of the data can be buffered and returned.

Could you say a bit more about what behavior you're looking for? If you want to read only up to some maximum amount, you're probably better off actually calling read() yourself rather than using something like collect_output(), wait(), or run(). Just be aware that the read() call could block, so you might need separate asyncio tasks if you want to read from both stdout and stderr in parallel.

**Comment by xuhang57** [comment]
Thanks so much for your thorough writeup and explanation! It looks like `read()` should be what I am looking for? 

The behavior I am looking for is, given a limit of size, the process should be stopped and returned when reaching the limit. Currently, when a command generates a very large stdout/stderr on a server with limited memory, the server will be killed due to OOM. Truncating the size of stdout/stderr seems to be a reasonable solution in my case as I don't want to increase the memory or any other approaches. Any recommendations/suggestions on how to achieve it within `Asyncssh` would be much appreciated!

Thanks again!

**Comment by ronf** [comment]
Do you need to capture data from both stdout & stderr, or just stdout?

If you just want to read data from stdout up to some maximum number of bytes, the easiest thing to do would be to call readexactly() on process.stdout, passing in your limit as the number of bytes to read. If the read completes without an error, you'll know you you hit the limit and you'll get back that many bytes. If the remote process outputs less than that before closing, an IncompleteReadError will be raised, letting you know you got all the bytes that were available, and you can access those bytes via the "partial" field in the exception. It's a bit backwards, but it works.

Your other option is to call read() in a loop, keeping track of the total bytes so far and exiting out of the loop when you hit the limit, but that's more complicated than using readexactly().

If you want to read data from both stdout and stderr, you can use asyncio.gather() on calls to both stdout.readexactly() and stderr..readexactly() in parallel, and then check the results you get back to see if they are returned data (if you hit the limit) or an exception if the stream closes before hitting the limit, in which case you can pull out the bytes from exc.partial as mentioned above. Just make sure to set return_exceeptions=True in the gather() call.

**Comment by xuhang57** [comment]
Both would be great, but only stdout is necessary.

If I understand this correctly, currently, in Asyncssh, the best approach to limit the stdout/stderr is via `SSHStreamSession`. I haven't used it before as I've been using `SSHClientProcess` and `SSHCompletedProcess`. Using `readexactly()` sounds great but my first preference is use some methods directly from the `Asyncssh` so that I don't have to change the codebase dramatically. 

Really appreciate your help! Feel free to close the issue. 👍

**Comment by ronf** [comment]
I was actually thinking of the readexactly() method on SSHReader, which you have in your existing process object as "stdout" and "stderr" members. The process object itself is a subclass of SSHStreamSession, and the SSHReader/SSHWriter objects inside it call back into that SSHProcess to actually do their I/O.

The code I'm suggesting would look something like:

```python
    async with asyncssh.connect('localhost') as conn:
        process = await conn.create_process(command)

        try:
            data = await process.stdout.readexactly(limit)
            print('Limit reached:', data, len(data))
        except asyncio.IncompleteReadError as exc:
            data = exc.partial
            print('Data:', data, len(data))
```

You'll need to fill in values for "command" and "limit" here. You could do a similar read call on stderr if you want to get that output as well, potentially even setting a different limit. If the limits are small enough, there's no need to run these two read calls in parallel, but if you wanted to do that you could, using asyncio.gather().

**Comment by xuhang57** [comment]
Wow, great! This is definitely something I am looking for! Sounds great with using `asyncio.gather()` to do in parallel. 

Thank you so much for helping Ron!

**Comment by ronf** [comment]
Happy to help! For completeness, here's an example showing the use of asyncio.gather and how you can make a read_limit() function which does what you were looking for:

```python
async def read_limit(reader, limit):
    """Read up to limit bytes from a stream"""

    try:
        return await reader.readexactly(limit)
    except asyncio.IncompleteReadError as exc:
        return exc.partial

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        process = await conn.create_process(command)

        stdout_data, stderr_data = await asyncio.gather(
            read_limit(process.stdout, stdout_limit),
            read_limit(process.stderr, stderr_limit))

        print('stdout: ', stdout_data)
        print('stderr: ', stderr_data)
```
