### ISSUE TITLE
How to enable passphrase input or provide passphrase for ProxyJump

### ISSUE THREAD

**Issue by ddutt** [ronf/asyncssh#307]
Hi,

This is not a bug report, as much as a request for help. 
Version of asyncssh used is 2.3.0. I'm using asyncssh within an open source project called Suzieq (netenglabs/suzieq). 

I have a case where I have to access a device through a jump host. I used ProxyJump which works correctly in asyncssh. I also have client keys that need to be decoded both from my client machine and on the jump host. Passing passphrase to decode the private keys worked on the client machine but did not work on the jump host, though I specified the passphrase as an option. Using SSH from the command line works the same way: I'm prompted for password on my client machine and also again from the jump host. So, this is also not different from what asyncssh is encountering. But the passphrase passed does not get passed to the jump host passphrase challenge, it seems. 

Here are my code snippets.
```python
                self.pvtkey = asyncssh.public_key.read_private_key(
                    pvtkey_file, self.passphrase)
```
```python
                self._conn = await asyncio.wait_for(
                    asyncssh.connect(
                        self.address,
                        port=self.port,
                        known_hosts=None,
                        client_keys=self.pvtkey if self.pvtkey else None,
                        username=self.username,
                        passphrase=self.passphrase,
                        password=self.password if not self.pvtkey else None,
                    ),
                    timeout=self.cmd_timeout,
                )
```
I appreciate any help you can offer.

Thanks for a wonderful, very helpful package.

Dinesh

**Comment by ronf** [comment]
Hello - I'm happy to hear you're finding AsyncSSH useful!

The authentication to both the jump host and the device behind it both happen from the client machine running AsyncSSH. So, you should be able to load the private key once and use it for authentication on both connections, without actually passing the passphrase to the jump host. However, you'd need to pass the client_keys arguments when making both connections. If you use ProxyJump in the SSH config file to open the tunnel, though, you can't pass an encrypted private key, as the config file doesn't provide an argument to pass in a passphrase.

Instead, you'll want to do something like:

```python
    self._tunnel = await asyncssh.connect(
        JUMPHOST,
        username=self.username,
        client_keys=self.pvtkey if self.pvtkey else None
        password=self.password if not self.pvtkey else None)

    self._conn = await tunnel.connect_ssh(
        self.address,
        port=self.port,
        client_keys=self.pvtkey if self.pvtkey else None,
        username=self.username,
        password=self.password if not self.pvtkey else None)
```

You can clean this up somewhat by doing the following:

```python
    options = asyncssh.SSHClientConnectionOptions(
        username=self.username,
        client_keys=self.pvtkey if self.pvtkey else None
        password=self.password if not self.pvtkey else None)

    self._tunnel = await asyncssh.connect(JUMPHOST, options=options)
    self._conn = await self._tunnel.connect_ssh(self.address, port=self.port, options=options)
```

Either or both of these calls can be wrapped a wait_for() with a timeout, though you're probably better off using the "login_timeout" option in the connect() call for that, or adding login_timeout to the arguments in SSHClientConnectionOptions to have it apply to both connections. You can also pass in the passphrase in options and  the filename of the private key file in client_keys, avoiding the need to call read_private_key() explicitly.

When cleaning up, don't forget to call close() on both self._tunnel and self._conn, since you aren't calling connect() inside an "async with" block in this case.

I could potentially change AsyncSSH to allow any passphrase argument you provide to both the tunneled connection and the establishing of the tunnel when ProxyJump is present in the config file. However, you'd need to put the filenames of the client keys you want to use in the config file as well for that to be available to both connections and not use the client_keys argument in this case. Since the keys and passphrases might be different, I think it's cleaner to specify the options explicitly in each connect() as shown above, using an options argument if you want to use the same values for both.

I guess another option might be for AsyncSSH to pass everything in options in a connect call to the call to open the tunnel when ProxyJump is set in the config. I kind of like that idea. You could still make two separate calls when the options need to be different, but in the cases where they aren't, this could simplify the code. I'll experiment with that and get back to you. In the meantime, creating the SSHClientConnectionOptions yourself and passing it to both connect calls should get you going.

**Comment by ddutt** [comment]
What a fantastic and detailed response. Thanks so much @ronf I'll proceed with your suggestion for now, and also look forward to your suggestion to doing all the work with an option within asyncssh itself. 

Appreciate your help and your work in making asyncssh available to benefit from.

Best wishes,
Dinesh

**Comment by ronf** [comment]
I took a closer look at this tonight, and there's a complication with trying to use options from the main call as the options when opening the tunnel. Specifically, tunneling is supported not only for connect(), but also other functions like listen() and connect_reverse() which set up listeners. However, those calls take SSHServerConnectionOptions, not SSHClientConnectionOptions. Options such as client_keys and known_hosts aren't present in this case, so the only way to establish the outbound tunnel to set up a listener on is to make separate calls to first create the tunnel with SSHClientConnectionOptions and then to set up a listener on that tunnel with SSHServerConnectionOptions.

While it might be possible to try and share options in the connect() and listen_reverse() cases, there's a good chance even there that some of the options might need to be different when setting up the tunnel vs. setting up the connection being opened within that tunnel. So, I'm thinking that using the default options actually is the safer thing to do in all cases. Some of this can be set in the SSH config file with appropriate matching rules to know which options to apply to the different destinations. However, if you need to provide explicit client keys to use to establish the tunnel or a passphrase to support loading of such client keys, I think it's probably best if you provide those options explicitly, as in the example above. This will also work well in the listen() and connect_reverse() cases, as you'd have the ability to create both SSHClientConnectionOptions and  SSHServerConnectionOptions objects if needed, each with appropriate arguments (or just pass those arguments explicitly on the connect() of the tunnel and then on the listen_ssh()/connect_reverse_ssh() calls).

Note that you can still specify some information via the config file. However, if you need anything more than the default options or things that can come from the config file when opening the tunnel, it's probably best not to specify ProxyJump in the config, and make that call yourself with whatever additional arguments are needed.

**Comment by ddutt** [comment]
Thanks for the detailed feedback. Because the jump host user name and port could be different from the final device, I ended up with the following code:
```python
                if self.jump_host:

                    jump_options = asyncssh.SSHClientConnectionOptions(
                        client_keys=self.pvtkey if self.pvtkey else None,
                        agent_path=self.ssh_agent,
                        username=self.jump_user)

                    self.logger.info(
                        'Using jump host: {}, with username: {}, and port: {}'
                        .format(self.jump_host, self.jump_user, self.jump_port)
                    )
                    self._tunnel = await asyncssh.connect(
                        self.jump_host, port=self.jump_port,
                        options=jump_options, login_timeout=self.cmd_timeout)
                    self.logger.info(
                        f'Connection to jump host {self.jump_host} succeeded')

                    self._conn = await asyncio.wait_for(
                        self._tunnel.connect_ssh(
                            self.address,
                            port=self.port,
                            options=options
                        ),
                        timeout=self.cmd_timeout,
                    )
```

Does that look good? I have to ask somebody else to try it since I don't have the specific setup of the jump host

**Comment by ronf** [comment]
This looks like it should work, except that you don't define "options" used in the self._conn assignment. I think you'll want to use the same options object for both self._tunnel and self._conn, for the subset of parameters that are shared. Also, I'm not sure about your conditional at the top checking for self._jump_host. If your goal is to skip opening the tunnel but still open the main connection in that case, you'd need an "else" clause that covers that. Also, should username be shared by both calls?

You can also simplify it a bit by using login_timeout for the self._conn assignment, similar to what you did for self._tunnel. Since you are setting the same timeout for both connection calls, you can actually just add login_timeout as an argument in the options and share it for both. For instance:

```python
    options = asyncssh.SSHClientConnectionOptions(
        client_keys=self.pvtkey if self.pvtkey else None,
        agent_path=self.ssh_agent,
        login_timeout=self.cmd_timeout)

    self.logger.info(
        'Using jump host: {}, with username: {}, and port: {}'
            .format(self.jump_host, self.jump_user, self.jump_port)
    )
    self._tunnel = await asyncssh.connect(
        self.jump_host, port=self.jump_port,
        username=self.jump_user, options=options)
   self.logger.info(
       f'Connection to jump host {self.jump_host} succeeded')

    self._conn = await self._tunnel.connect_ssh(
        self.address, port=self.port,
        username=self.user, options=options)
```

**Comment by ddutt** [comment]
Thanks again Ron. In the specific case I'm dealing with, the jump host user name may be different from the one used to connect to the final device. Your code looks cleaner, but I have a few more cases to handle. I can modify what you have and go from there. 

BTW, does asyncssh and/or you have a twitter handle? I want to tweet out the fantastic support from you. 

Thanks again, Dinesh

**Comment by ddutt** [comment]
One more q. What's the diff between using self._tunnel.connect_ssh VS using connect(tunnel=self._tunnel) ?

**Comment by ddutt** [comment]
Will do Ron, thanks. Making tit a single call is exactly why I asked about the use of tunnel. It cuts down the code.

I'm not active on social media myself, I just want to do the work. But I do want to support open source as much as I can, and the least I can do is appreciate help.

Do you mind if I close the issue later today after I get confirmation from my users that the jump host logic is working?

**Comment by ronf** [comment]
> Do you mind if I close the issue later today after I get confirmation from my users that the jump host logic is working?

Sure, no problem!

**Comment by ddutt** [comment]
Done! It all worked. I'm still using the _tunnel.connect_ssh() version, which I'll change. But it looks like what you suggested above works well! Thanks again. Best wishes, Dinesh
