### ISSUE TITLE
TypeError: 'AsyncContextManager' object is not iterable

### ISSUE THREAD

**Issue by dinesh3367** [ronf/asyncssh#320]
I am getting the following error when i try to execute one of your solution to run multiple commands in a single SSH connection

```
cat@ubuntu:~$ python3 async_multiple_cmd.py
async_multiple_cmd.py:5: RuntimeWarning: coroutine 'connect' was never awaited
  with (yield from asyncssh.connect('165.26.79.3', username='dev', password='ahs08')) as conn:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "async_multiple_cmd.py", line 23, in <module>
    asyncio.get_event_loop().run_until_complete(run_multiple())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "async_multiple_cmd.py", line 5, in run_multiple
    with (yield from asyncssh.connect('165.26.79.3', username='dev', password='ahs08')) as conn:
TypeError: 'AsyncContextManager' object is not iterable
cat@ubuntu:~$

```

the code snippet is attached below & i am using python3.7 with asyncssh to execute the example code

```
import asyncio, asyncssh, sys

@asyncio.coroutine
def run_multiple():
    with (yield from asyncssh.connect('165.26.79.3', username='dev', password='ahs08')) as conn:
        commands = ['cd /tmp', 'touch foo', 'ls -l foo']

        process = yield from conn.create_process(stderr=asyncssh.STDOUT)

        for command in commands:
            print('--- Running "%s" ---' % command)
            process.stdin.write(command + '; echo "\\n***END***"\n')

            while True:
                line = yield from process.stdout.readline()

                if line == '***END***\n':
                    break
                else:
                    print(line, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_multiple())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))

```

any thoughts on this issue would help me to move further. 

I am trying to select a folder & execute a command in a remote host & read the return status of the command to understand the success/failure of the command.

Hope this information helps, Looking for your support

**Comment by ronf** [comment]
My apologies for not responding sooner. For some reason, I never received an e-mail notification when this issue was filed, and only noticed it today when doing some housekeeping.

I think the problem here is that you are still using the older "yield from" and "@asyncio.coroutine" syntax. That is still supported in the AsyncSSH 1.x releases, but AsyncSSH 2.x now requires that you use the new "await" syntax (and the corresponding "async def"). While some code will still work using the old syntax, things like iterators require the new syntax in AsyncSSH 2.x.

You can see an example of the new syntax at https://asyncssh.readthedocs.io/en/latest/#running-multiple-clients.
