### ISSUE TITLE
why process.redirect make channel closed?

### ISSUE THREAD

**Issue by chenzhenyang** [ronf/asyncssh#328]
```
async def handle_client(process):
    process.stdout.write('chenzhenyang@LAPTOP-1KF5BTDO:~$ ')
    if process.command:
        print('Line was = %s\n' % process.command)
        local_proc = await asyncio.create_subprocess_shell(
            process.command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
        await process.redirect(stdin=local_proc.stdin, stdout=local_proc.stdout,
                               stderr=local_proc.stderr)
        await process.stdout.drain()
        process.exit(0)
        print("命令执行结束")
    else:
        try:
            async for line in process.stdin:
                line = line.rstrip('\n')
                if line:
                    try:
                        local_proc = await asyncio.create_subprocess_shell(
                            line, stdin=PIPE, stdout=PIPE, stderr=PIPE)
                        await process.redirect(stdin=local_proc.stdin, stdout=local_proc.stdout,
                                               stderr=local_proc.stderr)
                        await process.stdout.drain()
                    except ValueError:
                        process.stdout.write('chenzhenyang@LAPTOP-1KF5BTDO:~$ ')
        except asyncssh.BreakReceived as e:
            print(e)
            pass
        # process.stdout.write('Total = %s\n' % total)
        # process.exit(0)
        process.stdout.write('chenzhenyang@LAPTOP-1KF5BTDO:~$ ')
```

why process.redirect make channel closed?

**Comment by ronf** [comment]
One problem here is that you are trying to both read from process.stdin yourself and do a redirect of process.stdin to the subprocess shell you are creating. Once you do the redirect, it's going to try and feed all the remaining input to that subprocess, whether or not the subprocess tries to read any of it. So, by the time the process.stdout.drain() returns, all of the input on stdin has likely be forwarded onto the first subprocess you started, and there's no input left to read into "line" to start a second subprocess.

If you want to run multiple commands and somehow allow those commands to each read input, you're going to need to find some way to determine how much of the input should be forwarded to each subprocess, and that means probably reading it yourself so you can look for some kind of delimiter or something like a byte or line count before each set of input you feed in.

**Comment by chenzhenyang** [comment]
how to resolve ? I want to  develop a ssh server that can execute any shell command ,just like openssh server that can execute interactive command.

```
try:
            async for line in process.stdin:
                line = line.rstrip('\n')
                if line:
                    try:
                        local_proc = await asyncio.create_subprocess_shell(
                            line, stdin=PIPE, stdout=PIPE, stderr=PIPE)
                        await process.redirect(stdin=local_proc.stdin, stdout=local_proc.stdout,
                                               stderr=local_proc.stderr)
                        await process.stdout.drain()
                    except ValueError:
                        process.stdout.write('chenzhenyang@LAPTOP-1KF5BTDO:~$ ')
        except asyncssh.BreakReceived as e:
            print(e)
            pass
        # process.stdout.write('Total = %s\n' % total)
        # process.exit(0)
        process.stdout.write('chenzhenyang@LAPTOP-1KF5BTDO:~$ ')
```
code above can be connected by openssh client and execute interactive command but only execute once, the ssh server will close channel (close connection with openssh client)。

**Comment by ronf** [comment]
The problem here is distinguish between what in the input is intended to be shell commands and what is intended to be input to those commands. With the regular OpenSSH client, it doesn't try to figure that out. As far as it is concerned, it is launching a single process and feeding ALL the input to that. When you don't provide a command, the process it launches is an interactive shell, but it's the shell that takes responsibility for figuring out what input goes to the child processes it starts and what goes to the shell itself. The SSH client has no knowledge about this, though.

If you just wanted to launch a shell on the remote system and feed all the input to that, it should work fine. However, if you want to break it into a series of commands and launch each command as a separate SSH session, there's really no good way to do that. There are some other potential concerns as well -- see #171 for a bit of discussion on this.

If you limit yourself to only handling the case where the SSH client provides you with a specific command to run (like the top half of your example), you should be in much better shape. There, each command started by the client is on its own channel, and so feeding all of the input from stdin on that channel to the remote command shouldn't be a problem in that case. That command could even be a UNIX shell, but you won't be able to see the individual commands that the user is entering into the shell in that case.
