### ISSUE TITLE
X forwarding is too strict

### ISSUE THREAD

**Issue by oremanj** [ronf/asyncssh#338]
Suppose you have an OpenSSH configuration file that enables X forwarding, but there's no X display available on the client side.
```
oremanj@somehost:~$ cat > example-config <<EOF
> Host *
>   ForwardX11Trusted yes
> EOF
```
OpenSSH will interpret this as a request to perform X forwarding if possible, and will silently avoid doing so if not. This is a very reasonable configuration someone might want, if they sometimes ssh from an X session and other times from the console.
```
oremanj@somehost:~$ echo $DISPLAY

oremanj@somehost:~$ ssh -F example-config otherhost
... snip motd ...

Last login: [etc]
oremanj@otherhost:~$ logout
```
But asyncssh will complain if there's no local display. I think this is problematic -- if you're going to use OpenSSH configuration, it's important to use it with the same semantics that OpenSSH does, else users will get confusing breakages.
```
oremanj@somehost:~$ python3.8 -m asyncio
>>> import asyncio
>>> import asyncssh
>>> conn = await asyncssh.connect("otherhost", config="example-config")
>>> session = await conn.open_session()
Traceback (most recent call last):
  File ".../python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File ".../python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File ".../python3.8/site-packages/asyncssh/connection.py", line 3274, in open_session
    chan, session = await self.create_session(SSHClientStreamSession,
  File ".../python3.8/site-packages/asyncssh/connection.py", line 3250, in create_session
    session = await chan.create(session_factory, command, subsystem,
  File ".../python3.8/site-packages/asyncssh/channel.py", line 1075, in create
    raise ChannelOpenError(OPEN_REQUEST_X11_FORWARDING_FAILED,
asyncssh.misc.ChannelOpenError: X11 display not set
>>> asyncssh.__version__
'2.4.2'
```

**Comment by ronf** [comment]
Agreed - this came up in the last few days in #336. See the discussion there, and in particular commit 41c477b in the "develop" branch which adds a new "ignore_failure" option to the x11_forwarding config option and changes the meaning of "ForwardX11Trusted" to map to this new "ignore-failure" setting rather than to True, so that it will continue opening the session even if X11 forwarding can't be set up.

This change will be going into the next release, but you're welcome to pick it up sooner from the "develop" branch or by manually merging that commit to your local copy. It should fix your problem.

Note that I actually revised this code as part of commit f1cd67b, which implements the other change requested in #336 to make it possible to set session-level options like this at the connection level. The current version of the "develop" branch has both of these changes in it.

**Comment by oremanj** [comment]
Whoops, shame on me for only searching through open issues!

The solution you've devised seems perfect. Looking forward to seeing it in a release -- for now, I've worked around the issue by passing `config=None` at connection time.
