### ISSUE TITLE
[Question] Running multiple commands on same session to use env and shell variables 

### ISSUE THREAD

**Issue by biditsh** [ronf/asyncssh#344]
Hi! 

I'm trying to run miltiple commands under the same AsyncSSH session so that can assign and reuse environment and shell variables across commands. If I understand it correctly, using `connection.run()` reuses the connection, but creates a new session per command, so we can't do something like this: 

```
async with asyncssh.connect(hostname) as conn:
    run1 = await conn.run("foo=/run/my/utility.par")
    print("exitcode: ", run1.returncode)

    run2 = await conn.run("/run/another/utility.par $foo")
    print(run2.stdout, run2.returncode)
```

I was able to achieve this by using stdio stream handlers through something like this:
```
async with asyncssh.connect(hostname) as conn:
    separator = "some_random_unique_string"
    _, process = await conn.create_session(SSHClientProcess)

    process.stdin.write("foo=/run/my/utility.par \n")
    process.stdin.write(f"echo $?; echo {separator} \n")
    out = await process.stdout.readuntil(separator)
    out = out.split('\n')
    print("Exitcode: ", out[-2]) 

    process.stdin.write("/run/another/utility.par $foo \n")
    process.stdin.write(f"echo $?; echo {separator};  \n")
    out = await process.stdout.readuntil(separator)
    out = out.split('\n')
    print("stdout: ", ("\n").join(out[:-2]))
    print("exitcode: ", out[-2]) 

    process.channel.get_connection().close()
```

However, I am concerned that I might be reinventing the wheel to do something that is already possible in a more robust way, that hopefully doesn't include 'echo'-ing arbitrary separator strings into the stream. 

My implementation also exposes it to some other issues, so I've usually tried to avoid dealing with raw stdin/out/err streams. 
- danger of weird behaviours because of I/O buffers filling up or being empty for some reason. 
- when an invalid command (ex. `stdin.write(;; \n"`), it raises `asyncio.streams.IncompleteReadError: 0 bytes read on a total of None expected bytes`, and subsequent calls will throw `Channel not open for sending`

Is there a better way to achieve what I am trying to do?

**Comment by ronf** [comment]
Sadly, what you're doing is pretty much as good as it gets. You have a choice between running independent commands each of which provide clear boundaries of what input and output streams are associated with each command and when those streams close vs. running an interactive shell which can accept multiple commands which do things like change the environment from one command to the next, but which provides no clear indicator of where command output begins and ends for those commands, and less control over what input goes to what command and what goes to the shell to be run as a new command.

Unfortunately, if you get "out of sync" about when a particular command ends and the shell exits for any reason, you can run into the IncompleteReadError you saw. You can also run into trouble if one of the commands actually reads from stdin, as it will "swallow" your next command that tries to output the separator unless you get the amount of input just right.

Your best bet is to probably build a shell script on the remote system that runs a collection of commands and then launch that as a single session via AsyncSSH. However, that may mean building some of the logic for what commands to run into that script, rather than doing it in the AsyncSSH client code, if you are dynamically changing the commands you send based on the output you're getting back.

Using conn.create_process(), you can avoid some of the problems with run() needing to buffer a large amount of output. Also, you can just call that directly rather than calling conn.create_session() with SSHClientProcess as a session handler. That provides some other additional capabilities as well if you do that, like the ability to set redirection for stdin/stdout/stderr if you want it.

**Comment by biditsh** [comment]
Thanks for the quick response @ronf! This is very helpful.
