### ISSUE TITLE
SSH connection failed: Host key is not trusted

### ISSUE THREAD

**Issue by Iwith** [ronf/asyncssh#361]
The first time using asyncssh to log in to a host that has never been logged in, an error will be displayed

When I manually SSH login, then asyncsh login is normal.

What options are used when logging in？
---------------------
The authenticity of host '172.16.1.200 (172.16.1.200)' can't be established.
RSA key fingerprint is SHA256:yny0LA2pgwcixnxwJRQprSGD8guXc4vDH73YS7pWMso.
Are you sure you want to continue connecting (yes/no)?

**Comment by Iwith** [comment]
I found that if I set known_hosts=None will solve the problem.

**Comment by ronf** [comment]
Yes - this is expected behavior. Setting `known_hosts` to `None` will work as you discovered, but it's not the recommended solution as it leaves open the possibility for a man-in-the-middle to get between your client and the SSH server. It's better to connect there once with OpenSSH first and save the host key, or populate the host key yourself either in `.ssh/known_hosts` or in another file you specify via the `known_hosts` argument.
