### ISSUE TITLE
asyncssh v2.5.0 exibits extra fd resource needed on host_based_auth mode vs publickey mode

### ISSUE THREAD

**Issue by pete312** [ronf/asyncssh#362]
While switching from publickey auth to the host based auth (added last year), I got errors 
 `OSError: [Errno 24] Too many open files`

switching back and forth between host based and public key auth shows there are more file descriptors needed on host based. 

To recreate this I have made this test script and added (on my side) about 400 machines to it.

```
import asyncio, asyncssh
import sys, os
import logging
testhosts = """
host1
host2
.
.
"""

async def run_client(host, command):
    result = None
    
    argshostkey =dict(host=host, client_host_keysign=True, host_based_auth=True, known_hosts=None, client_host_keys='/etc/ssh/ssh_host_rsa_key.pub')
    argspubkey = dict(host=host, client_keys=['/home/user1/.ssh/id_rsa'], known_hosts=None)

    async with asyncssh.connect(**argspubkey) as conn:
        result = await conn.run(command)

        print(f"v=v=v {host} v=v=v")
        print(f"stdout : \n{result.stdout}")
        print(f"stderr : \n{result.stderr}" if result.stderr else "")
        print(f"exit   : {result.exit_status}")  

    return  result

async def multi_client(hosts, command):
    tasks = (run_client( host, command) for host in hosts)
    return await asyncio.gather(*tasks)
    
    
if __name__ == "__main__":
    hosts = [f"{s}.domain" for s in testhosts.splitlines() if s][:400]
    run = asyncio.get_event_loop().run_until_complete(multi_client(hosts, 'echo ok'))

```

using the setting displayed and a ulimit -n of 1024  this completes using publickey. 
If you switch the connect() args to `**argshostkey` it will fail with too many files open.

The point at which it fails is about 270 machines done by changing this line `hosts = [f"{s}.domain" for s in testhosts.splitlines() if s][:270]`

You have to raise ulimit to about 4096 before you can go 400 sessions wide. Doing a rough strace on the script while it runs looks like publickey may be closing more file descriptors than hostbased mode but I have not matched fd's to see which ones its closing.

Is this expected with host based ?

**Comment by ronf** [comment]
I'm traveling at the moment, so I won't have a chance to dig too deep on this for another week or so.

To answer your question, it is expected that more file descriptors will be needed for host-based auth, as the "keysign" application is executed as a subprocess with pipes created for stdin, stdout, and stderr. However, those pipes shouldn't remain open for long. If you stagger your calls to reduce the number SSH connections trying to authenticate simultaneously, the larger number of FDs needed to use "keysign" might not run into the issue you are seeing.

If you trace it, do all of the FDs eventually get properly closed, or are you seeing an actual "leak" where even after closing the SSH connection some FDs are remaining open?

**Comment by pete312** [comment]
I have not looked close enough yet on the strace calls I just noticed an extra set close calls than on the host based side.  Comparing the 2 sets of open fd with lsof shows the exact same count when both sessions are established.  

For me the gains had in host based call is offset by the resource problem.  Because this is a user utility its better to run within the constraints of a default shell.  I need to find a safe limit that is performant.  Batching is not great because 1 slow host will delay a batch. So maybe a connection pool might be a work around.

Thanks for your work on this API. Its very good.

**Comment by ronf** [comment]
Since the extra FDs are only needed during authentication, you may be able to do something with an asyncio Semaphore where you limit the number of simultaneous calls into opening new connections. Once the connection is established, you'd release the semaphore, allowing other coroutines to acquire it. That way, you're not adding any unnecessary delays. Connections will be established as quickly as possible while still limiting the total number "extra" FDs that would be open at any given time.

For instance, if you wanted to target 400 connections and you had a ulimit of 1024 FDs and you knew that host-based auth was going to create an additional 3 FDs per connection during connection establishment, you might put a limit of something like 200 connections being established at once (or maybe 150 to be on the safe side). This would be the limit on your Semaphore when you create it and you'd wrap your connect() call in an "async with" referencing the semaphore. Just make sure only the connect call is being done with the semaphore held and not anything using the connection. If you are using an "async with" on the connect() call today, you'd need to split that up into something like:

```python
    async with sem:
        conn = asyncssh.connect(...)

    async with conn:
        """do stuff on the established connection"""
```

You'd create the semaphore once and provide it to the code doing the connect(). That'd look something like

```
    sem = asyncio.Sempahore(MAX_SIMULTANEOUS_CONNECTS)
```

**Comment by pete312** [comment]
Thank you for this suggestion it did work out.

**Comment by ronf** [comment]
Glad to hear it, Peter - thanks for letting me know!
