### ISSUE TITLE
[Question] How to do faster transfers for a single big file through SFTP

### ISSUE THREAD

**Issue by isidentical** [ronf/asyncssh#374]
Hello! AsyncSSH is an amazing library and I was quite hyped to see that it internally parallelizes the read/write calls and actually was expecting this to be faster than paramiko (it also does pipelining though it is limited to the threads, and for this case I was expecting coroutines to be much efficient since it spawns 128 of them!) though it seems like that is not the case. 

Here is the base script;
```py
import asyncio
import time
from pathlib import Path

import asyncssh


start_time = None

def progress_handler(from_file, to_file, offset, _):
    mb_offset = offset / (1024 ** 2)
    time_spent = time.perf_counter() - start_time
    print(f"{from_file} -> {to_file} {mb_offset/time_spent:06.2f}", end='\r')

async def main():
    async with asyncssh.connect(<options>) as client:
        async with client.start_sftp_client() as channel:
            await channel.put(
                <bigfile>,
                '/tmp/bigfile', 
                progress_handler=progress_handler
            )

asyncio.run(main())
```

This performs about 11.5 mb/s in general (after some time passes to offset the initialization cost).

If I do something a bit risky and set the `block_size` to `SFTP_BLOCK_SIZE * 15` (240~ kb) (I'm aware that 256+ is a bit problematic on some servers) then it sees up to `17 mb/s` (the avg is `16 mb/s` though). I didn't see any improvement when I modified `max_requests` (tried 64, 256, 512), and in fact, it actually dropped to `9 mb/s` in some point when I was testing with `512`. 

I have a similar script for paramiko which performs about 23mb/s and I couldn't figure out why there is such a gap (without any extra parameters, using the defaults for both of them there is about 2X difference) (I am not sure but it seems like it is using 8kb for the block_size, https://github.com/paramiko/paramiko/blob/ce2f45962493a36f84349c488f6162304331aa8b/paramiko/file.py#L36).

I haven't got time to test this with multiple files at the same time, and I believe that might be more effective though single big files are also is a common use case in the tool I'm migrating to asyncssh. Any advice would be really great! (maybe accelerating modules for improving package processing time? config options that I might have missed etc).

**Comment by ronf** [comment]
Unfortunately, I haven't done much benchmarking of AsyncSSH's SFTP against Paramiko, so I'm not sure offhand what the different might be here. I can confirm that you're on the right track in terms of optimizing, though. I see similar gains when playing with increasing the block size. On my system, I get about 20 MBytes/sec with the default arguments on a 256 MB file transfer (total time, including the initial SSH login), and that goes up to around 29 MBytes/sec when the 240 KB block size. I can also confirm that increasing max requests doesn't make much difference.

Changing the encryption algorithm to `aes128-gcm@openssh.com` sped things up a bit more, to around 34 MBytes/sec. Do you know if Paramiko and AsyncSSH were defaulting using the same algorithms? If not, that might explain some of the difference.

After some more experimenting, though, I found that the bottleneck in AsyncSSH in my testing appears to be related to gzip compression, which is enabled by default. If I disable that (with `compression_algs=None`), I see about a 3.5X speedup to around 116 MBytes/sec!

What's even more interesting is that the slowdown with gzip enabled is even worse on compressible data than it is on incompressible data. I see a 7X slowdown with gzip enabled on compressible data. With incompressible data and compression enabled, it's only about 3.5X slower. This is consistent with the time it takes to just gzip compress the data locally without SFTP involved -- doing the gzip on the compressible data I am using took about 2.2X longer than attempting to do gzip on the same amount of completely random incompressible data.

So, the lesson here is that you should disable compression if you are on a fast network. If you have compressible data and the network is slower than the rate that gzip runs at, it might be worth leaving compression enabled so you can send fewer bytes, but otherwise you're better off sending the original data to save the gzip cost.

Getting back to the Paramiko question, I'm not sure if it has compression enabled by default or not. If it does, perhaps the fact that it is using multiple threads means it might be able to take advantage of more than one CPU core, though, whereas AsyncSSH with a single event loop will only ever use a single core's worth of CPU, not matter how much parallelism you configure it for. If you look at the total CPU used by the process in each of the two cases, do you see Paramiko using more than one core's worth of CPU?

**Comment by isidentical** [comment]
Thanks for the quick response and all the insights @ronf! 

> Changing the encryption algorithm to aes128-gcm@openssh.com sped things up a bit more, to around 34 MBytes/sec.

I can also see a similar speedup

>  Do you know if Paramiko and AsyncSSH were defaulting using the same algorithms? If not, that might explain some of the difference.

No, unfortunately, I don't know. 

> After some more experimenting, though, I found that the bottleneck in AsyncSSH in my testing appears to be related to gzip compression, which is enabled by default. If I disable that (with compression_algs=None), I see about a 3.5X speedup to around 116 MBytes/sec!

Wow! I just tested it, and yes can confirm that it bumps the numbers for my case. Now the speed for putting is about 80mb/s (and sometimes sees 90mb/s, especially in the beginning then it slowly goes down to 70s and then jumps so I'd say the avg is 80). 

> Getting back to the Paramiko question, I'm not sure if it has compression enabled by default or not.

It seems like the compression is off by default on paramiko; http://docs.paramiko.org/en/stable/api/transport.html#paramiko.transport.Transport.use_compression

> If it does, perhaps the fact that it is using multiple threads means it might be able to take advantage of more than one CPU core, though, whereas AsyncSSH with a single event loop will only ever use a single core's worth of CPU, not matter how much parallelism you configure it for.

Yes, I see.

>  If you look at the total CPU used by the process in each of the two cases, do you see Paramiko using more than one core's worth of CPU? 

I don't think it does though not sure.

**Comment by isidentical** [comment]
Interestingly the same speedup does not apply in the same factor to downloads. So on uploads, the speed goes to avg of 70s from 15s and on download, it goes to avg of 30s from 10s. In paramiko it is about 25 mb/s so this is still better but I wonder what is different in that case.

**Comment by isidentical** [comment]
Here are some interesting timings after the final adjustments;
|          	| push (12 x 800Mb) 	| pull (12 x 800Mb) 	| push (single 14G file) 	| pull (single 14G file) 	|
|----------	|-------------------	|-------------------	|------------------------	|------------------------	|
| paramiko 	| 7m51.375s         	| 4m39.270s         	| 10m9.651s              	| 6m38.765s              	|
| asyncssh 	| 2m29.854s         	| 3m16.753s         	| 3m42.075s              	| 8m28.901s              	|

When pushing (uploading) files, asyncssh seems like doing ~3-3.3x better than paramiko which is huge. Regarding the pull, it seems a bit weird in the first glance since when pulling multiple files paramiko is actually slower (threading vs async?) but when pulling a single file it gets a bit faster (the progress is also a bit different, it starts writing 10-11mb/s and then moves up to 45-50mb/s's after a minute or so).

It seems like there might be some effect of prefetching? 
https://github.com/paramiko/paramiko/blob/ce2f45962493a36f84349c488f6162304331aa8b/paramiko/sftp_client.py#L780
https://github.com/paramiko/paramiko/blob/ce2f45962493a36f84349c488f6162304331aa8b/paramiko/sftp_file.py#L440-L448

So instead of waiting something to be `read()`, it starts workers in the back to fetch so even though the local disk write is blocking you, you still download the file (just an assumption, not confirmed). I wonder whether we could have a similar thing on the asyncssh as well?

I'll now give it a shot with `uvloop`, since at least in our case we start about 8 (maximum number of download tasks we do in a single time, each try to get it's own channel but if the server can't handle more connections some may share connections with other workers) x ((total_data_size / block_size) * 128) coroutines. Maybe we can even more bump these numbers up (I also wonder how it would look with multiple event loops on different cores for systems that has multi processors to make the asyncssh benefit from it, since as you commented it will only use only one now).

**Comment by ronf** [comment]
I don't see much of a difference between "get" and "put" here. WIth compression disabled and a 256 MByte file, the numbers look something like the following:

```
get:  2.037s   126.0 MBytes/sec
put:  1.855s   138.3 MBytes/sec
```

In this case, I'm measuring just the time for the transfer, after the SSH connection and SFTP client session have been opened. With compression enabled but non-compressible data, both get and put slow down by about 3.5X:

```
get:  6.992s    36.7 MBytes/sec
put:  7.291s    35.2 MBytes/sec
```

Switching to compressible data slows things down by a little more than another 2X:

```
get: 14.648s    17.5 MBytes/sec
put: 16.750s    15.3 MBytes/sec
```

In all cases here, though, I'm not seeing much of a difference between get & put.

Switching to multiple files in parallel (16 files of 16 MB each), the result wasn't pretty close to the original single file run with compression disabled:

```
get:  2.065s   124.0 MBytes/sec
put:  1.978s   129.4 MBytes/sec
```

Running that same test with 16 files of 256 MB produces results even closer to the original single-file case:

```
get: 31.341s   130.6 MBytes/sec
put: 29.910s   136.8 MBytes/sec
```

Regarding the prefetching you saw in Paramiko, you'll see the same sort of thing in AsyncSSH with its "max_requests" parameter. It starts multiple transfers in parallel (even for a single file), without waiting for the read() or write() to complete. The individual coroutines that do the fetch will need to complete both the read() and write() before allowing _additional_ requests (beyond max_requests) to start up, but throughout the transfer it will always be trying to keep max_requests number of requests running in parallel.

Regarding putting transfers on different channels, there's no need to do that, at least not until you hit the limit on the number of open files allowed on a single channel. In all my testing here, I had all the file transfers running in parallel on a single channel. That may allow you to scale up the number of transfers you allow.

Going to "uvloop" has helped speed things up in past testing I've done, but I didn't see much of an improvement when I attempted that here.

Going to multiple event loops on different cores should increase the speed as well, as long as the server has enough capacity to keep up with the larger number of parallel requests. I haven't measured how much gain that would provide, though.

**Comment by isidentical** [comment]
Interestingly I was able to confirm this.

After trying to perfect the block sizes and multiple changes on my code, I've applied `uvloop` and noticed a substainall speed up. I was a bit skeptical after a couple tries since the timing get increased and increased on every isolated run (but consecutive ones). So I've also tried without the uvloop and was able to confirm that asyncssh is in fact not slower than paramiko but the issue was in my network (an AWS machine). 

So here are my results (10 consecutive runs for 14G file);
```
paramiko:             5m18.753s, 5m35.355s, 7m23.846s, 7m22.000s,
                      7m22.923s, 7m23.836s, 7m21.991s, 7m22.860s,
                      7m22.844s, 7m22.826s
   
sshfs without uvloop: 5m22.112s, 5m12.357s, 5m22.846s, 7m22.616s,
                      7m23.603s, 7m21.681s, 7m23.466s, 7m21.739s,
                      7m23.161s, 7m21.928s

sshfs with uvloop:    5m0.909s, 4m56.686s, 5m58.404s, 7m22.183s,
                      7m22.143s, 7m22.108s, 7m22.573s, 7m21.887s,
                      7m22.097s, 7m22.147s
```

**Comment by isidentical** [comment]
I think the issue can be closed safely since I've also confirmed that is faster on paramiko in all cases. Thanks so much for your answers @ronf!

**Comment by ronf** [comment]
Sounds good. Happy to help!

**Comment by JavaScriptDude** [comment]
I found the exact same and was getting sad that I could not use the elegant API's in `asyncssh`. Now the download performance for large files is within a reasonable performance margin, I can switch to using `asyncssh`.

For those who are new to `asyncssh`, the settings to override are `encryption_algs` and `compression_algs` in [SSHClientConnectionOptions](https://asyncssh.readthedocs.io/en/latest/api.html#sshclientconnectionoptions) constructor.

Sample to use faster encryption algorithm and disable compression:

```python3
    ssh_opts = asyncssh.SSHClientConnectionOptions(
         #...
        ,encryption_algs =[
            "aes128-gcm@openssh.com",
            "aes256-ctr",
            "aes192-ctr",
            "aes128-ctr",
        ]
        ,compression_algs=None
    )

    async with asyncssh.connect(host='<host>', options=ssh_opts) as conn:
        #...
```

**Comment by ronf** [comment]
Thanks, @JavaScriptDude! In my experience, the main benefit you'll see is in disabling compression since the cost of the compression is actually greater than the cost of the extra encryption and network costs when transferring files over high bandwidth, low-latency connections.

Since many CPUs these days have hardware acceleration for AES encryption, I can believe you might get some benefit there over the default of chacha20-policy1305 on some systems, but I haven't specifically tested that.

**Comment by ronf** [comment]
That's an interesting result. Are you disabling compression here? If so, how?

Keep in mind there are two SSH connections involved in this case, and if you set `compression_algs=None` on the main SSH connect call, that won't disable compression on the tunnel you set up. You'd either have to do your own connect call on the tunnel with this argument and then pass that SSHServerConnection in as the `tunnel` argument, or you'd need to disable compression in the ~/.ssh/config file by adding "Compression no". If you set that outside of any "Host" block, that would apply to all requests (both the main SSH connection and the tunnel).

I believe OpenSSH defaults to no compression now, but AsyncSSH still defaults to it being enabled. So, switching from `tunnel` to `proxy_connection` could end up disabling compression on the tunnel, resulting in a speed improvement, if you don't explicitly disable compression when asking AsyncSSH to set up the tunnel.

In a quick test here, I confirmed that not disabling compression on the tunnel did significantly hurt the performance. There was a bigger penalty than I expected when tunneling, though,  even with compression properly disabled on both. Switching from `tunnel` to `proxy_command` didn't make a difference in my testing in this case, though.

Here are some numbers for a local SFTP put of a 100 MB file:

No tunnel, compression disabled: 56 MB/sec
No tunnel, compression enabled: 27 MB/sec
Compression disabled on main connection, but enabled on tunnel: 17 MB/sec
Tunnel with compression disabled on both connections: 25 MB/sec
Proxy command with compression disabled on both connections: 25 MB/sec

As you can see, running with either a tunnel or proxy_command was a lot slower than no tunnel, even with compression disabled everywhere. However, the tunnel and proxy_command cases were about the same in that case.

**Comment by JPrazak** [comment]
Here is examples of my script, i hope compression is disabled. Sorry about my scp interrest, I need fastest method. I also add parameter to ~/.ssh/config to disable compression but I can't see any effect.

options:
```python
ssh_opts = asyncssh.SSHClientConnectionOptions(agent_forwarding=True,
                                                compression_algs=None, 
                                                encryption_algs = [ "aes128-gcm@openssh.com", "aes128-ctr"])`
```
1. test `tunnel` parameter with jumphost:
  scp from tunnel finished, speed: 58.0315 MB/s
  scp to tunnel finished, speed: 23.7211 MB/s

```python
async def scp_to_tunnel_1(host: str, user: str, agent_path: str):  # sshd on jumphost 100% core
    async with asyncssh.connect(host, username=user, options=ssh_opts, tunnel="tester@jumphost" , connect_timeout=10) as conn:
        await asyncssh.scp((conn, '/tmp/import.tar'), '/tmp/import.tar')
        # second function same but swap this
        await asyncssh.scp('/tmp/import.tar, (conn, '/tmp/import.tar')
```
2.  test `tunnel` param with connection:
 conn2tunnel_scp_from finished, speed: `94.3097 MB/s` why?
 conn2tunnel_scp_to finished, speed: 54.0960 MB/s why?
```python
async def conn2tunnel_scp_to(jumphost: str, remotehost: str, user: str, agent_path: str):  # sshd on jumphost 40% on core
    async with asyncssh.connect(jumphost, username=user, options=ssh_opts, connect_timeout=10) as conn:
        async with asyncssh.connect(remotehost, tunnel=conn, username=user, agent_path=agent_path, options=ssh_opts) as conn2:
            await asyncssh.scp('/tmp/import.tar', (conn2, '/tmp/import.tar'))
            # second function same only swap this
            await asyncssh.scp((conn2, '/tmp/import.tar'), '/tmp/import.tar' )
```

3. test without `tunnel` parameter, proxy jump in ~/.ssh/config wih ProxyCommand
scp_from ProxyCommand finished, speed: 91.2747 MB/s
scp_to ProxyCommand finished, speed: 94.8013 MB/s
```python
async def scp_from_proxycmd(host: str, user: str, agent_path: str):
    async with asyncssh.connect(host, username=user, options=ssh_opts, connect_timeout=10) as conn:
        await asyncssh.scp((conn, '/tmp/import.tar'), '/tmp/')
```
I forget test with "standard" ProxyJump paramter, but I  hope it's enough. I did some anonymization in log.
[log.txt](https://github.com/ronf/asyncssh/files/10510972/log.txt)
Best regards JP

**Comment by ronf** [comment]
In case 1 above, I think compression will still be enabled on the tunnel. Since you are passing in a string, AsyncSSH will use default values for all the options (except those set in the default config file, if there is one).

In case 2, though, you are explicitly creating the tunnel and passing in ssh_opts, which disables compression, in addition to passing in ssh_opts to disable compression on conn2. So, you see the higher throughput.

Offhand, I can't explain why the "scp_to" is so much slower than the "scp_from" in case 2, where you aren't seeing that performance difference when running without the tunnel in case 3. I did some testing here, and I'm seeing similar numbers for the two directions, with & without a tunnel, but the performance drop due to the tunnel is significant:

```
Direct scp from remote: 93.73 MB/sec
Direct scp to remote: 94.46 MB/sec
Tunneled scp from remote: 37.36 MB/sec
Tunneled scp to remote: 37.42 MB/sec
```

These numbers were on macOS, but I got similar results on a Linux VM on that host:

```
Direct scp from remote: 100.08 MB/sec
Direct scp to remote: 103.04 MB/sec
Tunneled scp from remote: 40.55 MB/sec
Tunneled scp to remote: 40.56 MB/sec
```

All tests were done with localhost as both the tunnel endpoint and the final destination, and all with compression disabled.

Note: This is measuring just the cost of the copy, not including the time to set up the SSH connections. I saw more variability when I was initially measuring total time, including the setup time.

**Comment by ronf** [comment]
Just noticed an error in the tests I ran. It turns out that I am seeing significant speed differences in scp to vs. from:

```
Direct scp from remote: 260.79 MB/sec
Direct scp to remote: 92.24 MB/sec
Tunneled scp from remote: 130.58 MB/sec
Tunneled scp to remote: 36.58 MB/sec
```

I also found that the localhost numbers were significantly different than what I saw when going between my host and a VM running on it, but I'm suspecting that this might be because I'm using bridged networking on a WiFi network, so I think the packets may actually be limited by the WiFi network speed. There, I saw numbers like:

```
Direct scp from remote: 10.15 MB/sec
Direct scp to remote: 22.38 MB/sec
Tunneled scp from remote: 9.47 MB/sec
Tunneled scp to remote: 20.62 MB/sec
```

The performance penalty for the tunnel was much less in this case, and the copy _to_ the remote was actually faster, unlike the numbers above. When running this same test from the other system, things were reversed:

```
Direct scp from remote: 26.99 MB/sec
Direct scp to remote: 10.61 MB/sec
Tunneled scp from remote: 20.50 MB/sec
Tunneled scp to remote: 12.36 MB/sec
```

I'm going to try and set up something using internal networking between my host & VM to see how it compares.

**Comment by ronf** [comment]
Ok - I did a new set of tests here where the "direct" case is host1 -> host2 over an internal virtual network (using Parallels) and where the "tunnel" case is host1 -> host2 (tunnel) -> host1, again over this same virtual network. In all cases, AsyncSSH is used as the client, and OpenSSH is used as the tunnel endpoint and the server. I tried this with macOS as host1 and Linux as host2 and vice-versa. The performance was very similar betweenthose two variants. Here are some example numbers:

```
host1: macOS, host: Linux:

Direct scp from remote: 231.67 MB/sec
Direct scp to remote: 76.55 MB/sec
Tunneled scp from remote: 112.22 MB/sec
Tunneled scp to remote: 29.51 MB/sec

host1: Linux, host2: macOS:

Direct scp from remote: 236.09 MB/sec
Direct scp to remote: 104.00 MB/sec
Tunneled scp from remote: 114.83 MB/sec
Tunneled scp to remote: 31.67 MB/sec
```

I know that AsyncSSH is slower than OpenSSH on transfers like this (mainly due to Python vs. C) -- bulk transfers like this aren't AsyncSSH's primary use case. That said, it's been a while since I've explicitly measured this or looked at whether there's any easy ways to improve it. I think a good next step here would be to try different combinations of using AsyncSSH as the server and tunnel endpoint instead of OpenSSH, and maybe also trying OpenSSH as the client (with and without AsyncSSH as the tunnel endpoint or server).

**Comment by ronf** [comment]
Here are some new measurements I ran, testing out using OpenSSH vs. AsyncSSH for the tunnel and remote systems. As above, the client is always AsyncSSH. Direct connections go between a host and a VM on it via a local virtual network. Tunnel connections go from a host to the VM as the tunnel endpoint and then back to the host as the remote system.

|  Tunnel | Remote | Download (MBytes/sec) | Upload (MBytes/sec) |
| :--- | :--- | ---: | ---: |
| None | OpenSSH | 237.70 | 77.24 |
| None | AsyncSSH | 97.83 | 80.07 |
| OpenSSH | OpenSSH | 115.25 | 29.77 |
| OpenSSH | AsyncSSH | 53.51 | 29.58 |
| AsyncSSH | OpenSSH | 94.42 | 28.15 |
| AsyncSSH | AsyncSSH | 48.93 | 27.51 |

So, the best case by far is downloading directly from an OpenSSH server (no real surprise). However, even when using OpenSSH as both the server and tunnel endpoint, the performance drops roughly in half compared to direct. Downloading from an AsyncSSH server is noticeably slower (less than half the performance), and it drops again by half when tunneling through either OpenSSH or AsyncSSH, with only a small amount of extra overhead with the AsyncSSH tunnel.

For uploads, the type of tunnel and server host didn't matter as much. Direct still shows the best speed and there's an even bigger drop when tunneling (almost 3x), but this performance is roughly the same when running OpenSSH vs. AsyncSSH as the server or tunnel host.

I still haven't had a chance to dig into the reason for the differences, but I thought these numbers might be useful to share.

**Comment by ronf** [comment]
The following shows the results of increasing the block size used by "scp" from 16 KB to 64 KB. There was definitely some improvement, particularly in the upload cases:

|  Tunnel | Remote | Download (16 KB) | Upload (16 KB)  | Download (64 KB) | Upload (64 KB) |
| :--- | :--- | ---: | ---: | ---: | ---: |
| None | OpenSSH | 237.70 | 77.24 | 254.59 | 132.40 |
| None | AsyncSSH | 97.83 | 80.07 | 98.51 | 133.73 |
| OpenSSH | OpenSSH | 115.25 | 29.77 | 123.32 | 45.56 |
| OpenSSH | AsyncSSH | 53.51 | 29.58 | 54.92 | 44.83 |
| AsyncSSH | OpenSSH | 94.42 | 28.15 | 99.53 | 42.19 |
| AsyncSSH | AsyncSSH | 48.93 | 27.51 | 49.54 | 42.33 |

Here's an example of setting the block size for "scp":

```python
    asyncssh.scp((conn, '/tmp/data'), '/tmp/data1', block_size=65536)
```

**Comment by JPrazak** [comment]
Thank you for perfect analyse. For my use case download speed is perfect (block_size param +~5MB/s). Upload on my test I can fix with proxy command (as connect parameter `proxy_command`).
I would like to test host by host copy.  Can you please recommend what is right way to scp between remote hosts?
`asyncssh.scp((conn, '/tmp/data'),  ( conn2, '/tmp/data'))` or `asyncssh.scp((conn2, '/tmp/data'),  ( conn, '/tmp/data'))`  is not right, I think it transfer data to localhost and after to jump or remote host.

**Comment by ronf** [comment]
The asyncssh.scp() function supports remote-to-remote copies, but it always copies the bytes through the local host, allowing it to provide the same kind of progress messages as what you get with local-to-remote and remote-to-local copies. Basically, it works like when you pass "-3" to the OpenSSH scp.

If you want to do a true remote-to-remote copy without copying the bytes through the local host, you can just use the normal conn.run() call to launch scp on one of the remote systems, pointing at the other. That's actually what OpenSSH scp does under the covers when you don't specify "-3" (in older versions, before OpenSSH switched to using SFTP by default).

It would look something like:

```python
    async with asyncssh.connect('host1') as conn:
        await conn.run('scp /tmp/data host2:/tmp/data1')
```

You could also do:

```python
    async with asyncssh.connect('host2') as conn:
        await conn.run('scp host1:/tmp/data /tmp/data1')
```

For this to work, host1 would need to be able to connect to host2 via SSH or vice-versa, so you may need additional options on the "scp" command you send if the necessary info isn't already in host1's SSH config file.

Jump hosts could be used here as well, if you specify them either in your connect() call or in the "scp" command you run (or the remote system's config file).

**Comment by JPrazak** [comment]
Thank you very much for your help and patience, now it's clear.
