### ISSUE TITLE
SFTP: put data from an object

### ISSUE THREAD

**Issue by tifling85** [ronf/asyncssh#378]
Hey!
Thanks for the project, it helps a lot!

I have a task: I have to send data to the sftp server, which I receive from another source and save it to a Python object. Is it possible to use sftp.put() (or another method) by specifying this object rather than the filename?

I want to avoid writing this data to a file.

Thank you!

**Comment by ronf** [comment]
Yes - instead of using sftp.put(), you can use sftp.open() instead to get back an SFTP file handle. You can then loop over the data that's in your Python object and call write() on the SFTP file handle to serialize the data out to a remote file, similar to how you would do using open() in Python to write data to a local file. Just keep in mind that open() and write() are both async methods so you'll need to use "await" when you call them, or in the case of open() you'll want to use "async with" instead of "with". This will automatically close the file handle when you leave that scope.

You didn't say what kind of Python object you have or how you want to serialize it, but here's an example that shows outputting a a single block of data:

```python
import asyncio
import asyncssh
import sys

async def run_client():
    data = b'abcd\n'

    async with asyncssh.connect('remote_host') as conn:
        async with conn.start_sftp_client() as sftp:
            async with sftp.open('/tmp/remote_file', 'wb') as f:
                await f.write(data)

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (asyncssh.Error) as exc:
    sys.exit('SFTP operation failed: ' + str(exc))
```

In the actual code, I expect you'd replace the single call to `f.write(data)` with a series of calls that pull data from your object and turn it into bytes that you want to write to the remote file.

You can do more complicated things as well, like opening up an existing file and overwriting some arbitrary portion of it, or doing a mixture of reads and writes at different offsets within the file. Basically, anything you can do with a regular file open() can be done with `sftp.open()`.

You can also do other operations like removing or renaming remote files using the `sftp` client object. See https://asyncssh.readthedocs.io/en/latest/api.html#sftpclient for more details - just scroll down past the "File transfer methods" section to see the other operations.

Once you have an open SFTP file handle, see https://asyncssh.readthedocs.io/en/latest/api.html#sftpclientfile for the operations you can perform on the remote file object.

**Comment by tifling85** [comment]
I tested the sftp.open() method - this is what I need.
Thanks and good luck!
