### ISSUE TITLE
How to properly close an SSHAcceptor?

### ISSUE THREAD

**Issue by paulo-raca** [ronf/asyncssh#382]
Hello, and thanks for this awesome library :)

I have a tool based on asyncssh, it listens for a single (reverse) connection and then terminates.
My much simplified code looks like this:

```
server = await asyncssh.listen_reverse(...)
async with server:
    ...
    await wait_until_complete()
```

While that did work on previous versions, `listen_reverse` now returns an `SSHAcceptor` instead of a `Server`
From what I can tell, it doesn't provide an easy way to "close" it.

For now, I'm using `async with acceptor._server:`, but that doesn't seem ideal. 

What is the recommended way of closing it?

Thanks!

**Comment by ronf** [comment]
The SSHAcceptor class is just a wrapper around the server object inside it. So, any operation that you would have previously been able to perform on the server object (async with, close, wait_closed, etc.) can be performed directly on the returned SSHAcceptor object. In other words, the original block of code that worked on older versions should work on newer versions as well. Did you run into a problem with it?

The reason for moving to SSHAcceptor is so that an update() method could be added to change the set of options applied on new incoming connections without the need to close and re-open the listening sockets, potentially leading to new connections being missed for a short time.

**Comment by paulo-raca** [comment]
> So, any operation that you would have previously been able to perform on the server object (async with, close, wait_closed, etc.) can be performed directly on the returned SSHAcceptor object. In other words, the original block of code that worked on older versions should work on newer versions as well. Did you run into a problem with it?

Yes, the code now fails with 
```
  File "/media/Paulo/Workspace/adb-proxy/adbproxy/adb_proxy.py", line 463, in listen_reverse
    async with server:
AttributeError: __aenter__
```

Interestingly, `print(server.__aenter__)` succeeds and prints `<bound method AbstractServer.__aenter__ of <Server ....>`

**Comment by ronf** [comment]
Interesting. I get a slightly different error here (complaining about __aexit__ instead of __aenter__). I'll look into this further.

In the meantime, it should be possible to replace your "async with" with an "await server.wait_closed()" and then call "server.close()" from whatever code was previously waking up the "wait_until_complete()" call. This will cause the wait_closed() to return, and doesn't require the use of a context manager.

**Comment by paulo-raca** [comment]
Sounds good, thank you

**Comment by ronf** [comment]
After some additional experimentation, I can confirm that Python doesn't seem to support using __getattr__ to delegate the definition of __aenter__ and __aexit__ to another object. Since the functionality needed for the async context manager is quite simple in this case, though, I think repeating it explicitly in the SSHAcceptor may be the easiest solution. Here's a patch which does that if you'd like to try it:

```patch
@@ -507,6 +507,13 @@ class SSHAcceptor:
         self._server = server
         self._options = options

+    async def __aenter__(self):
+        return self
+
+    async def __aexit__(self, *exc_info):
+        self.close()
+        await self.wait_closed()
+
     def __getattr__(self, name):
         return getattr(self._server, name)

```

If you get a chance to try this, let me know if it solves the problem for you - it seems to work here. I'll get this into the "develop" branch shortly, for inclusion in the next release. Thanks for reporting this!

**Comment by ronf** [comment]
A fix for this is now checked into the "develop" branch as commit c8653a4, and will be included in the next release. Thanks for reporting this!

**Comment by paulo-raca** [comment]
Thank you for looking into it!
