### ISSUE TITLE
Keep track of `listen_host` and `listen_port` in when port forwarding

### ISSUE THREAD

**Issue by AndrewLaneX** [ronf/asyncssh#385]
Is it possible to get the `listen_host` and `listen_port` in the process factory when port forwarding? 

```python3
import asyncio
import logging

import asyncssh

logging.basicConfig(level=logging.DEBUG)


class Server(asyncssh.SSHServer):
    def server_requested(self, listen_host, listen_port):
        return listen_port == 8080


async def handle_client(process):
    # Get `listen_host` and `listen_port`
    ...


async def main():
    await asyncssh.create_server(
        Server, '', 8022, server_host_keys=['ssh_host_key'],
        authorized_client_keys='ssh_user_ca',
        process_factory=handle_client,
    )


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_forever()
```

**Comment by ronf** [comment]
Do you really want the listen_host here (which in this example would be empty), or would you want to get the IP address that the inbound connection actually connected to? If you want the local IP/port of the established connection, you can get the local socket information by calling process.get_extra_info('sockname'). It'll return a 2-tuple of host and port for IPv4 or a 4-tuple of host, port, flowinfo, and scope_id for IPv6. So, something like the following should work:

```python
    local_host, local_port = process.get_extra_info('sockname')[:2]
```

If you have multiple listeners all using a common handle_client() function and you want to distinguish between different listeners, you might want to consider using something like functools.partial to pass additional arguments to handle_client, which you'd then customize in the process_factory argument to create_server() as you set up each listener. Alternately, you could just pass different functions entirely there, and factor out common code in other ways once you got into those functions.

**Comment by AndrewLaneX** [comment]
Yeah, I don't think I need the host, but `process.get_extra_info('sockname')` gives me my server's public IP and the port SSH is running on - I need the forwarded port.

**Comment by ronf** [comment]
The handle_client function is run for SSH shell/exec/subsystem sessions, which would be completely independent of any requests a client made to open up a port forwarding listener on the server. In fact, you could receive connections on the remote port 8080 listener without any shell/exec/subsystem session even being created, in which case handle_client would never be run. There could also be multiple connections opened, with no association between them and any client sessions.

If you want to be able to see the individual forwarded tunnel connections, you'll probably need to provide your own SSHListener class, instead of returning `True` in the server_requested() function. However, even then, I'm not sure what port number you'd be looking to return. When a new connection arrives at AsyncSSH on port 8080, it creates a new "forwarded-tcp-ip" session to the SSH client, delivering the remote client's IP and port and the fact that the connection arrived on port 8080. However, it would be up to the client to decide what to do with that traffic, including what local port if any to open a connection to. This could be any host & port (see the arguments to "-R" in OpenSSH), and what the client chooses is not visible to the AsyncSSH server.

Are you looking to get the dynamically assigned source port number for each forwarded connection? If so, that information is also only available in the SSH client, since it is the client that ends up opening the local connection. The only information available to AsyncSSH would be the source IP and port of the inbound connections made to the listener it opened on port 8080.

**Comment by AndrewLaneX** [comment]
I've scrapped this project and wrote it in a different language that I feel a bit more comfortable with - not sure if I should close this issue.
