### ISSUE TITLE
Cannot read from SSHClientProcess

### ISSUE THREAD

**Issue by Fisch37** [ronf/asyncssh#391]
I'm trying to use asyncssh to launch a Minecraft Server. I can create a connection, but the issue occurs, when I am starting to read output from my process.

The server starts just fine, I can see that with top + connect to it, but neither `process.stdout.read`, nor `process.stdout.readline`, nor `process.collect_output` give me anything back. I tried to use a test script, but I still didn't get any results.
This here is my code: 
Main Executed code: https://pastebin.com/WiyjbEz9
Module of library mcconnect: https://pastebin.com/dPEWGNZW
Test script: https://pastebin.com/DCVKDPJy

I'm sorry if I gave too much information with that, but I don't know how to compress that into the useful code. (Everything can matter, I think)

Help would be greatly appreciated; thank you in advance ^^

**Comment by ronf** [comment]
As you said, there's a lot to go through here. Have you tried enabling debug logging? If so, do you see it actually writing the commands to the shell session like you expect? Do you see any sign of output coming back over the SSH connection on that SSH channel?

**Comment by Fisch37** [comment]
Debug didn't show any output either. I watched SSH traffic on Wireshark and there doesn't seem to be any data received after connection.
It might be a compatibility issue then. I'm gonna try connecting to a different server

**Comment by ronf** [comment]
I'd still be curious to see if authentication completed successfully, and if the opening of the session was successful or not after that. Also, at the very least, you should see the code write the command to the session, even if there's no response. If you're not seeing the write, then that would be a place to start debugging.

Turning on AsyncSSH debug logging at level 3 will let you see each and every packet which is sent/received. Be careful to edit those logs before sharing them if any passwords are being sent during auth, but that can provide a lot more useful info than what you get from Wireshark.

**Comment by Fisch37** [comment]
Question: What exactly do you mean by "AsyncSSH debug logging at level 3" and how can I enable that? Is there an AsyncSSH command for that or do I have to put something into the level parameter of my logging config?

**Comment by ronf** [comment]
AsyncSSH logging uses the standard Python event logging, but adds its own function for setting a debug log level. You should be able to add lines like the following to enable this:

```python
    import logging
    logging.basicConfig(level='DEBUG')
    asyncssh.set_debug_level(3)
```

Log output should show up on stdout.

**Comment by Fisch37** [comment]
So... turns out I'm an idiot. I just switched my output back to a readline instead of collect_output and low and behold: A message from the server. Turns out when I was originally testing the logging level was set to WARN and my watcher used INFO.

However: I'm still not getting an output from my test script which I find most curious. I will have to look into that, but in the meantime here is the auth procedure if you still care about that: https://pastebin.com/2uneDxkx

**Comment by ronf** [comment]
While collect_output() is designed not to block, be careful not to call wait() until you expect the remote process to exit. Otherwise, you'll block in that wait() call and may never get a chance to do non-blocking retrieve of written data.

Also, be aware that when using collect_output() you can't really predict when you have received ALL of the data that will be written. Generally speaking, if you're not going to have the process exit, you're better off using readline() or readuntil() so you can look for something specific in the output which tells you the current response is complete and that you can safely send the next command.

**Comment by ronf** [comment]
Regarding the debug output, everything looks good to me in that.

**Comment by Fisch37** [comment]
So I solved the command issue as well. Problem was that I had a trailing Change-Return character which debian recognised as a regular character not as an operator char. That's solved now and I'm getting correct output.

Issue with readline is I can only either have stdout or stderr. Both will require asyncio.gather. Also, my program didn't execute, because my loop of
```
while True:
    out, err = process.collect_output()
    print(out,end="")
    print(err,end="")
```
was completely synchronous therefore not allowing any async call in between it's own. All that's now fixed, thanks for your help, ronf! ^^

**Comment by ronf** [comment]
Glad you got it working!

It's definitely trying to try and read both stdout and stderr from a single coroutine. As you said, the easiest thing to do is to split the reads into two separate coroutines, but that can have its own challenges if relative ordering of the two streams needs to be maintained (although there's no way to really guarantee that).

Looking at what you're doing, it also seems like a callback-based approach could work better for you. As data arrives, you'll get callbacks with every new block of data that arrives, along with whether it is destined for stdout or stderr. You'd just need to use create_session() instead of create_process(). It takes a bit code to make this approach work as you're using a lower-level API, but if you want to experiment, check out the example at https://asyncssh.readthedocs.io/en/latest/#callback-example. The third example of the group there is probably the closest to what you might want.

**Comment by Fisch37** [comment]
I'll definitely look into that. I tried to use sessions actually, but stopped at the point where I had to know what a session factory is.
One question now, though: Do sessions get closed when you close the SSH connection? (same question for processes)

**Comment by ronf** [comment]
Yes, in both cases.

For sessions, the connection_lost() callback on the SSHSession you provide will be called for each channel which is still open at the time of an SSH connection close. If you have a custom SSHClient class, the connection_lost on that will be called as well. These methods provide an exception which is associated with the close if there is one or `None` if the connection closed cleanly.

For processes, the SSHProcess class automatically handles the connection_lost() for you, delivering EOF on stdout/stderr for the processes and passing on the exception to any blocking read() or drain() callers after any remaining data is flushed out.

One difference is that there's no concept of using "async with" with sessions (unless you write it yourself) the way there is with processes, to automatically trigger a close of the channel when leaving the scope of the "with". You need to call close() explicitly on the associated channel (or do it with something like a "finally" block). Also, if you want to do a wait_closed(), you do that on the channel object, which is provided when AsyncSSH calls your session's connection_made() callback when the session is first created.

The main missing functionality if you don't use processes would be the redirect capability, to automatically feed data from other input/output sources to stdin/stdout/stderr.

**Comment by Fisch37** [comment]
Good to know how that works, thanks ^^
