### ISSUE TITLE
connection errror 'Opening SSH connection to' lacking hostname.

### ISSUE THREAD

**Issue by pete312** [ronf/asyncssh#398]
File "/home/<user>/venv/lib/python3.6/site-packages/asyncssh/connection.py", line 6462, in connect
    conn_factory, 'Opening SSH connection to')

During a ssh permission error this message is lacking the hostname.   Can we add that or is there another way to derive that?

version is
asyncssh==2.5.0

**Comment by ronf** [comment]
The PermissionDenied exception would generally be raised in response to your call to asyncssh.connect(), or one of its variants. Those calls all take the hostname to connect to as an argument, so I would expect any code you write which catches the exception to have access to the hostname, if you want to raise your own exception that includes the hostname, or otherwise print out that information.

Also, if you enable logging, there should be information in the log output showing which hostname you were trying to connect to for each connection which is opened, and later log lines reporting the permission denied error would have a "conn=" entry with a connection number that you could use to match up the error with which hostname the connection was made to.

**Comment by pete312** [comment]
Yes I agree and I do catch the error with this.

```
except asyncssh.misc.PermissionDenied as e:
            logger.exception(e)
            error_str = str(e)
```

Since that does not have all the information needed, I have to return a wrapped response object with the host.

`return AsyncResult(RuntimeError(f"operation failed with {noof_retry} retries. {error_str}"), host)`


So here is my dirty laundry.

```
async def run_client(host, command, creds=None, callable=None, conn_pool=None, call_map=None):
   
    noof_retry = 2
    global _semaphore
    if callable and not hasattr(callable, '__call__'):
        raise ValueError("callback has no __call__ method", callable)
            
    
    args = dict(host=host, client_host_keysign=True, host_based_auth=True, known_hosts=None)
    retry = noof_retry
    error_str = ""
    while retry:
        try:
            conn_start = time.time()
            async with _semaphore:
                async with asyncssh.connect( **args ) as conn:
                    conn_took = time.time() - conn_start
                    exe_time_start = time.time()

                    if call_map:
                        command = call_map[conn._host]
                        result = AsyncResult( await run_wrapper(command, conn, conn_pool),  conn._host)
                    else:
                        result = AsyncResult( await conn.run(command), conn._host ) 
                                    
                    result.conn_took = conn_took
                    result.exe_took = time.time() - exe_time_start
                    result.took = result.conn_took + result.exe_took
                    result.execution = result.exe_took
                    result.duration = result.took
                    result.connect = result.conn_took
                    if callable :
                        callable(result)
                        
                    return result
                return AsyncResult(RuntimeError("connection not acquired."), host)
        except asyncssh.misc.PermissionDenied as e:
            logger.exception(e)
            error_str = str(e)
        except KeyboardInterrupt:
            conn.abort()
            logger.exception(e)
            error_str = str(e)
        except Exception as e:
            logger.exception(e)
            if retry:
                logger.warn("retry after exception", e)
            else:
                logger.exception(e)
                error_str = str(e)
                    
        retry -= 1
        
    return AsyncResult(RuntimeError(f"operation failed with {noof_retry} retries. {error_str}"), host)
```

I do not log the async API calls because its very chatty and usually not necessary.  Indeed this error is very rare.

However the point is the exception error 'Opening SSH connection to' seems to be a half baked error message ("to what?" you would naturally ask) and could be more useful to the client if it has host.   Also not all client code is written with proper logging enabled or even correctly trapping exceptions.  So its a reasonable improvement to the connection exception and make client code less cumbersome.  Last point forcing client code to re-throw API exceptions seems awkward at best.

The full stack trace is here. 

```
  File "/home/USER1/.venv/lib/python3.6/site-packages/toolbox/parallel.py", line 593, in run_copy
    async with asyncssh.connect(**hostkey_args) as conn:
  File "/home/USER1/.venv/lib/python3.6/site-packages/asyncssh/misc.py", line 220, in __aenter__
    self._result = await self._coro
  File "/home/USER1/.venv/lib/python3.6/site-packages/asyncssh/connection.py", line 6462, in connect
    conn_factory, 'Opening SSH connection to')
  File "/home/USER1/.venv/lib/python3.6/site-packages/asyncssh/connection.py", line 223, in _connect
    await conn.wait_established()
  File "/home/USER1/.venv/lib/python3.6/site-packages/asyncssh/connection.py", line 2107, in wait_established
    await self._waiter
asyncssh.misc.PermissionDenied: Permission denied

```



Thanks

**Comment by ronf** [comment]
If you take a look at how the 'Opening SSH connection to' string is used, you'll see that it is only a piece of the message that gets logged. In the `_connect()` function, it calls one of the following:

```python
        new_tunnel.logger.info('%s %s via %s', msg, (host, port), tunnel)
```
or
```python
        tunnel_logger.info('%s %s via SSH tunnel', msg, (host, port))
```
or
```python
        logger.info('%s %s', msg, (host, port))
```


So, the full message logged always includes the host and port, and sometimes also a tunnel that the connection request was sent over. The reason that `msg` is an argument here is that `_connect()` can also be called with the values 'Opening reverse SSH connection to' or 'Fetching server host key from', depending on whether you call `asyncssh.connect()`, `asyncssh.connect_reverse()` or `asyncssh.get_server_host_key()`. It uses this `msg` argument to make sure it logs the correct message depending on the action being performed.

As for the exception, that has nothing to do with the `msg` argument. In fact, in your example where you are getting a PermissionDenied exception, the error is unrelated to making the connection. It has to do with not being to authenticate to the server you are connecting to after you successfully connect. The exceptions returned by AsyncSSH (like most libraries) are not intended to be directly presented to the end user. That's the application's responsibility. The library just returns the specific thing that went wrong, and possibly some information that the application wouldn't otherwise know to help provide a more detailed error. However, the caller definitely knows the host & port in this case as those are being passed in by the caller, so there's no need to include that information in the exception.
