### ISSUE TITLE
Why PyCrypto instead of the cryptography lib ?

### ISSUE THREAD

**Issue by sametmax** [ronf/asyncssh#42]
Since the latter is becoming the standard, is there something the former offers the other one doesn't ?

**Comment by nchammas** [comment]
I think the GitHub description is out of date. AsyncSSH recently did switch over to [using Cryptography](https://github.com/ronf/asyncssh/blob/e9d31619f8a90dbe896d79bbd9d5685d6a0c7ea0/setup.py#L46) and [removed support for PyCrypto](https://github.com/ronf/asyncssh/blob/e9d31619f8a90dbe896d79bbd9d5685d6a0c7ea0/docs/changes.rst#release-130-10-oct-2015):

> Updated AsyncSSH dependencies to make PyCA version 1.0.0 or later mandatory and remove the older PyCrypto support. This change also adds support for the PyCA implementation of ECDSA and removes support for RC2-based private key encryption that was only supported by PyCrypto.

**Comment by ronf** [comment]
Yes, that's right. I've updated the Github description. Thanks for letting me know!

The PyCrypto library did support some older ciphers that PyCA did not, but they are considered so insecure now that I decided it was better to just drop support for them rather than depending on both PyCA and PyCrypto.
