### ISSUE TITLE
Remove use of asyncio.async()

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#43]
We discussed this previously [on the user list](https://groups.google.com/d/msg/asyncssh-users/ihqdEgV83a0/I9IkqSitCQAJ); just opening an issue here for tracking purposes.

AsyncSSH uses `asyncio.async()` in a few places. [`asyncio.async()`](https://docs.python.org/3/library/asyncio-task.html?highlight=async#asyncio.async) is deprecated as of Python 3.4.4 in favor of [`asyncio.ensure_future()`](https://docs.python.org/3/library/asyncio-task.html?highlight=async#asyncio.ensure_future).

**Comment by ronf** [comment]
Thanks, Nick.

I've actually been working on this since we discussed it and the latest code has only a single place where asyncio.async() is used, which is a create_task() function in SSHConnection. All other places that create tasks are routed through this, allowing SSHConnection to keep track of any background tasks which are created and also do some exception handling to make debugging easier.

I'd like to switch this last reference over to BaseEventLoop.create_task(), but that only appeared in Python 3.4.2 and I currently support back to 3.4.0. So, any change I'd make here would have to be conditional on Python version and still fall back to asyncio.async() on older versions.

**Comment by nchammas** [comment]
:+1: Sounds good to me.

**Comment by jquast** [comment]
This is a conditional I use:

```python
    if platform.python_version_tuple() <= ('3', '4', '4'):
        create_task = asyncio.async
    else:
        create_task = asyncio.ensure_future
```

**Comment by ronf** [comment]
Thanks. I've changed SSHConnection.create_task to look like:

```python
        if platform.python_version_tuple() >= ('3', '4', '2'):
            task = self._loop.create_task(self._run_task(coro))
        else:
            task = asyncio.async(self._run_task(coro), loop=self._loop)
```
