### ISSUE TITLE
"client_keys" option on connect() does not disable ssh-agent usage

### ISSUE THREAD

**Issue by Aglesia2** [ronf/asyncssh#432]
The documentation says that specify "client_keys" option on connect() disable the ssh-agent.
After many "Too many authentication failures" error, I saw that asyncSSH tried all my ssh-agent keys...
Specify "agent_path=None" resolved my problem.

Specify a Key on "client_keys" must disable the usage of ssh-agent, or I don't understand the documentation.

**Comment by ronf** [comment]
Thank you for reporting this. You're right that the documentation is out of date. This behavior changed in v2.5.0. Here's the relevant change log entry:

```
* Changed AsyncSSH to allow SSH agent identities to still be used when
  an explicit list of client keys is specified, for better compatibility
  with OpenSSH. The previous behavior can still be achieved by explicitly
  setting the agent_path option to None when setting client_keys.
```

Part of the reason for this change was that this release also added support for the OpenSSH config file option "IdentitiesOnly", which allows you to specify public key files as client keys with the corresponding private keys stored in an SSH agent, using the public key list to limit which agent keys will be used.

Unfortunately, it looks like the documentation of the agent_path parameter was never updated to remove the text about the agent being disabled when client_keys is set. As you discovered, the proper way to disable use of the SSH agent now is only by setting agent_path to `None`. Setting client_keys no longer disables the agent. I'll get the documentation fixed in the next release.

**Comment by ronf** [comment]
This change is now available in the "develop" branch as commit 6fd0f5f. If there were any other places where the documentation wasn't updated about this behavior, please let me know!

**Comment by Aglesia2** [comment]
Thank you very much for the update !

On https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnectionOptions, there is also the "client_keys" option : 

`client_keys (see Specifying private keys) – (optional) A list of keys which will be used to authenticate this client via public key authentication. If no client keys are specified, an attempt will be made to get them from an ssh-agent process and/or load them from the files [...]`

"If no client keys are specified" made me think if I specify a key, it will not try to use ssh-agent or load from common files.

**Comment by ronf** [comment]
Yeah, I can try to reword this one as well. What do you think of the following?

> client_keys (see Specifying private keys) – (optional) A list of keys which will be used to authenticate this client via public key authentication. These keys will be used after trying keys from a PKCS11 provider or an ssh-agent, if either of those are configured. If no client keys are specified, an attempt will be made to load them from the files .ssh/id_ed25519_sk, .ssh/id_ecdsa_sk, .ssh/id_ed448, .ssh/id_ed25519, .ssh/id_ecdsa, .ssh/id_rsa, and .ssh/id_dsa in the user’s home directory, with optional certificates loaded from the files .ssh/id_ed25519_sk-cert.pub, .ssh/id_ecdsa_sk-cert.pub, .ssh/id_ed448-cert.pub, .ssh/id_ed25519-cert.pub, .ssh/id_ecdsa-cert.pub, .ssh/id_rsa-cert.pub, and .ssh/id_dsa-cert.pub. If this argument is explicitly set to None, client public key authentication will not be performed.

**Comment by ronf** [comment]
The update above is now in the "develop" branch as commit 6717cfc and should be available at https://asyncssh.readthedocs.io/en/develop/api.html#sshclientconnectionoptions. Both of these changes will be included in the next release.
