### ISSUE TITLE
passsing named 'options' argument to asyncssh.connect seems broken

### ISSUE THREAD

**Issue by fillest** [ronf/asyncssh#445]
I had some working code with `asyncssh==2.4.2`, now I upgraded to `asyncssh==2.9.0` and asyncssh.connect() began to fail.
The code looks like this:

```python
opts = asyncssh.SSHClientConnectionOptions(
	keepalive_interval = 10,
	username = user,
	client_keys = keys,
	kex_algs = ...
	#and so on
)
async with asyncssh.connect(host, options = opts, config = None) as conn:
	#...
```

After the upgrade I began to get immediately `asyncssh.misc.ConnectionLost: Connection lost`, turned on debug logging and saw a `Proxy command` there (the one that I use in `~/.ssh/config`), which means that neither `config = None` nor `options = opts` are applied now (or just `config = None`? I don't know actually because the ignored `config` prevents the further connection).
Now, if I call it like this -  `async with asyncssh.connect(host, config = None, **opts) as conn:`  - it works again.
So the problems are:
- either [docs](https://asyncssh.readthedocs.io/en/latest/api.html#connect) are out-of-date or named `options` passing got broken, probably affecting `config`
- would be great to see in info/debug logging that some ssh config file was loaded and used (it was very confusing too see that `Proxy command`)

**Comment by ronf** [comment]
Thank you for the report!

I think I'm able to reproduce this here, but it looks to me like the behavior was present even in 2.4.2.

More specifically, both SSHClientConnectionOptions and named config arguments are working for me, but it looks like the combination of "options=opts" and "config=None" passed into the connect() call may still read the default config file. The options passed in through "options=" are correctly handled from what I can see, but anything not specified in options can end up being pulled from the default config file, even though that's supposed to be disabled. This seems like a bug to me, but it's not a behavior change since 2.4.2. Both 2.4.2 and 2.9.0 behave this way for me, loading the default config file.

It looks like it works if you include the "config=None" as part of constructing "opts" rather than passing "config=None" and "options=opts" in the connect() call, so that might be a workaround for you. As you discovered, it also appears to work if you pass in "config=None" in the connect() call along with other keyword arguments, but without an "options=" argument.

I'll continue to examine this and see what I can do to make AsyncSSH honor the "config=None" even when "options=" is passed in the connect() call, but I'm curious why you're not seeing this problem in 2.4.2.

**Comment by ronf** [comment]
Ok - I think I see what's going on here, and it looks like this is intended behavior.

When you construct "opts" without passing "config=" to it, you're asking AsyncSSH to load not only the arguments you pass in explicitly but also to include any settings in the default config file into that SSHClientConnectionOptions object (or whatever config fie you specify explicitly in that call). If you pass "config=None" to connect() along with an options object, it's basically a no-op, as any config file specified in the "config" argument at that point is loaded _in addition_ to the config previously loaded when "opts" was constructed. So, specifying "None" in the connect() tells AsyncSSH not to load any new config, but the config previously loaded when "opts" was constructed remains active, and that includes the default config.

If you don't want "opts" to pick up any settings from the default config file you need to specify "config=None" when it is constructed. Once you do that, you don't need to specify "config=None" on the connect() call, as the config choice you made constructing "opts" is remembered and used whenever you specify "options=opts" (unless you explicitly ask to load additional config files).

Updating the documentation for connect() to make this more clear is a good idea. Before I do that, though, I'd like to try and understand why this worked for you previously with AsyncSSH 2.4.2. Can you confirm that and give a more complete example so I could try to reproduce it?

**Comment by ronf** [comment]
Regarding your suggestion about more debug logging around config files, I can look into possibly logging which config paths are active for a given request, or at least log something when a config file is loaded (though it might be hard to tie it back to a specific options object and where that options object is later used).

**Comment by ronf** [comment]
I just pushed commit f6a8fa6 to the "develop" branch, which fixes a couple of bugs I noticed while experimenting with the config support. This commit also adds a level 1 debug message whenever a config file is loaded. Since these objects are created independently from connections, the messages aren't labeled with any connection information, but the messages should help at least identify which config files (if any) are being loaded.

Regarding documentation, there is already a note under SSHClientConnectionOptions for the "config" parameter which states:

> Specifying configuration files when creating an SSHClientConnectionOptions object will cause the config file to be read and parsed at the time of creation of the object, including evaluation of any conditional blocks. If you want the config to be parsed for every new connection, this argument should be added to the connect or listen calls instead. However, if you want to save the parsing overhead and your configuration doesn't depend on conditions that would change between calls, this argument may be an option.

However, this doesn't discuss the case where you attempt to use both "options" and "config" in a single call, or the fact that the default config file will be loaded when creating an SSHClientConnectionOptions object unless you explicitly pass in "config=None". I'll look into improving the documentation around that.

**Comment by ronf** [comment]
Thinking more about this, I'm going to look into another approach to address the main issue here, if I can make it backward compatible enough with existing behavior in the common use cases.

Basically, I'm thinking of making  the default for the "config" argument for SSHClientConnectionOptions be `None` rather than `()` (which is a marker to mean load the default config). However, the default when calling connect() and the other top-level functions for the "config" argument would still be to load the default config. This would apply when either "options" wasn't specified in the connect() or when it was but no "config" was specified when that SSHClientConnectionOptions object was created.

In the case where neither the SSHClientConnectionOptions object or the connect() call specify a "config" argument, I should be able to get roughly the same result as loading the default config during the "options" object creation.  In fact, I can probably make this work slightly better since at that point more information is available when evaluating the config conditionals.

If I can make this work, it would mean specifying no config on the SSHClientConnectionOptions object creation and then specifying `config=None` later in connect() would do what I think you want here, which is to load no config. You could also explicitly specify "config" when creating an SSHClientConnectionOptions and get a config to load early like it does now (in which case that config would take precedence.

Not specifying "options" in the connect() would also behave exactly as it does now, loading either no config with `config=None`, the default config if that argument isn't specified, or a specifically named config if it is.

**Comment by ronf** [comment]
Ok - I've managed to change the model as I described above.

Previously, if an options object was passed in on the connect() and no config argument was specified when creating that object, the default SSH config file would be loaded at the time the options object was created. To avoid this, "config=None" had to be specified when creating the options. Loading the config early prevented some conditionals from being evaluated properly, since information to match those conditionals against wasn't available yet. Also, leaving "config" unset when creating the options object meant that "config=None" in the connect() call could not be honored since the default config was already loaded before connect() was called.

With this change, the decision about whether to load the default config or not is deferred until the connect() call when config is not specified in either the options object creating or in the connect() call. This delay also means that specifying "config=None" on the connect() call now properly prevents the default config file from being loaded.

Here's a more detailed summary of the old/new behavior:

When options is not specified at all on connect() call:

- When config is specified in connect(): Attempt to load specified config (UNCHANGED)
- When config is not specified on connect(): Attempt to load default config, if present (UNCHANGED)
- When config is explicitly set to `None` on connect(): Don't load any config (UNCHANGED)

When options is specified on connect(), but no config was specified when creating options:

- When config is specified in connect(): Attempt to load specified config (CHANGED)
  - Previously, this would attempt to load the default config when options was created and then add the specified config later in connect(), but any settings from the default config would take precedence.
- When config is not specified on connect(): Attempt to load default config at connect() time, if present (CHANGED)
  - Previously this would attempt to load the default config earlier, when options was created. This meant that some conditionals in the config might not be evaluated correctly, as the information wasn't available yet.
- When config is explicitly set to `None` on connect(): Don't load any config (CHANGED)
  - Previously, the default config was already loaded when options was created and setting `None` here couldn't prevent this.

When options is specified on connect() and config is specified when creating options:

- When config is specified in connect(): Attempt to load both config in options and config on connect() (UNCHANGED)
  - As before, there are limitations on this, as many config settings will get "locked in" at the time the options was created and not be affected by the additional config file loaded on the connect().
- When config is not specified on connect(): Load only the config specified in options (UNCHANGED)
- When config is explicitly set to `None` on connect(): Load only the config specified in options (UNCHANGED)

The documentation under connect(), listen_reverse(), and get_server_host_key() has also been updated to describe the new behavior.

This change is now available as commit 2809f70 in the "develop" branch. Feedback is welcome!

**Comment by ronf** [comment]
This change is now available in AsyncSSH 2.10.0.

**Comment by fillest** [comment]
Thanks for quick and detailed responses!

**Comment by ronf** [comment]
My pleasure - this was an interesting one. Let me know if you have any trouble with the change!
