### ISSUE TITLE
get_exit_status() returning `None`

### ISSUE THREAD

**Issue by qix** [ronf/asyncssh#45]
Hey,

It seems to happen on occasion, but the documentation over `get_exit_status()` seems problematic. The example code shows:

```
        output = yield from stdout.read()
        print(output, end='')
        status = stdout.channel.get_exit_status()
```

Often in production we're seeing `status = None` there every so often, unless I throw a `yield from asyncio.sleep(1)` on the line above it.

I tried the following but it didn't improve the situation:
```
    stdout_stream.channel.close()
    yield from stdout_stream.channel.wait_closed()
```

Perhaps there is a need for `wait_for_exit`? I'll probably be switching over to the ClientSession class which should allow me to more easily wait, so this isn't urgent on my side.

**Comment by ronf** [comment]
If you actively close a channel yourself, you can risk doing so before the remote end sends its exit status. I don't think there's anything I can do about that, as the requirement in the SSH spec on close is that the other end is required to close immediately when they receive a close. I will wait to receive their close before I clean up and record the exit status if they send it, but if they choose to close without sending the status, None will be reported even if you do a wait_closed(). A separate wait_for_exit() wouldn't help here, as it would never come.

If you know the remote end is going to exit & close, the solution is to do the wait_closed() call without calling close() yourself. Then, you're sure the other end will have time to send everything it wanted to.

If the remote won't close without seeing that you're done sending, you can try doing a write_eof() on stdin instead of a close(). That will still give the other end a chance to send everything, including exit status.

If you still see this problem without calling close() yourself, please let me know. If you have a reproducible test case, that would be terrific -- I'd be happy to take a closer look at it.

**Comment by ronf** [comment]
Also, where are you seeing the example you mentioned above? I can't seem to find it. The only example I can find is the session-based example at:

http://asyncssh.readthedocs.org/en/latest/#checking-exit-status

If there is a streams-based example, I'll update it to add in a wait_closed() before calling get_exit_status().

**Comment by ronf** [comment]
I've just updated the example in the README in the "develop" branch to add a call to wait_closed() before retrieving the exit status. This will be part of the next release.

**Comment by qix** [comment]
This all makes sense, tested it out and not seeing any issues.
