### ISSUE TITLE
pyright compatiblity

### ISSUE THREAD

**Issue by timsampsoncujo** [ronf/asyncssh#457]
The most recent release included type hints and support for mypy type checking. Thank you for that! We however use Pyright instead of mypy and that doesn't play nicely with asyncssh. Specifically it fails to "see" the re-exports (or whatever I should call those...) of `asyncssh/__init__.py` as it considers those to be private (see the second bullet here: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface). That section of their docs refs pep-561 but reading through that I can't see anything about the point of keeping those members private. Neither glancing through the mypy docs can I see anything about that either (though I didn't check them super thoroughly).

So the solutions for us, as I see it would be:

- directly import symbols from their original locations e.g. `from asyncssh.misc import ConnectionLost` rather than `from asyncssh import ConnectionLost` => pyright works but this seems unfortunate as to my understanding we'd then being using asyncssh's private API so things might break for us in future releases
- maintain our own type stub for asyncssh => this would work but feels unfortunate as it's basically duplicate work and may go out of date in future releases
- make a PR to asyncssh to make pyright and asyncssh to play nicely together

Of those the last one seems like the best option to me. Would you be amenable to such a PR? From looking at the pyright docs (same link I posted earlier) it seems like one could make it understand that the symbols in `asyncssh/__init__.py` are public by defining `__all__` there. That seems a _little_ bit ugly to me from asyncssh's point of view but would you accept such a PR?

**Comment by ronf** [comment]
After getting the AsyncSSH code to run through "mypy" cleanup, I took a shot at trying to run it through "pyright" as well, but I ran into some serious roadblocks. Despite a 100% clean "mypy" run, pyright is reporting over 1100 errors, and as I started digging into these, I found a number of cases where the strictness of pyright would require MAJOR surgery on AsyncSSH to get rid of the errors. While I would be willing to accept some changes to improve compatibility if they weren't too disruptive, my experience so far is that it's not possible to make this codebase compatible without more effort than is worth putting into it.

It might be possible to silence some of the errors via config options in pyright, but in general pyright seems MUCH stricter than mypy in terms of what it can be configured to allow, and taking this large a code base and trying to retrofit into those rules is not a simple matter. I'm also not sure how much value that would add over what's already working with mypy. I wish the two were more compatible, but since they aren't I'm not sure I want to clutter the AsyncSSH code too much with what in the end will probably only be a partially working solution.

In terms of the specific issue you mentioned, adding "as" versions of all those imports sounds very ugly, as there are hundreds of symbols in that file which would require that treatment. Having to add all those symbols to "__all__" is only marginally better. This seems like the perfect example of something that really should be a config option, especially given that "mypy" has set a precedent of already working without either of those changes.

Regarding PEP-0484, I think one of the later bullets covers the way AsyncSSH is importing things:

> Just like in normal Python files [[importdocs]](https://www.python.org/dev/peps/pep-0484/#importdocs), submodules automatically become exported attributes of their parent module when imported. For example, if the spam package has the following directory structure:
> 
> ```
> spam/
>     __init__.pyi
>     ham.pyi
> ```
> where `__init__.pyi` contains a line such as `from . import ham` or `from .ham import Ham`, then ham is an exported attribute of spam.

This is a bit ambiguous as It only mentions the export of `ham` and not what happens with the second import of `Ham`, but it's definitely the case that the regular Python import mechanism properly exports `Ham` in this case, and this bullet seems to be saying that stub files should work the same as the regular import in this regard. By extension, I would want a type-checker to also be compatible with the standard Python import rules, at least as an option.

I can see why pyright might not want to default to this (as you may only want to use the imported symbol locally and not export it), but in a file like my __init__.py where its only purpose is to import symbols meant to be public, having to explicitly list all of those names twice is not a pleasant thought.

**Comment by timsampsoncujo** [comment]
> This is a bit ambiguous as It only mentions the export of ham and not what happens with the second import of Ham,

The Pyright docs state exactly that `ham` is public but that `Ham` isn't in that case i.e. (again from https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface):

> Imported symbols are considered private by default. If they use the “import A as A” (a redundant module alias), “from X import A as A” (a redundant symbol alias), or “from . import A” forms, symbol “A” is not private unless the name begins with an underscore. If a file __init__.py uses the form “from .A import X”, symbol “A” is not private unless the name begins with an underscore (but “X” is still private). If a wildcard import (of the form “from X import *”) is used, all symbols referenced by the wildcard are not private.

I sympathise with your reluctance. Both doing the "redundant" `as` imports or defining `__all__` seem ugly to me in `asyncssh`'s codebase. Also I was surprised by this choice as in this case those symbols *are* public (i.e. obviously Python itself is happy) and in general if you want to hide some symbols you define an `__all__` with those things excluded i.e. symbols are public by default.

FWIW I just ran current pyright on this codebase and yeah, even excluding `tests` there's 600ish issues reported. So that would be a non-trivial effort I imagine (if one wanted to do that). At a glance, there's a some of the visibility things we've been discussing here, some trivial things and some things that look like they would be painful to address.

But anyway, fair enough. I guess we'll just maintain our own stub. Cheers for your consideration.

**Comment by ronf** [comment]
Yeah - I was kind of hoping to find a configuration options that controlled this (especially given that it doesn't match the default Python behavior), but I don't think that exists.

If you run into anything regarding the declared types in AsyncSSH which appears to be wrong, please let me know. Also, if there are modest changes which don't break compatibility with mypy but make it easier for you to maintain your pyright stub, I'd be happy to consider them. Sorry I'm not able to provide full compatibility at this point!

**Comment by llchan** [comment]
I just ran into this as well.  For the time being I'll import from the module directly (e.g. `asyncssh.connection`), which may wind up being more brittle in the future.

My 2c is that since the public facade is intended to be the top-level `asyncssh`, we can sacrifice readability in the `__init__.py` and either do the `from .connection import Blah as Blah` or add `__all__`.  The file doesnt contain any logic anyways so I think it's fine to have it be very explicit about what's exported.  With black-style formatting it would wind up having one exported name for line anyways so it should still be pretty easy to read/grep.

Happy to send over a PR so this is minimal effort for you.  I dont think this will impact mypy's interpretation of the exported names.

**Comment by ronf** [comment]
Thanks for the offer, but there's already a PR filed by @nagua (#489) that should cover adding `__all__` to address this issue. There are just a few minor edits I've requested around the formatting and to remove some of the modules imported only for their side-effects (registration calls) and then I should be able to merge it in.

That said, I'm still curious if microsoft/pyright#2277 might be a solution for this without the need to mess with the imports or `__all__`, but I haven't had a chance to experiment with that yet.

**Comment by ronf** [comment]
Tonight, I tried to reproduce this issue with the command-line "pyright" (version 1.1.256) by running it against my "examples" directory. I did this without adding `__all__` to AsyncSSH's `__init__.py` and without having any pyrightconfig.json or pyproject.toml config files, and it didn't report any errors:

```
No configuration file found.
No pyproject.toml file found.
stubPath /Users/ronf/src/asyncssh/typings is not a valid directory.
Assuming Python platform Darwin
Searching for source files
Found 41 source files
pyright 1.1.256
0 errors, 0 warnings, 0 informations
Completed in 1.089sec
```

Based on the discussion here and in #485, I would have expected to get errors about the asyncssh symbols used by these files being private. What am I missing? Before committing anything in AsyncSSH related to this, I want to be sure I can reproduce the problem and confirm that the change in AsyncSSH fixes the problem.

**Comment by timsampsoncujo** [comment]
I get the same behaviour as you when I run pyright 1.1.256 on the examples dir _in situ_. However if I copy them out of tree (which is more representative of calling asyncssh from another project) and rerun I get the expected wall of `reportPrivateImportUsage` errors e.g.

```
$ cp -r examples/ /tmp
$ cd /tmp/
$ pyright examples/
No configuration file found.
No pyproject.toml file found.
stubPath /tmp/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 41 source files
pyright 1.1.256
/tmp/examples/callback_client.py
  /tmp/examples/callback_client.py:27:10 - error: "set_log_level" is not exported from module "asyncssh" (reportPrivateImportUsage)
  /tmp/examples/callback_client.py:30:35 - error: "SSHClientSession" is not exported from module "asyncssh" (reportPrivateImportUsage)
  /tmp/examples/callback_client.py:31:59 - error: "DataType" is not exported from module "asyncssh" (reportPrivateImportUsage)
  /tmp/examples/callback_client.py:39:28 - error: "SSHClient" is not exported from module "asyncssh" (reportPrivateImportUsage)
  /tmp/examples/callback_client.py:40:46 - error: "SSHClientConnection" is not exported from module "asyncssh" (reportPrivateImportUsage)
...
```

**Comment by ronf** [comment]
Thanks - I was also able to confirm the errors when asyncssh was pulled from Python's site-packages instead of the local directory, though it took me a while to figure out how to control which instance of the Python interpreter that pyright used. The "pyright" script seems to ignore the Python version in the "#!" and the version of python in PATH and always kept trying to use the system version of Python (which was only available under the name "python3"). In the end, I finally managed to get it working by setting up a virtualenv, though.

This should now be fixed in the "develop" branch (thanks, @nagua !). Also, as discussed in #485, I confirmed that you can get rid of the errors in the existing version of AsyncSSH if you add the following to the pyright config:

```json
    "reportPrivateImportUsage": false
```
