### ISSUE TITLE
Connect Lost on CentOS stream 9 hosts

### ISSUE THREAD

**Issue by oliviajindi** [ronf/asyncssh#461]
Hi team! We are testing on some hosts newly upgraded to CentOS stream 9 with openssl3. And we found we are not able to connect to those hosts with asyncssh while we can use the same cert ssh to it by just running `ssh <hostname>`.

We got connect lost error from asyncssh connection and following is the detailed logs.
```
2022-03-24 11:31:47,365 DEBUG    [asyncssh] [conn=0] Received key exchange request
2022-03-24 11:31:47,365 DEBUG    [asyncssh] [conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]   Host key algs: rsa-sha2-512,rsa-sha2-256,ssh-rsa,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]   Client to server:
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     Encryption algs: aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     MAC algs: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     Compression algs: none,zlib@openssh.com
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]   Server to client:
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     Encryption algs: aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     MAC algs: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512
2022-03-24 11:31:47,366 DEBUG    [asyncssh] [conn=0]     Compression algs: none,zlib@openssh.com
2022-03-24 11:31:47,367 DEBUG    [asyncssh] [conn=0] Beginning key exchange
2022-03-24 11:31:47,367 DEBUG    [asyncssh] [conn=0]   Key exchange alg: curve25519-sha256
2022-03-24 11:31:47,367 DEBUG    [asyncssh] [conn=0, pktid=1] Sent MSG_KEX_ECDH_INIT (30), 37 bytes
  00000000: ...<some bytes>
  00000010: ...<some bytes>
  00000020: ...<some bytes>  
2022-03-24 11:31:47,387 INFO     [asyncssh] [conn=0] Connection lost
2022-03-24 11:31:47,387 INFO     [asyncssh] [conn=0] Aborting connection
```

And on the target host side we got `fatal: mm_answer_sign: sign: error in libcrypto`.

Here is how I use asyncssh to connect.
```
priv_path = "somepaht"
cert_path = priv_path + "-cert.pub"
privkey = asyncssh.read_private_key(priv_path)
cert = asyncssh.read_certificate(cert_path)

options = asyncssh.SSHClientConnectionOptions(
    username="root",
    client_keys=[(privkey, cert)],
    known_hosts=None,
    x509_trusted_certs=None,
    # signature_algs="rsa-sha2-512",  # I tried with and without this line. Both are failed
)

async with asyncssh.connect(
    "hostname>"
    port=22,
    options=options,
) as conn:
    result = await conn.run("ls /")
    logging.info(" --- ".join(result.stdout.splitlines()))
```

Any help is appreciated! Thanks!

**Comment by ronf** [comment]
Is the target system running in FIPS mode by any chance? Based on a quick search, one possible reason for this error is if FIPS is enabled and you try to use a non-FIPS-compliant algorithm, which curve25519 would be. I would have expected the server to not advertise any non-FIPS-compliant algorithms in the SSH handshake, but that's apparently not the case here. If you edit the config on the server to remove non-FIPS algorithms, though, it may fix the problem.

There's no way for AsyncSSH to know whether the remote system is in FIPS mode or not, or more generally that some of the algorithms being advertised by the server aren't really supported by it, so I don't think there's anything which can be done on the client if this is the problem.

**Comment by oliviajindi** [comment]
Thanks @ronf! So I did a quick check. It seems the client host is enabling FIPS while target is not. I validated as follow. Please correct me if this is not a right to verify it.

```
# Client
ssh -V                                                                                                                   [8:05:17]
OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021

# Server
OpenSSH_8.7p1, OpenSSL 3.0.1 14 Dec 2021
```

So my question is, if the case is opposite, which the client is FIPS enabled, will it also be possbile that the non-FIPS reject the handshake as well?

**Comment by ronf** [comment]
I wouldn't expect the OpenSSH version on the client to matter in this case, since you are using AsyncSSH as your client. It has its own independent crypto, provided by the Python "cryptography" package. While that's generally also based on OpenSSL, it may not be the same version of OpenSSL that the OpenSSH client is using.

Also, you said the target host reported "fatal: mm_answer_sign: sign: error in libcrypto", which would suggest the error is being returned by libcrypto on the server.

What do you see when you do "cat /proc/sys/crypto/fips_enabled" on the target machine?

**Comment by oliviajindi** [comment]
Also I'm taking a look on the asyncssh.SSHCertificate read by asyncssh. And I got `{'algorithm': b'ssh-rsa-cert-v01@openssh.com', 'sig_algorithms': (b'rsa-sha2-256', b'rsa-sha2-512', b'ssh-rsa-sha224@ssh.com', b'ssh-rsa-sha256@ssh.com', b'ssh-rsa-sha384@ssh.com', b'ssh-rsa-sha512@ssh.com', b'ssh-rsa'), 'host_key_algorithms': (b'ssh-rsa-cert-v01@openssh.com',),....}`. I have a noob quesiton, what is the alogrithm and sig_algorithms here? From the cert read from `ssh-keygen`, we are using rsa-sha2-512 but it seems I didn't see it in above?

**Comment by ronf** [comment]
> Also I'm taking a look on the asyncssh.SSHCertificate read by asyncssh. And I got {'algorithm': b'ssh-rsa-cert-v01@openssh.com', 'sig_algorithms': (b'rsa-sha2-256', b'rsa-sha2-512', b'ssh-rsa-sha224@ssh.com', b'ssh-rsa-sha256@ssh.com', b'ssh-rsa-sha384@ssh.com', b'ssh-rsa-sha512@ssh.com', b'ssh-rsa'), 'host_key_algorithms': (b'ssh-rsa-cert-v01@openssh.com',),....}. I have a noob quesiton, what is the alogrithm and sig_algorithms here? From the cert read from ssh-keygen, we are using rsa-sha2-512 but it seems I didn't see it in above?

RSA is very messy compared to other algorithms, allowing "ssh-rsa" to be listed as the "algorithm" but then multiple signature algorithms (like "rsa-sha2-512") to be used to actually do signatures. So, there are multiple options for "sig-algorithms" for different hashing algorithms, rather than having different top-level SSH algorithm names, each of which has a single corresponding signature algorithm.

I've had problems in the past with needing "fix up" certificates that start out as "ssh-rsa-cert-v01@openssh.com" but later pick up a signature algorithm of "rsa-sha2-512", where the advertised algorithm needs to be changed to "rsa-sha2-512-cert-v01@openssh.com", but since AsyncSSH is a client here, that wouldn't come up until later when you were trying to do user authentication. This seems to be failing during the key exchange, which would only involve the server's host key/certificate.

I think we need to look closer at the MSG_KEX_ECDH_INIT to see if anything seems off there, but since the error on the server is a libcrypto error and not an SSH error, it makes me think the server is happy with that init message and running into an issue after that trying to generate the reply.

**Comment by oliviajindi** [comment]
Oh thanks! It works when I add `server_host_key_algs="rsa-sha2-512",`. Does that mean the we set multiple host keys on the client and async randomly pick up one which is not supported by the server?

**Comment by ronf** [comment]
If you select "rsa-sha2-512", I think you are asking for the server to sign directly with its server host key, and not with a server host certificate. This would require the client to have the server's public key directly in its `known_hosts` file or for known hosts checking to be disabled (as it appears to be here). On the other hand, with "rsa-sha2-512-cert-v01@openssh.com" as the server host key algorithm, the server would be signing with its same public key but providing a certificate which associated that public key with a certificate authority, and the client could have a `known_hosts` entry for that certificate authority's public key instead, which could potentially be shared by multiple servers.

So, it sounds like there's some issue with signing with the server's host certificate. Did you mean to be using server host certificates here?

**Comment by ronf** [comment]
Note that it is the server picking which server host key/certificate to use. The client just specifies a list of server host key algorithms it will accept, and the server then picks a key (and optional certificate) which matches one of the listed algorithms or gives an error if it doesn't have a host key/certificate matching any of those algorithms.

**Comment by oliviajindi** [comment]
Actually I tried `rsa-sha2-512-cert-v01@openssh.com` first but got following exception. And I don't see it listed in [wiki](https://asyncssh.readthedocs.io/en/latest/api.html#publickeyalgs) as well.
```
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "<string>", line 47, in __run
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/scripts/oliviajindi/centos9.py", line 42, in <module>
    asyncio.run(test_coro())
  File "/usr/local/fbcode/platform009/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/fbcode/platform009/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/scripts/oliviajindi/centos9.py", line 21, in test_coro
    options = asyncssh.SSHClientConnectionOptions(
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/connection.py", line 5574, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/misc.py", line 268, in __init__
    self.prepare(**self.kwargs)
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/connection.py", line 6164, in prepare
    _select_host_key_algs(server_host_key_algs,
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/connection.py", line 458, in _select_host_key_algs
    return _select_algs('host key', algs, possible_algs,
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/connection.py", line 426, in _select_algs
    algs = _expand_algs(alg_type, algs, possible_algs,
  File "/data/users/oliviajindi/fbsource/fbcode/buck-out/dev/gen/scripts/oliviajindi/centos9#link-tree/asyncssh/connection.py", line 397, in _expand_algs
    raise ValueError('"%s" matches no valid %s algorithms' %
ValueError: "rsa-sha2-512-cert-v01@openssh.com" matches no valid host key algorithms
```

Also noob question is, seems using "rsa-sha2-512" is different with "rsa-sha2-512-cert-v01@openssh.com"?

**Comment by ronf** [comment]
Actually, good point. This goes back to what I was saying earlier about having to convert ssh-rsa-cert-v01@openssh.com (which is listed in the table you mentioned) to the sha512 variety of it. I was thrown a bit by what you listed above, though, where rsa-sha2-512-cert-v01@openssh.com was listed. However, I see now that this algorithm was listed in the received host key algorithms coming from the server, and not the list from AsyncSSH.

This may be getting to the heart of the problem, though. It may be that OpenSSH is trying to the rsa-sha2 forms of the host algorithm name and AsyncSSH is not listing those, where OpenSSH running on both sides would list it. I'm also thinking that OpenSSH is probably no longer allowing "ssh-rsa-cert-v01@openssh.com", which is the only RSA flavor of certificate algorithm that AsyncSSH is listing now. I may need to change AsyncSSH to list those additional certificate variants of the rsa-sha2 algorithms.

> Also noob question is, seems using "rsa-sha2-512" is different with "rsa-sha2-512-cert-v01@openssh.com"? One is signed with host key while the other is certificate?

Both sign with the server host key, but using the certificate version then sends a certificate which associates the host key with a certificate authority, so that clients can list only the certificate authority in their `known_hosts` file instead of having to list each server's public key individually.

**Comment by oliviajindi** [comment]
Thanks @ronf ! Yeah in new openssh they are going to deprecate "ssh-rsa-cert-v01@openssh.com". They will not be able to used in new openssh which is used by centos c9.

**Comment by ronf** [comment]
The "ssh-rsa" version is still usable, but it'll be disabled by default and only available if you explicitly configure it.

I'll have to experiment a bit to see if things work properly if I register the rsa-sha2 versions of the names in AsyncSSH as not just signature algorithms but also public key/certificate algorithms.

In the meantime, if you don't need to use a server host certificate, setting host_key_algorithms to "rsa-sha2-512" should be a fine workaround.

**Comment by oliviajindi** [comment]
Sure. Thanks a lot for your time and help! I'll close this issue first.

**Comment by oliviajindi** [comment]
Hi @ronf! Got some following quesitons on the host key algorithm side. Not sure if I understand correctly, so if I use "rsa-sha2-512" in `server_host_key_algorithm`, so in the handshake process, the server will return a host priv key instead of a certs. And in this case, if a priv key is returned instead of the certs, the hosts must be in the `known_hosts` right?

**Comment by ronf** [comment]
Either way, the server will use its host private key to perform the key exchange. The difference is only in what it sends for the client to verify. If you use "rsa-sha2-512", the server will send its host public key to the client and that's what will be needed in `known_hosts` for the connection to succeed. If you use the "cert" version (and have a server host certificate specified on the server), the server will send that certificate in place of its public key, and the client will need to have the public key of the certificate in its `known_hosts` instead of the public key of individual servers. In this case, though, you'd be to trust only a single certificate authority public key in `known_hosts` and use that key to sign public keys belonging to many different servers.

If you set `known_hosts=None` on the client, this doesn't really matter, as you aren't doing `known_hosts` validation. However, that's a potential security hole, so you may not want to leave that in place long-term.

If you end up using only the host public key here, you don't even need to create a server host certificate. Unlike SSL, SSH does not need certificates to function.

I haven't had a chance to do full testing on this change yet, but if you apply the following, does it allow things to work without you specifying server_host_key_algs?

```patch
diff --git a/asyncssh/rsa.py b/asyncssh/rsa.py
index 2ee35fd..bbf1547 100644
--- a/asyncssh/rsa.py
+++ b/asyncssh/rsa.py
@@ -263,10 +263,11 @@ class RSAKey(SSHKey):
         return priv_key.decrypt(data, _hash_algs[algorithm])


-register_public_key_alg(b'ssh-rsa', RSAKey, True)
+for alg in (b'rsa-sha2-256', b'rsa-sha2-512', b'ssh-rsa'):
+    register_public_key_alg(alg, RSAKey, True)

-register_certificate_alg(1, b'ssh-rsa', b'ssh-rsa-cert-v01@openssh.com',
-                         RSAKey, SSHOpenSSHCertificateV01, True)
+    register_certificate_alg(1, alg, alg + b'-cert-v01@openssh.com',
+                             RSAKey, SSHOpenSSHCertificateV01, True)

 for alg in RSAKey.x509_algorithms:
     register_x509_certificate_alg(alg, True)
```

**Comment by oliviajindi** [comment]
Thanks! Sorry seems having a lot of questions.. But since we don't do the server host key validation, so why it failed when asyncssh does not support the host key algorithem returned by the server? It seems it will skip this part since we disabled it. Or we still exchange the keys and checking the key/cert like algorithm, but we don't validate the key/cert.

Also yeah, I'll test the changes and let you know the result. Thanks a lot!

**Comment by ronf** [comment]
For the SSH connection to work, you still need to finish the key exchange, even if the client chooses not to validate the server's public key or certificate. In this case, it is the server which is giving up on the key exchange, and I'm guessing it is because the server sees that the client listed ssh-rsa certificate authentication as one of the algorithms it supports but that's disabled in the version of OpenSSH you are running. What I don't understand is why the server doesn't just skip that and pick one of the other algorithms the client listed which it supports. That seems like a bug in OpenSSH.

**Comment by oliviajindi** [comment]
Maybe I can make a post on openssh group as well to ask why openssh does not try different algorithms. So `server_host_key_algorithm` is specifying what algorithm the server key/cert is used that the client will accept right?

**Comment by ronf** [comment]
Host key algorithms are actually sent in both directions during the key exchange, with each side telling the other side which algorithms are supported. However, in the end, it's the server that needs to choose which host key to use based on the list of algorithms the client offers. In AsyncSSH, it chooses the earliest host key algorithm in the client's list that the server actually has a matching host key (and certificate, when applicable) for.

Here it seems like the server chooses an algorithm which the server has disabled, instead of just skipping that entry and trying to find a matching host key for a host key algorithm later in the client's list.

You might see if you can reproduce this with OpenSSH on both sides by setting the client's host key algorithm list using something like "-o HostKeyAlgorithms=ssh-rsa-cert-v01@openssh.com,rsa-sha2-512". That seems to be doing the right thing here and automatically choosing rsa-sha2-512, but it'd be interesting to do that same test against your SSH server.

You'll probably need to do this test from a machine with an older OpenSSH client which doesn't disable ssh-rsa by default.

**Comment by ronf** [comment]
Regarding the patch listed above, you can ignore that for now. I've found some issues with it and will provide a new one once I've worked them out.

**Comment by ronf** [comment]
Here's an updated patch:

```patch
diff --git a/asyncssh/rsa.py b/asyncssh/rsa.py
index 2ee35fd..053b7d3 100644
--- a/asyncssh/rsa.py
+++ b/asyncssh/rsa.py
@@ -265,8 +265,9 @@ class RSAKey(SSHKey):

 register_public_key_alg(b'ssh-rsa', RSAKey, True)

-register_certificate_alg(1, b'ssh-rsa', b'ssh-rsa-cert-v01@openssh.com',
-                         RSAKey, SSHOpenSSHCertificateV01, True)
+for alg  in (b'rsa-sha2-256', b'rsa-sha2-512', b'ssh-rsa'):
+    register_certificate_alg(1, alg, alg + b'-cert-v01@openssh.com',
+                             RSAKey, SSHOpenSSHCertificateV01, True)

 for alg in RSAKey.x509_algorithms:
     register_x509_certificate_alg(alg, True)
```

The previous code was already adding the RSA SHA2 variants to the public key algorithms, so the only thing needed here was to add the certificate versions. I think this should be enough to allow the two sides to negotiate an RSA SHA2 host certificate algorithm that's supported by the server, rather than it picking `ssh-rsa-cert-v01@openssh.com` and failing due to that being disabled. However, I still need to set up an environment here to test that this handshake succeeds.

**Comment by ronf** [comment]
Ok - I did some testing here, against a server with ssh-rsa disabled, and I was able to reproduce the "Connection reset by peer" before this change and getting it to work after the change. I'm still not sure why OpenSSH didn't fall back from the disabled certificate algorithm to one of the supported host key algorithms, but with this change that is no longer necessary. After this change, if you have an RSA host key with a certificate on the server, AsyncSSH will be able to use SHA-2 signature algorithms with that key and validate the cert's public key rather than the host's public key in known_hosts.

Thanks for the report on this! I'll be checking this change in shortly, and am hoping to do a release later today if all goes well.

**Comment by ronf** [comment]
This change is now available as commit 85a3cda in the "develop" branch.

**Comment by ronf** [comment]
This change is now available in the AsyncSSH 2.10.0 release. Let me know if it works for you (without having to specify a limited set of host key algorithms).

**Comment by oliviajindi** [comment]
Thanks @ronf ! Let me test it on my side and check if this can fix the issue.

> You might see if you can reproduce this with OpenSSH on both sides by setting the client's host key algorithm list using something like "-o HostKeyAlgorithms=[ssh-rsa-cert-v01@openssh.com](mailto:ssh-rsa-cert-v01@openssh.com),rsa-sha2-512".

I tried this and your are right here, it failed when I added `-o HostKeyAlgorithms=ssh-rsa-cert-v01@openssh.com,rsa-sha2-512` but worked with `-o HostKeyAlgorithms=rsa-sha2-512`

**Comment by oliviajindi** [comment]
Hi @ronf ! The problem is fixed in 2.10.0 version. Thanks a lot for your help! :)

**Comment by ronf** [comment]
Thank you for the confirmation, and for helping me work though this...

**Comment by oliviajindi** [comment]
We opened a report in RedHat https://bugzilla.redhat.com/show_bug.cgi?id=2069495. In case you want to follow up you can check the posts above

**Comment by ronf** [comment]
That's great - thanks for letting me know!
