### ISSUE TITLE
gather_results and hosts details

### ISSUE THREAD

**Issue by albundy83** [ronf/asyncssh#463]
Hello,

first thanks a lot for your great job with this module I have tried many libs and this one has the best support I have seen, especially with complex bash commands :)
Then, my small problem, I use the [gather_results](https://github.com/ronf/asyncssh/blob/develop/examples/gather_results.py) example to run on multiple hosts.
In the [for i, result in enumerate(results, 1):](https://github.com/ronf/asyncssh/blob/develop/examples/gather_results.py#L36) loop at the end to print the tasks status, is it possible to have the hostname of the corresponding host ?
I did not find a way to print it also...
(for information, I use the latest asyncssh 2.10.0 as I was waiting for the fix about known_hosts and ProxyJump [here](https://github.com/ronf/asyncssh/issues/441)).

**Comment by ronf** [comment]
In the gather_results example, there is a "hosts" array which controls which host each of the tasks is connecting to. Since you have the task number in `i`, you could use that to get back to the host. However, since the example has `i` starting from 1 instead of 0, the corresponding host in each case would be `host[i-1]`. You could add that to the status it outputs.

**Comment by albundy83** [comment]
Ah yes, thanks a lot, it works perfectly :)
