### ISSUE TITLE
Reading `~/.ssh/known_hosts` runs on every connection

### ISSUE THREAD

**Issue by qix** [ronf/asyncssh#47]
The library I've been working on connects to a large number of hosts simultaneously which seems to break the asyncssh `known_hosts` reading implementation. As far as I can tell it's designed to scan through and decode the entire file for every connection -- which causes obvious problems.

I don't know if you want to try cache the scan internally, or if you'd rather I passed in the `known_hosts` variable into `create_connection`... at which point the `known_hosts._parse_entries` function should be properly exposed.

**Comment by ronf** [comment]
If you are connecting to the same host repeatedly and you know the known hosts list isn't changing, my recommendation would to be make your own call to match_known_hosts() to get back the keys and then store those on a per-host basis. On each new connection, you can pass in that tuple of (host_keys, ca_keys, revoked_keys) in place of a file name or known hosts byte string and AsyncSSH will use them without doing the matching again.

It would be difficult to automatically cache this information. A separate result would have to be cached for each host/addr/port combination that is passed in. Also, since the file can change at any time, it would be necessary to read the file (or at least do something like a stat to check the timestamp) to know when the cache needed to be invalidated. In the end, I'm not sure there would be enough value out of doing the caching to justify it in the typical use case.

**Comment by qix** [comment]
I don't think using `match_known_hosts` will help. The problem I'm experiencing is due to `match_known_hosts` being far too slow to run on every `host/port` pair.

Just submitted pull request #48 which seperates the parsing so that it only needs to be done once.

**Comment by ronf** [comment]
Ok - I see what you're looking for now, but I must admit I'm a bit surprised that the parsing operation was take a noticeable amount of time compared to the matching. Have you done any timing tests on this, or could you provide a sample known_hosts file I could use to explore this a bit more? Since the match function is where it calls things like fnmatch() multiple times on each entry and it scans all of the entries linearly every time, I would have expected that to be where most of the time went.

That said, I'm happy to consider a split like this, but I'd probably name things a bit differently to be more consistent with the rest of the API. I'm thinking of having import_known_hosts() and read_known_hosts() functions to parse known hosts data from a string and a file, respectively. Both of these would return an SSHKnownHosts object with a match() method that would do the matching against the parsed data. I'd then have match_known_hosts() allow create_connection()'s known_hosts argument to take an SSHKnownHosts as another option, in which case it would use the parsed data and only do the match call.

On another note, what sort of entries are in your known_hosts file? If you're always matching on exact hostnames or IP addresses, you could make things a LOT faster on the matching if you used something like a dictionary lookup to do the match instead of calling match_known_hosts() and walking the list linearly. That's not something I can easily do generically given the rules of matching known_hosts entries, but an application could if it knew it didn't need to do pattern-based matches.

**Comment by ronf** [comment]
I've just checked in a first cut of what I described above in 133ce51.

**Comment by ronf** [comment]
I've been thinking about the exact match issue overnight, and I think there is something more I can do here. I just need to check each host entry at parse time to see if it is a pattern match or not. For those that aren't, I can pull them into a dictionary and make the lookup much faster, only needing to linearly walk over the subset of the entries with some kind of wildcard, CIDR, or negative match in them.

 I'll try and prototype this when I get home from work tonight.

**Comment by ronf** [comment]
Commit 44349b7 contains my first cut at implementing optimized exact match host and address lookups.

I did some basic timing tests using a known_hosts test file with 1023 entries in it. Each entry contained two patterns (a host name and an IP address).

Before this optimization, calling match_known_hosts() by passing in the file name (so it was loaded each time) took about 90 msec per lookup, When breaking that into a separate call to read_known_hosts() first followed by match_known_hosts(), the initial read took about 45 msec and each lookup took another 45 msec. So, commit 133ce51 which allowed loading the file only once basically cut the time in half.

Commit 44349b7 reduced the cost of read_known_hosts() from 45 msec to about 10 msec, which was a nice improvement I wasn't expecting. Apparently creating the various objects needed by the HostPatternList class is pretty expensive. However, the much more important number was the cost of match_known_hosts() once the file was parsed. This commit reduced the matching time from 45 msec to about 1.9 usec on this 1023 line known_hosts file -- about 24,000 times faster!

If the known hosts file has a mix of exact match and wildcard/CIDR/hashed entries in it, the speedup won't be quite as dramatic as this, but it will essentially make all of the exact match lookups nearly free, and you'll only pay the cost of matching on the other patterns.

**Comment by ronf** [comment]
The changes described here are now available in the AsyncSSH 1.5.1 release.
