### ISSUE TITLE
Trouble with cryptography 2.8

### ISSUE THREAD

**Issue by xoffey** [ronf/asyncssh#470]
On some ubuntu 20.04 machines, I get a TypeError "private_key() missing 1 required positional argument: 'backend"".

It is "fixable" by upgrading cryptography package, but maybe asyncssh should require a newer version of cryptography.

Before upgrade:
asyncssh in /home/xxx/.local/lib/python3.8/site-packages (2.10.0)
cryptography>=2.8 in /usr/lib/python3/dist-packages (from asyncssh) (2.8)

Then:
pip3 install --user --upgrade cryptography
...
Successfully installed cffi-1.15.0 cryptography-36.0.2 pycparser-2.21

**Comment by ronf** [comment]
Sorry for the trouble - It turns out that a change made in AsyncSSH 2.10.0 actually depends on a newer version of cryptography than I realized. You need to update the dependency to cryptography version 3.1 to pick up changes where the "backend" argument is no longer required. See #465 and #467 for details.

This dependency change is fixed in the "develop" branch as commit e0da30a, and will be included in the next release.

**Comment by ronf** [comment]
This dependency has been updated in the AsyncSSH 2.10.1 release.
