### ISSUE TITLE
Recursive SFTPClient.glob error handling

### ISSUE THREAD

**Issue by LuckyDams** [ronf/asyncssh#474]
Hi,

In current version (Asyncssh 2.10.1), SFTPClient.glob() error_handler is managed globally. With recursive pattern '**', it would break the task and return partial result. I am looking for a solution to permit the task to continue on SFTPError exception(s) authorized by error_handler. 

My concrete case is about dealing with directories with no read/access permission in a recursive search using glob().

Consider following code:
```python
import asyncio, asyncssh, sys

async def run_client() -> None:
    async with asyncssh.connect('localhost', username='other') as conn:
        async with conn.start_sftp_client() as sftp:
            files = await sftp.glob('test/**/*', error_handler=permission_handler)
            for file in files:
                print(f"File found: {file}")

def permission_handler(err):
    if isinstance(err, asyncssh.SFTPPermissionDenied):
        pattern = getattr(err, 'srcpath', b'').decode()
        print(f"ERROR: SFTP Permission Denied with pattern '{pattern}' !")
    else:
        raise err

try:
    asyncio.run(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SFTP operation failed: ' + str(exc))
```

In a path tree with following permissions:
```
drwxr-xr-x]  test
├── [-rw-r--r--]  good_file
├── [-rw-------]  bad_file
├── [drwx------]  bad
│   ├── [-rw-------]  bad_file
│   └── [-rw-r--r--]  good_file
└── [drwxr-xr-x]  good
    ├── [-rw-------]  bad_file
    └── [-rw-r--r--]  good_file
```

Running above code as a non-owner (user with group or other permissions) would produce following output:
```
ERROR: SFTP Permission Denied on pattern 'test/**/*' !
File found: test/good_file
File found: test/bad_file
File found: test/bad
File found: test/good

Process finished with exit code 0
```

In this example we are missing files from 'good' directory. Result may differ depending on which order sub-directories are accessed.

In my specific case, it seems issue is due to listdir() call made in [sftp.py:_glob](https://github.com/ronf/asyncssh/blob/a89241a778b09e117cd5673acbd3d7bc38b90468/asyncssh/sftp.py#L639) function. A possible workaround would be to enclose listdir() in try/except clause and pass error_handler from parent function to manage exceptions at this level. Please see a quick and dirty proof of concept [here](https://gist.github.com/LuckyDams/a4c2c620930f601a4fb797edd8819a87).

Would it be possible to implement a solution to manage errors with recursive glob() patterns ?
(better and more generic than my quick fix)

I assume this is an arguable discussion with pros & cons... 
However implementing a manual solution for recursive search would be painful. Also in current situation, it is quite difficult to define which path has caused the issue. Exceptions from glob() is only returning current pattern (srcpath). Only logging at DEBUG level would help to find it.

Not same topic but having a glob iterator we can use in "async for" would be a great feature for long sub-trees and/or long list of patterns. (I have seen this [comment](https://github.com/ronf/asyncssh/issues/332#issuecomment-748533577) which sounds interesting).

Don't be mistaken, I really like Asyncssh. Nice design, simple to use, good doc, great works !

**Comment by LuckyDams** [comment]
Please find diff of changes made to sftp.py to catch listdir() exceptions in _glob() function:
(used in previous mentioned [fix](https://gist.github.com/LuckyDams/a4c2c620930f601a4fb797edd8819a87))

``` diff
diff --git a/asyncssh/sftp.py b/asyncssh/sftp.py
--- a/asyncssh/sftp.py	(revision 9cbf2337c5cfd643592b5cfbe113055e7b084084)
+++ b/asyncssh/sftp.py	(date 1651129967477)
@@ -631,13 +631,25 @@
 
 
 async def _glob(fs: _SFTPGlobProtocol, basedir: Optional[bytes],
-                patlist: Sequence[object], result: List[bytes]) -> None:
+                patlist: Sequence[object], result: List[bytes], 
+                error_handler: SFTPErrorHandler = None) -> None:
     """Recursively match a glob pattern"""
 
     pattern, newpatlist = patlist[0], patlist[1:]
-
-    names = await fs.listdir(basedir or b'.')
+    
+    try:
+        names = await fs.listdir(basedir or b'.')
+        
+    except (OSError, SFTPError) as exc:
+        setattr(exc, 'srcpath', pattern)
+        setattr(exc, 'basedir', basedir)
 
+        if error_handler:
+            error_handler(exc)
+            return 
+        else:
+            raise
+
     if isinstance(pattern, list):
         if len(pattern) == 1 and not pattern[0] and not newpatlist:
             result.append(basedir or b'.')
@@ -651,11 +663,11 @@
                 if not newpatlist:
                     result.append(newbase)
                 else:
-                    await _glob(fs, newbase, newpatlist, result)
+                    await _glob(fs, newbase, newpatlist, result, error_handler)
                 break
     else:
         if pattern == b'**':
-            await _glob(fs, basedir, newpatlist, result)
+            await _glob(fs, basedir, newpatlist, result, error_handler)
 
         for name in names:
             if name in (b'.', b'..'):
@@ -672,9 +684,9 @@
 
                     if attrs.type == FILEXFER_TYPE_DIRECTORY:
                         if pattern == b'**':
-                            await _glob(fs, newbase, patlist, result)
+                            await _glob(fs, newbase, patlist, result, error_handler)
                         else:
-                            await _glob(fs, newbase, newpatlist, result)
+                            await _glob(fs, newbase, newpatlist, result, error_handler)
 
 
 async def match_glob(fs: _SFTPGlobProtocol, pattern: bytes,
@@ -687,7 +699,7 @@
     try:
         if any(c in pattern for c in b'*?[]'):
             basedir, patlist = _split_path_by_globs(pattern)
-            await _glob(fs, basedir, patlist, names)
+            await _glob(fs, basedir, patlist, names, error_handler)
 
             if not names:
                 exc = SFTPNoSuchPath if sftp_version >= 4 else SFTPNoSuchFile
```

**Comment by ronf** [comment]
Thanks for the suggestion, and proposed implementation! I like the idea, and the change looks pretty clean.

I'm in the middle of migrating over to a new computer here at home, so it may take me a bit of time to get to this, but I'll try to get this in soon.

I also like the idea of adding an async iterator for glob(). This could be called iglob(), to match the naming in the "glob" package. I think this should be straightforward. Similar to scandir(), the iterator would just need to yield values one name at a time as it found matches, rather than appending them to a passed-in result list which only gets returned at the end.

To avoid duplicating code, it'd probably make sense to make the existing glob() use the iglob() async iterator to get the results, similar to what the code currently does with readdir() calling scandir(). This would probably mean changing the internal functions to also be async iterators.

This may require an "yield from" to properly return results on the recursive calls, but hopefully that works for async iterators now that the new async/await syntax has replaced using "yield from" as a form of "await".

**Comment by LuckyDams** [comment]
Hi ronf,

Thanks for your reply. I am really excited about iglob() idea. I would definitely let it yield SFTPName object as now it would be possible using scandir(). It would be a great feature, not only because of async iterator but also because of its more atomic nature (single operation instead of subsequent stat() call as in current _glob(). In my current usage, I am also doing a stat() operation on files returned by glob() and was a little worry about doing 3 stat() operations per file. I believe it is a common case to use stat() on result from glob() when you need to compare files size or mtime.

This let me also think about multi patterns case (list of patterns to glob()): current implementation iterate over each patterns one after the other and go for full readdir, stat,... to build result for each. By the way if we have overlapping patterns, we get duplicates (same file) returned from glob. 
I was wondering if it would make sense to try to reduce patterns list at first by looking for common base. I would assume most usage are about looking for different files in same base directory. Typical case like "all music files in my collection" which would be patterns list similar to: /media/\*\*/\*.mp3, /media/\*\*/\*.flac, ...
In this case figuring out we have same base /media and doing single recursive dir read and iterate over patterns difference for fnmatch would be a clear improvement in term of operations required (and times). But maybe quite tricky and not always possible.

Take times to rebuild your env. I will be out of my computer for few days also...

**Comment by ronf** [comment]
Thanks - having a version of glob() which returns SFTPName objects does sound like it could be helpful both internally and externally. To better mirror the glob module semantics, I'm thinking it'd be best to do this as new methods named something like globname() and iglobname(), and then have methods glob() and iglob() which use iglobname() internally but return just the names. Callers would then have their choice of which to use depending on if they wanted the stat information or not, and if they wanted the data as an iterator or not.

Regarding looking for common bases, one thought on that would be to memoize the directory listings as they happened. So, the iterator would still return all the entries from the first pattern before moving on to the second pattern, but if there were any common directories in later patterns it could keep around the result of those listings in memory and use them instead of requesting a directory listing multiple times. A similar approach could be used to eliminate duplicate results from being returned. The only downside is that this eliminates one of the benefits of having the iterator, which would be reduced memory usage by not having to keep those intermediate results in memory. Perhaps there could be an argument to enable/disable this behavior, though, giving the caller a choice. The benefit here is enough to probably enable this by default, especially since the current code already keeps full directory listings in memory, at least long enough to fully evaluate each subtree.

**Comment by ronf** [comment]
Sorry for the delay on this. I actually started on it last weekend, but realized that replacing listdir with scandir or readdir might not be the best approach. Right now, the code only calls stat() on a small fraction of the files it gets back from listdir, and I think I might be able to reduce the need for that even further. So, asking the FTP server to return attributes for all of the files in every directory it matches against may not be the best option. 

I can probably still offer an iterator version of glob, and possibly do something to either cache previous directory listings or group them in some way to avoid calling listdir() multiple times on the same parent dir. If I keep previous results, I can also eliminate duplicates. It's going to take a bit more time to figure out the best way to do all of that, though. I'll let you know when I have something.

**Comment by LuckyDams** [comment]
Thanks for the update. 
I do understand implementing such glob iterator would need times. I was first thinking about reducing patterns when possible until I realized how it would be complex (and probably inefficient). Memorization is probably best approach also because it would help to avoid duplicates but as you said there are concerns about memory consumption. No sure to get all about your last comment and would probably need to spend more times on asyncssh code. 

Would it be possible to implement error handler in _glob for recursive search at least ? This was initial call for this issue and probably the most impacting (at least in my case).

**Comment by ronf** [comment]
I actually made good progress on this yesterday, and figured out a way to leverage readdir (which I may eventually turn into scandir) to reduce some of the need for separate stat() calls. I also eliminated some of the stat() calls entirely. I was worried that returning attributes for all the entries in each scanned directory might be costly, but then I remembered that listing a directory over SFTP actually always returns the attributes, and listdir() just ends up throwing them away. So, the cost of returning the attributes is already there and I might as well leverage them whenever I can.

Regarding the error handler, I actually realized that my existing implementation of glob() was far too aggressive about returning errors. To better match Python's glob module for local files, I really shouldn't be aborting with things like a "no such file" or "permission denied" error when doing a listdir() or stat() in an intermediate step. I'm keeping the error handler for more serious errors or for when the result of a whole pattern lookup fails to return anything as I depend on this behavior in things like mget/mput/mcopy, but I think eliminating the early error return will cover most of the original cases you needed this for and be useful to everyone even when they don't pass an error handler in.

I'm willing to consider passing in the error handler to _glob() to handle intermediate errors when it is something other than a "no such file" or "permission denied" error if you have a need for that, but I'd recommend taking a look at the new version I have before you decide.

Breaking this up into multiple steps is a good idea. I'm thinking I can probably do the variants which return SFTPNames and support async iterators first along with better compatibility with Python's glob() but without the memoization, and go back and add that in another round. I may do the duplication detection in the first pass, as I have an idea about how to do that fairly easily leveraging some of the code that's already there.

**Comment by LuckyDams** [comment]
This sounds promising. It was my understanding SFTP returns stat and all dir listing methods are based on scandir(). I confirm "no such file" & "perm denied" errors are the only cases I have seen so far and will cover my need and probably most of everyone.

**Comment by ronf** [comment]
Ok - commit 3d6740c in the develop branch is a first cut at this. It has the error handling changes where it won't call the error handler when a partial match is non-existent or inaccessible. It also provides a new glob_sftpname() call which will return SFTPNames with attributes for each of the matching files, avoiding the need for the caller to do a stat(). Internally, it has also been switched to use scandir() instead of listdir() to get attribute information on possible matches without separate calls to stat(). The exact-match parts of the glob are also handled much more efficiently, with a single call to stat() for multiple levels of directories, without ever retrieving the contents of those directories.

This version includes code to eliminate duplicates in the result, but doesn't yet do the memoization to avoid fetching directory listings multiple times when multiple patterns examine the same directories. I'll be adding that in a second pass.

Unfortunately, I discovered as part of this work that Python's async generators don't support "yield from", making it more difficult to provide the iglob() and iglob_sftpname() functions I was hoping to provide which returned async iterators. So, even though the directory listings are processed incrementally when doing the matching, the list of matches is only returned in its entirety when matching completes. I may revisit that later, but the code to do that probably won't be pretty.

**Comment by LuckyDams** [comment]
Really nice implementation with new `SFTPGlob` class. 

'No matches found' exception is now returning plain path portion value in 'srcpath' attribute instead of pattern value (in contrast with previous implementation). This makes sense but in case of multiple patterns, we are missing which pattern is raising this error.  My suggestion is to add a new 'pattern' attribute here (see #481).

As mentioned in previous comment, non-existent or inaccessible partial match are now silently ignored to better match Python glob. However in case of non-existent or inaccessible plain path portion of a pattern, we still raise such error. Is it expected behavior or should they be included in 'No matches found' error case ?

From initial example, using pattern such as 'test/not_exist/*' will return `SFTPNoSuchFile` error. This is related to initial stat() performed in SFTPGlob.match(): https://github.com/ronf/asyncssh/blob/8e2192e2b8447221d96fd10c9b7525e63d5297b1/asyncssh/sftp.py#L2141

**Comment by ronf** [comment]
Regarding the failure on the initial stat(), my original thinking was that an error there would always end up resulting in no matches, so I could just use the existing exception rather than catching it and raising a new one. However, I didn't take into account that this would mean 'srcpath' wouldn't be set in that case, and the inconsistent message depending on whether you search for "/test/not_exist" vs. "/*/not_exist" is probably not a good thing. I'll fix it in the next round so that "No matches found" is returned in that case.

**Comment by ronf** [comment]
Actually, looking more closely, 'srcpath' is set correctly in this case, so the only issue is around whether to replace the message or not. However, I'll see what I can do there. Once I add the caching, some of the error handling will need to be done differently.

**Comment by ronf** [comment]
Ok - commit 177c878 adds directory and stat caching and should make the handling of the initial pattern exact match consistent with later stat errors. It also fixes an error related to duplicate results incorrectly returning "No matches found" in some cases.

**Comment by LuckyDams** [comment]
Great work there, well done !

'No matches found' is now returned in all cases (no pattern match but also no such file or permission denied with stat on plain path portion). This would simplify error handler implementation for glob.

Caching should have a clear improvement in execution time for overlapping patterns. 
As it is actually based on dict, it could cause some issues in terms of memory consumption. What about using Python [lru_cache](https://docs.python.org/3.9/library/functools.html#functools.lru_cache) or kind of where we could set a limit or even disable it ? 
Not sure LRU is best caching technique for file trees, maybe LFU (Least Frequently Used) from [cachetools](https://cachetools.readthedocs.io/en/latest/index.html#cachetools.LFUCache) would be a better fit. Another round for future developments...

Just a last semantic question about 'srcpath' attribute in glob exception: why not using 'pattern' instead ? It could cause confusion as 'srcpath' is also used in 'copy' and its derived methods. I am not sure about terminology/definition, but does a glob pattern can be considered as a file path ?

**Comment by ronf** [comment]
I thought about potentially limiting the total size of the cache in some way, but the cache has a very limited lifetime (just a single glob expansion), so I'm not sure in practice if the overhead to maintain the ordering of the cache to allow for choosing which element to delete is actually worth the cost (in both memory and CPU). I could provide a way to disable it completely if someone needed that, but you'd have to be scanning a REALLY big filesystem in your glob expansion to actually end up using significant memory here, and even that may be over-designing this until there's a clear need for it.

I had similar feelings about the duplicate detection, which also uses additional memory, considering whether there should be an option to disable that or not. However, disabling it would mean that duplicates might appear again, which is probably something no caller would ever want. If they did, they could always submit the patterns to glob() one at a time. I suppose I could put in an optimization to disable both features in the case where only a single pattern is passed in, as I don't think there's any case where either caching or duplicate detection is useful in that case.

Regarding the 'srcpath' name, that was actually designed to match the name in calls like mget/mput/mcopy, as the glob expansion is shared by both the glob() method and these calls. In those calls, there is an argument called 'srcpaths' which passes in the set of paths (some of which may be glob patterns), and any errors which occur in the copy will end up calling the optional error handler with the fields 'srcpath' and 'dstpath'. Since the glob expansion in those cases is operating on the 'srcpaths' argument, it made sense to me to also use 'srcpath' for reporting errors in the glob expansion. This doesn't completely align if you call glob() directly (where the argument is called 'patterns'), but I didn't want to complicate things by trying to name this differently depending on which method invoked it.

**Comment by ronf** [comment]
I took a closer look tonight at the optimization I mentioned above. It looks like it's not quite as simple as I thought. Even in the single pattern case, there are cases with '**' where the same directory can be scanned more than once, with different items in the remaining pattern list. So, even for a single pattern, there is value in the caching since every directory before a '**' and all of the subdirectories under it are all visited twice. It's important to do the duplicate detection as well, or else some matches will show up twice.

Since the primary purpose of the second scan is to find all subdirectories but just apply two different sets of remaining patterns, there may be a way to avoid that double scanning, but I'll need to think about that some more.

**Comment by LuckyDams** [comment]
Thanks for the explanations.
Did some testing around cached glob and getting significant perf factors over previous version (as expected). Will not share numbers here as it mostly related to your environment... Best benefit is to get extra patterns for free if they are using same files tree. Regarding memory consumption, I have a rough estimate of ~2k per item (file path information) for all caches (scandir, stat, prev & new matches). I agree this would probably feet with most user cases. However from my understanding only `SFTPGlob._prev_matches` is required for duplicate detection which is the lower memory consumer. So maybe having a switch to disable other caches would be enough.

For this required cache for duplicate detection (SFTPGlob._prev_matches), I would suggest to use hash of path values. This would reduce memory footprint even further, and from my testing the cost of hashing is lower than improved lookup benefit. The change would be simple as:
```python
    def _report_match(self, path, attrs):
        """Report a matching name"""

        self._matched = True
        _path_hash = hash(path)

        if _path_hash not in self._prev_matches:
            self._prev_matches.add(_path_hash)
            self._new_matches.append(SFTPName(path, attrs=attrs))
```

Another suggestion is about path normalization, in actual implementation using patterns like 'test/*' with './test/*' would produce distinct (duplicate) in glob() (and its caches):

```
>>> test_glob(["test/good_*", "./test/good_*"])
DEBUG: prev_matches: 2 items, 0.28 kb
DEBUG: new_matches: 1 items, 10515.47 kb
DEBUG: stat_cache: 2 items, 10515.97 kb
DEBUG: scandir_cache: 2 items, 10522.24 kb
Execution time: 0.271 seconds
File found: test/good_file
File found: ./test/good_file
Files count: 2
```

A solution can be implemented using posix.normpath():
```python
    async def match(self, pattern: bytes,
                    error_handler: SFTPErrorHandler = None,
                    sftp_version = MIN_SFTP_VERSION) -> Sequence[SFTPName]:
        """Match against a glob pattern"""

        self._new_matches = []
        self._matched = False

        _normalized_pattern = posixpath.normpath(pattern)
        path, patlist = self._split(_normalized_pattern)
...
```
But this is only for `SFTPGlob` class, as I don't know implication in other parts of code, I will let you decide if it is suitable.

**Comment by ronf** [comment]
Regarding normalization, I'd prefer to leave that to the caller. If they pass in something like "./foo*", it makes sense to me to return results with the "./" intact. This is consistent with how Python's glob.glob() currently behaves. If you pass in a normalized pattern, the glob implementation should always return normalized paths as well, as that would never add a '.' or '..' component into the set of matching paths. As such, the caller can avoid getting duplicates if they're careful to have all of their input patterns consistent with one another (normalized or not).

On that note, though, I noticed that glob.glob() does something a bit odd with '**' at the end of pattern, and I'm wondering whether I should mimic this or not. Consider a tree which looks like:

```
dir1/
        file1
        file2
dir2/
        dir3/
                file3
        file4
```

If you match on something like `/dir*/**/*3`, you get back `['dir2/dir3', 'dir2/dir3/file3']`, which makes sense. Similarly, you can match on only directories with the pattern `/dir*/**/`, which returns `['dir1/', 'dir2/', 'dir2/dir3/']`. So far, so good!

However, if you match on `/dir*/**`, you get back `['dir1/', 'dir1/file1', 'dir1/file2', 'dir2/', 'dir2/dir3', 'dir2/dir3/file3', 'dir2/file4']`. Note the entries for `dir1/` and `dir2/` there, along with the various subdirectories and files. It sort of makes sense if you believe `**` is allowed to match on an empty string. It does make sure the prefix exists, so matching on something like `dir1/xxx/**` will return no matches. However, I think it goes a bit off the rails when you match on `/dir1/file1/**`, as that returns `['dir1/file1/']`, even though `file1` is not a directory and referencing `dir1/file1/` actually raises a "Not a directory" error. I would expect that to return an empty match.

My question is how much of this behavior should I preserve. I definitely like the behavior when a pattern ends in `/` (including `**/`) as a way to only return directory matches. However, should I allow `**` to match on an empty string, or only return files and subdirectories under whatever the prefix of `**` matches but not the prefix itself? If I do return the prefixes, should I keep the trailing slash only for those like glob.glob() does or should I report the prefix without a trailing `/`, more like the way it reports all the other files and subdirectories which match?

I'm definitely not going to preserve the `/dir1/file1/` result, as I consider that to be a bug.

I'm also still working on whether I can avoid scanning a directory multiple times when `**` is used, but that's turning out to be harder than it sounds.

**Comment by LuckyDams** [comment]
Basically you would need to choose which `glob` behavior you want to comply with....

From my understanding `asyncssh` behaves the same as Python `glob.glob` with `recursive=True` argument which is looking to match shell (bash) filename expansion where  `recursive=True` whould be equivalent to enabling `globstar` shopt. You probably know `pathlib.Path.glob` is having a different interpretation of '**' (also notice path normalization).

```python
>>> from glob import glob
>>> from pathlib import Path
>>> HERE = Path('.')

>>> glob('./dir*/**')
['./dir2/dir3', './dir2/file4', './dir1/file2', './dir1/file1']

>>> glob('./dir*/**', recursive=True)
['./dir2/', './dir2/dir3', './dir2/dir3/file3', './dir2/file4', './dir1/', './dir1/file2', './dir1/file1']

>>> [ f"{p}" for p in HERE.glob('./dir*/**')]
['dir2', 'dir2/dir3', 'dir1']
```
```bash
$ shopt -u globstar
$ list=(./dir*/**); echo ${list[@]}
./dir1/file1 ./dir1/file2 ./dir2/dir3 ./dir2/file4

$ shopt -s globstar
$ list=(./dir*/**); echo ${list[@]}
./dir1 ./dir1/file1 ./dir1/file2 ./dir2 ./dir2/dir3 ./dir2/dir3/file3 ./dir2/file4
```

In `/dir1/file1/**` case, Python `glob.glob` behaves the same as you mentioned. I do agree this is a mistake compared to bash shell behaviors with depends of your [shopt settings](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html) ( `nullglob` &  `failglob`).

```python
>>> glob('./dir1/file1/**')
[]

>>> glob('./dir1/file1/**', recursive=True)
['./dir1/file1/']

>>> [ f"{p}" for p in HERE.glob('./dir1/file1/*')]
[]
```
```bash
$ list=(./dir1/file1/**); echo ${list[@]}
./dir1/file1/**

$ shopt -s nullglob
$ list=(./dir1/file1/**); echo ${list[@]}

$ shopt -s failglob
$ list=(./dir1/file1/**); echo ${list[@]}
-bash: no match: ./dir1/file1/**
```

By default, bash is returning pattern value when no expansion occurred (no match) while Python `glob.glob` with `recursive=True`  is returning a non existing path (I believe this is an open [issue](https://github.com/python/cpython/issues/79382)).

A said at first, it is really about which `glob` behavior we want. I would probably continue to comply with Python built-in. `glob.glob` is the closest match with shell filename expansion but I like `pathlib.Path.glob` (simplified) behaviour: '**' is only for directories and sub-directories. So should we wait for a fix in `glob.glob` or fix it now in `asyncssh` ?
I believe the fix is about avoiding to add the plain portion of a pattern in result if we have no match on pattern portion (`posixpath.join(path, *pattern)` ?).

Thinking back to error handler for glob(), why not having a specialized optional argument to mimic  `nullglob` &  `failglob` shell shopts which could be called 'no_match_fail' and behaves like this:
- if `callable(no_match_fail)`: behave the same as current error handler,
- if `no_match_fail=True`: raise 'no match' error on first occurrence,
- if `no_match_fail=False`: ignore 'no match' pattern(s) and return empty result.  

Would default to True to match current glob() behavior.

I know current error handler can raise any `OSError` or `SFTPError` exceptions but it is mostly here to manage  'no match' case. Maybe it can be kept for other corner cases (even if I don't have any real use case in mind).

**Comment by ronf** [comment]
Thanks for the additional research here! I knew about the version of glob in pathlib, but didn't specifically test out how it compared with glob.glob().

It's interesting that pathlib chooses to normalize the path, but given both glob.glob() and shells typically don't do that, I think I'd rather stick to passing through any unnormalized prefix. However, fixing the bad behavior in the dir/file/** case seems like a good idea given pathlib and shells already do that "right" and a fix may be coming for glob.glob() to do so as well.

That leaves the question about whether to add a trailing slash when returning the initial directory when the pattern ends with "/**".  Given that both pathlib and shells seem to return that initial directory without the trailing slash and all other matches are returned without a trailing slash in all three cases, not adding the slash is probably the best option. Note that this is only an issue when the pattern ends with "/**". Otherwise, it continues to match the remainder of the pattern and any behavior around trailing slashes is consistent for all the matches returned.

On the nullglob/failglob thing, you can already do something like nullglob by simply creating an "empty" error handler which never raises an exception, and you already get the equivalent of failglob by default when not providing an error handler. So, I don't think any changes should be needed there. I could alias something like `False` to be treated the same as an error handler that does nothing on errors, but I'm not sure that adds much value and it complicates the code and the typing. Also, as you mentioned, the current error handler will be called on errors that are not related to file not found or permissions issues in scandir/stat, so I think it is best to pass in an error handler which is given the exception as an argument so it can be selective about what it ignores and what it re-raises.

On your last question, I really didn't look closely at the implementation of either the glob or pathlib modules originally. I was already familiar with `**` from zsh and used it all the time, so I added support for that even though glob.glob() didn't have the recursive option yet, and I'm not sure I knew that pathlib supported that. It was quite new at that time.

Regarding avoiding scanning a directory multiple times, it would mostly be an optimization. If I can do it without complicating the code too much though, it might mean I could disable the storage of directory listings when only a single pattern is being matched. It might also mean I could disable the storage of previous results for duplicate detection, as long as I only ever add any given element of a directory to the results once when there's a match.

**Comment by ronf** [comment]
Hmm - I just did some additional testing against pathlib, and it appears there's a much more significant difference between it and glob.glob() when it comes to `**`. In pathlib, that only seems to match on directories. So, in my example tree above, doing a `pathlib.Path().glob('dir*/**')` returns only `['dir1', 'dir2', 'dir2/dir3']`, and none of the files. To return both directories and files in pathlib, you have to pass in something like `'dir*/**/*'`.

I think leaving out the plain files would be too much of a change from current behavior. So, I'm going to stick with returning both directories and files, but without the trailing slash on the initial matches. In other words, instead of glob.glob()'s return of `['dir1/', 'dir1/file1', 'dir1/file2', 'dir2/', 'dir2/dir3', 'dir2/dir3/file3', 'dir2/file4']` with inconsistent trailing slashes, I'll be looking to return `['dir1', 'dir1/file1', 'dir1/file2', 'dir2', 'dir2/dir3', 'dir2/dir3/file3', 'dir2/file4']`.

The good news here is that all the implementations seems to consistently return the above list when the pattern ends in `/**/*` instead of just `/**`. They're also consistent with one another when the pattern ends in `/**/`, returning only directories in that case, all with trailing slashes (`['dir1/', 'dir2/', 'dir2/dir3/']`). So, this isn't an issue if you just avoid ending the pattern in `/**`.

The updated code is now available in commit bb0adbd.

**Comment by ronf** [comment]
Just to be clear, to get the equivalent of what is returned when matching on `dir*/**`, you'd actually have to match on two patterns: `dir*` and `dir*/**/*`. This returns consistent results between glob.glob() and pathlib's glob, as well as the results now returned by AsyncSSH. However, AsyncSSH lets you use the shorter single pattern if you want both directories and files.

**Comment by LuckyDams** [comment]
Still exploring corner cases...

```bash
$ shopt -s globstar failglob

$ find .
.
./dir1
./dir1/file1
./dir1/file2
./dir2
./dir2/dir3
./dir2/dir3/file3
./dir2/file4

$ echo ./**/../file*
./dir2/dir3/../file4
```

Glob result from `asyncssh.SFTPClient`:

```python
>>> test_glob('./**/../file')
['./../*', './dir1/../dir1', './dir1/../dir2', './dir2/../dir1', './dir2/../dir2', './dir2/dir3/../dir3', './dir2/dir3/../file4']
```

'./../*' are paths from parent directory where glob() is running !

**Comment by ronf** [comment]
A couple of more updates tonight (b3ef264 and e2bac91) further optimize glob matching by never attempting to add a given match more than once while matching on any given pattern. So, matches with only one pattern no longer need to take up CPU and memory to store and check against previous matches. This code will now only be active when you pass multiple patterns into a glob or get/put/copy call.

Regarding ".." in a pattern, I was not able to reproduce the results here. While it's true that it can match on things above the "." directory when you match on "./**/..", that actually matches sense, as "./**" matches on "." in addition to subdirectories, so ".." on that will provide access to files in the parent directory of ".".

That said, your match was on "./**/../file*", so all the matches should end in something that matches "file*". In my test here, I used the tree I mentioned above, but with "file0" added to the top level:

```
file0
dir1/
        file1
        file2
dir2/
        dir3/
                file3
        file4
```

I then matched on `dir*/**/../file*` and got back `['dir2/../file0', 'dir2/dir3/../file4', 'dir1/../file0']`. This matches what I see with zsh:

```shell
$ echo dir*/**/../file*
dir1/../file0 dir2/../file0 dir2/dir3/../file4
```

I get the same result with bash on Linux, when I do "shopt -s globstar failglob" first.

**Comment by LuckyDams** [comment]
Thanks for the update. Test with "./**/../file*" was my mistake. This is why I have removed my comment.

**Comment by ronf** [comment]
Sounds good. I thought you had removed the comment yesterday as it wasn't showing up even though I got e-mail about it, but then it re-appeared again last night. I guess there was some sync issue between Github's back-end servers.

**Comment by ronf** [comment]
All the changes discussed here are now available in the AsyncSSH 2.11.0 release. Thanks again for your help on this, @LuckyDams !

**Comment by LuckyDams** [comment]
Great announcement to have it included in last release. 
Was a pleasure discussing this topic. Thanks again for all works made around this new SFTP glob.

**Comment by ronf** [comment]
Any time - it was great working with you on it...
