### ISSUE TITLE
Py3.5 async/await + sftp.posix_rename = TypeError: object generator can't be used in 'await' expression

### ISSUE THREAD

**Issue by sisoftrg** [ronf/asyncssh#51]
While converting some of my code to new async syntax I'm got the following exception:
```py
    await sftp.posix_rename(tmp, "/etc/test.conf")
TypeError: object generator can't be used in 'await' expression
```

Snippet of problem code:
```py
        with (await asyncssh.connect(addr)) as conn:
            with (await conn.start_sftp_client()) as sftp:
                tmp = "/tmp/{}.cfg".format(randint(1e8, 1e9))
                cfg = await sftp.open(tmp, 'w')
                await cfg.write('\n\n'.join(config) + '\n')
                await cfg.close()
                await sftp.posix_rename(tmp, "/etc/test.conf")
```

After some googling I found similar (resolved) problem: https://github.com/aio-libs/aiomcache/issues/7

I think that problem can be resolved by adding missing ``@asyncio.coroutine`` decorator to ``posix_rename`` method  (and may be some others).

**Comment by ronf** [comment]
In Python 3.4, it was legal for a regular function to "return" a coroutine (without doing a "yield from" on it), allowing a caller to yield from that function as if it were itself a coroutine. This seemed like it might be slightly more efficient, so I was taking advantage of that where I could. It looks like that is causing problem for the stricter Python 3.5 syntax, though, so I'll need to go back and convert all of those to a "return (yield from some_coro)" and decorate the functions as coroutines explicitly rather than just doing "return some_coo".

Thanks for the report!

**Comment by ronf** [comment]
Ok - change 0bcd91a in the develop branch should fix this.

As it turned out, the posix_rename() function in SFTPClient was missing an "@asyncio.coroutine" decorator, as it was explicitly yielding from something already. However, there were also a number of methods of SFTPClientHandler that were taking advantage of what I mentioned above. All of these are now explicitly marked as coroutines and are doing explicit yields.

**Comment by sisoftrg** [comment]
I'm test it a bit early by adding only one decorator to ``SFTPClient.posix_rename`` and it works well.
Your solution from develop branch also works as expected, thanks for fast fix.

**Comment by ronf** [comment]
Great - thanks for the confirmation!
