### ISSUE TITLE
How to run multiple tasks on multiple clients

### ISSUE THREAD

**Issue by anarchy89** [ronf/asyncssh#516]
I am trying to run multiple tasks on multiple clients. I am able to run a single task on multiple clients, how am I supposed to do multiple tasks on multiple clients?

I have your code snipped here

```
import asyncio, asyncssh

async def run_client(host, command: str) -> asyncssh.SSHCompletedProcess:
    async with asyncssh.connect(host) as conn:
        return await conn.run(command)

async def run_multiple_clients() -> None:
    # Put your lists of hosts here
    hosts = ['ip1','ip2','ip3',.....]

    tasks = (run_client(host, 'ls ~') for host in hosts)
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, result in enumerate(results, 1):
        if isinstance(result, Exception):
            print('Task %d failed: %s' % (i, str(result)))
        elif result.exit_status != 0:
            print('Task %d exited with status %s:' % (i, result.exit_status))
            print(result.stderr, end='')
        else:
            print('Task %d succeeded:' % i)
            print(result.stdout, end='')

        print(75*'-')

asyncio.get_event_loop().run_until_complete(run_multiple_clients())
```

I want to do `ls ~`, `mkdir Documents` then `cd Documents`. Where do I add the commands? 

Also where do I feed my ssh keys ?

**Comment by ronf** [comment]
If you simply wanted to run more than one unrelated command per host, that would be easy. Instead of just a single for loop over the hosts, you could have nested for loops for hosts & commands, or a single for loop on a list of tuples each containing a host and a  command, and you'd do the run_client() on each of those. However, what you're describing is a bit different.

If you want to do things like "cd", though. you need a shell on the remote system, and you need to feed input to that shell interactively. The easiest way to do this is to just put all of the commands you want into a shell script and run that on the remote system as a single command. However, if you want to generate the commands dynamically based on what output you get back, that becomes more complicated. You need to use something like conn.create_process() instead of conn.run(), and you need to manually write input to process.stdin, and read back output from process.stdout and process.stderr. You also need to know how much output to expect from each command, or you need to do something like setting a unique prompt in the shell that won't appear in the command output, so you can read until you see a new shell prompt.

There's some discussion about this in #227, including some example code that writes a command and tries to read back the output, by looking for a unique string in a prompt.

**Comment by ronf** [comment]
Assuming you want to run commands to each host in sequences (waiting for each command to complete before sending the next one), but do this across multiple hosts in parallel, you could do something like:

```python
import asyncio, asyncssh

async def run_client(host, commands, **kwargs):
    output = ''

    async with asyncssh.connect(host, **kwargs) as conn:
        for i, command in enumerate(commands):
            result = await conn.run(command)

            if result.exit_status != 0:
                output += f'=== Command {i+1}: {command} failed ===\n' + result.stderr
            else:
                output += f'=== Command {i+1}: {command} succeeded ===\n' + result.stdout

        return output

async def run_multiple_clients():
    # Put your lists of hosts and commands here
    hosts = 2*['127.0.0.1'] + ['0.0.0.1']
    commands = ['echo foo', 'echo bar', 'echo baz']

    tasks = (run_client(host, commands, client_keys=['~/.ssh/id_rsa']) for host in hosts)
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, result in enumerate(results):
        if isinstance(result, Exception):
            print(f'Connection {i+1} to host {hosts[i]} failed: ' + str(result))
        else:
            print(f'Connection {i+1} to host {hosts[i]}:\n' + result, end='')

        print(75*'-')

asyncio.run(run_multiple_clients()
```

This also shows how to pass additional arguments (such as what client keys to use). They can be passed as keyword arguments to the asyncssh.connect() call, and here I've passed all keyword arguments to run_client() through to that.

Note that run_client() doesn't have to be given the commands to run as a list, and doesn't need to have the same handling code for each command you run. You could do a conn.run() of one command, and then immediately look at the exit status, stdout, and stderr results from that command before deciding what command(s) to run next. There could be a series of such calls to conn.run() with whatever logic you needed. As long as all of this happens inside the "async with" that opens the connection, you should be able to run as many commands as you like in sequence all over a single SSH connection, and by using asyncio.gather() as shown here, all of this can happen to different hosts in parallel.

You also don't need to run the exact same set of commands on each host. If you wanted to, you could make that conditional on which host you are connecting to.

**Comment by anarchy89** [comment]
I am getting an error now, i dont know why but it used to work,
@ronf 
RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by ronf** [comment]
You can't call asyncio.run() from within an async function. It should be run at the top level like my example above, or at most inside a non-async function called from the top level, with no async event loop active yet.
