### ISSUE TITLE
SCP API is too restrictive

### ISSUE THREAD

**Issue by acerv** [ronf/asyncssh#534]
Hi,
the following scp used to copy one file from SCP server has a lack of versatility:
```
async def scp(srcpaths: Union[_SCPConnPath, Sequence[_SCPConnPath]],
              dstpath: _SCPConnPath = None, *, preserve: bool = False,
              recurse: bool = False, block_size: int = SFTP_BLOCK_SIZE,
              progress_handler: SFTPProgressHandler = None,
              error_handler: SFTPErrorHandler = None, **kwargs) -> None:
```
In particular, the destination file is forcing applications using the API to physically copy a file inside the current system. It would be useful to obtain bytes content of that file instead. The API would look something like this:
```
async def scp(srcpaths: Union[_SCPConnPath, Sequence[_SCPConnPath]],
              block_size: int = SFTP_BLOCK_SIZE,
              progress_handler: SFTPProgressHandler = None,
              error_handler: SFTPErrorHandler = None, **kwargs) -> bytes:
```
Is it possible to emulate/obtain the same result with current asyncssh API?

Thanks in advice

**Comment by ronf** [comment]
If you want to open a remote file and read bytes without copying it locally, you should use the [open](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClient.open) API in the [SFTPClient](https://asyncssh.readthedocs.io/en/latest/api.html#sftpclient) class. This will return an [SFTPClientFile](https://asyncssh.readthedocs.io/en/latest/api.html#sftpclientfile) object which you can use to read or write data from a remote file. This API supports both sequential and random access IO, and doesn't require the full file to be transferred.

This relies on the remote system supporting SFTP rather than scp, but that generally shouldn't be a problem and should be much more efficient than trying to use scp for this, since that's only capable of transferring complete files, and only in  a sequential manner.

In fact, newer versions of OpenSSH have actually changed their "scp" client to use SFTP, deprecating native "scp" support. AsyncSSH still supports both, but the "scp" port was only ever intended for file copying, not remote file read/write. The AsyncSSH SFTP support can be used for either, depending on whether you use the get/put/copy APIs or the open API.

**Comment by ronf** [comment]
Here's an example of using [open](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SFTPClient.open):

```python
import asyncio, asyncssh

async def run_client():
    async with asyncssh.connect('remote_host') as conn:
        async with conn.start_sftp_client() as sftp:
            async with sftp.open('remote_file') as f:
                data = await f.read()

    print(data)

asyncio.run(run_client())
```

For large files, you'd probably want to process data a chunk at a time, which you can do by passing a size on the read() call and wrapping a loop around that. However, for small files, it should be fine to call read() with no argument, which will cause it to return the entire contents of the file.

**Comment by acerv** [comment]
Actually I was able to create my own scp client to obtain bytes instead of file copy, by inheriting `_SCPHandler` and to create my own handler.
The problem is that in my own application there's no way to know SSH version and to handle it accordingly, so, in any case, scp is required. I always liked sftp much more than scp, but we don't really know if sftp server is going to be installed.

I guess there's no intention to maintain scp support anymore, since it's going to be deprecated. Am I right?

**Comment by acerv** [comment]
The source code of my own implementation `_SCPHandler` can be found here: https://github.com/acerv/runltp-ng/blob/361a4cfc3945cc2e7d1bcf40e91ea67b25a99027/altp/ssh.py#L29

Let me know what you think. Thanks!

**Comment by ronf** [comment]
> The problem is that in my own application there's no way to know SSH version and to handle it accordingly, so, in any case, scp is required. I always liked sftp much more than scp, but we don't really know if sftp server is going to be installed.

Fair enough, but couldn't you run into the same problem with 'scp' not being installed?

I was thinking about this a bit more, and it seems to me you don't need either SFTP or scp for this use case. It should be sufficient to just use "cat". More specifically:

```python
    async with asyncssh.connect('remote_host') as conn:
        data = (await conn.run('cat remote_file')).stdout
```

Additional work would be required if you wanted to support something like multiple files or glob pattern matches, but if you just need to pull down the contents of a single file, this should work nicely.

**Comment by acerv** [comment]
I didn't use `conn.run` because it looks there might be a problem with buffer size when file is big enough. But maybe I'm wrong. Can you tell if this would happen and (eventually) how to fix it?

**Comment by ronf** [comment]
If you want to process the data a block at a time and not have to buffer the entire contents of the file in memory, it's still possible to use the "cat" approach. It would look something like the following:

```python
    async with asyncssh.connect('remote_host') as conn:
        async with conn.create_process('cat remote_file') as proc:
            while True:
                data = await proc.stdout.read(32768)

                if not data:
                    break

                # process data
```

If you are just going to end up collecting all the data in a single `str` or `bytes` object, though, you should be fine using `conn.run()`. Data is only flowing in one direction in this case, so you don't need to worry about things getting blocked because of buffer limits. You just need to have enough memory to hold the full file contents.

On the point about `str` vs. `bytes`, you'll want to set `encoding=None` in your call to `run()` or `create_process()` if you want all your I/O to be in `bytes`. Otherwise, encoding will default to 'utf-8', and AsyncSSH will try to do a conversion back to `str` when returning output from stdout.

**Comment by acerv** [comment]
Thank you very much for the explaination!

**Comment by ronf** [comment]
Happy to help...
