### ISSUE TITLE
Send commands to switch

### ISSUE THREAD

**Issue by obeleh** [ronf/asyncssh#54]
Hey,

I'm trying to connect to a procurve switch. I've tested the connection with putty and that seems to work.

```
ProCurve J9137A Switch 2520-8-PoE
Software revision S.14.03
```

As far as I understand it the switch does not have the sftp or tftp subsystem enabled. And I want my program to work as soon as putty "works".

My basic setup:

```python
import asyncssh
import asyncio

async def tst():
    conn = await asyncssh.connect(ip4, username=username, password=password, known_hosts=None)
    print('opening')
    stdin, stdout, stderr = await conn.open_session(command='sh name', subsystem=None, term_type='ansi')
    response = await stdout.read()
    conn.close()
    return response

fut = asyncio.ensure_future(tst())
loop = asyncio.get_event_loop()
loop.run_until_complete(fut)

```

**Comment by obeleh** [comment]
I've tried a few variantions without success. I'm clearly missing something but I don't know in what direction I should look. 

some variations I've tried:
 - not sending the command but wait for a terminal (I think this is what I should do?)
 - try 'tftp' as subsystem
 - different term_types

**Comment by obeleh** [comment]
Never mind. I got in:

```
stdin, stdout, stderr = await conn.open_session(subsystem=None, term_type='ansi')
res = await stdout.read(2048)
```

**Comment by ronf** [comment]
The "subsystem=None" is the default here, so that should not be necessary.

I think the change that made it work for you is a combination of asking to open a shell (by not specifying the "command" argument) and then reading a specific number of bytes rather than calling read(). When you call read() with no arguments, it reads until the channel is closed by the SSH server. However, when you open a shell, the server doesn't close the channel after it generates output. It goes back to reading your next command. So, you need to use something like readline() if you know how many lines of output are expected, or need to call read() with a count of the maximum number of bytes to read until you get all the output you are looking for.
