### ISSUE TITLE
The second SSHReader returned by open_session doesn't seem to contain stderr output

### ISSUE THREAD

**Issue by Rasnar** [ronf/asyncssh#548]
Hi, 
I'm doing a remote shell tested framework using the `open_session` approach, mostly because I need to be able to interact remotely with a target in multiple steps in a single session (write, wait for response, read, write again, wait for password prompt, etc). 
However, while testing my code, I saw that the stdout and stderr outputs are both in the same SSHReader, here is a sample of code to illustrate it: 
```
import asyncio
import asyncssh

async def run_client(host, user, password):
    async with asyncssh.connect(host, username=user, password=password, term_type="xterm") as conn:
        writer, stdout, stderr = await conn.open_session(f"echo -n stdout_message; >&2 echo -n stderr_message")

        while not stderr.at_eof():
            data = await stderr.readline()
            print(f"stderr= '{data.strip()}'")

        while not stdout.at_eof():
            data = await stdout.readline()
            print(f"stdout= '{data.strip()}'")

            
        print("ret=", stderr.channel.get_returncode())


loop = asyncio.get_event_loop()

# Set your connection details
host = '127.0.0.1'
user = 'ubuntu'
password = '<>'

try:
    loop.run_until_complete(run_client(host, user, password))
except (OSError, asyncssh.Error) as exc:
    print(f'SSH connection failed: {exc}')
```
When running it, I get the following output: 
```
stderr= ''
stdout= 'stdout_messagestderr_message'
ret= 0
```

I would have expected that the second SSHReader from the `open_session` would output only the stderr content, while the first reader would only contain stdout. 

This is at least what I understood while reading the following description on the `open_session` method:
```
Instead of taking a `session_factory` argument for constructing an object which will handle activity on the session via callbacks, it returns an :class:`SSHWriter` and two :class:`SSHReader` objects representing stdin, stdout, and stderr which can be used to perform I/O on the session.
```

Is there any way to separate stderr from stdout using the `open_session` approach?

**Comment by Rasnar** [comment]
It seems to only happen if we force it to be an interactive session by using `request_pty` or setting `term_type`. 
However, if we want to be able to use the SSHWriter, we need to use an interactive session, correct?

**Comment by ronf** [comment]
You're correct that asking for a pseudo-tty will cause stdout and stderr to be the same, as TTYs support only a single stream in each direction. This is an OS thing, not an SSH thing, but all SSH implementations basically work this way.

There's no requirement that you must request a TTY to use SSHWriter, though. You can do interactive I/O without one. You just won't get things like support for echoing if your input on the remote system, and you may not get things like shell prompts. This is often a good thing, though, as usually if you are scripting access to a remote system you end up having to filter out any output like that.

You can use any of the interactive modes (e.g. `create_session`, `open_session`, or `create_process`) with or without requesting a PTY. The only thing that isn't really interactive is when you use the `run` method, since it expects to be able to run a remote command with just a single block of optional input up front, and after that it collects up all the output and returns it without any further interaction.

**Comment by ronf** [comment]
One other point -- if you do split stdout and stderr by not requesting a PTY, it's a bit dangerous to read the output from those sequentially, unless you know the amount of output is going to be really small. Otherwise, you run the risk of the remote command blocking while writing to stderr while you are block waiting to read more data from stdout. This will lead to a deadlock. To avoid this, you need to read from stdout and stderr in parallel by creating separate tasks for each, and then if you like you can use something like `asyncio.gather` to wait for both of these tasks to finish before you continue.

Also, there's a potential race condition where `at_eof` may not return `True` before getting into the `readline` call. In that case, `readline` will return an empty string or a partial line without a newline at the end. So, you're better off with a `while True` that looks to see if `readline` returns an empty value to break out of the loop.

If you want to read a line at a time, your other option is to use the SSHReader as an iterator (`async for line in stdout'), and it will handle this issue for you.

**Comment by Rasnar** [comment]
Hi @ronf thank you so much for you quick and concise response! 
That makes perfect sense, and thank you for the warning me about splitting both stdout and stderr. 
You have there an amazing library, keep on the good work!
