### ISSUE TITLE
No matching encryption algorithm found

### ISSUE THREAD

**Issue by xpertimage** [ronf/asyncssh#556]
Running a python 3.9 script on RHEL Version 7 connecting to Cisco network devices. Can connect to some devices but not to others.
Any help is much appreciated.

Device with Error: 
16:11:21,95 asyncssh INFO [conn=0] Sending disconnect: No matching encryption algorithm found, sent chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr and received aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc (3)
16:11:21,106 asyncssh INFO [conn=0] Connection failure: No matching encryption algorithm found, sent chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr and received aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
16:11:21,116 asyncssh INFO [conn=0] Aborting connection

Python Code:
`import asyncio
import asyncssh
import time
import argparse
import json
import logging
logging.basicConfig(filename='./ErrorLog.log',
                    filemode='w',
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.DEBUG)
asyncssh.set_debug_level(2)

async def fetch_config(hostname, username, password):
    try:
        async with asyncssh.connect(hostname, username=username, password=password, known_hosts = None) as conn:
            # Send command to fetch running configuration file
            result = await conn.run('show running-config | section tacacs')
            config = result.stdout
            print(f"Processing {hostname}")
            conn.close()
    except asyncssh.Error as e:
        print(f"Failed to fetch config for {hostname}: {e}")

def parseArgs():
    parser = argparse.ArgumentParser(
        description="passwords from ADO library")
    parser.add_argument('--username', dest='username', action='store',
                        help="Username")
    parser.add_argument('--password', dest='password', action='store',
                        help="Password")
    args, unknown = parser.parse_known_args()
    return args

async def main():
    args = parseArgs()
    username = args.username
    password = args.password
    print('*************************************')
    print('Start of run')
    # List of routers to connect to
    with open('dot48.json') as file:
        routers = json.load(file)
    start_time = time.time()
    # Create tasks for each router
    tasks = [asyncio.create_task(fetch_config(router['ip'], username, password)) for router in routers]

    # Run tasks concurrently
    await asyncio.gather(*tasks)
    end_time = time.time()
    total_time = end_time - start_time
    print(f'Total time:{total_time}')
if __name__ == '__main__':
    asyncio.run(main())`

**Comment by ronf** [comment]
From the error message, the target device with the problem is only accepting CBC ciphers (aes128-cbc, 3des-cbc, aes192-cbc, aes256-cbc) but these are off by default in AsyncSSH (and modern versions of OpenSSH) because of potential security concerns.

You can fix the problem by passing in an explicit list of encryption algorithms you are willing to support when connecting to those devices, or you can add back one or more CBC ciphers to the allowed list for all devices. If you add them to the end of the list, they'll only be used when none of the stronger ciphers are available.

In your call to asyncssh.connect(), you can add something like `encryption_algs='+aes256-cbc'` as another argument to add aes256-cbc to the end of the list of allowed encryption algorithms. This should avoid there error you reported.
