### ISSUE TITLE
Load /etc/ssh/ssh_known_hosts as well for default known hosts

### ISSUE THREAD

**Issue by minhuw** [ronf/asyncssh#562]
Thank you for your helpful work, first of all.

As the `asyncssh` document says, only `~/.ssh/known_hosts` is currently read by default for host key verification. I wonder whether the system-wide known hosts list, i.e., `/etc/ssh/ssh_known_hosts`, could also be loaded by default if it exists. It's specified by [OpenSSH document](https://en.wikibooks.org/wiki/OpenSSH/Client_Configuration_Files#/etc/ssh/ssh_known_hosts).

Though it's OK to add this file to `SSHClientConnectionOptions` manually, it only applies to the inside connection when using a tunnel as [this issue](https://github.com/ronf/asyncssh/issues/545) discusses. If the tunnel is implicitly created by `asyncssh` for `ProxyJump` option in the OpenSSH client config file, I found there is no way to specify its `known_hosts` option (correct me if I'm wrong).

I'm unsure whether there are any security concerns loading the system-wide known hosts records by default. But it would help if `async.connect(<machine>)` works just like `ssh <machine>` in my case when host keys are stored in `/etc/ssh/ssh_known_hosts` and a tunnel is set by a `ProxyJump` option in `~/.ssh/config`.

**Comment by ronf** [comment]
One of the main problem with the system-wide known hosts is that the path is not consistent across platforms. For instance, OpenSSH on my Mac uses /opt/local/etc/ssh/ssh_known_hosts and /opt/local/etc/ssh/ssh_known_hosts2 for the version coming from MacPorts. The version bundled with macOS would look for something like /etc/ssh/ssh_known_hosts and /etc/ssh/ssh_known_hosts2, matching the Linux default, but I'm sure I could find systems out there where it looks in /usr/local/etc rather than just /etc, and there are other variants I've seen where all the files live directly in /etc rather than in /etc/ssh. It all comes down to options set at build time.

If you want to use the system-wide known hosts file, it's probably better if you set it explicitly, as you'll know which values are needed for the specific platform you're on. If you do that in the SSH config file, it should apply to both the ProxyJump connection and the connection inside it, and it should be harmless on OpenSSH to have this set, if it is set to the current system's default value.

You can also open your own connection to the ProxyJump server without using the setting in the config file where you pass in your own connection options, and then use the `connect_ssh()` method on the returned connection object to open a tunneled connection. In your case, though, it's probably easier to just update the config file with what you need, if you are already getting ProxyJump from there.

**Comment by minhuw** [comment]
I've learned the difficulty of providing a cross-platform way to locate the system-wide known hosts file. It's OK for me to just manually copy the content of the system-wide file to the user file to work around. Thank you for your help.
