### ISSUE TITLE
In Linux, when I connect to hundreds of servers simultaneously, each connection takes a long time

### ISSUE THREAD

**Issue by xjie0626** [ronf/asyncssh#573]
when I connect to thousands of servers at the same time, many servers will timeout, which means there is no way to support thousands of concurrent connections. Does asyncssh support thousands of concurrent connections, and are there any restrictions? For example, if I connect to 2000 servers at the same time, if the connection speed is less than 1 second and the command execution is less than 1 second, should the return be fast even if the server resources are sufficient

**Comment by ronf** [comment]
There's nothing inherent in AsyncSSH itself which would limit the number of simultaneous connections you can make. However, you'll probably need to increase the number of file descriptors on the shell which you run AsyncSSH from. I think Linux typically defaults to 1024 there, and you'll need at least one file descriptor per connection you want to open, plus additional ones for things like stdin, stdout, and stderr.

Also, the SSH handshake can be very expensive. Even on a VERY fast machine (an M1-Ultra Mac Studio) that I have here, a remote connection that just printed a single line of output took 1-2 seconds to complete. Since each server is only getting one connection to it, the server probably won't be a bottleneck, but there's a fairly high cost on the client that you'll need to pay for each of those connections. Opening thousands of connections at once could take tens of minutes, and SSH servers limit the amount of time that they'll wait for a handshake to complete. So, to prevent hitting those timeouts, you'll probably have to limit the number of connections you open at once, waiting for at least the SSH handshake to finish before opening any more. I'd suggest limiting to no more than 20 connections at a time.

There's some discussion about a use case like this in #475. In particular, see the use of a Semaphore there to limit the number of simultaneous requests.

**Comment by xjie0626** [comment]
Thank you very much for your answer. 
I have carefully reviewed this issue(#475) and it may be different from mine.I just want to connect to thousands of servers at the same time and execute a command before returning
My Linux client has a relatively large number of processes and file openings
```
cat  /etc/security/limits.conf
*        soft    nproc  65535
*        hard    nproc  65535
*        soft    nofile  655350
*        hard    nofile  655350
```
And I have been observing the number of netstat connections at any time, and it seems that it can immediately increase by thousands
```
while true; do sleep 1; netstat -an|wc -l; done
2171
2171
2179
2347
2518
2598
2774
2948
3120
3294
3466
3619
3792
3964
5110
5986
5985
```
May there be a problem with my code? Can you help me check if there is room for optimization
remote.py
```
import asyncio
import asyncssh
import socket


class SSHClient:
    def __init__(self, ip, username, password, port):
        self.ip = ip
        self.username = username
        self.password = password
        self.port = port
        self.known_hosts = None
        self.connect_timeout = 30
        self.command_timeout = 30
        self.conn = None
        self.result = None

    async def connect(self):
        try:
            self.conn = await asyncssh.connect(self.ip, username=self.username, password=self.password,
                                               port=self.port, connect_timeout=self.connect_timeout,
                                               known_hosts=self.known_hosts)
            self.result = {'code': 0, 'ip': self.ip, 'data': "success"}
        except Exception as e:
            self.result = {'code': -1, 'ip': self.ip, 'data': str(e)}

    async def run_command(self, command=ip_check):
        if self.conn is not None:
            try:
                results = await self.conn.run("command,timeout=self.command_timeout)
                stdout = results.stdout
                stderr = results.stderr
                status = results.exit_status
                data = stdout if stdout else stderr
                data = data if data else 'no data'
                self.result = {'code': status, 'ip': self.ip, 'data': data}
            except asyncssh.process.TimeoutError:
                self.result = {'code': -1, 'ip': self.ip, 'data': 'command timeout'}
            except Exception as e:
                self.result = {'code': -1, 'ip': self.ip, 'data': str(e)}
   
   
   async def close(self):
    if self.conn is not None:
        self.conn.close()
        self.conn = None
```

a part of view.py

```
    def commandInfo(self, request):
        data = json.loads(request.body)
        datas = data['data']
        name = data['name']
        command = data['command']
        asyncio.run(self.runInfo(datas, command, name))
        return BaseView.successData(datas)
   
    async def runInfo(self, servers, command, name):
        coroutines = [self.run_command(server, command, name) for server in servers]
        await asyncio.gather(*coroutines)
    
    async def run_command(self, server, command, name):
        ip = server['ip']
        username = server['username']
        password = CryptPwd.decrypt(models.Host.objects.get(ip=ip).pkey)
        port = server['port']
        ssh_client = SSHClient(ip, username, password, port) # Here, I tested that only connecting and disconnecting is very slow
        await ssh_client.connect()  
        if ssh_client.result['code'] == 0:
            models.TaskLog.objects.create(
                name=name,
                ip=ip,
                command=command,
            )
            await ssh_client.run_command(command)
        else:
            models.Host.objects.filter(ip=ip).update(state=1)
        result = ssh_client.result
        await ssh_client.close()
        server.update(result)
```

Thank you very much

**Comment by ronf** [comment]
Opening a large number of TCP connections in parallel should be very quick, as you saw. Even sending the initial few SSH messages should happen quickly as well. However, when it comes time for the client to verify the server host key, that can be pretty expensive, and after that it would need to perform client authentication, and that's even more expensive. Trying to do that on a few thousand connections in parallel is likely to take so long that the authentication will fail.

One of the downsides of AsyncSSH is that Python asyncio generally only uses a single CPU core. Even if you try to create multiple threads, the Python global interpreter lock is going to get in the way of using all those threads. You'd end up needing to create multiple Python processes and then create independent asyncio event loops for each process, splitting up the set of servers you want to connect to across those different processes. Even then, I think it would be hard to open thousands of connections at once, but you might be able to scale to hundreds of new connections at once that way, if you were on a client with a large number of cores.

Note that this is only an issue for establishing the SSH connections. Once established, you could keep around a very large number of connections and use them all in parallel without an issue. However, it sounds like in your use case you aren't keep the connections around for very long, so I'm not sure that helps you.

**Comment by xjie0626** [comment]
I tried adding multiple threads through asyncssh, but the improvement was not significant. Later, I switched to multiple processes (configuring multiple processes under django is troublesome...), which greatly improved the speed. Even with a strong server, the high concurrency return speed is also very fast. asyncssh is indeed very powerful. Thank you very much for your patient answer.

**Comment by ronf** [comment]
Glad to hear that you were able to get that working!

Your experience mirrors mine, where going multi-threaded doesn't help much due to the Python global interpreter lock, even with separate asyncio event loops per thread. However, going to multiple processes each with their own asyncio event loop works much better.

In fact, one easy way to get this speedup is just to launch a bunch of separate Python interpreters as subprocesses, feeding each one the work you want it to do (like the list of hosts to connect to in your example). This can be done from a wrapper written in Python, or even just a shell script if the wrapper is simple enough.

**Comment by xjie0626** [comment]
Thank you very much for your suggestion. I will give it a try if there is a chance.

**Comment by xjie0626** [comment]
@ronf I'm sorry to bother you again
I am currently dividing a long list of IP addresses (approximately 2000) into dozens, and using the multiprocessing library, I am running multiple processes to execute asyncssh (there may be dozens of servers per process). When I set a scheduled task to execute every minute, it suddenly gets stuck after a period of normal execution and cannot obtain a return value. I have seen these multiprocessing processes on Linux all along, It will not disappear (it will disappear after normal execution), and there are many connections related to the SSH port in netstat - an. The status is ESTABLISHED, and it seems that it will not automatically disconnect. It is currently unknown what is causing it. Is there anything that needs to be optimized, or what configurations can be adjusted in asyncsh?

`class BatchTask:
    def __init__(self, data, task, *args, **kwargs):  # Data is a server list. Task is a function with ansyncssh
        self.data = data
        self.split_num = 30
        self.args = args
        self.kwargs = kwargs
        self.task = task
        self.result = None

    def startInfo(self):
        if len(self.data) > self.split_num:
            cpu_count = multiprocessing.cpu_count() # my system is 80
            data_len = len(self.data)
            thread_num = min(round(data_len / self.split_num), cpu_count)
            
            # splitting big data and executing multiple processes
            num_parts = thread_num
            part_size = len(self.data) // num_parts
            data_part = []
            for i in range(num_parts):
                start = i * part_size
                end = start + part_size
                if i == num_parts - 1:
                    end = len(self.data)
                    part = self.data[start:end]
                else:
                    part = self.data[start:end]
                data_part.append(part)

            # multiprocessing + asyncio
            resl = []
            pool = multiprocessing.Pool(thread_num)
            for item in data_part:
                reslPool = pool.apply_async(self.asyncrun, args=(item,))
                resl.append(reslPool)
            pool.close()
            pool.join()
            result = []
            for res in resl:
                result.append(res.get())
            result = [num for sublist in result for num in sublist]  # combining split data
            self.result = result
        else:
            result = self.asyncrun(self.data)
            self.result = result

    def asyncrun(self, async_data):
        result = asyncio.run(self.runInfo(async_data))
        return result

    async def runInfo(self, servers):
        coroutines = [
            self.task(server, *self.args, **self.kwargs) for server in servers # Task is a function with ansyncssh
        ]
        result = await asyncio.gather(*coroutines)
        return result`

**Comment by ronf** [comment]
I don't see any exception handling here, so my best guess is that an exception is being raised inside one of the coroutines in runInfo, and that's causing an exception to be raised by the gather() call. This in turn would then lead to asyncrun() raising that exception, which would then cause res.get() to raise it, aborting out of your loop appending the results from the apply_async() calls and preventing the rest of the results from being collected or the BatchTask result from being updated. Instead, your startInfo() call would probably see whatever that exception was, but I'm not sure whether that would be visible to you or not.

If you add check_exceptions=True to the gather() call, that might help, but you'll need to be prepared for the res.get() to return an exception instead of the expected result. If you still don't get back all the expected results, I would suggest adding "try" blocks around the asyncssh calls, to see if there are exceptions being raised that aren't getting bubbled up as results.

As for why it might be raising exceptions in the first place, I'm not sure you'll be able to keep up with trying to do thousands of fresh SSH handshakes per minute, even when splitting the work across multiple threads. The SSH handshake is expensive, and can take seconds to complete even on a very fast machine. You might be better off trying to open an SSH connection once to each destination and keep it open to periodically send commands to it, so you only pay the overhead of that SSH handshake once. Even then, you'll probably need to do something to space out the initial set of SSH connect calls, so you don't attempt to do them all at once. You can use a semaphore to help with this -- see #475 for an example of this.

**Comment by xjie0626** [comment]
Thank you for your reply.

Through multiprocessing, with normal server connections and simple bash, it only takes about 10 seconds for two thousand servers (CPU instantaneous utilization rate is around 50%, and other performance is normal). Moreover, when I tested, I entered a simple command such as "pwd" and set a command timeout time. Normally, it can be completed within one minute. I did the scheduled task to obtain the return value, and judged based on the return value, For example, whether the SSH connection is normal, whether the command result is 0, and other related alarms will be triggered. Ansyncssh is written as a CLASS, and under normal circumstances, the SSH connection of TCP will be disconnected （not in ESTABLISHED state）immediately after executing the command (is there any difference between close and wait_closed? whether the close function is executed or not, the TCP connection will be immediately disconnected). I am not sure if it is possible to maintain the connection of TCP and use it the next time the command is executed.

I added "try" blocks in each link,and alse set return_exceptions=True (Set check_ Exceptions=True reported an error, it seems that this parameter is not present) I haven't seen any error prompts when the exception occurred. According to the log I set, I only know that it was generated when some servers finished executing the command. By logging into the Linux server, I can see that the SSH TCP connection Always maintain ESTABLISHED status, And disconnect after a few minutes or hours (Linux can set the net.ipv4.tcp_keepalive_time parameter to automatically disconnect after a few seconds of no data transmission), and the task is completed normally,I think it may need to find the reason why TCP was not released normally,I don't know how to set up to see logs when stuck,set net.ipv4.tcp_keepalive_time can bring tasks to an end, but it can only alleviate the problem without a fundamental solution. It will appear again every few hours or minutes, without regularity

Of course, I also made other attempts to modify the startup process method of multiprocessing, change fork to spawn, and try using celery instead of multiprocessing, but the problem still exists,can you give me more advice?

Thank you very much

**Comment by ronf** [comment]
> Ansyncssh is written as a CLASS, and under normal circumstances, the SSH connection of TCP will be disconnected （not in ESTABLISHED state）immediately after executing the command (is there any difference between close and wait_closed? whether the close function is executed or not, the TCP connection will be immediately disconnected).

Calling `close` will start the close process, but the TCP connection won't be closed until the client has had a chance to send a disconnect message to the other side, and doing an `await` on `wait_closed` will wait until that's all done. If you do something similar at the channel level, calling `close` will wait until all outstanding data has been sent before even starting the close of the channel. There's also a separate concept of sending 'eof' there, which allows you to tell the other side you are not going to send any more data, but still allow you to receive any response data which hasn't been sent yet, only triggering a close when all data in both directions has been received. This is usually want you want, to avoid any data potentially be lost by triggering a close too early.

> I am not sure if it is possible to maintain the connection of TCP and use it the next time the command is executed.

This is possible, but you'll need to avoid calling `close` on the connection if you want this, and avoid using context managers (`async with`). You can still do a `close` or `eof` on a channel in this case, but you can then start a new channel with a new command running in it and it will be sent over the already open and authenticated SSH connection. There may be limits on some servers to the number of channels you can open on a given connection, though, or how long you can keep the connections open.

> Linux can set the net.ipv4.tcp_keepalive_time parameter to automatically disconnect after a few seconds of no data transmission.

This setting is generally about the opposite -- it will allow you to keep a connection open even when you aren't sending data on it when keep alive is enabled. It will also help you detect then the remote system has unexpectedly disconnected more quickly if you lower the keep alive time, but if you're seeing that it indicates that something is going wrong on the remote host or on the network used to reach it, which could be the source of the problem you are seeing. For instance, if there was a stateful firewall between the client & server, it might throw away state about the connection after some period of time, causing it to drop packets on that connection and eventually cause the connection to break. I'd only expect to see this if you tried to keep a connection open for a long time, though. Do you think such a firewall might be in place in your case?

There are options in AsyncSSH (and other SSH implementations) to send application-level keep alive messages to try and prevent idle connections from getting forgotten in this way. You might want to try setting `keepalive_interval` and `keepalive_count_max` to see if that helps. The idea is to keep data flowing on long-lived connections that might otherwise sit idle, to remind stateful firewalls that the connection exists.

Unfortunately, some firewalls have a limit to the number of connections they can remember, and in that case even a keep alive message may not be enough. It may simply not be possible to open more than a certain number of simultaneous connections through such a firewall.

**Comment by xjie0626** [comment]
Thank you very much for your patient answer

During this period, I have also been trying various tests and found that occasionally a server's SSH connection is abnormal, causing it to get stuck. When I execute the scheduled task of this server alone, it occasionally gets stuck. This server's SSH login is slow and may even fail. However, it is unclear why this situation occasionally causes server tasks to get stuck. I suspect it is related to SSH configuration. Have you encountered any issues in this regard, Can we optimize by setting SSH configuration parameters on Linux or asyncssh parameters ?

Also, are there any steps or examples for this to refer to？
**This is possible, but you'll need to avoid calling close on the connection if you want this, and avoid using context managers (async with). You can still do a close or eof on a channel in this case, but you can then start a new channel with a new command running in it and it will be sent over the already open and authenticated SSH connection. There may be limits on some servers to the number of channels you can open on a given connection, though, or how long you can keep the connections open.**

**Comment by ronf** [comment]
If you have a mix of working and non-working connections which take very different amounts of time to finish, you may not want to use `gather()` here, as it will wait for all of the tasks to finish before it returns. This isn't necessarily a problem if you are just waiting for everything to finish, but it could explain why a stuck server could cause the run as a whole to block for a long time. You might want to look at `asyncio.as_completed` as a way to get partial results to be returned, giving you a better idea of which ones are "stuck". You can also try setting a `connect_timeout` value on your `connect()` call and/or a `timeout` on the `run()` call.

Keeping connections open and re-using them to send new commands with connecting from scratch each time is a bit more complicated, especially when trying to do this in parallel using a mixture of threading & async IO. You're already using `await` on the connect call, though, and explicitly calling `close()` rather than using `async with`, and that's a good first step. However, to reuse the connection you'd have to keep hold of the connection objects in some kind of worker pool indexed by the destination you connected to, and then later look for already open connections in the pool when you want to send a new command to a server you previously connected to.

**Comment by xjie0626** [comment]
Why is it stuck? The reason may be quite complex. According to your suggestion, I have set a timeout for asyncio tasks. The scheduled tasks can be completed on time, and individual server issues do not affect the overall task.
Thanks to your help, my batch task efficiency has been very good. Regarding SSH connection pooling, I have the opportunity to try it out. Thank you very much for your help!

**Comment by ronf** [comment]
I'm glad to hear that things are working out for you.

Regarding why some requests may be getting "stuck", I still don't really know for sure, but the most common cases I've run across are when a target server is down or when there's some kind of network problem between the client and the target. If you are using hostnames, it could also be caused by a problem with the DNS servers you are using to resolve the hostname. Depending on what command you are running on the target, there could also be problems on the host itself when attempting to run the requested command. If this is something you can reproduce, you could try turning on debug logging to get more information about how far it is getting before it gets "stuck", and that might help narrow things down.

**Comment by xjie0626** [comment]
Thank you for your reply.
When the client SSH connection gets stuck, there is indeed an exception. What I am currently experiencing is that the SSH configuration for this client is full, but there are still other servers frantically connecting (not my program). The reason for the continuous TCP disconnection is still difficult to investigate, and it may be related to the underlying mechanism of the Linux operating system. In the future, I will check if there are any other situations that appear and see if there are any commonalities, I also tried to capture and analyze packets through 'tcpdump'.

Thank you again!

**Comment by xjie0626** [comment]
Sorry, the anomaly I am referring to here refers to the surface phenomenon (which was previously mentioned that the TCP connection cannot be disconnected), and neither asyncio nor asyncssh will generate logs. I am about to launch a large number of servers, and I will continue to observe if there are any other servers that have this question. 
thank you!

**Comment by xjie0626** [comment]
Sorry, the anomaly I am referring to here refers to the surface phenomenon (which was previously mentioned that the TCP connection cannot be disconnected), and neither asyncio nor asyncssh will generate logs. I am about to launch a large number of servers, and I will continue to observe if there are any other servers that have this question. 
thank you!

**Comment by ronf** [comment]
You won't see much in the way of logs with asyncio/asyncssh by default, but you can increase the logging level pretty easily to try and see if any exceptions aren't being handled properly. The following block of code at the top of your async main function should suffice:

```python
    logging.basicConfig()
    asyncssh.set_log_level('DEBUG')
    asyncssh.set_debug_level(2)
```

These logs will go to stdout. It may be a lot of output if you are opening a large number of connections, but you can look through the output for "exception" to see where there might be issues.

**Comment by xjie0626** [comment]
Thank you for your suggestion. I know which server is causing this phenomenon, so I just need to test this one. However, it seems that the SSH configuration of this server has been adjusted and there has been no timeout recently. I will observe which other servers are experiencing timeout and try using the testing environment to see what logs will appear. Asyncssh is an excellent library, and I may try to see how to handle executing interactive commands (such as switching users) in the future
thank you!

**Comment by ronf** [comment]
Happy to help - I'm glad it is working for you... If you have further questions, feel free to ask.
