### ISSUE TITLE
How to  run nohup command?

### ISSUE THREAD

**Issue by ljd1995** [ronf/asyncssh#585]
Hello!

I want to use nohup to run a Python file in the background, such as `nohup python test.py  >nohup.out 2>&1 &` , but the program does not end and has been waiting, code like this:

```
ssh_client= await asyncssh.connect(
        host='xxx',
        username='root',
        port=22,
        password='xxx',
        known_hosts=None,
 )
command = 'cd /tmp && nohup python test.py >nohup.out 2>&1 &'
await ssh_client.run(command)
```

in the host, I can find

```
root     27454     1  0 16:27 ?        00:00:00 bash -c cd /tmp && nohup python test.py >nohup.out 2>&1 &
root     27455 27454 13 16:27 ?        00:00:01 python test.py
```

but the program keeps getting stuck and doesn't end

so how to  run nohup command with asyncssh? use timeout?

**Comment by ronf** [comment]
It looks like you're only redirecting stdout & stderr here, but not stdin. If you add "< /dev/null", does that help? See #137 for some prior discussion on this.

**Comment by ljd1995** [comment]
> It looks like you're only redirecting stdout & stderr here, but not stdin. If you add "< /dev/null", does that help? See #137 for some prior discussion on this.

Thanks, I try to add '< /dev/null', it still hangs on, but I see #137 to use create_process(command), it  run normally!

At first, I tried create_process with term_type parameter, but it could not run successfully. Is there any problem with term_type parameter, code like this:

```
ssh_client= await asyncssh.connect(
        host='xxx',
        username='root',
        port=22,
        password='xxx',
        known_hosts=None,
 )
command = 'cd /tmp && nohup python test.py >nohup.out 2>&1 &'
await ssh_client.create_process (command, term_type='xterm')
```

```
await ssh_client.create_process (command, term_type='xterm') # it hangs
await ssh_client.create_process (command) # it normally
```

Why does term_type='xterm' cause hangs?

**Comment by ronf** [comment]
With `create_process()`, I wouldn't ever expect things to hang, since you're not actually waiting for the remote process to finish. It's really odd that you'd ever see a hang even in that case. The problem with create_process() is that AsyncSSH might exit before the "nohup" has finished trying to detach the child process, running the risk of it not fully starting up.

The difference with a term_type is that AsyncSSH would request a pseudo-tty from the remote server. This means the stdout and stderr would both be connected to the terminal output, and stdin to the terminal input, rather than being pipes going directly into the remote bash shell that processes the command you pass in.

In my testing here, conn.run() works just fine, with or without a term_type specified, even without using 'nohup', as long as there's an '&' at the end of the command to get it to run in the background. It doesn't even matter if I redirect stdin or not. For example, the following works for me:

```python
        await conn.run('cd /tmp && python3.11 test.py > nohup.out 2>&1 &', term_type='ansi')
```

If I take out the '&' at the end, it waits for the test.py script to finish before it exits, but even in that case, it doesn't hang. With the trailing '&', it exits immediately, without waiting for the script to exit. I see the exact same behavior when I remove the `term_type` argument, in both cases.

All of this really depends on the behavior of the remote SSH server, since that is what decides when to report the session as closed. In your tests, is the remote server OpenSSH or something else? Since you are using "nohup" and other UNIX shell features, I'm guessing the remote system is a UNIX system and not something like a network appliance running a specialized shell.

**Comment by ronf** [comment]
Have you tried using OpenSSH as a client, running the same remote command? What behavior do you see in that case?

**Comment by ljd1995** [comment]
thanks a lot, I will try again
