### ISSUE TITLE
Pending Task

### ISSUE THREAD

**Issue by SeniorK0tik** [ronf/asyncssh#596]
env:
python 3.11.5
OS - Manjaro

process.stdout.drain() server method doesn't finish Future task.
I used process_factory=handle_client.
Each call adds 1 more Future Task which are not being closed.

LOGS:
INFO:asyncssh:Creating SSH listener on port 8022
INFO:asyncssh:[conn=0] Accepted SSH client connection
INFO:asyncssh:[conn=0]   Local address: ::1, port 8022
INFO:asyncssh:[conn=0]   Peer address: ::1, port 56818
DEBUG:asyncssh:[conn=0] Sending version SSH-2.0-AsyncSSH_2.14.0
DEBUG:asyncssh:[conn=0] Received version SSH-2.0-AsyncSSH_2.14.0
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0] Completed key exchange
INFO:asyncssh:[conn=0] Beginning auth for user KotikZasranets
DEBUG:asyncssh:[conn=0] Trying keyboard-interactive auth
INFO:asyncssh:[conn=0] Auth for user KotikZasranets succeeded
DEBUG:asyncssh:[conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=0] New SSH session requested
INFO:asyncssh:[conn=0, chan=0]   Command: bc
INFO:asyncssh:[conn=0, chan=0] Received channel close
INFO:asyncssh:[conn=0, chan=0] Channel closed
DEBUG:asyncssh:[conn=0] Received disconnect: Disconnected by application (11)
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<handle_client() done, defined at /home/kotik/PycharmProjects/mass_sync/src/server/models/ssh_models/ssh_server_model.py:20> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[SSHConnection._reap_task(<SSHLogger asyncssh (DEBUG)>)()]>

**Comment by ronf** [comment]
Are you doing an `await` on `process.stdout.drain()`? If you call it to create a task but then don't actually await on it, you won't actually wait for content to drain and you will later see this error when the program exits.

If you are doing an await, you may be exiting the asyncio event loop before all the pending tasks have finished. You'll want to do something in whatever function is running your event loop to keep it running until all pending tasks have finished, which is generally done by awaiting on `wait_closed()` on all opened connections before exiting the loop, or just letting the loop run forever in the case of an SSH server, listening for new connections.

**Comment by SeniorK0tik** [comment]
Yes. 
async def handle_client(process: asyncssh.SSHServerProcess) -> None:
    bc_proc = subprocess.Popen(
        process.command,
        shell=True,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
        
     await process.redirect(
        stdin=bc_proc.stdin,
        stdout=bc_proc.stdout,
        stderr=bc_proc.stderr
    )

    await process.stdout.drain()
    await process.wait_closed()
if __name__ == "__main__":

    async def start_server():
      server = await asyncssh.create_server(
            MySSHServer, "", 8022,
            server_host_keys=['ssh_key'],
            process_factory=handle_client
        )
        return server

    loop = asyncio.get_event_loop()
        try:
        loop.run_until_complete(start_server())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('Error starting server: ' + str(exc))
        
    loop.run_forever()

**Comment by ronf** [comment]
The code kind of got mangled here -- you'll want to put all of it in it in a \`\`\` block. However, I think I have the general idea.

Since stdout is being redirected and you're not writing output to it yourself, you really shouldn't need to call `drain()` on it. Does the issue go away if you only call `await process_wait_closed()`?

In fact, even if you were writing data yourself, awaiting on `wait_closed()` on the process would generally be enough, as long as you did a `process.stdout.write_eof()` after you finished writing data. With redirection like what you're doing here, though, even that is not necessary, as any EOF coming from the pipe you are redirecting to would be passed through, on all of stdin, stdout, and stderr.

**Comment by SeniorK0tik** [comment]
Does the issue go away if you only call await process_wait_closed()? - No, doesn't.

**Comment by ronf** [comment]
Do you see an error about a different task being destroyed while pending in this case?

I'm still trying to figure out how the event loop is exiting, given that you appear to be doing a `run_forever()`.

I'm wondering if maybe there's an uncaught exception happening somewhere that's causing the event loop to exit. Since you have AsyncSSH debug logging enabled, I would expect any unexpected exceptions from within AsyncSSH itself to show up in the debug log output, but there could be exceptions elsewhere that might not get reported.

Does this code actually exit after printing the message about the destroyed task, or is it still waiting for new connections at that point, suggesting maybe this message was somehow being triggered due to garbage collection of the process which is closing? I'm not sure I've ever seen this kind of error showing up without an event loop actually being shut down.

**Comment by ronf** [comment]
If you do have code which is triggering the event loop to explicitly stop, you may need to make sure that any remaining pending tasks have a chance to finish. See https://xinhuang.github.io/posts/2017-07-31-common-mistakes-using-python3-asyncio.html#orgc09f339 for a discussion about that.

**Comment by SeniorK0tik** [comment]
```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<handle_client() done, defined at /home/kotik/PycharmProjects/mass_sync/src/server/models/ssh_models/ssh_server_model.py:20> wait_for= cb=[SSHConnection._reap_task(<SSHLogger asyncssh (DEBUG)>)()]>
```
This appears when loop is closed. 
No exception raises in runtime.

**Comment by SeniorK0tik** [comment]
> If you do have code which is triggering the event loop to explicitly stop, you may need to make sure that any remaining pending tasks have a chance to finish. See https://xinhuang.github.io/posts/2017-07-31-common-mistakes-using-python3-asyncio.html#orgc09f339 for a discussion about that.

I initially did this as a temporary solution.

**Comment by SeniorK0tik** [comment]
And I noticed all code after` await process.stdout.drain()` is not being executed. Future task blocks code.

**Comment by ronf** [comment]
AsyncSSH tries to do the best it can to clean up for you using calls like `wait_closed()`, but that's not really enough when the event loop is being explicitly stopped. In that case, it's up to the calling code in the application to properly let pending tasks complete before actually closing the loop, like in the link above.

I don't see any code which is explicitly stopping the event loop in the sample code you have pasted above so it's hard for me to say for sure, but I don't think you can avoid adding explicit code to let pending tasks complete, unless you wait until all open AsyncSSH connections are closed before you trigger the event loop stop. Even then, unless you shut down the listener first and wait for that to complete, there may be a race condition between you shutting down the loop and a process for a new connection being started.

**Comment by ronf** [comment]
Regarding drain blocking code after that from exiting, I'm not really sure what happens if you try to await on `drain()` when that stream is actually redirected, particularly if you're still in the middle of that redirection at the time the SSH connection is closed by the caller. It's possible that there could be a problem there, but unless you are writing data yourself (with no redirection)  there's really no point in doing the `drain()`. My suggestion would be to simply not do the `drain()` in this case. If you have a different example where redirection is not in use where you see this problem or have some other reason you think you need to be calling `drain()`, please let m know.

**Comment by ronf** [comment]
I remembered how `drain()` works when redirection is active. It should block until the redirection completes. So, for instance, if you redirect stdout to a pipe to another process, calling `drain()` on stdout should block until the other process writes EOF to stdout. This should be fine to do as long as you know the other process won't block waiting for something (such as more input from stdin), but it must either write EOF or exit the process to avoid blocking forever.

That said, I think the problem here is more around exiting the event loop before everything finishes, and not specifically anything to do with the `drain()` or the `wait_closed()`.

**Comment by SeniorK0tik** [comment]
Thanks for understanding
