### ISSUE TITLE
SSH connection closed after only one successful conn.run

### ISSUE THREAD

**Issue by barcitomor** [ronf/asyncssh#598]
Hi Ron I'm trying to execute a few commands on a switch using asyncssh but the ssh connection is closed after the first command. here is my code if you decide to help then thanks you very much!

```
import asyncio
import asyncssh

async def run_command(hostname, username, password, commands):
    try:
        async with asyncssh.connect(hostname, username=username, password=password) as conn:
            for command in commands:
                result = await conn.run(command)
                print(f"Output from {hostname}:\n{result.stdout}")
    except asyncssh.Error as e:
        print(f"Error connecting to {hostname}: {e}")

async def main():
    devices = [
        {
            'hostname': 'device1.example',
            'username': 'username',
            'password': 'password',
        }
    ]

    commands = ('show running-config view full', 'show configuration', 'show mac address-table')

    tasks = [run_command(device['hostname'], device['username'], device['password'], command) for device in devices]
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(main())

```

i get asyncssh.misc.ChannelOpenError: SSH connection closed

**Comment by barcitomor** [comment]
```
import asyncio
import asyncssh

async def run_command(hostname, username, password, commands):
    try:
        async with asyncssh.connect(hostname, username=username, password=password) as conn:
            for command in commands:
                result = await conn.run(command)
                print(f"Output from {hostname}:\n{result.stdout}")
    except asyncssh.Error as e:
        print(f"Error connecting to {hostname}: {e}")

async def main():
    devices = [
        {
            'hostname': 'device1.example',
            'username': 'username',
            'password': 'password',
        }
    ]

    commands = ('show running-config view full', 'show configuration', 'show mac address-table')

    tasks = [run_command(device['hostname'], device['username'], device['password'], command) for device in devices]
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(main())

```

**Comment by ronf** [comment]
The code here looks fine, but unfortunately there are a number of devices out there that don't support multiple SSH sessions being opened in a single connection. Only the first session request is accepted, and all others will give an error.

There are two workarounds for this, neither of which is great.

The first option is to change the code to do a separate `asyncssh.connect()` call for each command. So, you move the "for" loop up above that call and do both the `asyncssh.connect()` and `conn.run()` calls inside the loop. If the commands are independent of one another (which would have been a requirement even with the code you have here), opening a separate connection for each command should work, but it'll be slower because you are authenticating on every command.

If your commands are related (like entering a sub-mode with one command and then doing something in that sub-mode in a subsequent command), you'll need to have those commands all in a single session, whether the device supports multiple sessions per connection or not. Unfortunately, this is not easy to do as there's no good way to know when the output from a command ends and it is ready to accept the next command. You have to do things like a `readuntil()` looking for a unique prompt that doesn't otherwise appear in the command output. If you can get this working, you can run a series of commands (related or not) over a single SSH session, and authenticate only once for all the commands sent on that session.

For this second approach, look into using `create_process()` on a connection and then doing reads & writes using the `stdin`, `stdout`, and `stderr` members of the returned process object. See https://asyncssh.readthedocs.io/en/latest/#interactive-input for a simple example of this. The challenge in your case will be to figure out how much output to read after sending each command. If you look through the issues here, there have been earlier threads on this which show different possible approaches.

**Comment by barcitomor** [comment]
thank you very much for the detailed response I will absolutely try the second option it a very good lead to solve my problem thanks you again!

**Comment by o1dd** [comment]
@ronf 
Hi, I'm so exciting that I find this solved issue which confued me a long time before. Though I tried `create_process()` after reading the docs, I found it kind of hard to know when the output from a command ends and it is ready to accept the next command like you said.But I found an async function called `drain()` in `class asyncssh.SSHWriter` after reading docs and I thought if I can await the function and run new command after that. But, I tryied this way and it seems like it didn’t work and it confued me. Could you explain that or give me some explanation about how to use `drain()` ?

**Comment by ronf** [comment]
I don't think the `drain()` call will help you here. While it can be used to prevent from writing data too quickly (and potentially running out of memory as a result), it won't help you know when a command finishes and the remote system is back at a shell prompt waiting for you to send the next command. It also won't help you to know when you are done reading whatever output the command you run might generate.

As mentioned above, the best way AsyncSSH (or any SSH client) can know when a command finishes is to run each command in its own session, if the server supports this. If the server doesn't allow that, your only option which preserves your ability to see when commands finish is to open a new SSH connection for each command.

If you want to use an interactive shell to run multiple commands in a single session, you need to know what output to expect from each command you send, and you need to parse the output you get back from reading stdout/stderr looking for the end of the expected command output. Once you see that, you can then write the next command to stdin and again begin reading the output looking for the end of that command, repeating this process for each command you need to run.
