### ISSUE TITLE
Post Auth prompts/banners

### ISSUE THREAD

**Issue by lavih** [ronf/asyncssh#605]
Hey,
Thanks for the contribution great tool :)
I wanted to know if there is a built in handler for post auth prompts, or how can I solve this using
simple code.
Thanks

Example Code:
hostname="192.168.1.1"
username=""
password=""
sshkey=""
port = 22
known_hosts=None
command='df -ah'

async def run(hostname,username,port,password):
    async with asyncssh.connect(hostname,username=username,port=port,password=password,client_keys=sshkey,known_hosts=known_hosts) as ssh_conn:
      result = await ssh_conn.run(command)
      # parse the result using awk/python
      if "85" in result.stdout:
         print("Good disk space")

The issue is the server prompts for answer, ssh example:
##############################################
[test@srv ]# ssh user@192.168.1.1
user@192.168.1.1's password: 
# after entering correct password
Caution! All operations on the server or Unauthorized activities are monitored, Please press 'Y' to continue:
 (Press 'Y' to accept):
 
 and if I press 'Y' I can see the device terminal:
 [Device] #

**Comment by ronf** [comment]
If you use `create_process()` instead of `run()` on your SSHConnection, you will be given back an `SSHClientProcess` object which has members stdin, stdout, and stderr. If you know what the prompts look like, you can do an `await proc.stdout.readuntil()` with the expected prompt as an argument and block waiting for that to be sent and then use `proc.stdin.write()` to write whatever response is needed (don't forget to include a newline, if one is needed).

Once you get to the device prompt, you can continue with a similar pattern, alternating between providing input and reading back output interactively.

In some cases, if the remote system allows you to provide answers to the prompts without waiting for them to appear, you can also use `run()` by providing an `input` argument with all of the input that needs to be sent. You'll get a mixture of the prompts and the actual output in the result.stdout that you get back, but if you know what to expect here you can always filter those extra lines out. So, for instance, you might try adding `input='Y\n'` to `run()` in this example.

**Comment by lavih** [comment]
Thanks!

**Comment by lavih** [comment]
Hey sorry to re-open the issue, but I searched the docs and could not find how can I get the exit_status using create_process.
until now I was able to get the exit status like so:


hostname="192.168.1.1"
username=""
password=""
sshkey=""
port = 22
known_hosts=None
command='df -ah'

async def run(hostname,username,port,password):
  async with asyncssh.connect(hostname,username=username,port=port,password=password,client_keys=sshkey,known_hosts=known_hosts) as ssh_conn:
    result = await ssh_conn.run(command)
    if result.
    if result.exit_status == int(expected_exit_status):
      # do stuff
    else:
      # do stuff



**moving to create_process im getting always exit_status=None :**


async def run(hostname,username,port,password):
    async with asyncssh.connect(hostname,username=username,port=port,password=password,client_keys=sshkey,known_hosts=known_hosts) as ssh_conn:
        proc = await ssh_conn.create_process()
	proc.stdin.write('show system dns'+'\n')
	print(await read_timed(proc.stdout, 1))
	print(f"{proc.exit_status}")
        # also tried this, but still got none
	proc.stdin.write('exit 1'+'\n')
	print(f"{proc.exit_status}")


**read_timed**
```
async def read_timed(stream, timeout):
    """Read data from a stream with a timeout"""

    result = ''

    while True:
        try:
            result += await asyncio.wait_for(stream.read(1024), timeout=timeout)
        except asyncio.TimeoutError:
            return result
```


Thanks

**Comment by ronf** [comment]
As you saw, there are properties on the `SSHClientProcess` object for exit_status, exit_signal, and returncode similar to what can be found on the `ProcessError` and `SSHCompletedProcess` classes. However, you need to wait for the process exit status to be sent by the server. If you are using the process as an async context manager, it should be sufficient to just read those properties after exiting that context. Alternately, you can await on `wait_closed()` on the process and then access them, after you've done something which will trigger the process to close.

Note that it's possible for a server to close the connection without sending any exit status. In such cases, you may get back `None` even if you do the `wait_closed()` or exit the context.

**Comment by lavih** [comment]
So when I run create_process() and not run() I have to run this way?
```
proc.close()
await proc.wait_closed()
print(f"{proc.exit_status}")
```
when I run multiple commands I will have to keep create and close the process on each command to check the exit status of each line?
what would be the best practice programmatically?

Thanks

**Comment by ronf** [comment]
The SSH server (and as a result the AsyncSSH client) can only see the exit status for the command run when the session is started up. So, it works well when you actually create a separate session for each command you want to run, but in the case where you run an interactive shell, the SSH level will only be able to see the exit status of the shell. For that to work, you also probably shouldn't call close() on the process. Instead, just do something like `proc.stdin.write_eof()` if the command is waiting for input, or just directly await on `proc.wait_closed()` if the command exits on its own. Otherwise, the server might not have sent the exit status before receiving the close message.

If you want to start an interactive shell and run multiple commands on it by calling `proc.stdin.write()` and reading data back from stdout/stderr, you'll need to ask the shell what the exit status was for each of the commands it runs.

One way to do this would be to write "echo $?\n" after each command finishes and you are back at a shell prompt, and then parse out the line that the shell sends back with the exit status on it. You'll need to make sure you read all of the output from the command first, though, as well as any shell prompt that might appear if you are running with a pseudo-TTY. In fact, even the "echo $?" itself will probably be in the output and will need to be skipped over. There will also be another prompt output after the "echo $?"  finishes that you'll need to skip over as you prepare to run the next command. It's messy, but it's doable if you know enough about what kind of output to expect from each of the commands you are trying to run.

**Comment by lavih** [comment]
thank you for the detailed response.
since the ssh device I'm using offers only customized jail-shell with built-in commands
I can't use 'echo $?' and I did not find any customized command for this.

so assuming I want to run multiple commands and get the exit_status of each by starting an interactive shell,
is this the correct way to implement this? to close the process each time to get the output?

async def run(hostname,username,port,password):
  async with asyncssh.connect(hostname,username=username,port=port,password=password,client_keys=sshkey,known_hosts=known_hosts) as ssh_conn:
    # command 1
    proc = await ssh_conn.create_process()
    proc.stdin.write('show system dns'+'\n')
    print(await read_timed(proc.stdout, 1))
    proc.close()
    await proc.wait_closed()
    print(f"{proc.exit_status}")
    # command 2
    proc = await ssh_conn.create_process()
    proc.stdin.write('show system smtp'+'\n')
    print(await read_timed(proc.stdout, 1))
    proc.close()
    await proc.wait_closed()
    print(f"{proc.exit_status}")

**Comment by ronf** [comment]
Unfortunately, I'm not sure there's a way to do what you want. In a quick test here, the interactive shell you launch will not return the exit status of any of the commands you run inside it. Even if you only run one command and then try to close the shell, you'd need to tell the shell to run the "exit" command with the status value to return, but now you're back to needing to use something like `$?` in that shell to read the exit status to be returned.

If you pass the command to run directly rather than starting an interactive shell, you can get the exit status back for each command, but they'd have to each be run in their own session. It might be possible to do this over a single SSH connection, but only if the remote system allows you to start multiple sessions on it. In my experience, not all devices supporting SSH will support that.

**Comment by lavih** [comment]
I see, thank you for the guidance and insights.
I guess I will need to workaround this by evaluation of the output and based on that continue the logic rather depending on the exit_status.
