### ISSUE TITLE
Getting error when running script remotely.

### ISSUE THREAD

**Issue by anarchy89** [ronf/asyncssh#612]
I get this error when I run this script remotely.
```
commands = [f'/home/{REMOTEUSERNAME}/Documents/bashscript.sh'] # change to 1masterRun.sh and set trading amount 
asyncio.run(run_multiple_clients(hosts=ips, commands=commands, username=REMOTEUSERNAME, client_keys=[SSH_KEY_PATH]))
```
bashscript.sh looks like this
```
#!/bin/bash
username='ubuntu'
screen -dmS "pred" sh -c "python3 /home/${username}/Documents/pyscript.py; exec bash"
```

Error looks like this.
```
Traceback (most recent call last):
  File "/home/ubuntu/Documents/pyscript.py", line 73, in <module>
    from sklearn.preprocessing import RobustScaler, StandardScaler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 81, in <module>
    from .utils._show_versions import show_versions
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
```
It works fine if i run ./bashscript.sh directly from the remote server.

Any ideas?

I even tried adding export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD to .bashrc

**Comment by ronf** [comment]
This error doesn't appear to have anything to do with AsyncSSH. It seems to be in a Python package called "sklearn", which I'm not familiar with. Is this error traceback from the remote system? Is sklearn being invoked from pyscript.py?

If you try to run the bashscript.sh using OpenSSH, do you get the same error?

**Comment by anarchy89** [comment]
Hi @ronf I figured it out. 

It seems that commands in bashrc are not applied to the asyncssh session.

So I just had to add `export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD ` to the first line of the remote script I was running.

**Comment by ronf** [comment]
Ah - glad you figured it out!

If you're asking SSH to start a remote shell rather than running a command, it will run .bash_profile instead of .bashrc, since SSH treats the shell execution as a login shell. Bash only runs .bashrc when SSH is asked to execute a command. This is a function of the the SSH server on the target system, so it's not something you can control from AsyncSSH.

A lot of people change their .bash_profile to run .bashrc at the end, so that things in that get executed for both login and non-login shells.
