### ISSUE TITLE
Test if tunneled connection is alive

### ISSUE THREAD

**Issue by xbrianh** [ronf/asyncssh#615]
Is there a canonical way to test if a tunneled connection is alive?

For instance:
```
connection = await asyncssh.connect(addr, tunnel=tunnel_connection)
if not connection.is_alive:
    # deal with it
```

**Comment by ronf** [comment]
You can block waiting for a connection to be closed by doing an `await conn.wait_closed()`, either after calling `conn.close()` yourself, or to wait for the other side to initiate a close. You can also use the connection as a context manager with `async with`, in which case it will initiate the close and do the `wait_closed()` when you leave the block.

At the moment, there isn't a public method for polling to see if the connection is closed without waiting for it. In theory, that could be added easily enough, though. It'd look something like:

```python
    def is_closed(self):
        """Return whether the connection is closed"""

        return self._close_event.is_set()
```

Alternately, you can just catch the error if you try to use the connection to open a new session. AsyncSSH should raise a `ChannelOpenError` when you try to open a new channel on the connection.

**Comment by pyhedgehog** [comment]
You can use something like this pseudocode:
```python3
timeout = 1
conn_is_alive = True
conn_watchdog_tick = 0
def watchdog(orig_host, orig_port):
    conn_watchdog_tick = time.time()
    raise asyncssh.ChannelOpenError(
            asyncssh.OPEN_ADMINISTRATIVELY_PROHIBITED,
            'Connections only allowed from localhost')
testport = random.randint(1025,65535)
remote = await conn.create_server(watchdog, 'localhost', testport)
reader, writer = await conn.open_connection(MySSHTCPSession, 'localhost', testport)
writer.close()
await writer.wait_closed()
conn_is_alive = (time.time()-conn_watchdog_tick)<timeout
```

**Comment by xbrianh** [comment]
Thanks @ronf that helped! And you too, @pyhedgehog

**Comment by ronf** [comment]
I'd be a bit nervous about setting up port forwarding as a way to test this. Some of the ports could be in use by other applications, so you might not be able to open them. Also, this would need you to close the listener (`remote.close()`) if you don't want all those listeners to stay around. All in all, it seems like a very heavyweight way to do this.

I'm thinking it may be worth adding the `is_closed()` I mentioned above, so it will be available in a future version for anyone who needs it. That said, though, I still recommend just catching the error if you try to use an SSH connection which was closed. You probably need to do that anyway, since there's a race between calling `is_closed()` or anything similar and actually making your connection. So, why not always rely on that?

**Comment by pyhedgehog** [comment]
@ronf you are right about both "port can be busy" and "havy ops". That's why `autossh` not embedded into `ssh`. :-)
