### ISSUE TITLE
Connection number reset

### ISSUE THREAD

**Issue by SeniorK0tik** [ronf/asyncssh#617]
Is logs "conn" number set for python session ?
Is it possible to reset? 
It increments even a connection is closed.

```
INFO:asyncssh:[conn=0] Auth for user kotik succeeded
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
...
INFO:asyncssh:[conn=1] Auth for user kotik succeeded
INFO:asyncssh:[conn=1, chan=0] Requesting new SSH session
...
```

**Comment by ronf** [comment]
This is by design, so that the logs always show a unique connection identifier. It doesn't appear anywhere on the wire -- it is just meant for debugging.

Even if you wanted to reset this counter (which I don't recommend), AsyncSSH doesn't keep track the connection IDs of connections which are still open, so there's no way for it to skip over IDs of connections that are still open. Keeping track of connection IDs in use and finding the lowest unused connection number could also get very expensive in cases where there are a large number of connections remaining open.

**Comment by SeniorK0tik** [comment]
Ok. Thanks.
