### ISSUE TITLE
Potentially allow passing of SSH connection waiter (Future) into SSHConnectionOptions and SSHClientConnectionOptions

### ISSUE THREAD

**Issue by eytanschulman** [ronf/asyncssh#620]
Hello,
While developing using asyncssh, I stumbled upon the fact that the class `SSHConnectionOptions` provides the instance variable `waiter`, which allows one to `await` for authentication to be established on a connection.

This is a very useful feature, but it seems that the `prepare()` functions of `SSHConnectionOptions` and `SSHClientConnectionOptions` do not permit this variable.

Of course one can get around this by creating an instance of `SSHClientConnectionOptions` and setting the `waiter` outside the initialization, but it seems more elegant to include it within the initialization.

Thank you 😃

**Comment by ronf** [comment]
When you do an `await` on `asyncssh.connect()` it is already waiting until authentication is successfully completed before returning. If an error occurs either when connecting or when authenticating, an exception will be raised. If it returns an SSHConnection object, that means auth has succeeded.

Changing the value of `waiter` is a bad idea, as that will prevent the `connect()` call from unblocking correctly.

**Comment by eytanschulman** [comment]
I understand, in my case I'm initializing an existing `SSHClientConnection` myself instead of calling `connect()`

Out of curiosity, what is the current purpose of `waiter` being established on `SSHConnectionOptions` as it isn't exposed?

I noticed that it was added in [this commit](https://github.com/ronf/asyncssh/commit/09874319c7111f6177cffe952178bd9f29a86cc4) which removed the function `wait_established()`.

**Comment by ronf** [comment]
In order for cancellation to work correctly in all cases, it was important that the "waiter" object be created even before the SSHConnection object is, and so it couldn't just be a member of the SSHConnection set up in its constructor. Using "options" for this was arguably a bit lazy on my part, but there's a precedent already for the `options` object to hold information to pass to the `_connect()` or _listen()` internal functions called from the public API (`connect()`, `connect_reverse()`, etc.). So, I used this object to hold `waiter`, but didn't make it settable through the SSHConnectionOptions constructor. Another example of this is `family`, which  is an parameter to the public API functions passed to the internal functions via options, even though it is not one of the fields allowed in an SSHConnectionOptions constructor.

Directly instantiating SSHClientConnection is actually not supported. The class is public because there are APIs on it that are public, but it's not meant to be constructed directly from application code. Why would you want to do this instead of calling one of the documented APIs? They are meant to effectively act as constructors, returning an SSHClientConnection or SSHServerConnection, or a listener which creates one of those, mirroring the pattern of `asyncio.create_connection()` for opening plain TCP connections.

To be honest, I'm surprised you got this to work at all -- you need to actually construct this object from within a callback function associated with the asyncio socket API for things to work correctly, effectively duplicating code in the public asyncssh.connect() function, or one of the other variants of it.

**Comment by eytanschulman** [comment]
Understood, thank you! Migrating to usage of the public `connect()` method seems like the right thing for me to do.
