### ISSUE TITLE
Failure in limiting ciphers during the process of creating connection.

### ISSUE THREAD

**Issue by devfinwiz** [ronf/asyncssh#623]
```
async def _connect(self):
        logger.debug("Connecting to remote host {}".format(self._kwargs["host"]))
        self._conn, _ = await asyncssh.create_connection(SSHClient, **self._kwargs)
        logging.debug("Connection Successful.")
        return self._conn
```

The above is my code snippet. I need help with limiting ciphers used while creating connection. Something like this:

```
async def _connect(self):
    logger.debug("Connecting to remote host {}".format(self._kwargs["host"]))

    # Add 'ciphers' to the keyword arguments if it's supported
    if 'ciphers' not in self._kwargs:
        self._kwargs['ciphers'] = 'aes256-ctr,aes256-cbc,aes128-ctr'

    self._conn, _ = await asyncssh.create_connection(SSHClient, **self._kwargs)

    logging.debug("Connection Successful.")
    return self._conn
```
**OR this:** 
```
async def _connect(self):
        PREFERRED_CIPHERS=["aes256-gcm", "aes128-gcm", "aes256-ctr", "aes192-ctr", "aes128-ctr"]
        logger.debug("Connecting to remote host {}".format(self._kwargs["host"]))
        self._conn, _ = await asyncssh.create_connection(SSHClient, ciphers=PREFERRED_CIPHERS, **self._kwargs)
        logging.debug("Connection Successful.")
        return self._conn
```

Since, create_connection method does not directly accept the ciphers parameter, how can I do it? Can you help me with a workaround?

**Comment by ronf** [comment]
Anything showing up in SSHClientConnectionOptions can be used as keyword arguments on the connection functions such as `asyncio.connect()` and `asyncio.create_connection()`.

For ciphers in particular, you can replace `ciphers=` in your sample code with `encryption_algs=`.

Note that if you are passing in `SSHClient` to `create_connection()`, you're probably better off using `asyncio.connect()` instead. This will also avoid you needing to ignore the second return value there.

**Comment by ronf** [comment]
> As far as I know, if one is dealing specifically with SSH connections and SSHClient, create_connection() might be more suitable. If one is working with generic stream connections, asyncio.connect() could be a simpler option. This is what I came across while reading up about things in this context.

If you want to create your own subclass of `SSHClient` for some reason, and you want to get back not only the `SSHClientConnection` object but also the specific instance of your `SSHClient` subclass created when connecting, you'll probably want to use `asyncssh.create_connection()`. However, if you want the connection to use an instance of the default `SSHClient` class provided in AsyncSSH, then it's a bit cleaner to use `asyncssh.connect()`.

In both cases, it defaults to `SSHClient` as the `client_factory`. However, the two differences are:

- Calling `asyncssh.create_connection()` lets you pass in an alternate `client_factory` as the first positional argument, rather than having to pass it as a `client_factory` keyword argument.
- Calling `asyncssh.create_connection()` returns the instance created by `client_factory` along with the `SSHClientConnection` as a tuple, mirroring how other asyncio calls return a tuple of transport and protocol. Calling `asyncssh.connect()` returns only the `SSHClientConnection` which is usually all you need, though the `client_factory` instance can be retrieved later by calling `conn.get_owner()`.

**Comment by devfinwiz** [comment]
Hello @ronf ,
I have one more query about a similar issue. If I also want to limit my code to using certain mac algorithms, I can do it with mac_algs argument, right? 
When I did so through the keyword arguments, the code failed. 

`AsyncIOThread asyncssh: INFO - [conn=85] Sending disconnect: No matching MAC algorithm found, sent hmac-sha256-2@ssh.com,hmac-sha224@ssh.com,hmac-sha256@ssh.com,hmac-sha384@ssh.com,hmac-sha512@ssh.com and received umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 (3)"`

**Comment by ronf** [comment]
Yes - mac_algs is correct here. However, it looks like you are selecting only algorithms supported by the commercial version of SSH (Tectia SSH), none of which are supported by OpenSSH. As a result, there's no overlap between the algorithms you requested and the algorithms supported by the remote peer you are trying to connect to. The detailed list of what you request and what the peer returned are in the debug message you quoted here.

For things to work, at least one of the algorithms in the "received" list would need to be in your "sent" list.

**Comment by devfinwiz** [comment]
Thank you so much for the insights @ronf !
