### ISSUE TITLE
sftp.symlink does not honor the current path

### ISSUE THREAD

**Issue by Joschasa** [ronf/asyncssh#627]
While the oldpath variable is converted to the full path (e.g. after a chdir()), newpath is not.

Example code to illustrate the issue:
```python
import asyncio

import asyncssh


async def main():
    async with asyncssh.connect(
        host="localhost", port=2022, username="demo", password="demo", known_hosts=None
    ) as conn, conn.start_sftp_client() as sftp:
        print("Initial state")
        print("  cwd:", await sftp.getcwd())
        print("  files:", await sftp.listdir())

        await sftp.mkdir("directory")
        await sftp.chdir("directory")
        await sftp.put("main.py", "main.py")
        print("After setup")
        print("  cwd:", await sftp.getcwd())
        print("  files:", await sftp.listdir())

        await sftp.symlink("main.py", "link_to_main.py")
        print("After symlink")
        print("  cwd:", await sftp.getcwd())
        print("  files:", await sftp.listdir())

        print("Check initial folder")
        await sftp.chdir("..")
        print("  cwd:", await sftp.getcwd())
        print("  files:", await sftp.listdir())


asyncio.run(main())
```
(I used `docker run -p 2022:22 emberstack/sftp -v ./sftp.json:/app/config/sftp.json:ro` with [sftp.json](https://github.com/emberstack/docker-sftp/blob/main/samples/sample.sftp.json)

Output:
```text
Initial state
  cwd: /sftp
  files: ['..', '.']
After setup
  cwd: /sftp/directory
  files: ['main.py', '..', '.']
After symlink
  cwd: /sftp/directory
  files: ['main.py', '..', '.']
Check initial folder
  cwd: /sftp
  files: ['directory', 'link_to_main.py', '..', '.']
```

Expected behavior:
I would expect the link to be placed in the current directory, similar to the behavior of sftp.link():
```text
Initial state
  cwd: /sftp
  files: ['..', '.']
After setup
  cwd: /sftp/directory
  files: ['main.py', '..', '.']
After link
  cwd: /sftp/directory
  files: ['main.py', 'link_to_main.py', '..', '.']
```

**Comment by ronf** [comment]
I haven't been able to reproduce this exactly yet, but I am seeing some other strange behavior when running this test code against a regular OpenSSH server that I need to look into. It's reporting a generic "failure" when trying to make the link.

In your case, it looks like you might be running emberstack, which I'm not familiar with. However, there is a known issue with OpenSSH and paramiko where they have implemented the arguments to "symlink" backwards. AsyncSSH tries to work around this by detecting the remote server type, but if emberstack is sending its own name there instead of OpenSSH (which is what it seems to be based on), that would potentially prevent the auto-detect from working. 

Do you know what emberstack returns as its version string?

If this is the issue, you could edit the following in `SFTPHandler` in sftp.py:

```python
    # SFTP implementations with broken order for SYMLINK arguments
    _nonstandard_symlink_impls = ['OpenSSH', 'paramiko']
```

You'd just need to add whatever emberstack provides as a version to that list, assuming it is based on OpenSSH and thus needs the arguments in the opposite order.

**Comment by ronf** [comment]
Yes - you're on to something here. You're right that the code should have been calling `self.compose_path()` on newpath. However, it should have been calling only `self.encode()` on oldpath. The reason for this is that when setting the "value" of the link, it needs to be exactly what the caller specifies, which may be either an absolute or relative path, and when it is a relative path, it will be up to the server to interpret that as being relative to whatever destination directory the symlink exists in. At the time of link creation, no modification should be done on the value of the link.

I just tried the following, and I think it fixes the problem you're seeing:

```patch
diff --git a/asyncssh/sftp.py b/asyncssh/sftp.py
index 96f1e6a..365ba1e 100644
--- a/asyncssh/sftp.py
+++ b/asyncssh/sftp.py
@@ -5329,8 +5329,8 @@ class SFTPClient:

         """

-        oldpath = self.compose_path(oldpath)
-        newpath = self.encode(newpath)
+        oldpath = self.encode(oldpath)
+        newpath = self.compose_path(newpath)
         await self._handler.symlink(oldpath, newpath)

     async def link(self, oldpath: _SFTPPath, newpath: _SFTPPath) -> None:
```

Could you give it a try and see if it works for you?

**Comment by ronf** [comment]
I did some additional testing of this change against both OpenSSH and AsyncSSH servers (with and without chroot), and the test client provided here got the correct result in all cases, so I've gone ahead and put this in the "develop" branch as commit 3807b64. This will be included in the next release.

Thanks again for reporting this, and providing code to reproduce it!

**Comment by Joschasa** [comment]
The changes seem to work fine, thanks for fixing it :)
