### ISSUE TITLE
Feature: Equivalent to `-o HostKeyAlgorithms=+ssh-rsa`

### ISSUE THREAD

**Issue by SamuilDichev** [ronf/asyncssh#630]
`asyncssh` seems to support passing kwargs to `connect`. And I can pass `server_host_key_algs`

But that seems to replace all the algorithms that will be considered, which I think makes it not equivalent to `ssh -o HostKeyAlgorithms=+ssh-rsa` which seems additive.

Is there a supported way currently of doing it? At least I couldn't find it in the docs and it would be nice to have it as an option.

**Comment by ronf** [comment]
If you pass the server_host_key_algs value as a string rather than a list of strings, it will honor the '+', '-', and '^' prefixes that are supported by OpenSSH, and the resulting list will be based on the default values modified by whatever you include in your string. This should work in both the config file and when passing in a string argument.

**Comment by SamuilDichev** [comment]
That's neat, it will work for my use case! Thanks for the quick response.

I guess if the feature exists then I'm happy to close this. Unless you want to leave it open for docs?

**Comment by SamuilDichev** [comment]
Ah, that's my bad. No idea how I missed it, I could have sworn I used the search at the bottom and searched for "server_host_key_algs" but now I'm finding it and earlier I did not. Maybe I misspelled it.

**Comment by ronf** [comment]
No problem - I'm going to close this, but feel free to open a new issue if you have further questions...
