### ISSUE TITLE
Cannot ignore certificate  to check 'known_hosts'

### ISSUE THREAD

**Issue by jjohnson42** [ronf/asyncssh#632]
In openssh, by default, I get a warning, but it continues to check known_hosts the old fashioned way:
```
$ ssh test@localhost
Certificate invalid: name is not a listed principal
test@localhost's password: 
```
If I felt so inclined, I can suppress even that by:
```
$ ssh -o HostKeyAlgorithms=-*-cert-* localhost
test@localhost's password:
```

However, in asyncssh, it seems that a failed principal check fails out without a chance to fallback to checking the known_hosts.  Further, I can't seem to surpress the cert hostkeyalgorithms in this regard with server_host_key_algs, whether by blocking the -cert- algorithms or explicitly specifying a 'key-plain'.

**Comment by ronf** [comment]
I think I've been able to reproduce these issues here. Thanks for the report!

Once there is a known_hosts entry for a certificate authority, a principal mismatch seems to trigger an immediate failure without looking for other potential matches. I also wasn't able to stop this behavior by disabling the certificate-based server host key algorithms, and saw some other weirdness with trying to expand the glob on that. Even just explicitly setting the server_host_key_algs to 'ssh-ed25519' didn't help, though I did get a different error there ("Host key is not trusted" vs. "Certificate principal mismatch for host", so setting server_host_key_algs is doing SOMETHING. In my test, though, there should have been an available ssh_ed25519 plain host key that was listed in known_hosts, and so that should have succeeded.

I'll need some more time to get to the bottom of these two issues and look for potential fixes.

**Comment by jjohnson42** [comment]
Ok, realize that is a variant, that if I have the specific key *and* don't have the CA, then it doesn't care. So this is less problematic than I thought it was, because a user without a relevant CA will not see the problem.

In my use case, practically speaking, the software will have access to the CAs *and* be using the right principles, it just manifested odd when doing a quick test with 'localhost'.  For others' use cases the certificate shouldn't make a difference if they don't have it (they will get a slightly different ValueError as asyncssh fixates on the CA while ssh just pretends the cert doesn't exist, but functionally equally useful).

**Comment by ronf** [comment]
That's right - none of the certificate checking will even be attempted unless there's a matching "@cert-authority" line in `known_hosts`.

Looking at the code, the server cert's principal doesn't actually get verified until quite a bit later than the `known_hosts` check. It actually happens as part of the key exchange, just before validating the signature in the key exchange. To get AsyncSSH to fall back and allow a different key to be checked may not be a simple change, and might actually require changes to the messages send to the origin server, which I'd prefer to avoid. It might be possible in the case where the plain `known_hosts` entry uses the exact same public key as the key present in the cert, but that wouldn't always be the case, and the only way to get the server to send a different key would probably be to re-do the KEXINIT with a different set of server_host_key_algs.

Also, I took a closer look at disabling cert algorithms on the client via server_host_key_algs. It's a bit inconsistent to do this when there are matching "@cert-authority" lines in `known_hosts`, but as long as there is at least one matching known_hosts entry for a plain key, this seems to work. The cert algorithms are removed, leaving only the plain alg and the server no longer sends a certificate, just like in the case where there's no matching "@cert-authority" lines.

If you attempt to remove the cert algorithms without any matching plain keys in `known_hosts`, you get a different error, but it completely makes sense:

`SSH connection failed: No matching key exchange algorithm found, sent  and received sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-s,kex-strict-s-v00@openssh.com`

Note that there are two space after "sent" here -- basically, AsyncSSH ends up with an empty server host key algs in this case since the only `known_hosts` entries were for certificates but then you removed all of those.
