### ISSUE TITLE
How to distinguish clients when using key-based auth

### ISSUE THREAD

**Issue by rojamit** [ronf/asyncssh#642]
AsyncSSH server, how to get "label/username" associated with client key in ssh_user_ca? (for example root@pc in the end of key)

Or how to get key of the connecting user? (need to identify users by key)

**Comment by ronf** [comment]
You can get information about the connection using the `get_extra_info()` method. In particular, the username is available there using the name 'username'. You can also get information about the IP address of the client using the name 'peername', like you can for asyncio TCP sockets.

The public key sent by the client is not currently stored in AsyncSSH. Also, keep in mind that in some cases the client public key may not be directly in the authorized_keys list. If the client is using SSH certificates, only the CA which signed the client certificate would need to be present in authorized_keys, so there wouldn't be any comment associated with the specific client key to return here. In such cases, AsyncSSH will compare the client's requested username against the principal name in the certificate, though, so getting the 'username' value is probably your best option.

**Comment by rojamit** [comment]
Unfortunately i cant use 'username' from get_extra_info() because its used for another purpose in my project.

I need public key of the connecting user, comment is not so important
How i can do this?

**Comment by rojamit** [comment]
cut off my hands for this code but it works...
`from asyncssh.connection import SSHServerConnection

async def patched_validate_public_key(cls, username, key_data, msg, signature):
    cls.user_pubkey_b64 = base64.b64encode(key_data)
    return await cls.original_validate_public_key(username, key_data, msg, signature)
        
SSHServerConnection.original_validate_public_key = SSHServerConnection.validate_public_key
SSHServerConnection.validate_public_key = patched_validate_public_key`

user_pubkey_b64 is now accessible inside class MySSHServerSession(asyncssh.SSHServerSession) via channel._conn.user_pubkey_b64

**Comment by ronf** [comment]
It is possible to do something similar to what you're doing here without monkey-patching, but the complexity will depend on whether you still want to support things like SSH certificates or the ability to choose the set of keys/certificates to trust based on the SSH config file. If you can get by with a flat list of public keys to trust, it would look something like:

```python
import asyncio, asyncssh, sys

class MySSHServer(asyncssh.SSHServer):
    def connection_made(self, conn):
        self._conn = conn
        self._auth_keys = asyncssh.read_public_key_list('ssh_keys')

    def public_key_auth_supported(self):
        return True

    def validate_public_key(self, username, key):
        if key in self._auth_keys:
            self._conn.set_extra_info(client_key=key)
            return True
        else:
            return False

async def handle_client(process):
    process.stdout.write('Welcome to my SSH server, %s!\r\n' %
                         process.get_extra_info('username'))
    process.stdout.write('Key fingerprint: %s\r\n' %
                         process.get_extra_info('client_key').get_fingerprint())
    process.exit(0)

async def start_server():
    await asyncssh.create_server(MySSHServer, '', 8022,
                                 server_host_keys=['ssh_host_key'],
                                 process_factory=handle_client)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```

The trusted keys are loaded from a file named 'ssh_keys' in this case, and the client-provided key is compared against each of the public keys in that file. If one matches, it records the client key in the "extra info" and returns that auth has succeeded. If auth ends up succeeding without a key (via a password for instance), the extra info won't be filled in, and you'll get back a `None` value if you try to query extra info for 'client_key'. Note that the above example code doesn't handle `None` right now.

If you wanted to support a full authorized_keys file instead of just a list of public keys, that wouldn't be too hard, and that could also let you support SSH certificates. However, you'd need to decide what you wanted to record in that case as the client_key, since with SSH certificates the server wouldn't normally know all the possible public key values in advance.

**Comment by rojamit** [comment]
@ronf Initially i tried to make this work as you described, but ended up with monkey-patching because validate_public_key method wasn't being called

Now i realized:
It works only after removing "authorized_client_keys='ssh_user_ca'" argument of asyncssh.create_server method

Thanks!

**Comment by rojamit** [comment]
ah, now def session_requested(self) method wasnt being called...

**Comment by ronf** [comment]
The `session_requested()` method is only called if you don't specify a process_factory, session_factory, or sftp_factory. If you want to use this callback instead of the parameters to decide what code to run when a new session is requested, just take out these arguments from your `create_server()` call.

Also, you're right that this will only work if you don't set authorized_client_keys. If that is set, AsyncSSH will first try to compare against the keys listed there before calling the `validate_public_key()` or `validate_ca_key()` callbacks.

**Comment by rojamit** [comment]
@ronf 

```
class MySSHServer(asyncssh.SSHServer):
    def session_requested(self) -> asyncssh.SSHServerSession:
        print('session_requested')
        return MySSHServerSession()

    def public_key_auth_supported(self):
        return True
        
    def validate_public_key(self, *kwargs):
         print('validate_public_key', kwargs)
         return True

async def start_server() -> None:
    await asyncssh.create_server(MySSHServer, '', 2222,
                                 server_host_keys=['ssh_host_key'],
                                 authorized_client_keys='ssh_user_ca',
                                 reuse_port=True)
```


If i remove the authorized_client_keys arg from create_server, validate_public_key will be called, but session_requested doesn't

If i keep authorized_client_keys, only session_requested will be called.
How to have both callbacks?

MySSHServerSession is a class MySSHServerSession(asyncssh.SSHServerSession)

**Comment by rojamit** [comment]
Hm, i have both callbacks with `authorized_client_keys=[]`, strange behavior but it works as i want

**Comment by ronf** [comment]
I tried your code above here with "authorized_client_keys" removed, and I got the following output:

```
validate_public_key ('ronf', <asyncssh.rsa.RSAKey object at 0x106b26590>)
validate_public_key ('ronf', <asyncssh.rsa.RSAKey object at 0x106b26750>)
session_requested
```

As expected, both callbacks are called here. This was the complete version I tested:

```python
import asyncio, asyncssh, sys

class MySSHServer(asyncssh.SSHServer):
    def session_requested(self) -> asyncssh.SSHServerSession:
        print('session_requested')
        return asyncssh.SSHServerSession()

    def public_key_auth_supported(self):
        return True

    def validate_public_key(self, *kwargs):
         print('validate_public_key', kwargs)
         return True

async def start_server() -> None:
    await asyncssh.create_server(MySSHServer, '', 8022,
                                 server_host_keys=['ssh_host_key'],
                                 reuse_port=True)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```

Assuming authentication succeeds and your SSH client requests a session to be opened, the only way that `session_requested()` wouldn't be called is if you passed in process_factory, session_factory, or sftp_factory when starting up the server. In that case, the values you provide there would be used to construct the session instead of calling the `session_requested()` callback.

Since you say it is working for you with `authorized_client_keys=[]`, I wonder if authorized_client_keys is getting set some other way. Are you by chance using an SSH config file which sets AuthorizedKeysFile, or perhaps calling `set_authorized_keys()` explicitly somewhere? AsyncSSH doesn't use any server config file by default, but it does let you specify one.
