### ISSUE TITLE
getting Permission denied (publickey) 

### ISSUE THREAD

**Issue by rahulcode60** [ronf/asyncssh#652]
Hi, 

**I am trying to connect to server which is using listen method and the code looks something like this** 

**Code -**
import asyncio
import asyncssh
import sys
import logging
from asyncssh import SSHServerConnectionOptions

logging.basicConfig(level=logging.DEBUG)

asyncssh.set_debug_level(2)

options = SSHServerConnectionOptions(
    authorized_client_keys =['/home/ac/.ssh/authorized_keys'],
    x509_trusted_cert_paths=["/home/ac/pkixssh/"]
)

def handle_client(process: asyncssh.SSHServerProcess) -> None:
    process.stdout.write('Welcome to my SSH server, %s!\n' %
                         process.get_extra_info('username'))
    logging.debug("Handling client connection")
    process.exit(0)

async def start_server() -> None:
    await asyncssh.listen('ip', port=2222, config="/home/ac/pkixssh-14.2.1/sshd_config", process_factory=handle_client, options=options)

loop = asyncio.get_event_loop()

try:
    logging.info("SSH server is listening on port 2222...")
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    logging.error('Error starting server: %s', exc)
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()

**on client side when I initiate connection I get this error.**

debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
Offering public key: 'x509v3-rsa2048-sha256' certs/server-ssh_test.pem RSA+cert SHA256:q+Q6xfBbPKr9FL8Dj6m0cssMvucidlYNgAD2XZcPnAU explicit
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
ac@ip: **Permission denied (publickey).**

I have proper file permission to .ssh and /.ssh/authorized_keys

**Comment by ronf** [comment]
I see that you are using a mixture of authorized_client_keys and x509_trusted_cert_paths. You may not need the latter, if you convert your X.509 certificates into OpenSSH format. This gives you a bit more flexibility around which CAs are trusted for which client IPs or usernames. However, if you want to keep your certificates in PEM format, it should be possible to use a mixture of the two.

Since you are using "x509_trusted_cert_paths" here instead of "x509_trusted_certs", AsyncSSH is expecting the directory you specify to conform to the OpenSSL "hash directory" naming for the files inside it. You need to run a command such as `openssl x509 -hash -noout -in cert.pem` to get the hash value for a cert and then create a filename where you append ".0" to the end of the hash (or ".1", ".2", etc. in the unlikely event that multiple certs map to the same hash value) to form the filename you use for that cert in the hash directory.

What does your certificate hierarchy look like here? Do you have self-signed certs, or do you have a separate root CA? Do you have any intermediate CAs?

What are you putting in your authorized_client_keys file? If you have certificate paths defined elsewhere, you can get by with something like the following in your authorized_keys:

x509v3-ssh-rsa Subject:**_subject_prefix_**,*

The ",*" at the end here means to trust all certificate subjects which begin with the specified prefix.

In addition to the above checks, AsyncSSH will look to see if client certificates contain the SubjectAlternativeName extension with values of type 'email'. The associated names resulting names will be compared against the username attempting to authenticate once the certificate chain has been validated and successfully chained up to a trusted root CA. If there's no SAN extension, AsyncSSH will also look for a CN value in the subject name and use that as the only username allowed to log in with that cert. If both are missing, then any cert which chains up to a trusted root and matches the subject rule above would be allowed to log in as any user (which you may or may not want).

The authorized key file can also do explicit matching on subject CN values, but then you typically need to load a different authorized_keys file for each user. This can be done within a `begin_auth()` callback, but I wouldn't recommend this unless you wanted to have something like different root CAs for different users, which sort of defeats the point of using certificates.

**Comment by rahulcode60** [comment]
Hi @ronf,

**I have root ca and hostkey on these paths  in 
sshd_config -**
HostKey /home/ac/pkixssh/Syslog_VM1.pem
CACertificateFile /usr/local/etc/ca/crt/AcumenROOT.crt
CACertificatePath /usr/local/etc/ca/crt/d5bbb589.0

**I don't have any intermediate CA's.**

**I authorized_keys file I have this** 
x509v3-rsa2048-sha256 subject= CN=expcore.ac.local,OU=CC,O=abc,L=LAB,ST=NC,C=US

**Comment by ronf** [comment]
I see you are passing in "x509_trusted_cert_paths", but the pathname you are using there is different than what you mentioned in the sshd_config file. Is that path correct?

Also, I don't see you pass in the root CA to AsyncSSH (via "x509_trusted_certs"). You might want to add that into your SSHServerConnectionOptions call, pointing at the file containing the root CA which is signing the cert the clients are sending. See if that fixes your validation problem.

As an aside, the CACertificatePaths you show here in sshd_config doesn't look right to me. That's generally supposed to be a directory name containing the cert hash values, but here you are passing in one of the individual files in that directory.

Regarding not having an email value in the SAN, I think that will mean that AsyncSSH will allow that cert to be used to log in as any user, which may not be what you want. It doesn't really make sense here to pass in a DNS value in a client cert. You'd generally only do that if you were creating an X.509 server cert.

**Comment by rahulcode60** [comment]
Hi @ronf,

This was the updated SSHServerConnectionOptions I used and forgot to mention. 


options = SSHServerConnectionOptions(
    authorized_client_keys =['/home/acumensec/.ssh/authorized_keys'],
    #x509_trusted_cert_paths=["/home/acumensec/pkixssh/"]
    x509_trusted_cert_paths=["/usr/local/etc/ca/crt/","/home/acumensec/pkixssh/"],
    x509_trusted_certs  =['/usr/local/etc/ca/crt/AcumenROOT.pem'],
    #x509_trusted_certs= None,
    x509_purposes = None

)

**Comment by ronf** [comment]
Glad to hear you got it working!

AsyncSSH includes some good helper functions for generating certificates (both OpenSSH-style and X.509) if you need to create custom certs for specific user or host principals. It also automatically sets some other parameters the the key usage and extended key usage in X.509 certs to be compatible with use for SSH (though you can also override that if you want to use AsyncSSH to create certs for other purposes like HTTPS). Let me know if you need any help with how to use those. I'll also work with certs generated by other tools like OpenSSL, of course, but that takes a bit more effort to get everything configured right.

**Comment by rahulcode60** [comment]
Thanks @ronf. I will definitely try using asyncssh to generate certs and If I face any issues will ask for help.

Closing this ticket.
