### ISSUE TITLE
Suggestion Re Simple Client Example:

### ISSUE THREAD

**Issue by kwmartin** [ronf/asyncssh#681]
For a new user, not having the first simple example work can be a negative experience
__version__ = '2.16.0'
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
Python: 3.10

First run:
```
The program exited via sys.exit(). Exit status: SSH connection failed: Host key is not trusted for host localhost
```
Most users don't have localhost included in ~/.ssh/known_hosts. Suggestion: state this requirement
Work around: before running example run ` >ssh localhost` and type yes to include localhost in known_hosts
After doing workaround:
Second run:
```
> python3 tst_asyncssh.py
python3: can't open file '/home/martin/tst_asyncssh.py': [Errno 2] No such file or directory
```
This is because the example used runs the remote command: `ls abc` and most users won't realize (without some work) that this command fails unless there is a file or directory in their home directory on the remote machine named 'abc'. Wouldn't it be more straightforward to have an example that normally works such as changing line 5 of example  from `result = await conn.run('ls abc', check=True)` to something like `result = await conn.run('hostname', check=True)`. After this change,
Third run:
```
> python3 tst_asyncssh.py
g22
```
and we finally have the example working. Also, I'm guessing the output of Second run is the sdterr of Python's subprocess.communicate. Internally in asyncssh at process.py:1452, we have:
```
> /usr/local/lib/python3.10/dist-packages/asyncssh/process.py(1452)communicate()
-> return self.collect_output()
(Pdb) p self.collect_output()
('', "ls: cannot access 'abc': No such file or directory\n")
(Pdb) 
```
If this was printed out, it would considerably help a newbie understand what went wrong with the example.
Just some suggestions: the realization of ssh needing localhost included in known_hosts is useful information for me (so the time invested isn't all a waste).

**Comment by ronf** [comment]
Thanks for the feedback! See my response below.

> Most users don't have localhost included in ~/.ssh/known_hosts. Suggestion: state this requirement

If you take a look at https://asyncssh.readthedocs.io/en/stable/#client-examples, it currently says the following just above the first example:

    The following code shows an example of a simple SSH client which logs into localhost and
    lists files in a directory named ‘abc’ under the user’s home directory. The username provided
    is the logged in user, and the user’s default SSH client keys or certificates are presented during
    authentication. The server’s host key is checked against the user’s SSH known_hosts file and
    the connection will fail if there’s no entry for localhost there or if the key doesn’t match.

Was there something more you were looking for here? I could add a sentence around running "ssh localhost" to get the key added, but my expectation is that most AsyncSSH users are already familiar with the basics of SSH, like how user authentication and server host key checking works. Also, without knowing the config of OpenSSH on the system, I can't count on `ssh localhost` always prompting to add a server host key to known_hosts.

I intentionally avoided including `known_hosts=None` to disable host key checking in the example as I didn't want to encourage insecure behavior. I wanted it to fail if the server host key wasn't trusted.

> This is because the example used runs the remote command: ls abc and most users won't realize (without some work) that this command fails unless there is a file or directory in their home directory on the remote machine named 'abc'.

You're right that I could have used a command which would be less likely to fail, like `hostname`. The text above the example clearly states what the command is attempting to do, though, and I chose that in part so that there would be a chance it could fail, triggering a Python exception rather than just outputting an error back on stderr. Note that this example includes the `check=True` argument, which is what triggers it to turn the failure into an exception.

That said, the example doesn't do a very good job explaining what comes back. The current output is something like:

    SSH connection failed: Process exited with non-zero exit status 1

I could have the example catch the exception in `conn.run()` explicitly, and have it print out `result.stderr` instead of `result.stdout`. It makes the example a bit longer, but it could be worth it to make it clearer what's going on. For example:

```python
import asyncio, asyncssh, sys

async def run_client() -> None:
    async with asyncssh.connect('localhost') as conn:
        try:
            result = await conn.run('ls abc', check=True)
        except asyncssh.ProcessError as exc:
            print('ERROR:', exc)
            print(exc.stderr, end='')
        else:
            print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

I might rework this a bit more to move up the try block at the bottom and avoid a deprecation warning related to the use of `get_event_loop()`, but this should give you a rough idea of what I had in mind. What do you think?
