### ISSUE TITLE
Incorrect Type Inference on SSHReader, SSHWriter methods

### ISSUE THREAD

**Issue by xBiggs** [ronf/asyncssh#687]
```py
#! /usr/bin/env python3
import asyncio
from contextlib import asynccontextmanager

import asyncssh

@asynccontextmanager
async def google_ssh_tunnel(hostname: str):
  async with asyncssh.connect(hostname) as conn:
    try:
      [reader, writer] = await conn.open_connection('google.com', 80)
      yield reader, writer
    finally:
      writer.close()
      await writer.wait_closed()

async def main():
  async with google_ssh_tunnel(host) as [reader, writer]:
      writer.write(b'GET / HTTP/1.1\r\n\r\n')
      await writer.drain()
      res = await reader.readuntil(b'\r\n\r\n')
      print(res)

if __name__ == '__main__':
  asyncio.run(main())
```
I'm not getting the correct type inference on the `SSHReader` and `SSHWriter` streams.
`write(data)` is accepting `data: Unknown` instead of `data: str | bytes`
`read()` and friends are returning `Unknown`  instead of `str | bytes` (I would like `bytes` because there is no supplied encoding)

How can I get `readuntil()` to return `Coroutine[Any, Any, bytes]` instead of `Coroutine[Any, Any, Unknown]`? The source seems to have it return `AnyStr = str | bytes` but it's not getting properly inferred.

**Comment by ronf** [comment]
The default encoding is actually UTF-8, which means you would mean that AsyncSSH is going to expect and response with `str` data unless you explicitly set `encoding=None` when you open the channel. Unfortunately, since encoding can be passed via the "Options" classes, type inferencing isn't always able to determine what the encoding is at build time and whether it should treat the types at build time as `str` or `bytes`. That's why `AnyStr` is used here.

Also, note that type inferencing for AsyncSSH is built around mypy. I've looked into trying to make it also compatible with pyright a few times over the last few years, but the there are just too many differences between the two. In theory, that shouldn't prevent you from using other type systems on your application code, but I can't really promise you ahead of time how well they work.

The type `AnyStr` isn't quite the same as `str | bytes`. In particular if it used in multiple place in a scope, all the places must have the same type (either `bytes` or `str`). Also, SSHReader and SSHWriter are generics with `AnyStr` as their parameter. So, you should be able to explicitly declare something of type `SSHReader[bytes]` or `SSHReader[str]` if the type inferencing doesn't figure things out on its own. You might try an explicit type declaration on your reader & writer variables, or if necessary an explicit `cast()` to the type you need.

**Comment by xBiggs** [comment]
> So, you should be able to explicitly declare something of type `SSHReader[bytes]` or `SSHReader[str]` if the type inferencing doesn't figure things out on its own. You might try an explicit type declaration on your reader & writer variables, or if necessary an explicit `cast()` to the type you need.

Thanks, was able to change the generator prototype to:
```py
async def google_ssh_tunnel(hostname: str) -> AsyncGenerator[tuple[asyncssh.SSHReader[bytes], asyncssh.SSHWriter[bytes]], None]
```
Now my `readuntil()` is giving me `bytes`!

**Comment by xBiggs** [comment]
> So, you should be able to explicitly declare something of type `SSHReader[bytes]` or `SSHReader[str]` if the type inferencing doesn't figure things out on its own. You might try an explicit type declaration on your reader & writer variables, or if necessary an explicit `cast()` to the type you need.

Thanks, was able to change the generator prototype to:
```py
async def google_ssh_tunnel(hostname: str) -> AsyncGenerator[tuple[asyncssh.SSHReader[bytes], asyncssh.SSHWriter[bytes]], None]
```
Now my `readuntil()` is giving me `bytes`!

**Comment by ronf** [comment]
Do you also have `encoding=None` somewhere when opening the channel? Without that, I would expect things to fail at runtime when it tries to UTF-8 encode/decode the bytes.

**Comment by xBiggs** [comment]
> Do you also have `encoding=None` somewhere when opening the channel? Without that, I would expect things to fail at runtime when it tries to UTF-8 encode/decode the bytes.

Nope, I'm definitely getting bytes
```
b'HTTP/1.1 200 OK\r\nDate: Tue, 03 Sep 2024 23:21:43 GMT\r\nExpires: -1\r\nCache-Control: private, max-age=0\r\nContent-Type: text/html; charset=ISO-8859-1\r\nContent-Security-Policy-Report-Only: object-src \'none\';base-uri \'self\';script-src \'nonce-SrCv-UcWOVd9IO3End9R5w\' \'strict-dynamic\' \'report-sample\' \'unsafe-eval\' \'unsafe-inline\' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp\r\nP3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."\r\nServer: gws\r\nX-XSS-Protection: 0\r\nX-Frame-Options: SAMEORIGIN\r\nSet-Cookie: AEC=AVYB7coVcHZ50xQgMCOfXTL5IWbxn6uwVnSqq-gAGB2ngkJs4m4rQl8GQr0; expires=Sun, 02-Mar-2025 23:21:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax\r\nSet-Cookie: NID=517=dzmswc2RpwQJUN7rK60P_xWVhg3v5dWyLOWMoArFRCM2CGn22TaZmOQju6mIsWaJim5XyxEjnyEkeTph7adquoC3l1Nw3ixCCNSW_3QSWArYYLkp5WlxrQ4j_sukHLeGQqPZJtiEi_EkbGm8rJPqzUfEAmIT9c7_jaNDQHPdPr6E6zPvvfuRAoZ1; expires=Wed, 05-Mar-2025 23:21:43 GMT; path=/; domain=.google.com; HttpOnly\r\nAccept-Ranges: none\r\nVary: Accept-Encoding\r\nTransfer-Encoding: chunked\r\n\r\n'
```

**Comment by ronf** [comment]
Ah, never mind -- Looking more closely I see that you're opening a direct TCP/IP connection (with `conn.open_connection` on top of the SSH connection. That allows other encodings, but defaults to `None` (reading & writing bytes). Only regular SSH sessions/channels default to UTF-8 encoding and `str` values.
