### ISSUE TITLE
SFTP OOM Error

### ISSUE THREAD

**Issue by sullivan-sean** [ronf/asyncssh#726]
My profiler is reporting very large memory allocation (many GB) from asyncssh `compression.py` from a few concurrent read calls for relatively small files.

At the time of the OOM there was no space left on the remote device.

<img width="655" alt="image" src="https://github.com/user-attachments/assets/345998b3-85e1-47fe-8051-dec7ae0df2d2">

I'll try to reproduce, but my hunch would be that memory isn't freed properly if the compress call succeeds and the flush call fails here:
https://github.com/ronf/asyncssh/blob/e8169bf19c74e5dcaa184123764db403ad131a36/asyncssh/compression.py#L72-L76

Are you open to a PR that frees any allocation or explicitly deletes the `zlib.compressobj` on failure here?

**Comment by ronf** [comment]
A few comments/questions:

* On modern networks, enabling compression actually slows down transfers, in addition to using lots of additional CPU on the sender. AsyncSSH is now disabling compression by default (as of 2.18.0), though it will allow it if the remote system requires it. Independent of this memory issue, you might want to try without compression and see if that actually performs better than with compression enabled.

* Do you know why you are getting compression failures? That should basically never happen. The compression call should work no matter what the data is, and the decompression should only fail if the data bytes were tampered with, but with the end-to-end compression that should never happen unless you are connecting to a buggy (or malicious) SSH peer. In this case, the issue is supposedly with compression, so I don't see how that would ever return `None`.
* 

* If there was a compression failure, it should trigger a fatal error and immediately close the connection, which should make the compression object eligible for deletion. While the garbage collector might not kick in immediately, it shouldn't be too long before it did, especially if the amount of allocated memory is extremely large.

**Comment by sullivan-sean** [comment]
Haven't reproduced yet but this all makes sense. I will come back with more comprehensive logging, etc. if I can come up with a minimal reproduction.

**Comment by sullivan-sean** [comment]
More likely an issue with our profiling than asyncssh
