### ISSUE TITLE
handle 'control' command

### ISSUE THREAD

**Issue by maximumG** [ronf/asyncssh#75]
I would like to know if the 'control' command handling is supported with asyncssh. I would like to simulate some SSH server that requires to type CTRL-H to enter into interactive mode.

Is that feature possible ? I did not see anything concerning this in the documentation.

N.B: BTW really nice work regarding code and especially documentation which is really complete :-)

**Comment by ronf** [comment]
Yes, you can send any control or escape sequence you'd like. You just need to know the corresponding ASCII for the sequence. In the case of Ctrl-H, this would be hex 0x08, which can be represented in Python as the string '\x08'. More generally, uppercase letters in ASCII are in the range 0x41-0x5A hex, and their control equivalents are 0x40 less than that, in the range 0x01-0x1A. The other interesting common character here is Delete, which is 0x7F (or '\x7f' as a Python string).

You can also send escape sequences. For instance, the 'up arrow' on most ANSI-compatible terminals will send the three-byte sequence ESC [ A, which is '\x1b[A' as a Python string. You can simulate a user pressing any key if you know what sequence of characters the terminal sends when the user presses that key.

This isn't explicitly documented as it's not really specific to AsyncSSH. It's just the nature of the way terminals work, and the specific sequences will vary depending on your terminal type. However, there is online documentation for different terminals which will tell you what these sequences are.

One thing to note: You'll probably need to set the terminal type when you open the interactive SSH session if you want this to work. Otherwise, the remote system won't think it is connected to a terminal, and these sequences may not be handled correctly. When there's no terminal type set, the SSH server doesn't open a "pseudo-TTY" to attach to the running command, and most forms of interactive editing are disabled.

Thanks for the compliment. If you have any further questions on this, let me know!
