### ISSUE TITLE
persisting working directory in a connection

### ISSUE THREAD

**Issue by subyraman** [ronf/asyncssh#76]
Thanks for writing this! I'm building a utility on top of asyncssh, and I'm wondering if there is a way for a connection to preserve the working directory so that future `run` commands can be executed in that context. An example:

```
async def start_server():
    connection = await asyncssh.connect(HOST, username='root')

    await connection.run('cd /src')

    # prints '/root', but I want `/src/`
    print((await connection.run('pwd')).stdout)


loop = asyncio.get_event_loop()
loop.run_until_complete(start_server())
loop.close()
```

I know that I could do `await connection.run('cd /src && pwd')` but for what I'm doing it would be helpful if I had access to a reusable connection/session object that I can persistently change directories with, especially since I'll be working with a long list of commands. Does something like that exist?

**Comment by ronf** [comment]
This is possible, but only if you start a shell and feed your series of commands to that shell, rather than running each command in its own SSH session. In that case, things like the current working directory will be preserved from one command to the next, as will things like environment variables you set.

I talked about something like this in issue #59. The main challenge is knowing when each of the commands is done running, and so I showed an example there of echoing a special line of output you could look for after running each command to know when to start the next one. You may not need that if you already know how much output to expect from each command you run.

**Comment by subyraman** [comment]
Thanks for the response and the solution! Is there a way to get exit codes from each command using that method? Or does the caller just know only when the command has finished (with the `echo` string)?

**Comment by ronf** [comment]
You should  be able to ask the shell for the return code of the last command. In the "echo" to print the end marker,  just include "$?" where you want it to return the exit code. Since the output string can vary, you'll need the test for it to only match on the prefix, but the same basic approach should work.

**Comment by redixin** [comment]
@subyraman 

It may be simpler to move all the logic into bash script and just run it on remote side:

```python
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        await conn.run('/bin/bash -xs', input=open("/path/to/script.sh"))

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```
