### ISSUE TITLE
Using connection with open SFTP client

### ISSUE THREAD

**Issue by maciej-kisiel** [ronf/asyncssh#85]
Hi!

Firstly, this is a very cool project and helps me a lot!

I have a question, I tried to find the answer in the docs, issue tracker or the mailing list, but to no avail.

During some testing it seems that it's not correct to have an open SFTP client and trying to run some ssh commands at the same time. The commands are sometimes running forever (quite randomly I would say, sometimes they succeed). Is this correct? Should it be that way?

Thanks for help,
Maciej

**Comment by ronf** [comment]
Thanks very much, Maciej!

When you create an SFTP client, it opens a separate channel on the SSHConnection. It should work just fine to have that and other sessions open on the same connection in parallel. Since all of the sessions share the same TCP connection, though, you may see some delays due to file transfer data sent on the connection filing the pipe and preventing the other data from getting through right away.

If you are transferring large files, you may find it works better to keep your SFTP transfers on separate SSH connections from your interactive sessions.

I can't really explain why commands would not complete at all. If you can come up with a test case where you're able to reproduce this (even if you don't see it every time), feel free to post it here and I'll take a closer look.

**Comment by maciej-kisiel** [comment]
You're right, it should work. It turned out to be a bug in the ssh server (dropbear).

Here is a short description: https://github.com/robotframework/SSHLibrary/issues/128#issuecomment-160140410

After updating the server to newer version it seems to work fine.

Thank you for your help!

**Comment by ronf** [comment]
Good to know - thanks for the info, Maciej!
