### ISSUE TITLE
what is ssh_user_ca and how do I get it

### ISSUE THREAD

**Issue by LoganDark** [ronf/asyncssh#87]
I don't know what to doo.......... :c

I've generated `ssh_host_key` for the `chat_server.py` example but i don't know how to generate (or find) `ssh_user_ca`

**Comment by ronf** [comment]
You only need this if you want to support client key authentication in your server. In that case, you pass in a file containing either a list of authorized client keys, or a CA public key if you want the clients to be able to offer an SSH certificate instead of a public key.

To use certificates, you'd do something like the following:

Generate a CA key pair with:

    ssh-keygen -t rsa -b 2048 -f ca_key

Generate a user key pair with:

    ssh-keygen -t rsa -b 2048 -f id_rsa

Create a certificate signed by the CA key for this user:

    ssh-keygen -s ca_key -I user -n user id_rsa

Take the output of ca_key.pub and add the keyword "cert-authority" in front of "ssh-rsa" at the beginning of the line and save that as the ssh_user_ca file. Then, take the id_rsa, id_rsa.pub, and id_rsa-cert.pub files and move them into your client's ".ssh" directory.

In the above, the text "user" should be replaced with the username you want to use when logging into your server via SSH. Also, make sure you keep the "ca_key" file safe, as that's the private key you'd need to use to sign new user keys that you want to trust.

**Comment by LoganDark** [comment]
Oh yeah, I just removed the code that made it want `ssh_user_ca`, thanks.
