### ISSUE TITLE
Client protocol 

### ISSUE THREAD

**Issue by daniel98321** [ronf/asyncssh#90]
Hi
I'm using asyncssh alongside other communication protocols, and I see that all the asyncssh's create_connection functions are using a session_factory. I've looked at the code and saw that Session look very similar to asyncio.Protocol.
I need to use create_connection and give it a specific Protocol, but Protocol is not supported inside the craete_connection. 
My suggestion is that in future version, the session could be converted to a asyncio.Protocol for compatability with the asyncio framework. 
If you know of a way I could change it safely and easily, please let me know. 
Thanks.

**Comment by ronf** [comment]
Hi Daniel,

You're right that asynchssh's SSHSession is designed to mirror asyncio.Protocol. Similarly, SSHChannel is designed to mirror asyncio.Transport. So, when you call something like SSHClientConnection.create_session() or SSHClientConnection.create_connection() to open a channel on top of an open SSH client connection, it returns an (SSHChannel, SSHSession) pair, much like how asyncio.create_connection() returns a (Transport, Protocol) pair.

If you have an existing asyncio.Protocol implementation, it should be relatively straightforward to modify or subclass it to make it compatible with SSHSession. Here are some differences you'd have to address:

- The connection_made method is the same, but it is passed an SSHChannel instead of a Transport. See below on the differences between these, but for the most part the calls you make on the Transport shouldn't have to change.

- The connection_lost method is the same, giving you an Exception or None for a clean close.

- There's a new session_started() method which is called when a connection is fully open and ready to accept data. If you don't need this callback, you can implement this as an empty method (or you'll get this automatically if you make your class a subclass of SSHSession).

- The data_received() method takes an extra "datatype" argument along with the data, so you can distinguish output on stdout vs. stderr. This is the only really incompatible change. You can just ignore this value or only process data where datatype is None, depending on whether you want to process output to stderr or not.

- The data_received() method's "data" argument can either be bytes like it generally is for Protocol, or it can be a string if "encoding" is set when you open the channel. If you want to operate on bytes, just make sure to set encoding=None on the open/create call.

- The eof_received() method is the same, as are the pause_writing() and resume_writing() methods.

- There are some extra methods on SSHClientSession for handling SSH-specific things like xon/xoff flow control requests and exit status/signal information. If you don't need to process these, you can implement these as empty methods or inherit them from SSHClientSession.

- On the server side, there are some methods relating to returning whether to accept shell, exec, and subsystem requests. If you are implementing an SSHServerSession yourself and not using the higher-level stream APIs, you'll need to implement these.

As for SSHChannel vs. asyncio.Transport, here are the differences:

- The write() and writelines() calls are the same, except they take an optional datatype argument. Also, as above, they can take either bytes or str arguments for "data" depending on the encoding set when the channel is opened.

- The write_eof(), can_write_eof(), get_write_buffer_size(), and set_write_buffer_limtis() calls are all the same.

- The get_extra_info() call is basically the same, though the specific set of things available are different for each Transport, and this has some new SSH-specific items.

- The pause_reading() and resume_reading() calls are the same.
 
- The abort() and close() methods are the same. Right now, SSHChannel doesn't implement is_closing() (added to Transport in 3.5.1), but that would be easy to add if it is needed. SSHChannel was written before this API call existed.

- There's no support for get_protocol()/set_protocol() added in 3.5.3. I don't know if anything out there is using this yet, but I haven't run across a need for anything like it in AsyncSSH so far.

So, for the most part, you shouldn't need any changes in the calls your Protocol makes on Transport to allow it to work with an SSHChannel. You'll just need to add a few new methods to it and adapt the data_received() call to take an extra "datatype" argument. If you don't want to modify the Protocol class itself, you can easily do this by creating a subclass of that Protocol with the new methods & new data_received() method which then calls the superclass without passing datatype.

Let me know if you have further questions about this.

**Comment by ronf** [comment]
Closing this issue for now - please re-open it or open a new issue if you need more than the explanation above.
