### ISSUE TITLE
filename should be kept in unicode in win32 platform

### ISSUE THREAD

**Issue by fcicq** [ronf/asyncssh#91]
Thanks for your project so I have a working sftp & scp server in windows.

the error message in winscp:
Uncaught exception: 'mbcs' codec can't encode characters in position 0--1: invalid character

see also https://www.python.org/dev/peps/pep-0529/ for more details. what I need would be replacing the filenames in sftp.py to standard str type, and only use the bytes type just before sending to sftp network stream.

I have a temporary implementation that enabled uploading, but listdir() includes b'.' and b'..' increased the modification complexity, I guess the error message comes from one of the os.fsencode() call in sftp.py.

one thing unrelated, should I open another issue that handle the ~username on map_path?

===

some example code.
```
    def map_path(self, path):
        u8path = path.decode('utf8')
        if u8path.startswith('~'):
            path_sep = u8path.find('/')
            if path_sep != -1:
                u8path = u8path[path_sep:]
            else:
                u8path = '/'

        if self._chroot:
            normpath = posixpath.normpath(os.path.join('/', u8path))
            return posixpath.join(self._chroot, normpath[1:])
        else:
            return u8path

    def reverse_map_path(self, path):
        if self._chroot:
            if path == self._chroot:
                return b'/'
            elif path.startswith(self._chroot + '/'):
                return path[len(self._chroot):].encode('utf8')
            else:
                raise SFTPError(FX_NO_SUCH_FILE, 'File not found')
        else:
            return path.encode('utf8')
```

```
def _from_local_path(path):
    """Convert SFTP path to local path"""
    if sys.platform == 'win32': # pragma: no cover
        path = path.replace('\\', '/')

        if path[:1] != '/' and path[1:2] == ':':
            path = '/' + path

    return path

def _to_local_path(path):
    """Convert local path to SFTP path"""

    if sys.platform == 'win32': # pragma: no cover
        if path[:1] == '/' and path[2:3] == ':':
            path = path[1:]

        path = path.replace('/', '\\')

    return path
asyncssh.sftp._from_local_path = _from_local_path
asyncssh.sftp._to_local_path = _to_local_path
```

**Comment by fcicq** [comment]
btw I'm using python 3.5.3 mainly for extension compatibility reasons. I guess py3.6 should have this issue resolved but some extension does not provide py3.6 wheel for windows.

**Comment by ronf** [comment]
It's not as simple as saying that everything should be kept as a Unicode string except when data is put on the wire. I allow applications to call into AsyncSSH with either str or bytes values as the file names, and when I'm given bytes, there's no guarantee what encoding that might be in and it may not even be possible to represent it as a Unicode string. In those cases, I really wanted to be completely 8-bit clean and encoding-agnostic in the filenames I passed around, even passing them into the OS file access calls as bytes, and letting it figure out what to do with them.

Unfortunately, on Windows, I hit a wall where only some of the file system APIs accepted bytes values, and in fact more recently trying to pass in bytes to many of these raises deprecation warnings. So, I was forced to do a conversion from bytes back to Unicode strings before calling the Windows APIs.

I could have potentially avoided this conversion on some local file accesses if the caller passed in a str, but on something like an inbound request to an SFTP server, the request would ALWAYS be coming in as bytes, so this issue would still come up. I do have an ability to specify a "path encoding" right now for the SFTP client to control how it encodes and decodes paths on the wire when the caller uses str values as arguments, but nothing like that exists on the SFTP server side yet.

If the problem you're having is with fsencode/fsdecode, have you thought about monkey-patching those to encode & decode using utf-8 instead of mbcs on Python versions before 3.6? That would allow the larger range of characters to be represented when values are passed around as bytes, and since AsyncSSH always does an fsdecode() to convert back to str before calling the Windows file APIs, you should get what you want in terms of it passing in a Unicode string in all those cases.

My goal in using fsencode/fsdecode was to allow callers passing paths represented as bytes to use the native OS filesystem encoding of these names and have the file operations still work correctly, and I'm not sure I want to break that. However, if you are trying to operate on local path names which can't be represented in Python's native filesystem encoding on the version of Python you are running, overriding fsencode()/fsdecode() actually sounds like it might be a good workaround.

Regarding the '~username' thing, are you saying you'd like that string to be allowed in path names the caller is passing in? I would not ever expect to see such a string on the wire, so I would sort of expect that to be handled by the calling code before passing a path, at least for SFTP. I'll admit it's a bit less clear with SCP, though, as there an SCP server does handle things like glob expansion. What case did you have in mind here?

**Comment by fcicq** [comment]
I'm not sure if encode/decode is required to patch, I patched it anyway. As your suggestion, just monkey-patching os.fsencode would be enough. I'm not using copy() or other functions that requires listdir(), so I may have accidentally break those, just doing scp/sftp copy would make me happy :)

the ~user issue, mainly for scp, I may type scp xxx HOST:~ but by default it will write to a file that called "~", that would be so bad...

```
@classmethod
def encode_direct(cls, path): return path
asyncssh.sftp.LocalFile.encode = encode_direct
asyncssh.sftp.LocalFile.decode = encode_direct
os.fsencode = lambda x: x.encode('utf8')
```

**Comment by ronf** [comment]
You shouldn't need to touch LocalFile's encode/decode if you patch fsencode/fsdecode using something like:
```python
import os
os.fsencode = lambda path: path.encode('utf-8')
os.fsdecode = lambda path: path.decode('utf-8')
```

This should allow all the functions to work, including things like listdir.

Regarding the '~' expansion, it looks like it would be pretty straightforward to add a call to os.path.expanduser() to the _to_local_path() function. Doing a quick test here on a local Windows machine, though, I noticed that '~foo' is expanded to "C:\\Users\\foo" even when "foo" is not a valid user. On UNIX, it leaves '~foo' unexpanded when it isn't a valid user. So, I kind of wonder if the Windows version actually has any concept of actually looking up home directories when you do this.

By the way, note that '~' without a username would always end up expanding to the user running the SCP server instance in the AsyncSSH SCP server case, not the user you are ssh'ing in as, since it doesn't do validation of the SSH user against actual OS users or do any kind of a "login" as that user.

**Comment by ronf** [comment]
Closing this issue for now - please re-open it or open a new issue if you are still having problems.
