### ISSUE TITLE
SSHReader.read() blocking even though EOF should have been received

### ISSUE THREAD

**Issue by nyren** [ronf/asyncssh#96]
Hi,
Awesome work with asyncssh, really impressed with all the features in there!

I ran into an issue with SSHReader, it seems to block forever under certain conditions even though EOF should have been received.

```python
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        async with conn.create_process('cat') as process:
            process.stdin.write('Hello World\n')
            result = await process.stdout.read(50000)
        print(result)
        async with conn.create_process('cat') as process:
            process.stdin.write('Hello World\n')
            result = await process.stdout.read()
        print(result)
try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

I would expect the output of the above test script to output "Hello world" two times. However, the second call to process.stdin.read() just blocks forever.

Trying to debug the issue it looks like the connection_lost event is never received for he second process but I failed to figure out why.

OS: ArchLinux
Python: 3.6.1
asyncssh: 1.10.1

**Comment by nyren** [comment]
One should not report issues late at night... adding ```process.stdin.write_eof()``` of course solves the problem. Still a bit interesting with the different behaviour when not specifying the number of bytes to read.

Sorry for the noise.

**Comment by ronf** [comment]
Yeah - this is working as designed. Since you didn't write_eof(), the "cat" command continued to wait for input from you and didn't send an EOF back to you. So, the read() blocked forever.

Regarding the difference in behavior when you have a count value, this is covered in the docs, and it's actually behavior I replicated from the regular asyncio StreamReader class. It documents:

> coroutine read(n=-1)
> Read up to n bytes. If n is not provided, or set to -1, read until EOF and return all read bytes.
> 
> If the EOF was received and the internal buffer is empty, return an empty bytes object.

The one enhancement I've made with SSHReader is that you can mix sending data and signals on a channel. In the case where a signal is received and there's data prior to that signal, a read() with no length will return all the data leading up to the signal even when EOF hasn't been sent yet. The next read() will then report the signal (by raising an exception).

**Comment by nyren** [comment]
Makes perfect sense now, thanks for taking your time to respond in detail. Nice approach to the signal handling.
