### ISSUE TITLE
Question about SSHReader().read(n)

### ISSUE THREAD

**Issue by flaurencin** [ronf/asyncssh#99]
Hi,

Sorry to bother but I have a very strange behavior, and I guess I'm missing for knowledge on stream handling.
The doc says this :
```
    def read(self, n=-1):
        """Read data from the stream

           This method is a coroutine which reads up to ``n`` bytes
           or characters from the stream. If ``n`` is not provided or
           set to ``-1``, it reads until EOF or a signal is received.

           If EOF is received and the receive buffer is empty, an
           empty bytes or str object is returned.

           If the next data in the stream is a signal, the signal is
           delivered as a raised exception.

           .. note:: Unlike traditional ``asyncio`` stream readers,
                     the data will be delivered as either bytes or
                     a str depending on whether an encoding was
                     specified when the underlying channel was opened.

        """
```

But my understanding is,
    If there is data in the buffer I read at the maximum this (n) quantity of data of the specific datatype. But if there is less i'll still get it in return.

I'm working with a cisco device. I suppose the stream may get slow at some point and do not output characters for one second. Then I added a timer before reading.

Am I suppose to do all of this ?
If the buffer is empty when I call read(n), will the read wait for the total amount of data I asked for before returning something ?
If the buffer contains data will I immediately get the available data ?
 
My problem is that from the way I do it seems like sometime I get partial data and never detect the prompt properly the end of the result of the command is missing.

Thanks a lot for any clarification you can push to me. I'll try to rewrite my code and if the problem is still there I'll post it.

Kind regards,

**Comment by flaurencin** [comment]
Hi,

I think I answered my question alone reading this 
SSHStreamSession().read
```
  def read(self, n, datatype, exact):
        """Read data from the channel"""

        recv_buf = self._recv_buf[datatype]
        buf = '' if self._encoding else b''
        data = []

        while True:
            while recv_buf and n != 0:
                if isinstance(recv_buf[0], Exception):
                    if data:
                        break
                    else:
                        raise recv_buf.pop(0)

                l = len(recv_buf[0])
                # There you already have data in a buffer but the size i gave you is too small
                if n > 0 and l > n:
                    data.append(recv_buf[0][:n])
                    recv_buf[0] = recv_buf[0][n:]
                    self._recv_buf_len -= n
                    n = 0
                    break

                # There you already have data in a buffer but the size i gave you big enough
                data.append(recv_buf.pop(0))
                self._recv_buf_len -= l
                n -= l

            # I don't get this case ??
            if self._maybe_resume_reading():
                continue

            # There you consider you should probably return
            # Because there is data and the size requested was not exact so I can get data
            # Than my original request or you receive EOF
            if n == 0 or (n > 0 and data and not exact) or self._eof_received:
                break

            # if you did not break at this point then there was no data in the buffer
            # Then you wait for more data to come in before going back to the loop
            yield from self._block_read(datatype)

        buf = buf.join(data)
        # if the size I expected was exact then you raise an exception
        # else you just return the buffer
        if n > 0 and exact:
            raise asyncio.IncompleteReadError(buf, len(buf) + n)

        return buf
```

So  think I'll double check the behavior of my code. 
Isn't there any logging in this section planned ?

Thanks for your time.

Kind regards,

**Comment by ronf** [comment]
When you called read(), did you pass in a maximum length? If not, the expected behavior is for the read() to block until either EOF is received or something like a break, signal, or terminal size change is received. This was done to match the behavior of asyncio's StreamReader class. For more info, see the discussion in issue #96.

To get read() to return as soon as data is available, just pass in a maximum length to read. Even if less than that amount of data is available, it will return immediately with whatever data is available (up to the maximum length you requested).

Regarding the notes you put in the code:

  * You're right that the first block you commented on is where the number of bytes available to read is more than the requested size, so only part of the data available is returned. The next block is where an entire buffer can be consumed, but there might still be more data to read so it loops back around.

  * The maybe_resume_reading() call is designed to unblock the remote system if it has been paused due to flow control, since we've just pulled some data out of the receive buffer and so there could be room for more. This is done to allow more data to be sent by the remote system before this code blocks waiting for it.

  * The block after that exits if the number of bytes requested has been reached. It also exits if there's partial data available and readexactly() wasn't used or if EOF has been received, indicating there's no more data coming.

  * If none of the above conditions were true, the read() blocks waiting for more data.

  * Finally, as it exits, an IncompleteReadError() is raised if readexactly() was called and the amount of data available is less than the requested amount.

There's also a block just above your first comment which handles the case where an exception is waiting to be delivered on the stream (such as a break, signal, terminal size change, or some transport level error). In that case, any data read will be returned first, and after that another call to read() will cause the pending exception to be raised.

Regarding debug logging, that's still on my list of things to go back and insert, though it would need to be used sparingly in a function like this, as logging every read() would generate a LOT of output, and logging inside a read loop like this would really blow things up. I'd probably only log the return cases here, and only if you had the debug level set VERY high.

**Comment by flaurencin** [comment]
Thanks a lot for you comment !!!!!!!! I'll just review my code the problem is for sure on my side. This comment is a great answer, thanks for your precious time.
